// 
// Generated By: dol2asm
// 

#include "dolphin/types.h"

// 
// Additional Symbols:
// 

extern "C" {
extern void _unresolved();
extern void __register_global_object();
extern void __ct__12daE_TH_HIO_cFv();
extern void s_md_sub1__FPvPv();
extern void s_md_sub2__FPvPv();
extern void anm_init__FP10e_th_classifUcf();
extern void nodeCallBack__FP8J3DJointi();
extern void ke_control__FP10e_th_classP7th_ke_si();
extern void ke_pos_set__FP10e_th_classP7th_ke_si();
extern void ke_disp__FP10e_th_class();
extern void ke_move__FP10e_th_class();
extern void daE_TH_Draw__FP10e_th_class();
extern void e_th_wait__FP10e_th_class();
extern void e_th_spin__FP10e_th_class();
extern void e_th_spin_B__FP10e_th_class();
extern void e_th_shot__FP10e_th_class();
extern void e_th_return__FP10e_th_class();
extern void e_th_damage__FP10e_th_class();
extern void e_th_start__FP10e_th_class();
extern void e_th_end__FP10e_th_class();
extern void damage_check__FP10e_th_class();
extern void action__FP10e_th_class();
extern void cam_3d_morf__FP10e_th_classf();
extern void demo_camera__FP10e_th_class();
extern void anm_se_set__FP10e_th_class();
extern void daE_TH_Execute__FP10e_th_class();
extern void daE_TH_IsDelete__FP10e_th_class();
extern void daE_TH_Delete__FP10e_th_class();
extern void useHeapInit__FP10fopAc_ac_c();
extern void daE_TH_Create__FP10fopAc_ac_c();
extern void __dt__7th_ke_sFv();
extern void __ct__7th_ke_sFv();
extern void __ct__4cXyzFv();
extern void __dt__8dCcD_SphFv();
extern void __ct__8dCcD_SphFv();
extern void __dt__8cM3dGSphFv();
extern void __dt__8cM3dGAabFv();
extern void __dt__10dCcD_GSttsFv();
extern void __dt__12dBgS_ObjAcchFv();
extern void __dt__12dBgS_AcchCirFv();
extern void __dt__10cCcD_GSttsFv();
extern void __dt__12daE_TH_HIO_cFv();
extern void __sinit_d_a_e_th_cpp();
extern void func_807B4028();
extern void func_807B4030();
extern void setMidnaBindEffect__FP13fopEn_enemy_cP15Z2CreatureEnemyP4cXyzP4cXyz();
extern void __dt__4cXyzFv();
extern const u8 unknown_translation_unit_ctors__data_807B4488[8];
extern const void* __destroy_global_chain_reference;
SECTION_RODATA extern const u8 LIT_3906[4];
SECTION_RODATA extern const u8 LIT_3907[4];
SECTION_RODATA extern const u8 LIT_3908[8];
SECTION_RODATA extern const u8 LIT_3909[8];
SECTION_RODATA extern const u8 LIT_3910[8];
SECTION_RODATA extern const u8 LIT_3911[8];
SECTION_RODATA extern const u8 LIT_3912[4];
SECTION_RODATA extern const u8 LIT_3927[4];
SECTION_RODATA extern const u8 LIT_3928[4];
SECTION_RODATA extern const u8 LIT_3942[4];
SECTION_RODATA extern const u8 LIT_3956[4];
SECTION_RODATA extern const u8 LIT_3970[4];
SECTION_RODATA extern const u8 LIT_4055[4];
SECTION_RODATA extern const u8 LIT_4056[4];
SECTION_RODATA extern const u8 LIT_4057[4];
SECTION_RODATA extern const u8 LIT_4058[4];
SECTION_RODATA extern const u8 LIT_4059[4];
SECTION_RODATA extern const u8 LIT_4060[4];
SECTION_RODATA extern const u8 LIT_4061[4];
SECTION_RODATA extern const u8 LIT_4062[4];
SECTION_RODATA extern const u8 LIT_4064[8];
SECTION_RODATA extern const u8 LIT_4087[4];
SECTION_RODATA extern const u8 LIT_4127[4];
SECTION_RODATA extern const u8 LIT_4128[4];
SECTION_RODATA extern const u8 LIT_4164[4];
SECTION_RODATA extern const u8 LIT_4165[4];
SECTION_RODATA extern const u8 LIT_4263[4];
SECTION_RODATA extern const u8 LIT_4264[4];
SECTION_RODATA extern const u8 LIT_4351[4];
SECTION_RODATA extern const u8 LIT_4352[4];
SECTION_RODATA extern const u8 LIT_4353[4];
SECTION_RODATA extern const u8 LIT_4354[4];
SECTION_RODATA extern const u8 LIT_4355[4];
SECTION_RODATA extern const u8 LIT_4356[4];
SECTION_RODATA extern const u8 LIT_4462[4];
SECTION_RODATA extern const u8 LIT_4513[4];
SECTION_RODATA extern const u8 LIT_4540[4];
SECTION_RODATA extern const u8 LIT_4541[4];
SECTION_RODATA extern const u8 LIT_4542[4];
SECTION_RODATA extern const u8 LIT_4678[4];
SECTION_RODATA extern const u8 LIT_4679[4];
SECTION_RODATA extern const u8 LIT_4680[4];
SECTION_RODATA extern const u8 LIT_4681[4];
SECTION_RODATA extern const u8 LIT_5086[4];
SECTION_RODATA extern const u8 LIT_5087[4];
SECTION_RODATA extern const u8 LIT_5088[4];
SECTION_RODATA extern const u8 LIT_5089[4];
SECTION_RODATA extern const u8 LIT_5090[4];
SECTION_RODATA extern const u8 LIT_5091[4];
SECTION_RODATA extern const u8 LIT_5092[4];
SECTION_RODATA extern const u8 LIT_5093[4];
SECTION_RODATA extern const u8 LIT_5094[4];
SECTION_RODATA extern const u8 LIT_5095[4];
SECTION_RODATA extern const u8 LIT_5096[4];
SECTION_RODATA extern const u8 LIT_5097[4];
SECTION_RODATA extern const u8 LIT_5098[4];
SECTION_RODATA extern const u8 LIT_5099[4];
SECTION_RODATA extern const u8 LIT_5100[4];
SECTION_RODATA extern const u8 LIT_5101[4];
SECTION_RODATA extern const u8 LIT_5102[4];
SECTION_RODATA extern const u8 LIT_5103[4];
SECTION_RODATA extern const u8 LIT_5104[4];
SECTION_RODATA extern const u8 LIT_5105[4];
SECTION_RODATA extern const u8 LIT_5106[4];
SECTION_RODATA extern const u8 LIT_5107[4];
SECTION_RODATA extern const u8 LIT_5108[4];
SECTION_RODATA extern const u8 LIT_5109[4];
SECTION_RODATA extern const u8 LIT_5110[4];
SECTION_RODATA extern const u8 LIT_5111[4];
SECTION_RODATA extern const u8 LIT_5112[4];
SECTION_RODATA extern const u8 LIT_5113[4];
SECTION_RODATA extern const u8 LIT_5114[4];
SECTION_RODATA extern const u8 LIT_5115[4];
SECTION_RODATA extern const u8 LIT_5116[4];
SECTION_RODATA extern const u8 LIT_5117[4];
SECTION_RODATA extern const u8 LIT_5118[4];
SECTION_RODATA extern const u8 LIT_5119[4];
SECTION_RODATA extern const u8 LIT_5120[4];
SECTION_RODATA extern const u8 LIT_5121[4];
SECTION_RODATA extern const u8 LIT_5122[4];
SECTION_RODATA extern const u8 LIT_5123[4];
SECTION_RODATA extern const u8 LIT_5124[4];
SECTION_RODATA extern const u8 LIT_5125[4];
SECTION_RODATA extern const u8 LIT_5126[4];
SECTION_RODATA extern const u8 LIT_5127[4];
SECTION_RODATA extern const u8 LIT_5128[4];
SECTION_RODATA extern const u8 LIT_5129[4];
SECTION_RODATA extern const u8 LIT_5130[4];
SECTION_RODATA extern const u8 LIT_5131[4];
SECTION_RODATA extern const u8 LIT_5132[4];
SECTION_RODATA extern const u8 LIT_5191[4];
SECTION_RODATA extern const u8 LIT_5192[4];
SECTION_RODATA extern const u8 LIT_5193[4];
SECTION_RODATA extern const u8 LIT_5312[4];
SECTION_RODATA extern const u8 LIT_5313[4];
SECTION_RODATA extern const u8 LIT_5314[4];
SECTION_RODATA extern const u8 LIT_5315[4];
SECTION_RODATA extern const u8 LIT_5316[4];
SECTION_RODATA extern const u8 LIT_5317[4];
SECTION_RODATA extern const u8 LIT_5526[4];
SECTION_RODATA extern const u8 LIT_5527[4];
SECTION_RODATA extern const u8 stringBase0[5];
SECTION_DATA extern u8 cNullVec__6Z2Calc[12];
SECTION_DATA extern u8 LIT_1787[20];
SECTION_DATA extern u8 data_807B466C[8];
SECTION_DATA extern u8 data_807B4674[8];
SECTION_DATA extern u8 data_807B467C[8];
SECTION_DATA extern u8 data_807B4684[4];
SECTION_DATA extern u8 LIT_4357[44];
SECTION_DATA extern u8 LIT_4682[104];
SECTION_DATA extern u8 LIT_5133[56];
SECTION_DATA extern u8 data_807B4754[64];
SECTION_DATA extern u8 l_daE_TH_Method[32];
SECTION_DATA extern u8 g_profile_E_TH[48];
SECTION_DATA extern void* __vt__12dBgS_AcchCir[3];
SECTION_DATA extern void* __vt__10cCcD_GStts[3];
SECTION_DATA extern void* __vt__10dCcD_GStts[3];
SECTION_DATA extern void* __vt__8cM3dGAab[3];
SECTION_DATA extern void* __vt__8cM3dGSph[3];
SECTION_DATA extern void* __vt__18mDoExt_3DlineMat_c[5];
SECTION_DATA extern void* __vt__12dBgS_ObjAcch[9];
SECTION_DATA extern void* __vt__12daE_TH_HIO_c[3];
SECTION_BSS extern u8 __global_destructor_chain[4 + 4 /* padding */];
SECTION_BSS extern u8 global_destructor_chain__data_807B4874[0];
SECTION_BSS extern u8 LIT_3922[12];
SECTION_BSS extern u8 l_HIO[24];
}


/* ###################################################################################### */
/*                                        .rodata                                         */
/* ###################################################################################### */

extern "C" {
/* 807B4644-807B4649 0005 .rodata    @stringBase0                                                 */
#pragma push
#pragma force_active on
#pragma section ".dead"
SECTION_DEAD const char* const stringBase_807B4644 = "E_th";
#pragma pop
/* 807B449C-807B449C 0000 .rodata    ...rodata.0                                                  */
/* 807B449C-807B44A0 0004 .rodata    @3906                                                        */
SECTION_RODATA const u8 LIT_3906[4] = {
	0x42, 0xC8, 0x00, 0x00,
};
/* 807B44A0-807B44A4 0004 .rodata    @3907                                                        */
SECTION_RODATA const u8 LIT_3907[4] = {
	0x00, 0x00, 0x00, 0x00,
};
/* 807B44A4-807B44AC 0004 .rodata    @3908                                                        */
SECTION_RODATA const u8 LIT_3908[8] = {
	0x3F, 0x80, 0x00, 0x00,
	/* padding */
	0x00, 0x00, 0x00, 0x00,
};
/* 807B44AC-807B44B4 0008 .rodata    @3909                                                        */
SECTION_RODATA const u8 LIT_3909[8] = {
	0x3F, 0xE0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 807B44B4-807B44BC 0008 .rodata    @3910                                                        */
SECTION_RODATA const u8 LIT_3910[8] = {
	0x40, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 807B44BC-807B44C4 0008 .rodata    @3911                                                        */
SECTION_RODATA const u8 LIT_3911[8] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 807B44C4-807B44C8 0004 .rodata    @3912                                                        */
SECTION_RODATA const u8 LIT_3912[4] = {
	0x3C, 0x23, 0xD7, 0x0A,
};
/* 807B44C8-807B44CC 0004 .rodata    @3927                                                        */
SECTION_RODATA const u8 LIT_3927[4] = {
	0x44, 0xA2, 0x80, 0x00,
};
/* 807B44CC-807B44D0 0004 .rodata    @3928                                                        */
SECTION_RODATA const u8 LIT_3928[4] = {
	0x44, 0x2F, 0x00, 0x00,
};
/* 807B44D0-807B44D4 0004 .rodata    @3942                                                        */
SECTION_RODATA const u8 LIT_3942[4] = {
	0x44, 0x0C, 0x00, 0x00,
};
/* 807B44D4-807B44D8 0004 .rodata    @3956                                                        */
SECTION_RODATA const u8 LIT_3956[4] = {
	0xC4, 0x6D, 0x80, 0x00,
};
/* 807B44D8-807B44DC 0004 .rodata    @3970                                                        */
SECTION_RODATA const u8 LIT_3970[4] = {
	0xBF, 0x80, 0x00, 0x00,
};
/* 807B44DC-807B44E0 0004 .rodata    @4055                                                        */
SECTION_RODATA const u8 LIT_4055[4] = {
	0x41, 0x50, 0x00, 0x00,
};
/* 807B44E0-807B44E4 0004 .rodata    @4056                                                        */
SECTION_RODATA const u8 LIT_4056[4] = {
	0xC1, 0x20, 0x00, 0x00,
};
/* 807B44E4-807B44E8 0004 .rodata    @4057                                                        */
SECTION_RODATA const u8 LIT_4057[4] = {
	0x3F, 0x40, 0x00, 0x00,
};
/* 807B44E8-807B44EC 0004 .rodata    @4058                                                        */
SECTION_RODATA const u8 LIT_4058[4] = {
	0x3A, 0x83, 0x12, 0x6F,
};
/* 807B44EC-807B44F0 0004 .rodata    @4059                                                        */
SECTION_RODATA const u8 LIT_4059[4] = {
	0x3D, 0xCC, 0xCC, 0xCD,
};
/* 807B44F0-807B44F4 0004 .rodata    @4060                                                        */
SECTION_RODATA const u8 LIT_4060[4] = {
	0x40, 0x00, 0x00, 0x00,
};
/* 807B44F4-807B44F8 0004 .rodata    @4061                                                        */
SECTION_RODATA const u8 LIT_4061[4] = {
	0x41, 0x20, 0x00, 0x00,
};
/* 807B44F8-807B44FC 0004 .rodata    @4062                                                        */
SECTION_RODATA const u8 LIT_4062[4] = {
	0x41, 0x70, 0x00, 0x00,
};
/* 807B44FC-807B4504 0008 .rodata    @4064                                                        */
SECTION_RODATA const u8 LIT_4064[8] = {
	0x43, 0x30, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00,
};
/* 807B4504-807B4508 0004 .rodata    @4087                                                        */
SECTION_RODATA const u8 LIT_4087[4] = {
	0x40, 0x60, 0x00, 0x00,
};
/* 807B4508-807B450C 0004 .rodata    @4127                                                        */
SECTION_RODATA const u8 LIT_4127[4] = {
	0x41, 0xD8, 0x00, 0x00,
};
/* 807B450C-807B4510 0004 .rodata    @4128                                                        */
SECTION_RODATA const u8 LIT_4128[4] = {
	0x42, 0x0C, 0x00, 0x00,
};
/* 807B4510-807B4514 0004 .rodata    @4164                                                        */
SECTION_RODATA const u8 LIT_4164[4] = {
	0x42, 0x48, 0x00, 0x00,
};
/* 807B4514-807B4518 0004 .rodata    @4165                                                        */
SECTION_RODATA const u8 LIT_4165[4] = {
	0x44, 0x96, 0x00, 0x00,
};
/* 807B4518-807B451C 0004 .rodata    @4263                                                        */
SECTION_RODATA const u8 LIT_4263[4] = {
	0x42, 0x70, 0x00, 0x00,
};
/* 807B451C-807B4520 0004 .rodata    @4264                                                        */
SECTION_RODATA const u8 LIT_4264[4] = {
	0x40, 0xA0, 0x00, 0x00,
};
/* 807B4520-807B4524 0004 .rodata    @4351                                                        */
SECTION_RODATA const u8 LIT_4351[4] = {
	0x3F, 0x00, 0x00, 0x00,
};
/* 807B4524-807B4528 0004 .rodata    @4352                                                        */
SECTION_RODATA const u8 LIT_4352[4] = {
	0x40, 0x40, 0x00, 0x00,
};
/* 807B4528-807B452C 0004 .rodata    @4353                                                        */
SECTION_RODATA const u8 LIT_4353[4] = {
	0x43, 0x48, 0x00, 0x00,
};
/* 807B452C-807B4530 0004 .rodata    @4354                                                        */
SECTION_RODATA const u8 LIT_4354[4] = {
	0x40, 0x80, 0x00, 0x00,
};
/* 807B4530-807B4534 0004 .rodata    @4355                                                        */
SECTION_RODATA const u8 LIT_4355[4] = {
	0x3F, 0xC0, 0x00, 0x00,
};
/* 807B4534-807B4538 0004 .rodata    @4356                                                        */
SECTION_RODATA const u8 LIT_4356[4] = {
	0x3C, 0xCC, 0xCC, 0xCD,
};
/* 807B4538-807B453C 0004 .rodata    @4462                                                        */
SECTION_RODATA const u8 LIT_4462[4] = {
	0x43, 0x96, 0x00, 0x00,
};
/* 807B453C-807B4540 0004 .rodata    @4513                                                        */
SECTION_RODATA const u8 LIT_4513[4] = {
	0xC4, 0x96, 0x00, 0x00,
};
/* 807B4540-807B4544 0004 .rodata    @4540                                                        */
SECTION_RODATA const u8 LIT_4540[4] = {
	0x46, 0x1C, 0x40, 0x00,
};
/* 807B4544-807B4548 0004 .rodata    @4541                                                        */
SECTION_RODATA const u8 LIT_4541[4] = {
	0xC1, 0xF0, 0x00, 0x00,
};
/* 807B4548-807B454C 0004 .rodata    @4542                                                        */
SECTION_RODATA const u8 LIT_4542[4] = {
	0x3E, 0xCC, 0xCC, 0xCD,
};
/* 807B454C-807B4550 0004 .rodata    @4678                                                        */
SECTION_RODATA const u8 LIT_4678[4] = {
	0xC3, 0x16, 0x00, 0x00,
};
/* 807B4550-807B4554 0004 .rodata    @4679                                                        */
SECTION_RODATA const u8 LIT_4679[4] = {
	0xC2, 0x48, 0x00, 0x00,
};
/* 807B4554-807B4558 0004 .rodata    @4680                                                        */
SECTION_RODATA const u8 LIT_4680[4] = {
	0x3F, 0xE6, 0x66, 0x66,
};
/* 807B4558-807B455C 0004 .rodata    @4681                                                        */
SECTION_RODATA const u8 LIT_4681[4] = {
	0x43, 0xFA, 0x00, 0x00,
};
/* 807B455C-807B4560 0004 .rodata    @5086                                                        */
SECTION_RODATA const u8 LIT_5086[4] = {
	0x42, 0x5C, 0x00, 0x00,
};
/* 807B4560-807B4564 0004 .rodata    @5087                                                        */
SECTION_RODATA const u8 LIT_5087[4] = {
	0x3F, 0xF3, 0x33, 0x33,
};
/* 807B4564-807B4568 0004 .rodata    @5088                                                        */
SECTION_RODATA const u8 LIT_5088[4] = {
	0xC4, 0x8C, 0xE0, 0x00,
};
/* 807B4568-807B456C 0004 .rodata    @5089                                                        */
SECTION_RODATA const u8 LIT_5089[4] = {
	0x43, 0x0C, 0x00, 0x00,
};
/* 807B456C-807B4570 0004 .rodata    @5090                                                        */
SECTION_RODATA const u8 LIT_5090[4] = {
	0xC4, 0x9D, 0xC0, 0x00,
};
/* 807B4570-807B4574 0004 .rodata    @5091                                                        */
SECTION_RODATA const u8 LIT_5091[4] = {
	0x43, 0x02, 0x00, 0x00,
};
/* 807B4574-807B4578 0004 .rodata    @5092                                                        */
SECTION_RODATA const u8 LIT_5092[4] = {
	0x42, 0xC4, 0x00, 0x00,
};
/* 807B4578-807B457C 0004 .rodata    @5093                                                        */
SECTION_RODATA const u8 LIT_5093[4] = {
	0xC4, 0x70, 0xC0, 0x00,
};
/* 807B457C-807B4580 0004 .rodata    @5094                                                        */
SECTION_RODATA const u8 LIT_5094[4] = {
	0x41, 0xF0, 0x00, 0x00,
};
/* 807B4580-807B4584 0004 .rodata    @5095                                                        */
SECTION_RODATA const u8 LIT_5095[4] = {
	0x43, 0x34, 0x00, 0x00,
};
/* 807B4584-807B4588 0004 .rodata    @5096                                                        */
SECTION_RODATA const u8 LIT_5096[4] = {
	0xC4, 0x82, 0x60, 0x00,
};
/* 807B4588-807B458C 0004 .rodata    @5097                                                        */
SECTION_RODATA const u8 LIT_5097[4] = {
	0x42, 0xA8, 0x00, 0x00,
};
/* 807B458C-807B4590 0004 .rodata    @5098                                                        */
SECTION_RODATA const u8 LIT_5098[4] = {
	0xC4, 0xA8, 0x00, 0x00,
};
/* 807B4590-807B4594 0004 .rodata    @5099                                                        */
SECTION_RODATA const u8 LIT_5099[4] = {
	0x3E, 0x4C, 0xCC, 0xCD,
};
/* 807B4594-807B4598 0004 .rodata    @5100                                                        */
SECTION_RODATA const u8 LIT_5100[4] = {
	0x3D, 0x4C, 0xCC, 0xCD,
};
/* 807B4598-807B459C 0004 .rodata    @5101                                                        */
SECTION_RODATA const u8 LIT_5101[4] = {
	0xC3, 0x2C, 0x00, 0x00,
};
/* 807B459C-807B45A0 0004 .rodata    @5102                                                        */
SECTION_RODATA const u8 LIT_5102[4] = {
	0x42, 0xC7, 0x66, 0x66,
};
/* 807B45A0-807B45A4 0004 .rodata    @5103                                                        */
SECTION_RODATA const u8 LIT_5103[4] = {
	0xC4, 0x7E, 0x00, 0x00,
};
/* 807B45A4-807B45A8 0004 .rodata    @5104                                                        */
SECTION_RODATA const u8 LIT_5104[4] = {
	0xC3, 0x52, 0x00, 0x00,
};
/* 807B45A8-807B45AC 0004 .rodata    @5105                                                        */
SECTION_RODATA const u8 LIT_5105[4] = {
	0xC4, 0xA6, 0x40, 0x00,
};
/* 807B45AC-807B45B0 0004 .rodata    @5106                                                        */
SECTION_RODATA const u8 LIT_5106[4] = {
	0xC3, 0x96, 0x00, 0x00,
};
/* 807B45B0-807B45B4 0004 .rodata    @5107                                                        */
SECTION_RODATA const u8 LIT_5107[4] = {
	0xC4, 0x8A, 0x00, 0x00,
};
/* 807B45B4-807B45B8 0004 .rodata    @5108                                                        */
SECTION_RODATA const u8 LIT_5108[4] = {
	0xC2, 0x60, 0x00, 0x00,
};
/* 807B45B8-807B45BC 0004 .rodata    @5109                                                        */
SECTION_RODATA const u8 LIT_5109[4] = {
	0x43, 0x60, 0xB3, 0x33,
};
/* 807B45BC-807B45C0 0004 .rodata    @5110                                                        */
SECTION_RODATA const u8 LIT_5110[4] = {
	0x44, 0x15, 0x80, 0x00,
};
/* 807B45C0-807B45C4 0004 .rodata    @5111                                                        */
SECTION_RODATA const u8 LIT_5111[4] = {
	0xC2, 0x5A, 0x00, 0x00,
};
/* 807B45C4-807B45C8 0004 .rodata    @5112                                                        */
SECTION_RODATA const u8 LIT_5112[4] = {
	0x43, 0x31, 0x00, 0x00,
};
/* 807B45C8-807B45CC 0004 .rodata    @5113                                                        */
SECTION_RODATA const u8 LIT_5113[4] = {
	0x43, 0x8E, 0x80, 0x00,
};
/* 807B45CC-807B45D0 0004 .rodata    @5114                                                        */
SECTION_RODATA const u8 LIT_5114[4] = {
	0x3B, 0x03, 0x12, 0x6F,
};
/* 807B45D0-807B45D4 0004 .rodata    @5115                                                        */
SECTION_RODATA const u8 LIT_5115[4] = {
	0xC3, 0x38, 0x00, 0x00,
};
/* 807B45D4-807B45D8 0004 .rodata    @5116                                                        */
SECTION_RODATA const u8 LIT_5116[4] = {
	0x42, 0xB5, 0x66, 0x66,
};
/* 807B45D8-807B45DC 0004 .rodata    @5117                                                        */
SECTION_RODATA const u8 LIT_5117[4] = {
	0xC4, 0x80, 0x80, 0x00,
};
/* 807B45DC-807B45E0 0004 .rodata    @5118                                                        */
SECTION_RODATA const u8 LIT_5118[4] = {
	0xC3, 0x80, 0x40, 0x00,
};
/* 807B45E0-807B45E4 0004 .rodata    @5119                                                        */
SECTION_RODATA const u8 LIT_5119[4] = {
	0x42, 0x08, 0x00, 0x00,
};
/* 807B45E4-807B45E8 0004 .rodata    @5120                                                        */
SECTION_RODATA const u8 LIT_5120[4] = {
	0xC4, 0xA6, 0x60, 0x00,
};
/* 807B45E8-807B45EC 0004 .rodata    @5121                                                        */
SECTION_RODATA const u8 LIT_5121[4] = {
	0x39, 0x9D, 0x49, 0x52,
};
/* 807B45EC-807B45F0 0004 .rodata    @5122                                                        */
SECTION_RODATA const u8 LIT_5122[4] = {
	0x43, 0xC8, 0x00, 0x00,
};
/* 807B45F0-807B45F4 0004 .rodata    @5123                                                        */
SECTION_RODATA const u8 LIT_5123[4] = {
	0x42, 0xA0, 0x00, 0x00,
};
/* 807B45F4-807B45F8 0004 .rodata    @5124                                                        */
SECTION_RODATA const u8 LIT_5124[4] = {
	0x43, 0x16, 0x00, 0x00,
};
/* 807B45F8-807B45FC 0004 .rodata    @5125                                                        */
SECTION_RODATA const u8 LIT_5125[4] = {
	0x41, 0xA0, 0x00, 0x00,
};
/* 807B45FC-807B4600 0004 .rodata    @5126                                                        */
SECTION_RODATA const u8 LIT_5126[4] = {
	0x40, 0x20, 0x00, 0x00,
};
/* 807B4600-807B4604 0004 .rodata    @5127                                                        */
SECTION_RODATA const u8 LIT_5127[4] = {
	0x43, 0x2A, 0x00, 0x00,
};
/* 807B4604-807B4608 0004 .rodata    @5128                                                        */
SECTION_RODATA const u8 LIT_5128[4] = {
	0xC2, 0xA0, 0x00, 0x00,
};
/* 807B4608-807B460C 0004 .rodata    @5129                                                        */
SECTION_RODATA const u8 LIT_5129[4] = {
	0xC3, 0x48, 0x00, 0x00,
};
/* 807B460C-807B4610 0004 .rodata    @5130                                                        */
SECTION_RODATA const u8 LIT_5130[4] = {
	0x42, 0x8C, 0x00, 0x00,
};
/* 807B4610-807B4614 0004 .rodata    @5131                                                        */
SECTION_RODATA const u8 LIT_5131[4] = {
	0x41, 0xC8, 0x00, 0x00,
};
/* 807B4614-807B4618 0004 .rodata    @5132                                                        */
SECTION_RODATA const u8 LIT_5132[4] = {
	0xC2, 0x5C, 0x00, 0x00,
};
/* 807B4618-807B461C 0004 .rodata    @5191                                                        */
SECTION_RODATA const u8 LIT_5191[4] = {
	0x42, 0x34, 0x00, 0x00,
};
/* 807B461C-807B4620 0004 .rodata    @5192                                                        */
SECTION_RODATA const u8 LIT_5192[4] = {
	0x40, 0xE0, 0x00, 0x00,
};
/* 807B4620-807B4624 0004 .rodata    @5193                                                        */
SECTION_RODATA const u8 LIT_5193[4] = {
	0x41, 0x90, 0x00, 0x00,
};
/* 807B4624-807B4628 0004 .rodata    @5312                                                        */
SECTION_RODATA const u8 LIT_5312[4] = {
	0x42, 0x96, 0x00, 0x00,
};
/* 807B4628-807B462C 0004 .rodata    @5313                                                        */
SECTION_RODATA const u8 LIT_5313[4] = {
	0xC7, 0x43, 0x50, 0x00,
};
/* 807B462C-807B4630 0004 .rodata    @5314                                                        */
SECTION_RODATA const u8 LIT_5314[4] = {
	0x46, 0x9C, 0x40, 0x00,
};
/* 807B4630-807B4634 0004 .rodata    @5315                                                        */
SECTION_RODATA const u8 LIT_5315[4] = {
	0x46, 0x8C, 0xA0, 0x00,
};
/* 807B4634-807B4638 0004 .rodata    @5316                                                        */
SECTION_RODATA const u8 LIT_5316[4] = {
	0x42, 0x20, 0x00, 0x00,
};
/* 807B4638-807B463C 0004 .rodata    @5317                                                        */
SECTION_RODATA const u8 LIT_5317[4] = {
	0xC1, 0xA0, 0x00, 0x00,
};
/* 807B463C-807B4640 0004 .rodata    @5526                                                        */
SECTION_RODATA const u8 LIT_5526[4] = {
	0xC3, 0xFA, 0x00, 0x00,
};
/* 807B4640-807B4644 0004 .rodata    @5527                                                        */
SECTION_RODATA const u8 LIT_5527[4] = {
	0x47, 0x7F, 0xFF, 0x00,
};
}


/* ###################################################################################### */
/*                                         .data                                          */
/* ###################################################################################### */

extern "C" {
/* 807B464C-807B464C 0000 .data      ...data.0                                                    */
/* 807B464C-807B4658 000C .data      cNullVec__6Z2Calc                                            */
SECTION_DATA u8 cNullVec__6Z2Calc[12] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 807B4658-807B466C 0004 .data      @1787                                                        */
SECTION_DATA u8 LIT_1787[20] = {
	0x02, 0x00, 0x02, 0x01,
	/* padding */
	0x40, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x3F, 0xE0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 807B466C-807B4674 0008 .data      e_prim$3785                                                  */
SECTION_DATA u8 data_807B466C[8] = {
	0xFF, 0x78, 0x00, 0x00, 0xFF, 0x64, 0x78, 0x00,
};
/* 807B4674-807B467C 0008 .data      e_env$3786                                                   */
SECTION_DATA u8 data_807B4674[8] = {
	0x5A, 0x2D, 0x2D, 0x00, 0x3C, 0x1E, 0x1E, 0x00,
};
/* 807B467C-807B4684 0006 .data      eff_id$3794                                                  */
SECTION_DATA u8 data_807B467C[8] = {
	0x02, 0x9D, 0x02, 0x9E, 0x02, 0x9F,
	/* padding */
	0x00, 0x00,
};
/* 807B4684-807B4688 0004 .data      l_color$4083                                                 */
SECTION_DATA u8 data_807B4684[4] = {
	0x50, 0x0A, 0x0A, 0xFF,
};
/* 807B4688-807B46B4 002C .data      @4357                                                        */
SECTION_DATA u8 LIT_4357[44] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 807B46B4-807B471C 0068 .data      @4682                                                        */
SECTION_DATA u8 LIT_4682[104] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 807B471C-807B4754 0038 .data      @5133                                                        */
SECTION_DATA u8 LIT_5133[56] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 807B4754-807B4794 0040 .data      cc_sph_src$5396                                              */
SECTION_DATA u8 data_807B4754[64] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0xD8, 0xFB, 0xFD, 0xFF, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x75, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x42, 0x20, 0x00, 0x00,
};
/* 807B4794-807B47B4 0020 .data      l_daE_TH_Method                                              */
SECTION_DATA u8 l_daE_TH_Method[32] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 807B47B4-807B47E4 0030 .data      g_profile_E_TH                                               */
SECTION_DATA u8 g_profile_E_TH[48] = {
	0xFF, 0xFF, 0xFF, 0xFD, 0x00, 0x07, 0xFF, 0xFD, 0x01, 0xC2, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x12, 0x3C, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x86, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x01, 0x00, 0x02, 0x0E, 0x00, 0x00,
};
/* 807B47E4-807B47F0 000C .data      __vt__12dBgS_AcchCir                                         */
SECTION_DATA void* __vt__12dBgS_AcchCir[3] = {
	NULL, /* RTTI */
	NULL,
	NULL,
};
/* 807B47F0-807B47FC 000C .data      __vt__10cCcD_GStts                                           */
SECTION_DATA void* __vt__10cCcD_GStts[3] = {
	NULL, /* RTTI */
	NULL,
	NULL,
};
/* 807B47FC-807B4808 000C .data      __vt__10dCcD_GStts                                           */
SECTION_DATA void* __vt__10dCcD_GStts[3] = {
	NULL, /* RTTI */
	NULL,
	NULL,
};
/* 807B4808-807B4814 000C .data      __vt__8cM3dGAab                                              */
SECTION_DATA void* __vt__8cM3dGAab[3] = {
	NULL, /* RTTI */
	NULL,
	NULL,
};
/* 807B4814-807B4820 000C .data      __vt__8cM3dGSph                                              */
SECTION_DATA void* __vt__8cM3dGSph[3] = {
	NULL, /* RTTI */
	NULL,
	NULL,
};
/* 807B4820-807B4834 0014 .data      __vt__18mDoExt_3DlineMat_c                                   */
SECTION_DATA void* __vt__18mDoExt_3DlineMat_c[5] = {
	NULL, /* RTTI */
	NULL,
	NULL,
	NULL,
	NULL,
};
/* 807B4834-807B4858 0024 .data      __vt__12dBgS_ObjAcch                                         */
SECTION_DATA void* __vt__12dBgS_ObjAcch[9] = {
	NULL, /* RTTI */
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
};
/* 807B4858-807B4864 000C .data      __vt__12daE_TH_HIO_c                                         */
SECTION_DATA void* __vt__12daE_TH_HIO_c[3] = {
	NULL, /* RTTI */
	NULL,
	NULL,
};
}


/* ###################################################################################### */
/*                                          .bss                                          */
/* ###################################################################################### */

extern "C" {
/* 807B4874-807B4878 0004 .bss       None                                                         */
SECTION_BSS u8 d_a_e_th__data_807B4874[4];
/* 807B4878-807B4884 000C .bss       @3922                                                        */
SECTION_BSS u8 LIT_3922[12];
/* 807B4884-807B489C 0018 .bss       l_HIO                                                        */
SECTION_BSS u8 l_HIO[24];
}


/* ###################################################################################### */
/*                                         .text                                          */
/* ###################################################################################### */

/* 807B038C-807B03C4 0038 .text      __ct__12daE_TH_HIO_cFv                                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __ct__12daE_TH_HIO_cFv() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/__ct__12daE_TH_HIO_cFv.s"
}
#pragma pop

/* 807B03C4-807B0434 0070 .text      s_md_sub1__FPvPv                                             */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void s_md_sub1__FPvPv() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/s_md_sub1__FPvPv.s"
}
#pragma pop

/* 807B0434-807B04A4 0070 .text      s_md_sub2__FPvPv                                             */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void s_md_sub2__FPvPv() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/s_md_sub2__FPvPv.s"
}
#pragma pop

/* 807B04A4-807B0550 00AC .text      anm_init__FP10e_th_classifUcf                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void anm_init__FP10e_th_classifUcf() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/anm_init__FP10e_th_classifUcf.s"
}
#pragma pop

/* 807B0550-807B0630 00E0 .text      nodeCallBack__FP8J3DJointi                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void nodeCallBack__FP8J3DJointi() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/nodeCallBack__FP8J3DJointi.s"
}
#pragma pop

/* 807B0630-807B09A4 0374 .text      ke_control__FP10e_th_classP7th_ke_si                         */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void ke_control__FP10e_th_classP7th_ke_si() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/ke_control__FP10e_th_classP7th_ke_si.s"
}
#pragma pop

/* 807B09A4-807B09E8 0044 .text      ke_pos_set__FP10e_th_classP7th_ke_si                         */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void ke_pos_set__FP10e_th_classP7th_ke_si() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/ke_pos_set__FP10e_th_classP7th_ke_si.s"
}
#pragma pop

/* 807B09E8-807B0A6C 0084 .text      ke_disp__FP10e_th_class                                      */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void ke_disp__FP10e_th_class() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/ke_disp__FP10e_th_class.s"
}
#pragma pop

/* 807B0A6C-807B0BD0 0164 .text      ke_move__FP10e_th_class                                      */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void ke_move__FP10e_th_class() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/ke_move__FP10e_th_class.s"
}
#pragma pop

/* 807B0BD0-807B0D7C 01AC .text      daE_TH_Draw__FP10e_th_class                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daE_TH_Draw__FP10e_th_class() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/daE_TH_Draw__FP10e_th_class.s"
}
#pragma pop

/* 807B0D7C-807B0EFC 0180 .text      e_th_wait__FP10e_th_class                                    */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void e_th_wait__FP10e_th_class() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/e_th_wait__FP10e_th_class.s"
}
#pragma pop

/* 807B0EFC-807B0F20 0024 .text      e_th_spin__FP10e_th_class                                    */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void e_th_spin__FP10e_th_class() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/e_th_spin__FP10e_th_class.s"
}
#pragma pop

/* 807B0F20-807B12B0 0390 .text      e_th_spin_B__FP10e_th_class                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void e_th_spin_B__FP10e_th_class() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/e_th_spin_B__FP10e_th_class.s"
}
#pragma pop

/* 807B12B0-807B141C 016C .text      e_th_shot__FP10e_th_class                                    */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void e_th_shot__FP10e_th_class() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/e_th_shot__FP10e_th_class.s"
}
#pragma pop

/* 807B141C-807B1670 0254 .text      e_th_return__FP10e_th_class                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void e_th_return__FP10e_th_class() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/e_th_return__FP10e_th_class.s"
}
#pragma pop

/* 807B1670-807B176C 00FC .text      e_th_damage__FP10e_th_class                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void e_th_damage__FP10e_th_class() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/e_th_damage__FP10e_th_class.s"
}
#pragma pop

/* 807B176C-807B18C0 0154 .text      e_th_start__FP10e_th_class                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void e_th_start__FP10e_th_class() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/e_th_start__FP10e_th_class.s"
}
#pragma pop

/* 807B18C0-807B19AC 00EC .text      e_th_end__FP10e_th_class                                     */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void e_th_end__FP10e_th_class() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/e_th_end__FP10e_th_class.s"
}
#pragma pop

/* 807B19AC-807B1B78 01CC .text      damage_check__FP10e_th_class                                 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void damage_check__FP10e_th_class() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/damage_check__FP10e_th_class.s"
}
#pragma pop

/* 807B1B78-807B1EB4 033C .text      action__FP10e_th_class                                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void action__FP10e_th_class() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/action__FP10e_th_class.s"
}
#pragma pop

/* 807B1EB4-807B1F98 00E4 .text      cam_3d_morf__FP10e_th_classf                                 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void cam_3d_morf__FP10e_th_classf() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/cam_3d_morf__FP10e_th_classf.s"
}
#pragma pop

/* 807B1F98-807B2DEC 0E54 .text      demo_camera__FP10e_th_class                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void demo_camera__FP10e_th_class() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/demo_camera__FP10e_th_class.s"
}
#pragma pop

/* 807B2DEC-807B300C 0220 .text      anm_se_set__FP10e_th_class                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void anm_se_set__FP10e_th_class() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/anm_se_set__FP10e_th_class.s"
}
#pragma pop

/* 807B300C-807B3514 0508 .text      daE_TH_Execute__FP10e_th_class                               */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daE_TH_Execute__FP10e_th_class() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/daE_TH_Execute__FP10e_th_class.s"
}
#pragma pop

/* 807B3514-807B351C 0008 .text      daE_TH_IsDelete__FP10e_th_class                              */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daE_TH_IsDelete__FP10e_th_class() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/daE_TH_IsDelete__FP10e_th_class.s"
}
#pragma pop

/* 807B351C-807B3584 0068 .text      daE_TH_Delete__FP10e_th_class                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daE_TH_Delete__FP10e_th_class() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/daE_TH_Delete__FP10e_th_class.s"
}
#pragma pop

/* 807B3584-807B36D0 014C .text      useHeapInit__FP10fopAc_ac_c                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void useHeapInit__FP10fopAc_ac_c() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/useHeapInit__FP10fopAc_ac_c.s"
}
#pragma pop

/* 807B36D0-807B3B58 0488 .text      daE_TH_Create__FP10fopAc_ac_c                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daE_TH_Create__FP10fopAc_ac_c() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/daE_TH_Create__FP10fopAc_ac_c.s"
}
#pragma pop

/* 807B3B58-807B3BD4 007C .text      __dt__7th_ke_sFv                                             */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__7th_ke_sFv() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/__dt__7th_ke_sFv.s"
}
#pragma pop

/* 807B3BD4-807B3C3C 0068 .text      __ct__7th_ke_sFv                                             */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __ct__7th_ke_sFv() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/__ct__7th_ke_sFv.s"
}
#pragma pop

/* 807B3C3C-807B3C40 0004 .text      __ct__4cXyzFv                                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __ct__4cXyzFv() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/__ct__4cXyzFv.s"
}
#pragma pop

/* 807B3C40-807B3D0C 00CC .text      __dt__8dCcD_SphFv                                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__8dCcD_SphFv() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/__dt__8dCcD_SphFv.s"
}
#pragma pop

/* 807B3D0C-807B3D90 0084 .text      __ct__8dCcD_SphFv                                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __ct__8dCcD_SphFv() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/__ct__8dCcD_SphFv.s"
}
#pragma pop

/* 807B3D90-807B3DD8 0048 .text      __dt__8cM3dGSphFv                                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__8cM3dGSphFv() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/__dt__8cM3dGSphFv.s"
}
#pragma pop

/* 807B3DD8-807B3E20 0048 .text      __dt__8cM3dGAabFv                                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__8cM3dGAabFv() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/__dt__8cM3dGAabFv.s"
}
#pragma pop

/* 807B3E20-807B3E7C 005C .text      __dt__10dCcD_GSttsFv                                         */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__10dCcD_GSttsFv() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/__dt__10dCcD_GSttsFv.s"
}
#pragma pop

/* 807B3E7C-807B3EEC 0070 .text      __dt__12dBgS_ObjAcchFv                                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__12dBgS_ObjAcchFv() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/__dt__12dBgS_ObjAcchFv.s"
}
#pragma pop

/* 807B3EEC-807B3F5C 0070 .text      __dt__12dBgS_AcchCirFv                                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__12dBgS_AcchCirFv() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/__dt__12dBgS_AcchCirFv.s"
}
#pragma pop

/* 807B3F5C-807B3FA4 0048 .text      __dt__10cCcD_GSttsFv                                         */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__10cCcD_GSttsFv() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/__dt__10cCcD_GSttsFv.s"
}
#pragma pop

/* 807B3FA4-807B3FEC 0048 .text      __dt__12daE_TH_HIO_cFv                                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__12daE_TH_HIO_cFv() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/__dt__12daE_TH_HIO_cFv.s"
}
#pragma pop

/* 807B3FEC-807B4028 003C .text      __sinit_d_a_e_th_cpp                                         */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __sinit_d_a_e_th_cpp() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/__sinit_d_a_e_th_cpp.s"
}
#pragma pop

/* 807B4028-807B4030 0008 .text      @36@__dt__12dBgS_ObjAcchFv                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void func_807B4028() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/func_807B4028.s"
}
#pragma pop

/* 807B4030-807B4038 0008 .text      @20@__dt__12dBgS_ObjAcchFv                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void func_807B4030() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/func_807B4030.s"
}
#pragma pop

/* 807B4038-807B444C 0414 .text      setMidnaBindEffect__FP13fopEn_enemy_cP15Z2CreatureEnemyP4cXyzP4cXyz */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void setMidnaBindEffect__FP13fopEn_enemy_cP15Z2CreatureEnemyP4cXyzP4cXyz() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/setMidnaBindEffect__FP13fopEn_enemy_cP15Z2CreatureEnemyP4cXyzP4cXyz.s"
}
#pragma pop

/* 807B444C-807B4488 003C .text      __dt__4cXyzFv                                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__4cXyzFv() {
	nofralloc
#include "asm/rel/d_a_e_th/d_a_e_th/__dt__4cXyzFv.s"
}
#pragma pop


