// 
// Generated By: dol2asm
// 

// 
// Compiler Options: -str pool,readonly,reuse
// 

#include "dolphin/types.h"

// 
// Additional Symbols:
// 

struct JKRHeap;

extern void* operator new(u32, JKRHeap*, int); /* __nw__FUlP7JKRHeapi */
extern void operator delete(void*); /* __dl__FPv */

extern "C" {
extern void OSReport();
extern void alloc__7JKRHeapFUliP7JKRHeap();
extern void __nw__FUlP7JKRHeapi();
extern void __dl__FPv();
extern void __ct__11JKRDisposerFv();
extern void __dt__11JKRDisposerFv();
extern void Insert__Q27JGadget13TNodeLinkListFQ37JGadget13TNodeLinkList8iteratorPQ27JGadget13TLinkListNode();
extern void Remove__Q27JGadget13TNodeLinkListFPQ27JGadget13TLinkListNode();
extern void setCharColor__7JUTFontFQ28JUtility6TColor();
extern void drawString_size_scale__7JUTFontFffffPCcUlb();
extern void erase__14JUTDirectPrintFiiii();
extern void drawString__14JUTDirectPrintFUsUsPc();
extern void setCharColor__14JUTDirectPrintFQ28JUtility6TColor();
extern void __ct__10JUTConsoleFUiUib();
extern void __dt__10JUTConsoleFv();
extern void getObjectSizeFromBufferSize__10JUTConsoleFUiUi();
extern void getLineFromObjectSize__10JUTConsoleFUlUi();
extern void clear__10JUTConsoleFv();
extern void doDraw__10JUTConsoleCFQ210JUTConsole12EConsoleType();
extern void print__10JUTConsoleFPCc();
extern void JUTConsole_print_f_va_();
extern void __ct__17JUTConsoleManagerFv();
extern void appendConsole__17JUTConsoleManagerFP10JUTConsole();
extern void removeConsole__17JUTConsoleManagerFP10JUTConsole();
extern void JUTSetReportConsole();
extern u32 JUTGetReportConsole();
extern void JUTSetWarningConsole();
extern u32 JUTGetWarningConsole();
extern void JUTReportConsole_f_va();
extern void JUTReportConsole_f();
extern void __ct__13J2DOrthoGraphFffffff();
extern void setPort__13J2DOrthoGraphFv();
extern void J2DFillBox__FffffQ28JUtility6TColor();
extern void OSEnableInterrupts();
extern void OSRestoreInterrupts();
extern u32 VIGetRetraceCount();
extern void _savegpr_20();
extern void _savegpr_27();
extern void _savegpr_28();
extern void _savegpr_29();
extern void _restgpr_20();
extern void _restgpr_27();
extern void _restgpr_28();
extern void _restgpr_29();
extern void vsnprintf();
extern void strlen();
SECTION_RODATA extern const u8 JUTConsole__stringBase0[120];
SECTION_DATA extern const void* __vt__10JUTConsole[4];
SECTION_DATA extern const void* __vt__14J2DGrafContext[10];
SECTION_DATA extern const void* __vt__13J2DOrthoGraph[10];
SECTION_SBSS extern u8 sCurrentHeap__7JKRHeap[4];
SECTION_SBSS extern u8 sDirectPrint__14JUTDirectPrint[4];
SECTION_SBSS extern u8 sManager__8JUTVideo[4];
SECTION_SBSS extern u8 sManager__17JUTConsoleManager[4];
SECTION_SBSS extern u8 sReportConsole[4];
SECTION_SBSS extern u8 sWarningConsole[4];
SECTION_SDATA2 extern f32 JUTConsole__LIT_2460;
SECTION_SDATA2 extern u8 JUTConsole__LIT_2461[4];
SECTION_SDATA2 extern f32 LIT_2462;
SECTION_SDATA2 extern f32 LIT_2463;
SECTION_SDATA2 extern f32 LIT_2464;
SECTION_SDATA2 extern f32 LIT_2465;
SECTION_SDATA2 extern u8 JUTConsole__LIT_2466[8];
SECTION_SDATA2 extern f64 LIT_2469;
SECTION_SDATA2 extern f64 LIT_2471;
}


/* ###################################################################################### */
/*                                        .rodata                                         */
/* ###################################################################################### */

extern "C" {
/* 8039D9A8 0063 .rodata    @stringBase0                                                 */
const char* const stringBase_8039D9A8 = "[%03d] %s\n";
const char* const stringBase_8039D9B3 = "%s\n";
const char* const stringBase_8039D9B7 = 
    "\n:::dump of console[%x]---------"
    "-------\n";
const char* const stringBase_8039D9E0 = 
    ":::dump of console[%x] END------"
    "------\n";
const char* const stringBase_8039DA08 = "%s";
}


/* ###################################################################################### */
/*                                         .data                                          */
/* ###################################################################################### */

extern "C" {
/* 803CC9A8 000C .data      __vt__10JUTConsole                                           */
SECTION_DATA const  void* __vt__10JUTConsole[4] = {
	NULL, /* RTTI */
	NULL,
	(void*)__dt__10JUTConsoleFv,
	/* padding */
	NULL,
};
}


/* ###################################################################################### */
/*                                        .sdata2                                         */
/* ###################################################################################### */

extern "C" {
/* 80456118 0004 .sdata2    @2460                                                        */
// 0x40000000
SECTION_SDATA2 f32 JUTConsole__LIT_2460 = 2.000000f;
/* 8045611C 0004 .sdata2    @2461                                                        */
SECTION_SDATA2 u8 JUTConsole__LIT_2461[4] = {
	0x00, 0x00, 0x00, 0x00,
};
/* 80456120 0004 .sdata2    @2462                                                        */
// 0x44200000
SECTION_SDATA2 f32 LIT_2462 = 640.000000f;
/* 80456124 0004 .sdata2    @2463                                                        */
// 0x43f00000
SECTION_SDATA2 f32 LIT_2463 = 480.000000f;
/* 80456128 0004 .sdata2    @2464                                                        */
// 0xbf800000
SECTION_SDATA2 f32 LIT_2464 = -1.000000f;
/* 8045612C 0004 .sdata2    @2465                                                        */
// 0x3f800000
SECTION_SDATA2 f32 LIT_2465 = 1.000000f;
/* 80456130 0004 .sdata2    @2466                                                        */
SECTION_SDATA2 u8 JUTConsole__LIT_2466[8] = {
	0x40, 0x80, 0x00, 0x00,
	/* padding */
	0x00, 0x00, 0x00, 0x00,
};
/* 80456138 0008 .sdata2    @2469                                                        */
// 0x4330000000000000 | compiler-generated value used in cast: (float)u32
SECTION_SDATA2 f64 LIT_2469 = 4503599627370496.000000;
/* 80456140 0008 .sdata2    @2471                                                        */
// 0x4330000080000000 | compiler-generated value used in cast: (float)s32
SECTION_SDATA2 f64 LIT_2471 = 4503601774854144.000000;
}


/* ###################################################################################### */
/*                                         .sbss                                          */
/* ###################################################################################### */

extern "C" {
/* 80451570 0004 .sbss      sManager__17JUTConsoleManager                                */
SECTION_SBSS u8 sManager__17JUTConsoleManager[4];
/* 80451574 0004 .sbss      sReportConsole                                               */
SECTION_SBSS u8 sReportConsole[4];
/* 80451578 0004 .sbss      sWarningConsole                                              */
SECTION_SBSS u8 sWarningConsole[4];
SECTION_SBSS u8 pad_8045157C[4];
}


/* ###################################################################################### */
/*                                         .text                                          */
/* ###################################################################################### */

extern "C" {
/* 802E7354 0090 .text      create__10JUTConsoleFUiUiP7JKRHeap                           */
// JUTConsole::create(unsigned int, unsigned int, JKRHeap*)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void create__10JUTConsoleFUiUiP7JKRHeap() {
	nofralloc
#include "_include/JUtility/JUTConsole/create__10JUTConsoleFUiUiP7JKRHeap.s"
}
#pragma pop

/* 802E73E4 0088 .text      create__10JUTConsoleFUiPvUl                                  */
// JUTConsole::create(unsigned int, void*, u32)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void create__10JUTConsoleFUiPvUl() {
	nofralloc
#include "_include/JUtility/JUTConsole/create__10JUTConsoleFUiPvUl.s"
}
#pragma pop

/* 802E746C 00F0 .text      __ct__10JUTConsoleFUiUib                                     */
// JUTConsole::JUTConsole(unsigned int, unsigned int, bool)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __ct__10JUTConsoleFUiUib() {
	nofralloc
#include "_include/JUtility/JUTConsole/__ct__10JUTConsoleFUiUib.s"
}
#pragma pop

/* 802E755C 0070 .text      __dt__10JUTConsoleFv                                         */
// JUTConsole::~JUTConsole(void)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__10JUTConsoleFv() {
	nofralloc
#include "_include/JUtility/JUTConsole/__dt__10JUTConsoleFv.s"
}
#pragma pop

/* 802E75CC 0010 .text      getObjectSizeFromBufferSize__10JUTConsoleFUiUi               */
// JUTConsole::getObjectSizeFromBufferSize(unsigned int, unsigned int)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void getObjectSizeFromBufferSize__10JUTConsoleFUiUi() {
	nofralloc
#include "_include/JUtility/JUTConsole/getObjectSizeFromBufferSize__10JUTConsoleFUiUi.s"
}
#pragma pop

/* 802E75DC 0010 .text      getLineFromObjectSize__10JUTConsoleFUlUi                     */
// JUTConsole::getLineFromObjectSize(u32, unsigned int)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void getLineFromObjectSize__10JUTConsoleFUlUi() {
	nofralloc
#include "_include/JUtility/JUTConsole/getLineFromObjectSize__10JUTConsoleFUlUi.s"
}
#pragma pop

/* 802E75EC 005C .text      clear__10JUTConsoleFv                                        */
// JUTConsole::clear(void)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void clear__10JUTConsoleFv() {
	nofralloc
#include "_include/JUtility/JUTConsole/clear__10JUTConsoleFv.s"
}
#pragma pop

/* 802E7648 0570 .text      doDraw__10JUTConsoleCFQ210JUTConsole12EConsoleType           */
// JUTConsole::doDraw(JUTConsole::EConsoleType) const
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void doDraw__10JUTConsoleCFQ210JUTConsole12EConsoleType() {
	nofralloc
#include "_include/JUtility/JUTConsole/doDraw__10JUTConsoleCFQ210JUTConsole12EConsoleType.s"
}
#pragma pop

/* 802E7BB8 0080 .text      print_f__10JUTConsoleFPCce                                   */
// JUTConsole::print_f(const s8*, ...)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void print_f__10JUTConsoleFPCce() {
	nofralloc
#include "_include/JUtility/JUTConsole/print_f__10JUTConsoleFPCce.s"
}
#pragma pop

/* 802E7C38 02F8 .text      print__10JUTConsoleFPCc                                      */
// JUTConsole::print(const s8*)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void print__10JUTConsoleFPCc() {
	nofralloc
#include "_include/JUtility/JUTConsole/print__10JUTConsoleFPCc.s"
}
#pragma pop

/* 802E7F30 004C .text      JUTConsole_print_f_va_                                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void JUTConsole_print_f_va_() {
	nofralloc
#include "_include/JUtility/JUTConsole/JUTConsole_print_f_va_.s"
}
#pragma pop

/* 802E7F7C 012C .text      dumpToTerminal__10JUTConsoleFUi                              */
// JUTConsole::dumpToTerminal(unsigned int)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void dumpToTerminal__10JUTConsoleFUi() {
	nofralloc
#include "_include/JUtility/JUTConsole/dumpToTerminal__10JUTConsoleFUi.s"
}
#pragma pop

/* 802E80A8 00DC .text      scroll__10JUTConsoleFi                                       */
// JUTConsole::scroll(int)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void scroll__10JUTConsoleFi() {
	nofralloc
#include "_include/JUtility/JUTConsole/scroll__10JUTConsoleFi.s"
}
#pragma pop

/* 802E8184 0024 .text      getUsedLine__10JUTConsoleCFv                                 */
// JUTConsole::getUsedLine(void) const
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void getUsedLine__10JUTConsoleCFv() {
	nofralloc
#include "_include/JUtility/JUTConsole/getUsedLine__10JUTConsoleCFv.s"
}
#pragma pop

/* 802E81A8 0024 .text      getLineOffset__10JUTConsoleCFv                               */
// JUTConsole::getLineOffset(void) const
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void getLineOffset__10JUTConsoleCFv() {
	nofralloc
#include "_include/JUtility/JUTConsole/getLineOffset__10JUTConsoleCFv.s"
}
#pragma pop

/* 802E81CC 0028 .text      __ct__17JUTConsoleManagerFv                                  */
// JUTConsoleManager::JUTConsoleManager(void)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __ct__17JUTConsoleManagerFv() {
	nofralloc
#include "_include/JUtility/JUTConsole/__ct__17JUTConsoleManagerFv.s"
}
#pragma pop

/* 802E81F4 004C .text      createManager__17JUTConsoleManagerFP7JKRHeap                 */
// JUTConsoleManager::createManager(JKRHeap*)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void createManager__17JUTConsoleManagerFP7JKRHeap() {
	nofralloc
#include "_include/JUtility/JUTConsole/createManager__17JUTConsoleManagerFP7JKRHeap.s"
}
#pragma pop

/* 802E8240 0070 .text      appendConsole__17JUTConsoleManagerFP10JUTConsole             */
// JUTConsoleManager::appendConsole(JUTConsole*)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void appendConsole__17JUTConsoleManagerFP10JUTConsole() {
	nofralloc
#include "_include/JUtility/JUTConsole/appendConsole__17JUTConsoleManagerFP10JUTConsole.s"
}
#pragma pop

/* 802E82B0 00D4 .text      removeConsole__17JUTConsoleManagerFP10JUTConsole             */
// JUTConsoleManager::removeConsole(JUTConsole*)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void removeConsole__17JUTConsoleManagerFP10JUTConsole() {
	nofralloc
#include "_include/JUtility/JUTConsole/removeConsole__17JUTConsoleManagerFP10JUTConsole.s"
}
#pragma pop

/* 802E8384 00CC .text      draw__17JUTConsoleManagerCFv                                 */
// JUTConsoleManager::draw(void) const
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void draw__17JUTConsoleManagerCFv() {
	nofralloc
#include "_include/JUtility/JUTConsole/draw__17JUTConsoleManagerCFv.s"
}
#pragma pop

/* 802E8450 0074 .text      drawDirect__17JUTConsoleManagerCFb                           */
// JUTConsoleManager::drawDirect(bool) const
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void drawDirect__17JUTConsoleManagerCFb() {
	nofralloc
#include "_include/JUtility/JUTConsole/drawDirect__17JUTConsoleManagerCFb.s"
}
#pragma pop

/* 802E84C4 005C .text      setDirectConsole__17JUTConsoleManagerFP10JUTConsole          */
// JUTConsoleManager::setDirectConsole(JUTConsole*)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void setDirectConsole__17JUTConsoleManagerFP10JUTConsole() {
	nofralloc
#include "_include/JUtility/JUTConsole/setDirectConsole__17JUTConsoleManagerFP10JUTConsole.s"
}
#pragma pop

/* 802E8520 0008 .text      JUTSetReportConsole                                          */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void JUTSetReportConsole() {
	nofralloc
#include "_include/JUtility/JUTConsole/JUTSetReportConsole.s"
}
#pragma pop

/* 802E8528 0008 .text      JUTGetReportConsole                                          */
u32 JUTGetReportConsole() {
	return *(u32*)&sReportConsole;
}

/* 802E8530 0008 .text      JUTSetWarningConsole                                         */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void JUTSetWarningConsole() {
	nofralloc
#include "_include/JUtility/JUTConsole/JUTSetWarningConsole.s"
}
#pragma pop

/* 802E8538 0008 .text      JUTGetWarningConsole                                         */
u32 JUTGetWarningConsole() {
	return *(u32*)&sWarningConsole;
}

/* 802E8540 0088 .text      JUTReportConsole_f_va                                        */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void JUTReportConsole_f_va() {
	nofralloc
#include "_include/JUtility/JUTConsole/JUTReportConsole_f_va.s"
}
#pragma pop

/* 802E85C8 0080 .text      JUTReportConsole_f                                           */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void JUTReportConsole_f() {
	nofralloc
#include "_include/JUtility/JUTConsole/JUTReportConsole_f.s"
}
#pragma pop

/* 802E8648 0034 .text      JUTReportConsole                                             */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void JUTReportConsole() {
	nofralloc
#include "_include/JUtility/JUTConsole/JUTReportConsole.s"
}
#pragma pop

/* 802E867C 0080 .text      JUTWarningConsole_f                                          */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void JUTWarningConsole_f() {
	nofralloc
#include "_include/JUtility/JUTConsole/JUTWarningConsole_f.s"
}
#pragma pop

/* 802E86FC 0034 .text      JUTWarningConsole                                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void JUTWarningConsole() {
	nofralloc
#include "_include/JUtility/JUTConsole/JUTWarningConsole.s"
}
#pragma pop

}

