// 
// Generated By: dol2asm
// Translation Unit: unknown_translation_unit_ctors
// 

#include "dol2asm.h"
#include "dolphin/types.h"
#include "rel/d/a/e/d_a_e_fb/unknown_translation_unit_ctors.h"

// 
// Forward References:
// 


extern u8 data_806B8F78[8];

// 
// External References:
// 



// 
// Declarations:
// 

/* ############################################################################################## */
#pragma section ".ctors$10"
