// 
// Generated By: dol2asm
// 

#include "dolphin/types.h"

// 
// Additional Symbols:
// 

extern "C" {
extern void _unresolved();
extern void initWait__13daTagTWGate_cFv();
extern void executeWait__13daTagTWGate_cFv();
extern void initDemoFilone1__13daTagTWGate_cFv();
extern void executeDemoFilone1__13daTagTWGate_cFv();
extern void initDemoFilone2__13daTagTWGate_cFv();
extern void executeDemoFilone2__13daTagTWGate_cFv();
extern void initDemoFilone3__13daTagTWGate_cFv();
extern void executeDemoFilone3__13daTagTWGate_cFv();
extern void initDemoOrdin1__13daTagTWGate_cFv();
extern void executeDemoOrdin1__13daTagTWGate_cFv();
extern void initDemoOrdin2__13daTagTWGate_cFv();
extern void executeDemoOrdin2__13daTagTWGate_cFv();
extern void initDemoOrdin3__13daTagTWGate_cFv();
extern void executeDemoOrdin3__13daTagTWGate_cFv();
extern void initDemoRanail1__13daTagTWGate_cFv();
extern void executeDemoRanail1__13daTagTWGate_cFv();
extern void initDemoRanail2__13daTagTWGate_cFv();
extern void executeDemoRanail2__13daTagTWGate_cFv();
extern void initDemoRanail3__13daTagTWGate_cFv();
extern void executeDemoRanail3__13daTagTWGate_cFv();
extern void initDemoHyral1__13daTagTWGate_cFv();
extern void executeDemoHyral1__13daTagTWGate_cFv();
extern void initDemoHyral2__13daTagTWGate_cFv();
extern void executeDemoHyral2__13daTagTWGate_cFv();
extern void initDemoHyral3__13daTagTWGate_cFv();
extern void executeDemoHyral3__13daTagTWGate_cFv();
extern void initBaseMtx__13daTagTWGate_cFv();
extern void downloadModels__13daTagTWGate_cFv();
extern void initTalk__13daTagTWGate_cFiPP10fopAc_ac_c();
extern void talkProc__13daTagTWGate_cFPiiPP10fopAc_ac_c();
extern void createHeapCallBack__13daTagTWGate_cFP10fopAc_ac_c();
extern void CreateHeap__13daTagTWGate_cFv();
extern void daTagTWGate_Create__FP10fopAc_ac_c();
extern void daTagTWGate_Delete__FP13daTagTWGate_c();
extern void daTagTWGate_Execute__FP13daTagTWGate_c();
extern void daTagTWGate_Draw__FP13daTagTWGate_c();
extern void daTagTWGate_IsDelete__FP13daTagTWGate_c();
extern void __sinit_d_a_tag_TWgate_cpp();
extern const u8 unknown_translation_unit_ctors__data_80D557A0[8];
extern const u8 unknown_translation_unit_dtors__data_80D557A8[4];
SECTION_RODATA extern const u8 mAttr__13daTagTWGate_c[4];
SECTION_RODATA extern const u8 l_zevParamTbl[112];
SECTION_RODATA extern const u8 LIT_3857[4];
SECTION_RODATA extern const u8 LIT_3858[8];
SECTION_RODATA extern const u8 LIT_4079[4];
SECTION_RODATA extern const u8 LIT_4080[4];
SECTION_RODATA extern const u8 LIT_4081[4];
SECTION_RODATA extern const u8 LIT_4082[4];
SECTION_RODATA extern const u8 LIT_4083[4];
SECTION_RODATA extern const u8 LIT_4790[4];
SECTION_RODATA extern const u8 LIT_4791[4];
SECTION_RODATA extern const u8 stringBase0[297];
SECTION_DATA extern u8 cNullVec__6Z2Calc[12];
SECTION_DATA extern u8 LIT_1787[20];
SECTION_DATA extern u8 l_myName[4];
SECTION_DATA extern u8 LIT_3744[12];
SECTION_DATA extern u8 LIT_3745[12];
SECTION_DATA extern u8 LIT_3746[12];
SECTION_DATA extern u8 LIT_3747[12];
SECTION_DATA extern u8 LIT_3748[12];
SECTION_DATA extern u8 LIT_3749[12];
SECTION_DATA extern u8 LIT_3750[12];
SECTION_DATA extern u8 LIT_3751[12];
SECTION_DATA extern u8 LIT_3752[12];
SECTION_DATA extern u8 LIT_3753[12];
SECTION_DATA extern u8 LIT_3754[12];
SECTION_DATA extern u8 LIT_3755[12];
SECTION_DATA extern u8 LIT_3756[12];
SECTION_DATA extern u8 LIT_3757[12];
SECTION_DATA extern u8 LIT_3758[12];
SECTION_DATA extern u8 LIT_3759[12];
SECTION_DATA extern u8 LIT_3760[12];
SECTION_DATA extern u8 LIT_3761[12];
SECTION_DATA extern u8 LIT_3762[12];
SECTION_DATA extern u8 LIT_3763[12];
SECTION_DATA extern u8 LIT_3764[12];
SECTION_DATA extern u8 LIT_3765[12];
SECTION_DATA extern u8 LIT_3766[12];
SECTION_DATA extern u8 LIT_3767[12];
SECTION_DATA extern u8 LIT_3768[12];
SECTION_DATA extern u8 LIT_3769[12];
SECTION_DATA extern u8 ActionTable__13daTagTWGate_c[312];
SECTION_DATA extern u8 l_daTagTWGate_Method[32];
SECTION_DATA extern u8 g_profile_Tag_TWGate[48];
}


/* ###################################################################################### */
/*                                        .rodata                                         */
/* ###################################################################################### */

extern "C" {
/* 80D55848-80D55971 0129 .rodata    @stringBase0                                                 */
#pragma push
#pragma force_active on
#pragma section ".dead"
SECTION_DEAD const char* const stringBase_80D55848 = "TWGate_FL";
SECTION_DEAD const char* const stringBase_80D55852 = "TW_GATE_FILONE";
SECTION_DEAD const char* const stringBase_80D55861 = "TW_GATE_FILONE_TALK";
SECTION_DEAD const char* const stringBase_80D55875 = "TW_GATE_FILONE_IN";
SECTION_DEAD const char* const stringBase_80D55887 = "F_SP108";
SECTION_DEAD const char* const stringBase_80D5588F = "TWGate_OD";
SECTION_DEAD const char* const stringBase_80D55899 = "TW_GATE_ORDIN";
SECTION_DEAD const char* const stringBase_80D558A7 = "TW_GATE_ORDIN_TALK";
SECTION_DEAD const char* const stringBase_80D558BA = "TW_GATE_ORDIN_IN";
SECTION_DEAD const char* const stringBase_80D558CB = "F_SP121";
SECTION_DEAD const char* const stringBase_80D558D3 = "TWGate_RN";
SECTION_DEAD const char* const stringBase_80D558DD = "TW_GATE_RANAIL";
SECTION_DEAD const char* const stringBase_80D558EC = "TW_GATE_RANAIL_TALK";
SECTION_DEAD const char* const stringBase_80D55900 = "TW_GATE_RANAIL_IN";
SECTION_DEAD const char* const stringBase_80D55912 = "TWGate_HY";
SECTION_DEAD const char* const stringBase_80D5591C = "TW_GATE_HYRAL";
SECTION_DEAD const char* const stringBase_80D5592A = "TW_GATE_HYRAL_TALK";
SECTION_DEAD const char* const stringBase_80D5593D = "TW_GATE_HYRAL_IN";
SECTION_DEAD const char* const stringBase_80D5594E = "Gate";
SECTION_DEAD const char* const stringBase_80D55953 = "TWGate_Md";
SECTION_DEAD const char* const stringBase_80D5595D = "TWGate_Wf";
SECTION_DEAD const char* const stringBase_80D55967 = "TWGate_Lk";
#pragma pop
/* 80D557AC-80D557AC 0000 .rodata    ...rodata.0                                                  */
/* 80D557AC-80D557B0 0001 .rodata    mAttr__13daTagTWGate_c                                       */
SECTION_RODATA const u8 mAttr__13daTagTWGate_c[4] = {
	0x00,
	/* padding */
	0x00, 0x00, 0x00,
};
/* 80D557B0-80D55820 0070 .rodata    l_zevParamTbl                                                */
SECTION_RODATA const u8 l_zevParamTbl[112] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x17, 0x00, 0x0A, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x0A, 0x02, 0x0E, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x0A, 0x09, 0x0E, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0A, 0x02, 0x0E,
};
/* 80D55820-80D55824 0004 .rodata    @3857                                                        */
SECTION_RODATA const u8 LIT_3857[4] = {
	0x42, 0xC8, 0x00, 0x00,
};
/* 80D55824-80D5582C 0008 .rodata    @3858                                                        */
SECTION_RODATA const u8 LIT_3858[8] = {
	0x40, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80D5582C-80D55830 0004 .rodata    @4079                                                        */
SECTION_RODATA const u8 LIT_4079[4] = {
	0x3F, 0x80, 0x00, 0x00,
};
/* 80D55830-80D55834 0004 .rodata    @4080                                                        */
SECTION_RODATA const u8 LIT_4080[4] = {
	0x00, 0x00, 0x00, 0x00,
};
/* 80D55834-80D55838 0004 .rodata    @4081                                                        */
SECTION_RODATA const u8 LIT_4081[4] = {
	0x43, 0x70, 0x00, 0x00,
};
/* 80D55838-80D5583C 0004 .rodata    @4082                                                        */
SECTION_RODATA const u8 LIT_4082[4] = {
	0xC4, 0x31, 0x80, 0x00,
};
/* 80D5583C-80D55840 0004 .rodata    @4083                                                        */
SECTION_RODATA const u8 LIT_4083[4] = {
	0xBF, 0x80, 0x00, 0x00,
};
/* 80D55840-80D55844 0004 .rodata    @4790                                                        */
SECTION_RODATA const u8 LIT_4790[4] = {
	0x43, 0x7A, 0x00, 0x00,
};
/* 80D55844-80D55848 0004 .rodata    @4791                                                        */
SECTION_RODATA const u8 LIT_4791[4] = {
	0xC4, 0x52, 0x00, 0x00,
};
}


/* ###################################################################################### */
/*                                         .data                                          */
/* ###################################################################################### */

extern "C" {
/* 80D55974-80D55974 0000 .data      ...data.0                                                    */
/* 80D55974-80D55980 000C .data      cNullVec__6Z2Calc                                            */
SECTION_DATA u8 cNullVec__6Z2Calc[12] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80D55980-80D55994 0004 .data      @1787                                                        */
SECTION_DATA u8 LIT_1787[20] = {
	0x02, 0x00, 0x02, 0x01,
	/* padding */
	0x40, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x3F, 0xE0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80D55994-80D55998 0004 .data      l_myName                                                     */
SECTION_DATA u8 l_myName[4] = {
	0x00, 0x00, 0x00, 0x00,
};
/* 80D55998-80D559A4 000C .data      @3744                                                        */
SECTION_DATA u8 LIT_3744[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80D559A4-80D559B0 000C .data      @3745                                                        */
SECTION_DATA u8 LIT_3745[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80D559B0-80D559BC 000C .data      @3746                                                        */
SECTION_DATA u8 LIT_3746[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80D559BC-80D559C8 000C .data      @3747                                                        */
SECTION_DATA u8 LIT_3747[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80D559C8-80D559D4 000C .data      @3748                                                        */
SECTION_DATA u8 LIT_3748[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80D559D4-80D559E0 000C .data      @3749                                                        */
SECTION_DATA u8 LIT_3749[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80D559E0-80D559EC 000C .data      @3750                                                        */
SECTION_DATA u8 LIT_3750[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80D559EC-80D559F8 000C .data      @3751                                                        */
SECTION_DATA u8 LIT_3751[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80D559F8-80D55A04 000C .data      @3752                                                        */
SECTION_DATA u8 LIT_3752[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80D55A04-80D55A10 000C .data      @3753                                                        */
SECTION_DATA u8 LIT_3753[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80D55A10-80D55A1C 000C .data      @3754                                                        */
SECTION_DATA u8 LIT_3754[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80D55A1C-80D55A28 000C .data      @3755                                                        */
SECTION_DATA u8 LIT_3755[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80D55A28-80D55A34 000C .data      @3756                                                        */
SECTION_DATA u8 LIT_3756[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80D55A34-80D55A40 000C .data      @3757                                                        */
SECTION_DATA u8 LIT_3757[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80D55A40-80D55A4C 000C .data      @3758                                                        */
SECTION_DATA u8 LIT_3758[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80D55A4C-80D55A58 000C .data      @3759                                                        */
SECTION_DATA u8 LIT_3759[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80D55A58-80D55A64 000C .data      @3760                                                        */
SECTION_DATA u8 LIT_3760[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80D55A64-80D55A70 000C .data      @3761                                                        */
SECTION_DATA u8 LIT_3761[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80D55A70-80D55A7C 000C .data      @3762                                                        */
SECTION_DATA u8 LIT_3762[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80D55A7C-80D55A88 000C .data      @3763                                                        */
SECTION_DATA u8 LIT_3763[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80D55A88-80D55A94 000C .data      @3764                                                        */
SECTION_DATA u8 LIT_3764[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80D55A94-80D55AA0 000C .data      @3765                                                        */
SECTION_DATA u8 LIT_3765[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80D55AA0-80D55AAC 000C .data      @3766                                                        */
SECTION_DATA u8 LIT_3766[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80D55AAC-80D55AB8 000C .data      @3767                                                        */
SECTION_DATA u8 LIT_3767[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80D55AB8-80D55AC4 000C .data      @3768                                                        */
SECTION_DATA u8 LIT_3768[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80D55AC4-80D55AD0 000C .data      @3769                                                        */
SECTION_DATA u8 LIT_3769[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80D55AD0-80D55C08 0138 .data      ActionTable__13daTagTWGate_c                                 */
SECTION_DATA u8 ActionTable__13daTagTWGate_c[312] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80D55C08-80D55C28 0020 .data      l_daTagTWGate_Method                                         */
SECTION_DATA u8 l_daTagTWGate_Method[32] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80D55C28-80D55C58 0030 .data      g_profile_Tag_TWGate                                         */
SECTION_DATA u8 g_profile_Tag_TWGate[48] = {
	0xFF, 0xFF, 0xFF, 0xFD, 0x00, 0x07, 0xFF, 0xFD, 0x02, 0xC8, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x05, 0xE4, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x01, 0x05, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x0E, 0x00, 0x00,
};
}


/* ###################################################################################### */
/*                                         .text                                          */
/* ###################################################################################### */

/* 80D525F8-80D52604 000C .text      initWait__13daTagTWGate_cFv                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void initWait__13daTagTWGate_cFv() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/initWait__13daTagTWGate_cFv.s"
}
#pragma pop

/* 80D52604-80D528F0 02EC .text      executeWait__13daTagTWGate_cFv                               */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void executeWait__13daTagTWGate_cFv() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/executeWait__13daTagTWGate_cFv.s"
}
#pragma pop

/* 80D528F0-80D5297C 008C .text      initDemoFilone1__13daTagTWGate_cFv                           */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void initDemoFilone1__13daTagTWGate_cFv() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/initDemoFilone1__13daTagTWGate_cFv.s"
}
#pragma pop

/* 80D5297C-80D52AF4 0178 .text      executeDemoFilone1__13daTagTWGate_cFv                        */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void executeDemoFilone1__13daTagTWGate_cFv() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/executeDemoFilone1__13daTagTWGate_cFv.s"
}
#pragma pop

/* 80D52AF4-80D52BF0 00FC .text      initDemoFilone2__13daTagTWGate_cFv                           */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void initDemoFilone2__13daTagTWGate_cFv() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/initDemoFilone2__13daTagTWGate_cFv.s"
}
#pragma pop

/* 80D52BF0-80D52DB4 01C4 .text      executeDemoFilone2__13daTagTWGate_cFv                        */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void executeDemoFilone2__13daTagTWGate_cFv() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/executeDemoFilone2__13daTagTWGate_cFv.s"
}
#pragma pop

/* 80D52DB4-80D52E7C 00C8 .text      initDemoFilone3__13daTagTWGate_cFv                           */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void initDemoFilone3__13daTagTWGate_cFv() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/initDemoFilone3__13daTagTWGate_cFv.s"
}
#pragma pop

/* 80D52E7C-80D53250 03D4 .text      executeDemoFilone3__13daTagTWGate_cFv                        */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void executeDemoFilone3__13daTagTWGate_cFv() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/executeDemoFilone3__13daTagTWGate_cFv.s"
}
#pragma pop

/* 80D53250-80D532DC 008C .text      initDemoOrdin1__13daTagTWGate_cFv                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void initDemoOrdin1__13daTagTWGate_cFv() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/initDemoOrdin1__13daTagTWGate_cFv.s"
}
#pragma pop

/* 80D532DC-80D53454 0178 .text      executeDemoOrdin1__13daTagTWGate_cFv                         */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void executeDemoOrdin1__13daTagTWGate_cFv() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/executeDemoOrdin1__13daTagTWGate_cFv.s"
}
#pragma pop

/* 80D53454-80D53550 00FC .text      initDemoOrdin2__13daTagTWGate_cFv                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void initDemoOrdin2__13daTagTWGate_cFv() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/initDemoOrdin2__13daTagTWGate_cFv.s"
}
#pragma pop

/* 80D53550-80D53714 01C4 .text      executeDemoOrdin2__13daTagTWGate_cFv                         */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void executeDemoOrdin2__13daTagTWGate_cFv() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/executeDemoOrdin2__13daTagTWGate_cFv.s"
}
#pragma pop

/* 80D53714-80D537DC 00C8 .text      initDemoOrdin3__13daTagTWGate_cFv                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void initDemoOrdin3__13daTagTWGate_cFv() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/initDemoOrdin3__13daTagTWGate_cFv.s"
}
#pragma pop

/* 80D537DC-80D53BD0 03F4 .text      executeDemoOrdin3__13daTagTWGate_cFv                         */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void executeDemoOrdin3__13daTagTWGate_cFv() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/executeDemoOrdin3__13daTagTWGate_cFv.s"
}
#pragma pop

/* 80D53BD0-80D53C5C 008C .text      initDemoRanail1__13daTagTWGate_cFv                           */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void initDemoRanail1__13daTagTWGate_cFv() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/initDemoRanail1__13daTagTWGate_cFv.s"
}
#pragma pop

/* 80D53C5C-80D53DD4 0178 .text      executeDemoRanail1__13daTagTWGate_cFv                        */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void executeDemoRanail1__13daTagTWGate_cFv() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/executeDemoRanail1__13daTagTWGate_cFv.s"
}
#pragma pop

/* 80D53DD4-80D53ED0 00FC .text      initDemoRanail2__13daTagTWGate_cFv                           */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void initDemoRanail2__13daTagTWGate_cFv() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/initDemoRanail2__13daTagTWGate_cFv.s"
}
#pragma pop

/* 80D53ED0-80D54094 01C4 .text      executeDemoRanail2__13daTagTWGate_cFv                        */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void executeDemoRanail2__13daTagTWGate_cFv() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/executeDemoRanail2__13daTagTWGate_cFv.s"
}
#pragma pop

/* 80D54094-80D54178 00E4 .text      initDemoRanail3__13daTagTWGate_cFv                           */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void initDemoRanail3__13daTagTWGate_cFv() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/initDemoRanail3__13daTagTWGate_cFv.s"
}
#pragma pop

/* 80D54178-80D5456C 03F4 .text      executeDemoRanail3__13daTagTWGate_cFv                        */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void executeDemoRanail3__13daTagTWGate_cFv() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/executeDemoRanail3__13daTagTWGate_cFv.s"
}
#pragma pop

/* 80D5456C-80D545F8 008C .text      initDemoHyral1__13daTagTWGate_cFv                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void initDemoHyral1__13daTagTWGate_cFv() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/initDemoHyral1__13daTagTWGate_cFv.s"
}
#pragma pop

/* 80D545F8-80D54770 0178 .text      executeDemoHyral1__13daTagTWGate_cFv                         */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void executeDemoHyral1__13daTagTWGate_cFv() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/executeDemoHyral1__13daTagTWGate_cFv.s"
}
#pragma pop

/* 80D54770-80D5486C 00FC .text      initDemoHyral2__13daTagTWGate_cFv                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void initDemoHyral2__13daTagTWGate_cFv() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/initDemoHyral2__13daTagTWGate_cFv.s"
}
#pragma pop

/* 80D5486C-80D54A30 01C4 .text      executeDemoHyral2__13daTagTWGate_cFv                         */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void executeDemoHyral2__13daTagTWGate_cFv() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/executeDemoHyral2__13daTagTWGate_cFv.s"
}
#pragma pop

/* 80D54A30-80D54AF8 00C8 .text      initDemoHyral3__13daTagTWGate_cFv                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void initDemoHyral3__13daTagTWGate_cFv() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/initDemoHyral3__13daTagTWGate_cFv.s"
}
#pragma pop

/* 80D54AF8-80D54ECC 03D4 .text      executeDemoHyral3__13daTagTWGate_cFv                         */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void executeDemoHyral3__13daTagTWGate_cFv() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/executeDemoHyral3__13daTagTWGate_cFv.s"
}
#pragma pop

/* 80D54ECC-80D54F88 00BC .text      initBaseMtx__13daTagTWGate_cFv                               */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void initBaseMtx__13daTagTWGate_cFv() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/initBaseMtx__13daTagTWGate_cFv.s"
}
#pragma pop

/* 80D54F88-80D5502C 00A4 .text      downloadModels__13daTagTWGate_cFv                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void downloadModels__13daTagTWGate_cFv() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/downloadModels__13daTagTWGate_cFv.s"
}
#pragma pop

/* 80D5502C-80D55068 003C .text      initTalk__13daTagTWGate_cFiPP10fopAc_ac_c                    */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void initTalk__13daTagTWGate_cFiPP10fopAc_ac_c() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/initTalk__13daTagTWGate_cFiPP10fopAc_ac_c.s"
}
#pragma pop

/* 80D55068-80D55160 00F8 .text      talkProc__13daTagTWGate_cFPiiPP10fopAc_ac_c                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void talkProc__13daTagTWGate_cFPiiPP10fopAc_ac_c() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/talkProc__13daTagTWGate_cFPiiPP10fopAc_ac_c.s"
}
#pragma pop

/* 80D55160-80D55180 0020 .text      createHeapCallBack__13daTagTWGate_cFP10fopAc_ac_c            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void createHeapCallBack__13daTagTWGate_cFP10fopAc_ac_c() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/createHeapCallBack__13daTagTWGate_cFP10fopAc_ac_c.s"
}
#pragma pop

/* 80D55180-80D55288 0108 .text      CreateHeap__13daTagTWGate_cFv                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void CreateHeap__13daTagTWGate_cFv() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/CreateHeap__13daTagTWGate_cFv.s"
}
#pragma pop

/* 80D55288-80D55388 0100 .text      daTagTWGate_Create__FP10fopAc_ac_c                           */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daTagTWGate_Create__FP10fopAc_ac_c() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/daTagTWGate_Create__FP10fopAc_ac_c.s"
}
#pragma pop

/* 80D55388-80D5543C 00B4 .text      daTagTWGate_Delete__FP13daTagTWGate_c                        */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daTagTWGate_Delete__FP13daTagTWGate_c() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/daTagTWGate_Delete__FP13daTagTWGate_c.s"
}
#pragma pop

/* 80D5543C-80D554E4 00A8 .text      daTagTWGate_Execute__FP13daTagTWGate_c                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daTagTWGate_Execute__FP13daTagTWGate_c() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/daTagTWGate_Execute__FP13daTagTWGate_c.s"
}
#pragma pop

/* 80D554E4-80D55518 0034 .text      daTagTWGate_Draw__FP13daTagTWGate_c                          */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daTagTWGate_Draw__FP13daTagTWGate_c() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/daTagTWGate_Draw__FP13daTagTWGate_c.s"
}
#pragma pop

/* 80D55518-80D55520 0008 .text      daTagTWGate_IsDelete__FP13daTagTWGate_c                      */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daTagTWGate_IsDelete__FP13daTagTWGate_c() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/daTagTWGate_IsDelete__FP13daTagTWGate_c.s"
}
#pragma pop

/* 80D55520-80D557A0 0280 .text      __sinit_d_a_tag_TWgate_cpp                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __sinit_d_a_tag_TWgate_cpp() {
	nofralloc
#include "asm/rel/d_a_tag_TWgate/d_a_tag_TWgate/__sinit_d_a_tag_TWgate_cpp.s"
}
#pragma pop


