// 
// Generated By: dol2asm
// 

#include "dolphin/types.h"

// 
// Additional Symbols:
// 

extern "C" {
SECTION_SDATA2 extern f64 JAISoundParams__LIT_292;
}


/* ###################################################################################### */
/*                                        .sdata2                                         */
/* ###################################################################################### */

extern "C" {
/* 804557E8 0008 .sdata2    @292                                                         */
// 0x4330000000000000 | compiler-generated value used in cast: (float)u32
SECTION_SDATA2 f64 JAISoundParams__LIT_292 = 4503599627370496.000000;
}


/* ###################################################################################### */
/*                                         .text                                          */
/* ###################################################################################### */

extern "C" {
/* 802A2DB4 0058 .text      moveVolume__18JAISoundParamsMoveFfUl                         */
// JAISoundParamsMove::moveVolume(f32, u32)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void moveVolume__18JAISoundParamsMoveFfUl() {
	nofralloc
#include "_include/JAudio2/JAISoundParams/moveVolume__18JAISoundParamsMoveFfUl.s"
}
#pragma pop

/* 802A2E0C 0058 .text      movePitch__18JAISoundParamsMoveFfUl                          */
// JAISoundParamsMove::movePitch(f32, u32)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void movePitch__18JAISoundParamsMoveFfUl() {
	nofralloc
#include "_include/JAudio2/JAISoundParams/movePitch__18JAISoundParamsMoveFfUl.s"
}
#pragma pop

/* 802A2E64 0058 .text      moveFxMix__18JAISoundParamsMoveFfUl                          */
// JAISoundParamsMove::moveFxMix(f32, u32)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void moveFxMix__18JAISoundParamsMoveFfUl() {
	nofralloc
#include "_include/JAudio2/JAISoundParams/moveFxMix__18JAISoundParamsMoveFfUl.s"
}
#pragma pop

/* 802A2EBC 0058 .text      movePan__18JAISoundParamsMoveFfUl                            */
// JAISoundParamsMove::movePan(f32, u32)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void movePan__18JAISoundParamsMoveFfUl() {
	nofralloc
#include "_include/JAudio2/JAISoundParams/movePan__18JAISoundParamsMoveFfUl.s"
}
#pragma pop

/* 802A2F14 0058 .text      moveDolby__18JAISoundParamsMoveFfUl                          */
// JAISoundParamsMove::moveDolby(f32, u32)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void moveDolby__18JAISoundParamsMoveFfUl() {
	nofralloc
#include "_include/JAudio2/JAISoundParams/moveDolby__18JAISoundParamsMoveFfUl.s"
}
#pragma pop

}

