// 
// Generated By: dol2asm
// 

#include "dolphin/types.h"

// 
// Additional Symbols:
// 

struct JKRHeap;

extern void* operator new[](u32, JKRHeap*, int); /* __nwa__FUlP7JKRHeapi */
extern void operator delete(void*); /* __dl__FPv */

extern "C" {
extern void __dt__17JASSimpleWaveBankFv();
extern void __dt__Q217JASSimpleWaveBank11TWaveHandleFv();
extern void getWaveHandle__17JASSimpleWaveBankCFUl();
extern void getWaveArc__17JASSimpleWaveBankFUl();
extern void getWavePtr__Q217JASSimpleWaveBank11TWaveHandleCFv();
extern void __ct__Q217JASSimpleWaveBank11TWaveHandleFv();
extern u8* getWaveInfo__Q217JASSimpleWaveBank11TWaveHandleCFv(u8*);
extern int getArcCount__17JASSimpleWaveBankCFv();
extern void onLoadDone__10JASWaveArcFv();
extern void onEraseDone__10JASWaveArcFv();
extern void func_80298FA8();
extern void __ct__10JASWaveArcFv();
extern void __dt__10JASWaveArcFv();
extern void onDispose__10JASWaveArcFv();
extern void __nwa__FUlP7JKRHeapi();
extern void __dl__FPv();
extern void __destroy_new_array();
extern void __construct_new_array();
extern void _savegpr_29();
extern void _restgpr_29();
SECTION_DATA extern const void* __vt__13JASWaveHandle[5];
SECTION_DATA extern const void* __vt__11JASWaveBank[6];
SECTION_DATA extern const void* __vt__Q217JASSimpleWaveBank11TWaveHandle[5];
SECTION_DATA extern const void* __vt__17JASSimpleWaveBank[13];
SECTION_SDATA extern u8 one__11JASWaveInfo[8];
}


/* ###################################################################################### */
/*                                         .data                                          */
/* ###################################################################################### */

extern "C" {
/* 803C7798 0014 .data      __vt__Q217JASSimpleWaveBank11TWaveHandle                     */
SECTION_DATA const  void* __vt__Q217JASSimpleWaveBank11TWaveHandle[5] = {
	NULL, /* RTTI */
	NULL,
	(void*)__dt__Q217JASSimpleWaveBank11TWaveHandleFv,
	(void*)getWaveInfo__Q217JASSimpleWaveBank11TWaveHandleCFv,
	(void*)getWavePtr__Q217JASSimpleWaveBank11TWaveHandleCFv,
};
/* 803C77AC 0030 .data      __vt__17JASSimpleWaveBank                                    */
SECTION_DATA const  void* __vt__17JASSimpleWaveBank[13] = {
	NULL, /* RTTI */
	NULL,
	(void*)__dt__17JASSimpleWaveBankFv,
	(void*)getWaveHandle__17JASSimpleWaveBankCFUl,
	(void*)getWaveArc__17JASSimpleWaveBankFUl,
	(void*)getArcCount__17JASSimpleWaveBankCFv,
	NULL,
	NULL,
	(void*)func_80298FA8,
	(void*)onDispose__10JASWaveArcFv,
	(void*)onLoadDone__10JASWaveArcFv,
	(void*)onEraseDone__10JASWaveArcFv,
	/* padding */
	NULL,
};
}


/* ###################################################################################### */
/*                                         .text                                          */
/* ###################################################################################### */

extern "C" {
/* 80298C94 0060 .text      __ct__17JASSimpleWaveBankFv                                  */
// JASSimpleWaveBank::JASSimpleWaveBank(void)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __ct__17JASSimpleWaveBankFv() {
	nofralloc
#include "_include/JAudio2/JASSimpleWaveBank/__ct__17JASSimpleWaveBankFv.s"
}
#pragma pop

/* 80298CF4 0090 .text      __dt__17JASSimpleWaveBankFv                                  */
// JASSimpleWaveBank::~JASSimpleWaveBank(void)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__17JASSimpleWaveBankFv() {
	nofralloc
#include "_include/JAudio2/JASSimpleWaveBank/__dt__17JASSimpleWaveBankFv.s"
}
#pragma pop

/* 80298D84 005C .text      __dt__Q217JASSimpleWaveBank11TWaveHandleFv                   */
// JASSimpleWaveBank::TWaveHandle::~JASSimpleWaveBank::TWaveHandle(void)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__Q217JASSimpleWaveBank11TWaveHandleFv() {
	nofralloc
#include "_include/JAudio2/JASSimpleWaveBank/__dt__Q217JASSimpleWaveBank11TWaveHandleFv.s"
}
#pragma pop

/* 80298DE0 0080 .text      setWaveTableSize__17JASSimpleWaveBankFUlP7JKRHeap            */
// JASSimpleWaveBank::setWaveTableSize(u32, JKRHeap*)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void setWaveTableSize__17JASSimpleWaveBankFUlP7JKRHeap() {
	nofralloc
#include "_include/JAudio2/JASSimpleWaveBank/setWaveTableSize__17JASSimpleWaveBankFUlP7JKRHeap.s"
}
#pragma pop

/* 80298E60 0024 .text      getWaveHandle__17JASSimpleWaveBankCFUl                       */
// JASSimpleWaveBank::getWaveHandle(u32) const
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void getWaveHandle__17JASSimpleWaveBankCFUl() {
	nofralloc
#include "_include/JAudio2/JASSimpleWaveBank/getWaveHandle__17JASSimpleWaveBankCFUl.s"
}
#pragma pop

/* 80298E84 0094 .text      setWaveInfo__17JASSimpleWaveBankFUlRC11JASWaveInfo           */
// JASSimpleWaveBank::setWaveInfo(u32, const JASWaveInfo&)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void setWaveInfo__17JASSimpleWaveBankFUlRC11JASWaveInfo() {
	nofralloc
#include "_include/JAudio2/JASSimpleWaveBank/setWaveInfo__17JASSimpleWaveBankFUlRC11JASWaveInfo.s"
}
#pragma pop

/* 80298F18 0020 .text      getWaveArc__17JASSimpleWaveBankFUl                           */
// JASSimpleWaveBank::getWaveArc(u32)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void getWaveArc__17JASSimpleWaveBankFUl() {
	nofralloc
#include "_include/JAudio2/JASSimpleWaveBank/getWaveArc__17JASSimpleWaveBankFUl.s"
}
#pragma pop

/* 80298F38 0024 .text      getWavePtr__Q217JASSimpleWaveBank11TWaveHandleCFv            */
// JASSimpleWaveBank::TWaveHandle::getWavePtr(void) const
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void getWavePtr__Q217JASSimpleWaveBank11TWaveHandleCFv() {
	nofralloc
#include "_include/JAudio2/JASSimpleWaveBank/getWavePtr__Q217JASSimpleWaveBank11TWaveHandleCFv.s"
}
#pragma pop

/* 80298F5C 0034 .text      __ct__Q217JASSimpleWaveBank11TWaveHandleFv                   */
// JASSimpleWaveBank::TWaveHandle::JASSimpleWaveBank::TWaveHandle(void)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __ct__Q217JASSimpleWaveBank11TWaveHandleFv() {
	nofralloc
#include "_include/JAudio2/JASSimpleWaveBank/__ct__Q217JASSimpleWaveBank11TWaveHandleFv.s"
}
#pragma pop

/* 80298F90 0008 .text      getWaveInfo__Q217JASSimpleWaveBank11TWaveHandleCFv           */
// JASSimpleWaveBank::TWaveHandle::getWaveInfo(void) const
u8* getWaveInfo__Q217JASSimpleWaveBank11TWaveHandleCFv(u8* param0) {
	return (u8*)&param0[4]; /* param0->field_0x4 */
}

/* 80298F98 0008 .text      getArcCount__17JASSimpleWaveBankCFv                          */
// JASSimpleWaveBank::getArcCount(void) const
int getArcCount__17JASSimpleWaveBankCFv() {
	return 1;
}

/* 80298FA0 0004 .text      onLoadDone__10JASWaveArcFv                                   */
// JASWaveArc::onLoadDone(void)
void onLoadDone__10JASWaveArcFv() {
	return;
}

/* 80298FA4 0004 .text      onEraseDone__10JASWaveArcFv                                  */
// JASWaveArc::onEraseDone(void)
void onEraseDone__10JASWaveArcFv() {
	return;
}

/* 80298FA8 0008 .text      @4@__dt__17JASSimpleWaveBankFv                               */
// JASSimpleWaveBank::@4@__dt(void)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void func_80298FA8() {
	nofralloc
#include "_include/JAudio2/JASSimpleWaveBank/func_80298FA8.s"
}
#pragma pop

}

