// 
// Generated By: dol2asm
// 

#include "dolphin/types.h"

// 
// Additional Symbols:
// 

extern void operator delete(void*); /* __dl__FPv */

extern "C" {
extern void getInstParam__12JASVoiceBankCFiiiP12JASInstParam();
extern void __dt__12JASVoiceBankFv();
extern void getType__12JASVoiceBankCFv();
extern void __dl__FPv();
SECTION_RODATA extern const u8 sOscData__12JASVoiceBank[24];
SECTION_DATA extern const void* __vt__7JASBank[5];
SECTION_DATA extern const void* __vt__12JASVoiceBank[6];
SECTION_SBSS extern u8 sOscTable__12JASVoiceBank[4];
}


/* ###################################################################################### */
/*                                        .rodata                                         */
/* ###################################################################################### */

extern "C" {
/* 8039B1B8 0018 .rodata    sOscData__12JASVoiceBank                                     */
SECTION_RODATA const u8 sOscData__12JASVoiceBank[24] = {
	0x00, 0x00, 0x00, 0x00, 0x3F, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x3F, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
}


/* ###################################################################################### */
/*                                         .data                                          */
/* ###################################################################################### */

extern "C" {
/* 803C76D0 0014 .data      __vt__12JASVoiceBank                                         */
SECTION_DATA const  void* __vt__12JASVoiceBank[6] = {
	NULL, /* RTTI */
	NULL,
	(void*)__dt__12JASVoiceBankFv,
	(void*)getInstParam__12JASVoiceBankCFiiiP12JASInstParam,
	(void*)getType__12JASVoiceBankCFv,
	/* padding */
	NULL,
};
}


/* ###################################################################################### */
/*                                         .sbss                                          */
/* ###################################################################################### */

extern "C" {
/* 80451268 0004 .sbss      sOscTable__12JASVoiceBank                                    */
SECTION_SBSS u8 sOscTable__12JASVoiceBank[4];
SECTION_SBSS u8 pad_8045126C[4];
}


/* ###################################################################################### */
/*                                         .text                                          */
/* ###################################################################################### */

extern "C" {
/* 80297F74 0038 .text      getInstParam__12JASVoiceBankCFiiiP12JASInstParam             */
// JASVoiceBank::getInstParam(int, int, int, JASInstParam*) const
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void getInstParam__12JASVoiceBankCFiiiP12JASInstParam() {
	nofralloc
#include "_include/JAudio2/JASVoiceBank/getInstParam__12JASVoiceBankCFiiiP12JASInstParam.s"
}
#pragma pop

/* 80297FAC 005C .text      __dt__12JASVoiceBankFv                                       */
// JASVoiceBank::~JASVoiceBank(void)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__12JASVoiceBankFv() {
	nofralloc
#include "_include/JAudio2/JASVoiceBank/__dt__12JASVoiceBankFv.s"
}
#pragma pop

/* 80298008 000C .text      getType__12JASVoiceBankCFv                                   */
// JASVoiceBank::getType(void) const
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void getType__12JASVoiceBankCFv() {
	nofralloc
#include "_include/JAudio2/JASVoiceBank/getType__12JASVoiceBankCFv.s"
}
#pragma pop

}

