// 
// Generated By: dol2asm
// 

#include "dolphin/types.h"

// 
// Additional Symbols:
// 

extern "C" {
extern void _prolog();
extern void _epilog();
extern void _unresolved();
extern void solidHeapCB__Q212daObjSwpush25Act_cFP10fopAc_ac_c();
extern void rideCB__Q212daObjSwpush25Act_cFP4dBgWP10fopAc_ac_cP10fopAc_ac_c();
extern const u8 unknown_translation_unit_ctors__data_80CFFBEC[4];
extern const u8 unknown_translation_unit_dtors__data_80CFFBF0[4];
SECTION_RODATA extern const u8 M_arcname__Q212daObjSwpush25Act_c[12];
SECTION_RODATA extern const u8 M_attr__Q212daObjSwpush25Act_c[224];
SECTION_RODATA extern const u8 LIT_3857[4];
SECTION_RODATA extern const u8 LIT_3858[4];
SECTION_RODATA extern const u8 LIT_3939[4];
SECTION_RODATA extern const u8 LIT_4012[4];
SECTION_RODATA extern const u8 stringBase0[124];
SECTION_DATA extern u8 cNullVec__6Z2Calc[12];
SECTION_DATA extern void* __vt__12J3DFrameCtrl[3];
SECTION_BSS extern u8 struct_80CFFF14[4];
}


/* ###################################################################################### */
/*                                         .text                                          */
/* ###################################################################################### */

/* 80CFE020-80CFE04C 002C .text      _prolog                                                      */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void _prolog() {
	nofralloc
#include "asm/rel/d_a_obj_swpush2/executor/_prolog.s"
}
#pragma pop

/* 80CFE04C-80CFE078 002C .text      _epilog                                                      */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void _epilog() {
	nofralloc
#include "asm/rel/d_a_obj_swpush2/executor/_epilog.s"
}
#pragma pop

/* 80CFE078-80CFE098 0020 .text      _unresolved                                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void _unresolved() {
	nofralloc
#include "asm/rel/d_a_obj_swpush2/executor/_unresolved.s"
}
#pragma pop


