// 
// Generated By: dol2asm
// 

#include "dolphin/types.h"

// 
// Additional Symbols:
// 

extern "C" {
/* Function             */
extern void __GXSetVCD();
/* Function             */
extern void __GXCalculateVLim();
/* Function             */
extern void __GXSetVAT();
/* Function             */
extern void __GXSetDirtyState();
/* Function             */
extern void GXBegin();
/* Function             */
extern void __GXSendFlushPrim();
/* Function             */
extern void GXSetLineWidth();
/* Function             */
extern void GXSetPointSize();
/* Function             */
extern void GXEnableTexOffsets();
/* Function             */
extern void GXSetCullMode();
/* Function             */
extern void GXSetCoPlanar();
/* Function             */
extern void __GXSetGenMode();
/* Function             */
extern void __GXSetSUTexRegs();
/* ReturnFunction       */
extern void __GXUpdateBPMask();
/* SymbolReferenceArrayData */
SECTION_SDATA2 extern void* __GXData;
}


/* ###################################################################################### */
/*                                         .text                                          */
/* ###################################################################################### */

extern "C" {
/* 8035C6E4-8035C764 0080 .text      __GXSetDirtyState                                            Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __GXSetDirtyState() {
	nofralloc
#include "_include/gx/GXGeometry/__GXSetDirtyState.s"
}
#pragma pop

/* 8035C764-8035C834 00D0 .text      GXBegin                                                      Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void GXBegin() {
	nofralloc
#include "_include/gx/GXGeometry/GXBegin.s"
}
#pragma pop

/* 8035C834-8035C8BC 0088 .text      __GXSendFlushPrim                                            Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __GXSendFlushPrim() {
	nofralloc
#include "_include/gx/GXGeometry/__GXSendFlushPrim.s"
}
#pragma pop

/* 8035C8BC-8035C8FC 0040 .text      GXSetLineWidth                                               Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void GXSetLineWidth() {
	nofralloc
#include "_include/gx/GXGeometry/GXSetLineWidth.s"
}
#pragma pop

/* 8035C8FC-8035C93C 0040 .text      GXSetPointSize                                               Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void GXSetPointSize() {
	nofralloc
#include "_include/gx/GXGeometry/GXSetPointSize.s"
}
#pragma pop

/* 8035C93C-8035C984 0048 .text      GXEnableTexOffsets                                           Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void GXEnableTexOffsets() {
	nofralloc
#include "_include/gx/GXGeometry/GXEnableTexOffsets.s"
}
#pragma pop

/* 8035C984-8035C9AC 0028 .text      GXSetCullMode                                                Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void GXSetCullMode() {
	nofralloc
#include "_include/gx/GXGeometry/GXSetCullMode.s"
}
#pragma pop

/* 8035C9AC-8035C9E0 0034 .text      GXSetCoPlanar                                                Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void GXSetCoPlanar() {
	nofralloc
#include "_include/gx/GXGeometry/GXSetCoPlanar.s"
}
#pragma pop

/* 8035C9E0-8035CA04 0024 .text      __GXSetGenMode                                               Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __GXSetGenMode() {
	nofralloc
#include "_include/gx/GXGeometry/__GXSetGenMode.s"
}
#pragma pop

}

