// 
// Generated By: dol2asm
// Translation Unit: Math/Double_precision/w_acos
// 

#include "dol2asm.h"
#include "dolphin/types.h"
#include "MSL_C.PPCEABI.bare.H/Math/Double_precision/w_acos.h"

// 
// Forward References:
// 


extern "C" void acos(); // 1

// 
// External References:
// 


extern "C" void __ieee754_acos(); // 1

// 
// Declarations:
// 

/* 8036C6E0-8036C700 0020+00 rc=2 efc=2 rfr=False None .text      acos                                                         */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void acos() {
	nofralloc
#include "asm/MSL_C.PPCEABI.bare.H/Math/Double_precision/w_acos/acos.s"
}
#pragma pop


