// 
// Generated By: dol2asm
// 

#include "dolphin/types.h"

// 
// Additional Symbols:
// 

struct cM3dGTri;
struct Vec;
struct cM3dGCyl;

extern void cM3d_CalcPla(const Vec*, const Vec*, const Vec*, Vec*, f32*); /* cM3d_CalcPla__FPC3VecPC3VecPC3VecP3VecPf */
extern void cM3d_Cross_CylTri(const cM3dGCyl*, const cM3dGTri*, Vec*); /* cM3d_Cross_CylTri__FPC8cM3dGCylPC8cM3dGTriP3Vec */

extern "C" {
extern void cM3d_CalcPla__FPC3VecPC3VecPC3VecP3VecPf();
extern void cM3d_Cross_CylTri__FPC8cM3dGCylPC8cM3dGTriP3Vec();
extern void SetupNP__8cM3dGPlaFRC3VecRC3Vec();
extern void Set__8cM3dGPlaFPC8cM3dGPla();
}


/* ###################################################################################### */
/*                                         .text                                          */
/* ###################################################################################### */

extern "C" {
/* 8026F7B0 002C .text      cross__8cM3dGTriCFPC8cM3dGCylP3Vec                           */
// cM3dGTri::cross(const cM3dGCyl*, Vec*) const
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void cross__8cM3dGTriCFPC8cM3dGCylP3Vec() {
	nofralloc
#include "_include/SComponent/c_m3d_g_tri/cross__8cM3dGTriCFPC8cM3dGCylP3Vec.s"
}
#pragma pop

/* 8026F7DC 0080 .text      setPos__8cM3dGTriFPC3VecPC3VecPC3Vec                         */
// cM3dGTri::setPos(const Vec*, const Vec*, const Vec*)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void setPos__8cM3dGTriFPC3VecPC3VecPC3Vec() {
	nofralloc
#include "_include/SComponent/c_m3d_g_tri/setPos__8cM3dGTriFPC3VecPC3VecPC3Vec.s"
}
#pragma pop

/* 8026F85C 006C .text      setBg__8cM3dGTriFPC3VecPC3VecPC3VecPC8cM3dGPla               */
// cM3dGTri::setBg(const Vec*, const Vec*, const Vec*, const cM3dGPla*)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void setBg__8cM3dGTriFPC3VecPC3VecPC3VecPC8cM3dGPla() {
	nofralloc
#include "_include/SComponent/c_m3d_g_tri/setBg__8cM3dGTriFPC3VecPC3VecPC3VecPC8cM3dGPla.s"
}
#pragma pop

/* 8026F8C8 0074 .text      set__8cM3dGTriFPC3VecPC3VecPC3VecPC3Vec                      */
// cM3dGTri::set(const Vec*, const Vec*, const Vec*, const Vec*)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void set__8cM3dGTriFPC3VecPC3VecPC3VecPC3Vec() {
	nofralloc
#include "_include/SComponent/c_m3d_g_tri/set__8cM3dGTriFPC3VecPC3VecPC3VecPC3Vec.s"
}
#pragma pop

}

