// 
// Generated By: dol2asm
// 

#include "dolphin/types.h"

// 
// Additional Symbols:
// 

extern "C" {
extern void _prolog();
extern void _epilog();
extern void _unresolved();
extern void daObjProp_c_createHeap__FP10fopAc_ac_c();
extern const u8 unknown_translation_unit_ctors__data_80CB560C[4];
extern const u8 unknown_translation_unit_dtors__data_80CB5610[4];
SECTION_RODATA extern const u8 data_80CB5614[8];
SECTION_RODATA extern const u8 data_80CB561C[4];
SECTION_DATA extern u8 l_arcName[4];
SECTION_DATA extern void* __vt__11daObjProp_c[3];
}


/* ###################################################################################### */
/*                                         .text                                          */
/* ###################################################################################### */

/* 80CB5160-80CB518C 002C .text      _prolog                                                      */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void _prolog() {
	nofralloc
#include "asm/rel/d_a_obj_prop/executor/_prolog.s"
}
#pragma pop

/* 80CB518C-80CB51B8 002C .text      _epilog                                                      */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void _epilog() {
	nofralloc
#include "asm/rel/d_a_obj_prop/executor/_epilog.s"
}
#pragma pop

/* 80CB51B8-80CB51D8 0020 .text      _unresolved                                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void _unresolved() {
	nofralloc
#include "asm/rel/d_a_obj_prop/executor/_unresolved.s"
}
#pragma pop


