// 
// Generated By: dol2asm
// 

#include "dolphin/types.h"

// 
// Additional Symbols:
// 

extern "C" {
extern void _unresolved();
extern void __register_global_object();
extern void __ct__12daE_CR_HIO_cFv();
extern void anm_init__FP10e_cr_classifUcf();
extern void nodeCallBack__FP8J3DJointi();
extern void daE_CR_Draw__FP10e_cr_class();
extern void other_bg_check__FP10e_cr_classP10fopAc_ac_c();
extern void pl_check__FP10e_cr_classfs();
extern void damage_check__FP10e_cr_class();
extern void way_bg_check__FP10e_cr_classf();
extern void e_cr_move__FP10e_cr_class();
extern void e_cr_s_damage__FP10e_cr_class();
extern void e_cr_damage__FP10e_cr_class();
extern void action__FP10e_cr_class();
extern void daE_CR_Execute__FP10e_cr_class();
extern void daE_CR_IsDelete__FP10e_cr_class();
extern void daE_CR_Delete__FP10e_cr_class();
extern void useHeapInit__FP10fopAc_ac_c();
extern void daE_CR_Create__FP10fopAc_ac_c();
extern void __dt__8cM3dGSphFv();
extern void __dt__8cM3dGAabFv();
extern void __dt__10dCcD_GSttsFv();
extern void __dt__12dBgS_ObjAcchFv();
extern void __dt__12dBgS_AcchCirFv();
extern void __dt__10cCcD_GSttsFv();
extern void __dt__12daE_CR_HIO_cFv();
extern void __sinit_d_a_e_cr_cpp();
extern void func_80699878();
extern void func_80699880();
extern void setMidnaBindEffect__FP13fopEn_enemy_cP15Z2CreatureEnemyP4cXyzP4cXyz();
extern const u8 unknown_translation_unit_ctors__data_80699C9C[8];
extern const void* __destroy_global_chain_reference;
SECTION_RODATA extern const u8 LIT_3788[4];
SECTION_RODATA extern const u8 LIT_3789[4];
SECTION_RODATA extern const u8 LIT_3790[8];
SECTION_RODATA extern const u8 LIT_3791[8];
SECTION_RODATA extern const u8 LIT_3792[8];
SECTION_RODATA extern const u8 LIT_3793[8];
SECTION_RODATA extern const u8 LIT_3794[4];
SECTION_RODATA extern const u8 LIT_3809[4];
SECTION_RODATA extern const u8 LIT_3810[4];
SECTION_RODATA extern const u8 LIT_3811[4];
SECTION_RODATA extern const u8 LIT_3825[4];
SECTION_RODATA extern const u8 LIT_3954[4];
SECTION_RODATA extern const u8 LIT_4018[4];
SECTION_RODATA extern const u8 LIT_4019[4];
SECTION_RODATA extern const u8 LIT_4020[4];
SECTION_RODATA extern const u8 LIT_4021[4];
SECTION_RODATA extern const u8 LIT_4022[4];
SECTION_RODATA extern const u8 LIT_4023[4];
SECTION_RODATA extern const u8 LIT_4024[4];
SECTION_RODATA extern const u8 LIT_4025[4];
SECTION_RODATA extern const u8 LIT_4026[4];
SECTION_RODATA extern const u8 LIT_4027[4];
SECTION_RODATA extern const u8 LIT_4028[4];
SECTION_RODATA extern const u8 LIT_4051[4];
SECTION_RODATA extern const u8 LIT_4052[4];
SECTION_RODATA extern const u8 LIT_4053[4];
SECTION_RODATA extern const u8 LIT_4074[4];
SECTION_RODATA extern const u8 LIT_4075[4];
SECTION_RODATA extern const u8 LIT_4076[4];
SECTION_RODATA extern const u8 LIT_4077[4];
SECTION_RODATA extern const u8 LIT_4078[4];
SECTION_RODATA extern const u8 LIT_4124[4];
SECTION_RODATA extern const u8 stringBase0[10];
SECTION_DATA extern u8 cNullVec__6Z2Calc[12];
SECTION_DATA extern u8 LIT_1787[20];
SECTION_DATA extern u8 data_80699D74[8];
SECTION_DATA extern u8 data_80699D7C[8];
SECTION_DATA extern u8 data_80699D84[8];
SECTION_DATA extern u8 data_80699D8C[64];
SECTION_DATA extern u8 l_daE_CR_Method[32];
SECTION_DATA extern u8 g_profile_E_CR[48];
SECTION_DATA extern void* __vt__12dBgS_AcchCir[3];
SECTION_DATA extern void* __vt__10cCcD_GStts[3];
SECTION_DATA extern void* __vt__10dCcD_GStts[3];
SECTION_DATA extern void* __vt__8cM3dGSph[3];
SECTION_DATA extern void* __vt__8cM3dGAab[3];
SECTION_DATA extern void* __vt__12dBgS_ObjAcch[9];
SECTION_DATA extern void* __vt__12daE_CR_HIO_c[3];
SECTION_BSS extern u8 __global_destructor_chain[4 + 4 /* padding */];
SECTION_BSS extern u8 global_destructor_chain__data_80699E94[0];
SECTION_BSS extern u8 LIT_3804[12];
SECTION_BSS extern u8 l_HIO[20];
}


/* ###################################################################################### */
/*                                        .rodata                                         */
/* ###################################################################################### */

extern "C" {
/* 80699D44-80699D4E 000A .rodata    @stringBase0                                                 */
#pragma push
#pragma force_active on
#pragma section ".dead"
SECTION_DEAD const char* const stringBase_80699D44 = "E_CR";
SECTION_DEAD const char* const stringBase_80699D49 = "E_cr";
#pragma pop
/* 80699CB4-80699CB4 0000 .rodata    ...rodata.0                                                  */
/* 80699CB4-80699CB8 0004 .rodata    @3788                                                        */
SECTION_RODATA const u8 LIT_3788[4] = {
	0x42, 0xC8, 0x00, 0x00,
};
/* 80699CB8-80699CBC 0004 .rodata    @3789                                                        */
SECTION_RODATA const u8 LIT_3789[4] = {
	0x00, 0x00, 0x00, 0x00,
};
/* 80699CBC-80699CC4 0004 .rodata    @3790                                                        */
SECTION_RODATA const u8 LIT_3790[8] = {
	0x3F, 0x80, 0x00, 0x00,
	/* padding */
	0x00, 0x00, 0x00, 0x00,
};
/* 80699CC4-80699CCC 0008 .rodata    @3791                                                        */
SECTION_RODATA const u8 LIT_3791[8] = {
	0x3F, 0xE0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80699CCC-80699CD4 0008 .rodata    @3792                                                        */
SECTION_RODATA const u8 LIT_3792[8] = {
	0x40, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80699CD4-80699CDC 0008 .rodata    @3793                                                        */
SECTION_RODATA const u8 LIT_3793[8] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80699CDC-80699CE0 0004 .rodata    @3794                                                        */
SECTION_RODATA const u8 LIT_3794[4] = {
	0x3C, 0x23, 0xD7, 0x0A,
};
/* 80699CE0-80699CE4 0004 .rodata    @3809                                                        */
SECTION_RODATA const u8 LIT_3809[4] = {
	0x40, 0x40, 0x00, 0x00,
};
/* 80699CE4-80699CE8 0004 .rodata    @3810                                                        */
SECTION_RODATA const u8 LIT_3810[4] = {
	0x42, 0x20, 0x00, 0x00,
};
/* 80699CE8-80699CEC 0004 .rodata    @3811                                                        */
SECTION_RODATA const u8 LIT_3811[4] = {
	0x43, 0xC8, 0x00, 0x00,
};
/* 80699CEC-80699CF0 0004 .rodata    @3825                                                        */
SECTION_RODATA const u8 LIT_3825[4] = {
	0xBF, 0x80, 0x00, 0x00,
};
/* 80699CF0-80699CF4 0004 .rodata    @3954                                                        */
SECTION_RODATA const u8 LIT_3954[4] = {
	0x42, 0x48, 0x00, 0x00,
};
/* 80699CF4-80699CF8 0004 .rodata    @4018                                                        */
SECTION_RODATA const u8 LIT_4018[4] = {
	0x41, 0xF0, 0x00, 0x00,
};
/* 80699CF8-80699CFC 0004 .rodata    @4019                                                        */
SECTION_RODATA const u8 LIT_4019[4] = {
	0x42, 0x70, 0x00, 0x00,
};
/* 80699CFC-80699D00 0004 .rodata    @4020                                                        */
SECTION_RODATA const u8 LIT_4020[4] = {
	0x43, 0x48, 0x00, 0x00,
};
/* 80699D00-80699D04 0004 .rodata    @4021                                                        */
SECTION_RODATA const u8 LIT_4021[4] = {
	0x41, 0xA0, 0x00, 0x00,
};
/* 80699D04-80699D08 0004 .rodata    @4022                                                        */
SECTION_RODATA const u8 LIT_4022[4] = {
	0x41, 0x20, 0x00, 0x00,
};
/* 80699D08-80699D0C 0004 .rodata    @4023                                                        */
SECTION_RODATA const u8 LIT_4023[4] = {
	0x46, 0xEA, 0x60, 0x00,
};
/* 80699D0C-80699D10 0004 .rodata    @4024                                                        */
SECTION_RODATA const u8 LIT_4024[4] = {
	0x40, 0xA0, 0x00, 0x00,
};
/* 80699D10-80699D14 0004 .rodata    @4025                                                        */
SECTION_RODATA const u8 LIT_4025[4] = {
	0x46, 0x6A, 0x60, 0x00,
};
/* 80699D14-80699D18 0004 .rodata    @4026                                                        */
SECTION_RODATA const u8 LIT_4026[4] = {
	0x3F, 0x00, 0x00, 0x00,
};
/* 80699D18-80699D1C 0004 .rodata    @4027                                                        */
SECTION_RODATA const u8 LIT_4027[4] = {
	0x42, 0x0C, 0x00, 0x00,
};
/* 80699D1C-80699D20 0004 .rodata    @4028                                                        */
SECTION_RODATA const u8 LIT_4028[4] = {
	0x41, 0x70, 0x00, 0x00,
};
/* 80699D20-80699D24 0004 .rodata    @4051                                                        */
SECTION_RODATA const u8 LIT_4051[4] = {
	0x40, 0x00, 0x00, 0x00,
};
/* 80699D24-80699D28 0004 .rodata    @4052                                                        */
SECTION_RODATA const u8 LIT_4052[4] = {
	0xC1, 0xC8, 0x00, 0x00,
};
/* 80699D28-80699D2C 0004 .rodata    @4053                                                        */
SECTION_RODATA const u8 LIT_4053[4] = {
	0x40, 0x80, 0x00, 0x00,
};
/* 80699D2C-80699D30 0004 .rodata    @4074                                                        */
SECTION_RODATA const u8 LIT_4074[4] = {
	0x42, 0x18, 0x00, 0x00,
};
/* 80699D30-80699D34 0004 .rodata    @4075                                                        */
SECTION_RODATA const u8 LIT_4075[4] = {
	0x41, 0x00, 0x00, 0x00,
};
/* 80699D34-80699D38 0004 .rodata    @4076                                                        */
SECTION_RODATA const u8 LIT_4076[4] = {
	0xC1, 0xF0, 0x00, 0x00,
};
/* 80699D38-80699D3C 0004 .rodata    @4077                                                        */
SECTION_RODATA const u8 LIT_4077[4] = {
	0x44, 0x7A, 0x00, 0x00,
};
/* 80699D3C-80699D40 0004 .rodata    @4078                                                        */
SECTION_RODATA const u8 LIT_4078[4] = {
	0x41, 0xC8, 0x00, 0x00,
};
/* 80699D40-80699D44 0004 .rodata    @4124                                                        */
SECTION_RODATA const u8 LIT_4124[4] = {
	0x40, 0xE0, 0x00, 0x00,
};
}


/* ###################################################################################### */
/*                                         .data                                          */
/* ###################################################################################### */

extern "C" {
/* 80699D54-80699D54 0000 .data      ...data.0                                                    */
/* 80699D54-80699D60 000C .data      cNullVec__6Z2Calc                                            */
SECTION_DATA u8 cNullVec__6Z2Calc[12] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80699D60-80699D74 0004 .data      @1787                                                        */
SECTION_DATA u8 LIT_1787[20] = {
	0x02, 0x00, 0x02, 0x01,
	/* padding */
	0x40, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x3F, 0xE0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80699D74-80699D7C 0008 .data      e_prim$3667                                                  */
SECTION_DATA u8 data_80699D74[8] = {
	0xFF, 0x78, 0x00, 0x00, 0xFF, 0x64, 0x78, 0x00,
};
/* 80699D7C-80699D84 0008 .data      e_env$3668                                                   */
SECTION_DATA u8 data_80699D7C[8] = {
	0x5A, 0x2D, 0x2D, 0x00, 0x3C, 0x1E, 0x1E, 0x00,
};
/* 80699D84-80699D8C 0006 .data      eff_id$3676                                                  */
SECTION_DATA u8 data_80699D84[8] = {
	0x02, 0x9D, 0x02, 0x9E, 0x02, 0x9F,
	/* padding */
	0x00, 0x00,
};
/* 80699D8C-80699DCC 0040 .data      cc_sph_src$4251                                              */
SECTION_DATA u8 data_80699D8C[64] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0D,
	0xD8, 0xFB, 0xFD, 0xFF, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x75, 0x0B, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x42, 0x20, 0x00, 0x00,
};
/* 80699DCC-80699DEC 0020 .data      l_daE_CR_Method                                              */
SECTION_DATA u8 l_daE_CR_Method[32] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80699DEC-80699E1C 0030 .data      g_profile_E_CR                                               */
SECTION_DATA u8 g_profile_E_CR[48] = {
	0xFF, 0xFF, 0xFF, 0xFD, 0x00, 0x07, 0xFF, 0xFD, 0x01, 0xC3, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x0A, 0x60, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x71, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10, 0x04, 0x01, 0x00, 0x02, 0x00, 0x00, 0x00,
};
/* 80699E1C-80699E28 000C .data      __vt__12dBgS_AcchCir                                         */
SECTION_DATA void* __vt__12dBgS_AcchCir[3] = {
	NULL, /* RTTI */
	NULL,
	NULL,
};
/* 80699E28-80699E34 000C .data      __vt__10cCcD_GStts                                           */
SECTION_DATA void* __vt__10cCcD_GStts[3] = {
	NULL, /* RTTI */
	NULL,
	NULL,
};
/* 80699E34-80699E40 000C .data      __vt__10dCcD_GStts                                           */
SECTION_DATA void* __vt__10dCcD_GStts[3] = {
	NULL, /* RTTI */
	NULL,
	NULL,
};
/* 80699E40-80699E4C 000C .data      __vt__8cM3dGSph                                              */
SECTION_DATA void* __vt__8cM3dGSph[3] = {
	NULL, /* RTTI */
	NULL,
	NULL,
};
/* 80699E4C-80699E58 000C .data      __vt__8cM3dGAab                                              */
SECTION_DATA void* __vt__8cM3dGAab[3] = {
	NULL, /* RTTI */
	NULL,
	NULL,
};
/* 80699E58-80699E7C 0024 .data      __vt__12dBgS_ObjAcch                                         */
SECTION_DATA void* __vt__12dBgS_ObjAcch[9] = {
	NULL, /* RTTI */
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
};
/* 80699E7C-80699E88 000C .data      __vt__12daE_CR_HIO_c                                         */
SECTION_DATA void* __vt__12daE_CR_HIO_c[3] = {
	NULL, /* RTTI */
	NULL,
	NULL,
};
}


/* ###################################################################################### */
/*                                          .bss                                          */
/* ###################################################################################### */

extern "C" {
/* 80699E94-80699E98 0004 .bss       None                                                         */
SECTION_BSS u8 d_a_e_cr__data_80699E94[4];
/* 80699E98-80699EA4 000C .bss       @3804                                                        */
SECTION_BSS u8 LIT_3804[12];
/* 80699EA4-80699EB8 0014 .bss       l_HIO                                                        */
SECTION_BSS u8 l_HIO[20];
}


/* ###################################################################################### */
/*                                         .text                                          */
/* ###################################################################################### */

/* 8069800C-80698044 0038 .text      __ct__12daE_CR_HIO_cFv                                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __ct__12daE_CR_HIO_cFv() {
	nofralloc
#include "asm/rel/d_a_e_cr/d_a_e_cr/__ct__12daE_CR_HIO_cFv.s"
}
#pragma pop

/* 80698044-806980F0 00AC .text      anm_init__FP10e_cr_classifUcf                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void anm_init__FP10e_cr_classifUcf() {
	nofralloc
#include "asm/rel/d_a_e_cr/d_a_e_cr/anm_init__FP10e_cr_classifUcf.s"
}
#pragma pop

/* 806980F0-806981B4 00C4 .text      nodeCallBack__FP8J3DJointi                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void nodeCallBack__FP8J3DJointi() {
	nofralloc
#include "asm/rel/d_a_e_cr/d_a_e_cr/nodeCallBack__FP8J3DJointi.s"
}
#pragma pop

/* 806981B4-80698250 009C .text      daE_CR_Draw__FP10e_cr_class                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daE_CR_Draw__FP10e_cr_class() {
	nofralloc
#include "asm/rel/d_a_e_cr/d_a_e_cr/daE_CR_Draw__FP10e_cr_class.s"
}
#pragma pop

/* 80698250-80698328 00D8 .text      other_bg_check__FP10e_cr_classP10fopAc_ac_c                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void other_bg_check__FP10e_cr_classP10fopAc_ac_c() {
	nofralloc
#include "asm/rel/d_a_e_cr/d_a_e_cr/other_bg_check__FP10e_cr_classP10fopAc_ac_c.s"
}
#pragma pop

/* 80698328-806983A4 007C .text      pl_check__FP10e_cr_classfs                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void pl_check__FP10e_cr_classfs() {
	nofralloc
#include "asm/rel/d_a_e_cr/d_a_e_cr/pl_check__FP10e_cr_classfs.s"
}
#pragma pop

/* 806983A4-80698498 00F4 .text      damage_check__FP10e_cr_class                                 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void damage_check__FP10e_cr_class() {
	nofralloc
#include "asm/rel/d_a_e_cr/d_a_e_cr/damage_check__FP10e_cr_class.s"
}
#pragma pop

/* 80698498-806985A4 010C .text      way_bg_check__FP10e_cr_classf                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void way_bg_check__FP10e_cr_classf() {
	nofralloc
#include "asm/rel/d_a_e_cr/d_a_e_cr/way_bg_check__FP10e_cr_classf.s"
}
#pragma pop

/* 806985A4-80698A5C 04B8 .text      e_cr_move__FP10e_cr_class                                    */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void e_cr_move__FP10e_cr_class() {
	nofralloc
#include "asm/rel/d_a_e_cr/d_a_e_cr/e_cr_move__FP10e_cr_class.s"
}
#pragma pop

/* 80698A5C-80698B80 0124 .text      e_cr_s_damage__FP10e_cr_class                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void e_cr_s_damage__FP10e_cr_class() {
	nofralloc
#include "asm/rel/d_a_e_cr/d_a_e_cr/e_cr_s_damage__FP10e_cr_class.s"
}
#pragma pop

/* 80698B80-80698D6C 01EC .text      e_cr_damage__FP10e_cr_class                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void e_cr_damage__FP10e_cr_class() {
	nofralloc
#include "asm/rel/d_a_e_cr/d_a_e_cr/e_cr_damage__FP10e_cr_class.s"
}
#pragma pop

/* 80698D6C-80698F88 021C .text      action__FP10e_cr_class                                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void action__FP10e_cr_class() {
	nofralloc
#include "asm/rel/d_a_e_cr/d_a_e_cr/action__FP10e_cr_class.s"
}
#pragma pop

/* 80698F88-806991BC 0234 .text      daE_CR_Execute__FP10e_cr_class                               */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daE_CR_Execute__FP10e_cr_class() {
	nofralloc
#include "asm/rel/d_a_e_cr/d_a_e_cr/daE_CR_Execute__FP10e_cr_class.s"
}
#pragma pop

/* 806991BC-806991C4 0008 .text      daE_CR_IsDelete__FP10e_cr_class                              */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daE_CR_IsDelete__FP10e_cr_class() {
	nofralloc
#include "asm/rel/d_a_e_cr/d_a_e_cr/daE_CR_IsDelete__FP10e_cr_class.s"
}
#pragma pop

/* 806991C4-8069922C 0068 .text      daE_CR_Delete__FP10e_cr_class                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daE_CR_Delete__FP10e_cr_class() {
	nofralloc
#include "asm/rel/d_a_e_cr/d_a_e_cr/daE_CR_Delete__FP10e_cr_class.s"
}
#pragma pop

/* 8069922C-8069936C 0140 .text      useHeapInit__FP10fopAc_ac_c                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void useHeapInit__FP10fopAc_ac_c() {
	nofralloc
#include "asm/rel/d_a_e_cr/d_a_e_cr/useHeapInit__FP10fopAc_ac_c.s"
}
#pragma pop

/* 8069936C-806995E0 0274 .text      daE_CR_Create__FP10fopAc_ac_c                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daE_CR_Create__FP10fopAc_ac_c() {
	nofralloc
#include "asm/rel/d_a_e_cr/d_a_e_cr/daE_CR_Create__FP10fopAc_ac_c.s"
}
#pragma pop

/* 806995E0-80699628 0048 .text      __dt__8cM3dGSphFv                                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__8cM3dGSphFv() {
	nofralloc
#include "asm/rel/d_a_e_cr/d_a_e_cr/__dt__8cM3dGSphFv.s"
}
#pragma pop

/* 80699628-80699670 0048 .text      __dt__8cM3dGAabFv                                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__8cM3dGAabFv() {
	nofralloc
#include "asm/rel/d_a_e_cr/d_a_e_cr/__dt__8cM3dGAabFv.s"
}
#pragma pop

/* 80699670-806996CC 005C .text      __dt__10dCcD_GSttsFv                                         */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__10dCcD_GSttsFv() {
	nofralloc
#include "asm/rel/d_a_e_cr/d_a_e_cr/__dt__10dCcD_GSttsFv.s"
}
#pragma pop

/* 806996CC-8069973C 0070 .text      __dt__12dBgS_ObjAcchFv                                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__12dBgS_ObjAcchFv() {
	nofralloc
#include "asm/rel/d_a_e_cr/d_a_e_cr/__dt__12dBgS_ObjAcchFv.s"
}
#pragma pop

/* 8069973C-806997AC 0070 .text      __dt__12dBgS_AcchCirFv                                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__12dBgS_AcchCirFv() {
	nofralloc
#include "asm/rel/d_a_e_cr/d_a_e_cr/__dt__12dBgS_AcchCirFv.s"
}
#pragma pop

/* 806997AC-806997F4 0048 .text      __dt__10cCcD_GSttsFv                                         */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__10cCcD_GSttsFv() {
	nofralloc
#include "asm/rel/d_a_e_cr/d_a_e_cr/__dt__10cCcD_GSttsFv.s"
}
#pragma pop

/* 806997F4-8069983C 0048 .text      __dt__12daE_CR_HIO_cFv                                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__12daE_CR_HIO_cFv() {
	nofralloc
#include "asm/rel/d_a_e_cr/d_a_e_cr/__dt__12daE_CR_HIO_cFv.s"
}
#pragma pop

/* 8069983C-80699878 003C .text      __sinit_d_a_e_cr_cpp                                         */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __sinit_d_a_e_cr_cpp() {
	nofralloc
#include "asm/rel/d_a_e_cr/d_a_e_cr/__sinit_d_a_e_cr_cpp.s"
}
#pragma pop

/* 80699878-80699880 0008 .text      @36@__dt__12dBgS_ObjAcchFv                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void func_80699878() {
	nofralloc
#include "asm/rel/d_a_e_cr/d_a_e_cr/func_80699878.s"
}
#pragma pop

/* 80699880-80699888 0008 .text      @20@__dt__12dBgS_ObjAcchFv                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void func_80699880() {
	nofralloc
#include "asm/rel/d_a_e_cr/d_a_e_cr/func_80699880.s"
}
#pragma pop

/* 80699888-80699C9C 0414 .text      setMidnaBindEffect__FP13fopEn_enemy_cP15Z2CreatureEnemyP4cXyzP4cXyz */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void setMidnaBindEffect__FP13fopEn_enemy_cP15Z2CreatureEnemyP4cXyzP4cXyz() {
	nofralloc
#include "asm/rel/d_a_e_cr/d_a_e_cr/setMidnaBindEffect__FP13fopEn_enemy_cP15Z2CreatureEnemyP4cXyzP4cXyz.s"
}
#pragma pop


