// 
// Generated By: dol2asm
// 

#include "dolphin/types.h"

// 
// Forward References:
// 

extern "C" extern void mDoMtx_XrotM__FPA4_fs();
extern "C" extern void mDoMtx_YrotS__FPA4_fs();
extern "C" extern void mDoMtx_YrotM__FPA4_fs();
extern "C" extern void mDoMtx_ZrotM__FPA4_fs();
extern "C" extern void scaleM__14mDoMtx_stack_cFfff();
extern "C" extern void mDoExt_modelUpdateDL__FP8J3DModel();
extern "C" extern void setAnm__14mDoExt_McaMorfFP15J3DAnmTransformiffffPv();
extern "C" extern void play__14mDoExt_McaMorfFP3VecUlSc();
extern "C" extern void __ct__16mDoExt_McaMorfSOFP12J3DModelDataP25mDoExt_McaMorfCallBack1_cP25mDoExt_McaMorfCallBack2_cP15J3DAnmTransformifiiP10Z2CreatureUlUl();
extern "C" extern void setAnm__16mDoExt_McaMorfSOFP15J3DAnmTransformiffff();
extern "C" extern void play__16mDoExt_McaMorfSOFUlSc();
extern "C" extern void entryDL__16mDoExt_McaMorfSOFv();
extern "C" extern void modelCalc__16mDoExt_McaMorfSOFv();
extern "C" extern void stopZelAnime__16mDoExt_McaMorfSOFv();
extern "C" extern void init__19mDoExt_3DlineMat1_cFUsUsP7ResTIMGi();
extern "C" extern void update__19mDoExt_3DlineMat1_cFiR8_GXColorP12dKy_tevstr_c();
extern "C" extern void setMat__26mDoExt_3DlineMatSortPacketFP18mDoExt_3DlineMat_c();
extern "C" extern void mDoExt_J3DModel__create__FP12J3DModelDataUlUl();
extern "C" extern void __ct__10fopAc_ac_cFv();
extern "C" extern void fopAcIt_Judge__FPFPvPv_PvPv();
extern "C" extern void fopAcM_delete__FP10fopAc_ac_c();
extern "C" extern void fopAcM_createChild__FsUiUlPC4cXyziPC5csXyzPC4cXyzScPFPv_i();
extern "C" extern void fopAcM_entrySolidHeap__FP10fopAc_ac_cPFP10fopAc_ac_c_iUl();
extern "C" extern void fopAcM_SetMin__FP10fopAc_ac_cfff();
extern "C" extern void fopAcM_SetMax__FP10fopAc_ac_cfff();
extern "C" extern void fopAcM_searchActorAngleY__FPC10fopAc_ac_cPC10fopAc_ac_c();
extern "C" extern void fopAcM_createBokkuri__FUsPC4cXyziiiPC4cXyzii();
extern "C" extern void fopAcM_otherBgCheck__FPC10fopAc_ac_cPC10fopAc_ac_c();
extern "C" extern void gndCheck__11fopAcM_gc_cFPC4cXyz();
extern "C" extern void fpcSch_JudgeByID__FPvPv();
extern "C" extern void dComIfG_resLoad__FP30request_of_phase_process_classPCc();
extern "C" extern void dComIfG_resDelete__FP30request_of_phase_process_classPCc();
extern "C" extern void dComIfGp_getReverb__Fi();
extern "C" extern void dComIfGd_setShadow__FUlScP8J3DModelP4cXyzffffR13cBgS_PolyInfoP12dKy_tevstr_csfP9_GXTexObj();
extern "C" extern void isSwitch__10dSv_info_cCFii();
extern "C" extern void getRes__14dRes_control_cFPCclP11dRes_info_ci();
extern "C" extern void forceOnEventMove__Q213dPa_control_c7level_cFUl();
extern "C" extern void getEmitter__Q213dPa_control_c7level_cFUl();
extern "C" extern void set__13dPa_control_cFUcUsPC4cXyzPC12dKy_tevstr_cPC5csXyzPC4cXyzUcP18dPa_levelEcallBackScPC8_GXColorPC8_GXColorPC4cXyzf();
extern "C" extern void set__13dPa_control_cFUlUcUsPC4cXyzPC12dKy_tevstr_cPC5csXyzPC4cXyzUcP18dPa_levelEcallBackScPC8_GXColorPC8_GXColorPC4cXyzf();
extern "C" extern void StartShock__12dVibration_cFii4cXyz();
extern "C" extern void __ct__12dBgS_AcchCirFv();
extern "C" extern void SetWall__12dBgS_AcchCirFff();
extern "C" extern void __dt__9dBgS_AcchFv();
extern "C" extern void __ct__9dBgS_AcchFv();
extern "C" extern void Set__9dBgS_AcchFP4cXyzP4cXyzP10fopAc_ac_ciP12dBgS_AcchCirP4cXyzP5csXyzP5csXyz();
extern "C" extern void CrrPos__9dBgS_AcchFR4dBgS();
extern "C" extern void SetObj__16dBgS_PolyPassChkFv();
extern "C" extern void __ct__10dCcD_GSttsFv();
extern "C" extern void Move__10dCcD_GSttsFv();
extern "C" extern void Init__9dCcD_SttsFiiP10fopAc_ac_c();
extern "C" extern void __ct__12dCcD_GObjInfFv();
extern "C" extern void __dt__12dCcD_GObjInfFv();
extern "C" extern void ChkAtHit__12dCcD_GObjInfFv();
extern "C" extern void ChkTgHit__12dCcD_GObjInfFv();
extern "C" extern void GetTgHitObj__12dCcD_GObjInfFv();
extern "C" extern void Set__8dCcD_SphFRC11dCcD_SrcSph();
extern "C" extern void StartCAt__8dCcD_SphFR4cXyz();
extern "C" extern void MoveCAt__8dCcD_SphFR4cXyz();
extern "C" extern void def_se_set__FP10Z2CreatureP8cCcD_ObjUlP10fopAc_ac_c();
extern "C" extern void at_power_check__FP11dCcU_AtInfo();
extern "C" extern void settingTevStruct__18dScnKy_env_light_cFiP4cXyzP12dKy_tevstr_c();
extern "C" extern void setLightTevColorType_MAJI__18dScnKy_env_light_cFP12J3DModelDataP12dKy_tevstr_c();
extern "C" extern void dKy_darkworld_check__Fv();
extern "C" extern void GetAc__8cCcD_ObjFv();
extern "C" extern void Set__4cCcSFP8cCcD_Obj();
extern "C" extern void __pl__4cXyzCFRC3Vec();
extern "C" extern void __mi__4cXyzCFRC3Vec();
extern "C" extern void __ml__4cXyzCFf();
extern "C" extern void cM_atan2s__Fff();
extern "C" extern void cM_rndF__Ff();
extern "C" extern void cM_rndFX__Ff();
extern "C" extern void __dt__13cBgS_PolyInfoFv();
extern "C" extern void __dt__8cM3dGCirFv();
extern "C" extern void SetC__8cM3dGSphFRC4cXyz();
extern "C" extern void SetR__8cM3dGSphFf();
extern "C" extern void cLib_addCalc2__FPffff();
extern "C" extern void cLib_addCalc0__FPfff();
extern "C" extern void cLib_addCalcAngleS2__FPssss();
extern "C" extern void MtxScale__FfffUc();
extern "C" extern void MtxPosition__FP4cXyzP4cXyz();
extern "C" extern void deleteAllParticle__14JPABaseEmitterFv();
extern "C" extern void func_802807E0();
extern "C" extern void func_80280808();
extern "C" extern void __ct__15Z2CreatureEnemyFv();
extern "C" extern void init__15Z2CreatureEnemyFP3VecP3VecUcUc();
extern "C" extern void setLinkSearch__15Z2CreatureEnemyFb();
extern "C" extern void setEnemyName__15Z2CreatureEnemyFPCc();
extern "C" extern void __nw__FUl();
extern "C" extern void __dl__FPv();
extern "C" extern void checkPass__12J3DFrameCtrlFf();
extern "C" extern void PSMTXCopy();
extern "C" extern void PSMTXTrans();
extern "C" extern void PSMTXMultVec();
extern "C" extern void PSVECAdd();
extern "C" extern void PSVECSubtract();
extern "C" extern void PSVECSquareMag();
extern "C" extern void __construct_array();
extern "C" extern void _savegpr_19();
extern "C" extern void _savegpr_22();
extern "C" extern void _savegpr_23();
extern "C" extern void _savegpr_24();
extern "C" extern void _savegpr_25();
extern "C" extern void _savegpr_26();
extern "C" extern void _savegpr_27();
extern "C" extern void _savegpr_28();
extern "C" extern void _savegpr_29();
extern "C" extern void _restgpr_19();
extern "C" extern void _restgpr_22();
extern "C" extern void _restgpr_23();
extern "C" extern void _restgpr_24();
extern "C" extern void _restgpr_25();
extern "C" extern void _restgpr_26();
extern "C" extern void _restgpr_27();
extern "C" extern void _restgpr_28();
extern "C" extern void _restgpr_29();
SECTION_DATA extern void* const __vt__19mDoExt_3DlineMat1_c[5];
SECTION_DATA extern void* g_fopAc_Method[8];
SECTION_DATA extern void* g_fpcLf_Method[6];
SECTION_DATA extern void* const __vt__8dCcD_Sph[36];
SECTION_DATA extern void* const __vt__9dCcD_Stts[11];
SECTION_DATA extern void* const __vt__12cCcD_SphAttr[25];
SECTION_DATA extern void* const __vt__14cCcD_ShapeAttr[22];
SECTION_DATA extern void* const __vt__9cCcD_Stts[8];
SECTION_BSS extern u8 now__14mDoMtx_stack_c[48];
SECTION_BSS extern u8 mGndCheck__11fopAcM_gc_c[84];
SECTION_BSS extern u8 g_dComIfG_gameInfo[122384];
SECTION_BSS extern u8 mSimpleTexObj__21dDlst_shadowControl_c[32];
SECTION_BSS extern u8 g_env_light[4880];
SECTION_BSS extern u8 sincosTable___5JMath[65536];
SECTION_SDATA extern void* calc_mtx[2];
SECTION_SDATA extern u32 __float_nan;
SECTION_SBSS extern u8 mGroundY__11fopAcM_gc_c[4];
SECTION_SBSS extern u8 m_midnaActor__9daPy_py_c[4];
SECTION_SBSS extern u8 struct_80451124[4];
extern "C" extern void _unresolved();
extern "C" extern void __register_global_object();
extern "C" extern void __ct__12daE_HB_HIO_cFv();
extern "C" extern void anm_init__FP10e_hb_classifUcf();
extern "C" extern void leaf_anm_init__FP10e_hb_classifUcf();
extern "C" extern void daE_HB_Draw__FP10e_hb_class();
extern "C" extern void pl_check__FP10e_hb_classf();
extern "C" extern void damage_check__FP10e_hb_class();
extern "C" extern void e_hb_stay__FP10e_hb_class();
extern "C" extern void e_hb_appear__FP10e_hb_class();
extern "C" extern void e_hb_appear_v__FP10e_hb_class();
extern "C" extern void e_hb_wait__FP10e_hb_class();
extern "C" extern void e_hb_attack__FP10e_hb_class();
extern "C" extern void e_hb_chance__FP10e_hb_class();
extern "C" extern void e_hb_s_damage__FP10e_hb_class();
extern "C" extern void e_hb_damage__FP10e_hb_class();
extern "C" extern void kuki_control1__FP10e_hb_class();
extern "C" extern void kuki_control2__FP10e_hb_class();
extern "C" extern void kuki_control3__FP10e_hb_class();
extern "C" extern void kuki_ha_set__FP10e_hb_class();
extern "C" extern void action__FP10e_hb_class();
extern "C" extern void eff_set__FP10e_hb_classi();
extern "C" extern void anm_se_set__FP10e_hb_class();
extern "C" extern void daE_HB_Execute__FP10e_hb_class();
extern "C" extern void daE_HB_IsDelete__FP10e_hb_class();
extern "C" extern void daE_HB_Delete__FP10e_hb_class();
extern "C" extern void useHeapInit__FP10fopAc_ac_c();
extern "C" extern void daE_HB_Create__FP10fopAc_ac_c();
extern "C" extern void __dt__12dBgS_ObjAcchFv();
extern "C" extern void __dt__12dBgS_AcchCirFv();
extern "C" extern void __ct__8dCcD_SphFv();
extern "C" extern void __dt__8dCcD_SphFv();
extern "C" extern void __dt__8cM3dGSphFv();
extern "C" extern void __dt__8cM3dGAabFv();
extern "C" extern void __dt__10dCcD_GSttsFv();
extern "C" extern void __ct__5csXyzFv();
extern "C" extern void __ct__4cXyzFv();
extern "C" extern void __dt__10cCcD_GSttsFv();
extern "C" extern void __dt__12daE_HB_HIO_cFv();
extern "C" extern void __sinit_d_a_e_hb_cpp();
extern "C" extern void func_80500654();
extern "C" extern void func_8050065C();
extern "C" extern void setMidnaBindEffect__FP13fopEn_enemy_cP15Z2CreatureEnemyP4cXyzP4cXyz();
extern "C" extern void __dt__5csXyzFv();
extern "C" extern void __dt__4cXyzFv();
SECTION_RODATA extern const u32 lit_3788;
SECTION_RODATA extern const u8 lit_3789[4];
SECTION_RODATA extern const u32 lit_3790;
SECTION_RODATA extern const u8 lit_3791[8];
SECTION_RODATA extern const u8 lit_3792[8];
SECTION_RODATA extern const u8 lit_3793[8];
SECTION_RODATA extern const u32 lit_3794;
SECTION_RODATA extern const u32 lit_3809;
SECTION_RODATA extern const u32 lit_3823;
SECTION_RODATA extern const u32 lit_3870;
SECTION_RODATA extern const u32 lit_3871;
SECTION_RODATA extern const u32 lit_4035;
SECTION_RODATA extern const u32 lit_4036;
SECTION_RODATA extern const u32 lit_4037;
SECTION_RODATA extern const u32 lit_4038;
SECTION_RODATA extern const u32 lit_4039;
SECTION_RODATA extern const u32 lit_4040;
SECTION_RODATA extern const u32 lit_4041;
SECTION_RODATA extern const u32 lit_4042;
SECTION_RODATA extern const u32 lit_4043;
SECTION_RODATA extern const u32 lit_4044;
SECTION_RODATA extern const u32 lit_4078;
SECTION_RODATA extern const u32 lit_4108;
SECTION_RODATA extern const u32 lit_4109;
SECTION_RODATA extern const u32 lit_4110;
SECTION_RODATA extern const u32 lit_4111;
SECTION_RODATA extern const u32 lit_4112;
SECTION_RODATA extern const u32 lit_4113;
SECTION_RODATA extern const u32 lit_4206;
SECTION_RODATA extern const u32 lit_4207;
SECTION_RODATA extern const u32 lit_4208;
SECTION_RODATA extern const u32 lit_4209;
SECTION_RODATA extern const u32 lit_4210;
SECTION_RODATA extern const u8 lit_4212[8];
SECTION_RODATA extern const u32 lit_4405;
SECTION_RODATA extern const u32 lit_4406;
SECTION_RODATA extern const u32 lit_4407;
SECTION_RODATA extern const u32 lit_4408;
SECTION_RODATA extern const u32 lit_4409;
SECTION_RODATA extern const u32 lit_4410;
SECTION_RODATA extern const u32 lit_4411;
SECTION_RODATA extern const u32 lit_4464;
SECTION_RODATA extern const u32 lit_4465;
SECTION_RODATA extern const u32 lit_4510;
SECTION_RODATA extern const u32 lit_4511;
SECTION_RODATA extern const u32 lit_4588;
SECTION_RODATA extern const u32 lit_4589;
SECTION_RODATA extern const u32 lit_4590;
SECTION_RODATA extern const u32 lit_4669;
SECTION_RODATA extern const u32 lit_4670;
SECTION_RODATA extern const u32 lit_4725;
SECTION_RODATA extern const u32 lit_4821;
SECTION_RODATA extern const u32 lit_4822;
SECTION_RODATA extern const u32 lit_4823;
SECTION_RODATA extern const u32 lit_4824;
SECTION_RODATA extern const u32 lit_4963;
SECTION_RODATA extern const u32 lit_4964;
SECTION_RODATA extern const u32 lit_4965;
SECTION_RODATA extern const u32 lit_4966;
SECTION_RODATA extern const u32 lit_5136;
SECTION_RODATA extern const u32 lit_5137;
SECTION_RODATA extern const u32 lit_5234;
SECTION_RODATA extern const u32 lit_5440;
SECTION_RODATA extern const u32 lit_5441;
SECTION_RODATA extern const u32 lit_5442;
SECTION_RODATA extern const u32 lit_5443;
SECTION_RODATA extern const u32 lit_5444;
SECTION_RODATA extern const u8 lit_5446[8];
SECTION_RODATA extern const u8 stringBase0[5];
SECTION_DATA extern u8 cNullVec__6Z2Calc[12];
SECTION_DATA extern u32 lit_1787;
SECTION_DATA extern u8 data_80500C5C[8];
SECTION_DATA extern u8 data_80500C64[8];
SECTION_DATA extern u8 data_80500C6C[8];
SECTION_DATA extern u8 data_80500C74[4];
SECTION_DATA extern u8 data_80500C78[24];
SECTION_DATA extern void* lit_4967[9];
SECTION_DATA extern u8 data_80500CB4[8];
SECTION_DATA extern u8 data_80500CBC[12];
SECTION_DATA extern u8 data_80500CC8[64];
SECTION_DATA extern u8 data_80500D08[64];
SECTION_DATA extern u8 data_80500D48[64];
SECTION_DATA extern void* l_daE_HB_Method[8];
SECTION_DATA extern void* g_profile_E_HB[12];
SECTION_DATA extern void* const __vt__10cCcD_GStts[3];
SECTION_DATA extern void* const __vt__10dCcD_GStts[3];
SECTION_DATA extern void* const __vt__12dBgS_AcchCir[3];
SECTION_DATA extern void* const __vt__12dBgS_ObjAcch[9];
SECTION_DATA extern void* const __vt__8cM3dGSph[3];
SECTION_DATA extern void* const __vt__8cM3dGAab[3];
SECTION_DATA extern void* const __vt__18mDoExt_3DlineMat_c[5];
SECTION_DATA extern void* const __vt__12daE_HB_HIO_c[3];
SECTION_BSS extern u8 data_80500E74[4];
SECTION_BSS extern u8 lit_3804[12];
SECTION_BSS extern u8 l_HIO[28];

// 
// Functions:
// 

/* ###################################################################################### */
/* 80500B04-80500B08 0004 .rodata    @3788                                                        */
SECTION_RODATA const u32 lit_3788 = 0x42C80000;

/* 80500B08-80500B0C 0004 .rodata    @3789                                                        */
SECTION_RODATA const u8 lit_3789[4] = {
	0x00, 0x00, 0x00, 0x00,
};

/* 80500B0C-80500B14 0004 .rodata    @3790                                                        */
SECTION_RODATA const u32 lit_3790 = 0x3F800000;
/* padding 4 bytes */

/* 80500B14-80500B1C 0008 .rodata    @3791                                                        */
SECTION_RODATA const u8 lit_3791[8] = {
	0x3F, 0xE0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

/* 80500B1C-80500B24 0008 .rodata    @3792                                                        */
SECTION_RODATA const u8 lit_3792[8] = {
	0x40, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

/* 80500B24-80500B2C 0008 .rodata    @3793                                                        */
SECTION_RODATA const u8 lit_3793[8] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

/* 80500B2C-80500B30 0004 .rodata    @3794                                                        */
SECTION_RODATA const u32 lit_3794 = 0x3C23D70A;

/* 80500B30-80500B34 0004 .rodata    @3809                                                        */
SECTION_RODATA const u32 lit_3809 = 0x3F000000;

/* 80500C3C-80500C48 000C .data      cNullVec__6Z2Calc                                            */
u8 cNullVec__6Z2Calc[12] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

/* 80500C48-80500C5C 0004 .data      @1787                                                        */
u32 lit_1787 = 0x02000201;
/* padding 16 bytes */

/* 80500C5C-80500C64 0008 .data      e_prim$3667                                                  */
u8 data_80500C5C[8] = {
	0xFF, 0x78, 0x00, 0x00, 0xFF, 0x64, 0x78, 0x00,
};

/* 80500C64-80500C6C 0008 .data      e_env$3668                                                   */
u8 data_80500C64[8] = {
	0x5A, 0x2D, 0x2D, 0x00, 0x3C, 0x1E, 0x1E, 0x00,
};

/* 80500C6C-80500C74 0006 .data      eff_id$3676                                                  */
u8 data_80500C6C[8] = {
	0x02, 0x9D, 0x02, 0x9E, 0x02, 0x9F,
	/* padding */
	0x00, 0x00,
};

/* 80500C74-80500C78 0004 .data      l_color$3841                                                 */
u8 data_80500C74[4] = {
	0x14, 0x0F, 0x00, 0xFF,
};

/* 80500C78-80500C90 0016 .data      pow_xa$4594                                                  */
u8 data_80500C78[24] = {
	0x00, 0x00, 0x00, 0x00, 0x10, 0x00, 0x20, 0x00, 0x30, 0x00, 0x40, 0x00, 0x30, 0x00, 0x20, 0x00,
	0x10, 0x00, 0x00, 0x00, 0x00, 0x00,
	/* padding */
	0x00, 0x00,
};

/* 80500C90-80500CB4 0024 .data      @4967                                                        */
void* lit_4967[9] = {
	(void*)(((char*)action__FP10e_hb_class)+0x1CC),
	(void*)(((char*)action__FP10e_hb_class)+0x1E0),
	(void*)(((char*)action__FP10e_hb_class)+0x200),
	(void*)(((char*)action__FP10e_hb_class)+0x220),
	(void*)(((char*)action__FP10e_hb_class)+0x240),
	(void*)(((char*)action__FP10e_hb_class)+0x2AC),
	(void*)(((char*)action__FP10e_hb_class)+0x260),
	(void*)(((char*)action__FP10e_hb_class)+0x280),
	(void*)(((char*)action__FP10e_hb_class)+0x2A0),
};

/* 80500CB4-80500CBC 0006 .data      p_name$4973                                                  */
u8 data_80500CB4[8] = {
	0x83, 0x39, 0x83, 0x3A, 0x83, 0x3B,
	/* padding */
	0x00, 0x00,
};

/* 80500CBC-80500CC8 000C .data      p_idx$4974                                                   */
u8 data_80500CBC[12] = {
	0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x06,
};

/* 80500CC8-80500D08 0040 .data      cc_sph_src$5310                                              */
u8 data_80500CC8[64] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0D,
	0xD8, 0xFB, 0xFD, 0xFF, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x25, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x0A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x42, 0x20, 0x00, 0x00,
};

/* 80500D08-80500D48 0040 .data      at_sph_src$5311                                              */
u8 data_80500D08[64] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0D,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0B, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x42, 0x0C, 0x00, 0x00,
};

/* 80500D48-80500D88 0040 .data      kuki_sph_src$5312                                            */
u8 data_80500D48[64] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0D,
	0xD8, 0xFB, 0xFD, 0xFF, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x41, 0xA0, 0x00, 0x00,
};

/* 80500D88-80500DA8 0020 .data      l_daE_HB_Method                                              */
void* l_daE_HB_Method[8] = {
	(void*)daE_HB_Create__FP10fopAc_ac_c,
	(void*)daE_HB_Delete__FP10e_hb_class,
	(void*)daE_HB_Execute__FP10e_hb_class,
	(void*)daE_HB_IsDelete__FP10e_hb_class,
	(void*)daE_HB_Draw__FP10e_hb_class,
	NULL,
	NULL,
	NULL,
};

/* 80500DA8-80500DD8 0030 .data      g_profile_E_HB                                               */
void* g_profile_E_HB[12] = {
	(void*)0xFFFFFFFD,
	(void*)0x0007FFFD,
	(void*)0x01C90000,
	(void*)&g_fpcLf_Method,
	(void*)0x00001268,
	NULL,
	NULL,
	(void*)&g_fopAc_Method,
	(void*)0x008C0000,
	(void*)&l_daE_HB_Method,
	(void*)0x10050100,
	(void*)0x020E0000,
};

/* 80500DD8-80500DE4 000C .data      __vt__10cCcD_GStts                                           */
void* const __vt__10cCcD_GStts[3] = {
	NULL, /* RTTI */
	NULL,
	NULL,
};

/* 80500DE4-80500DF0 000C .data      __vt__10dCcD_GStts                                           */
void* const __vt__10dCcD_GStts[3] = {
	NULL, /* RTTI */
	NULL,
	NULL,
};

/* 80500DF0-80500DFC 000C .data      __vt__12dBgS_AcchCir                                         */
void* const __vt__12dBgS_AcchCir[3] = {
	NULL, /* RTTI */
	NULL,
	NULL,
};

/* 80500DFC-80500E20 0024 .data      __vt__12dBgS_ObjAcch                                         */
void* const __vt__12dBgS_ObjAcch[9] = {
	NULL, /* RTTI */
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
};

/* 80500E20-80500E2C 000C .data      __vt__8cM3dGSph                                              */
void* const __vt__8cM3dGSph[3] = {
	NULL, /* RTTI */
	NULL,
	NULL,
};

/* 80500E2C-80500E38 000C .data      __vt__8cM3dGAab                                              */
void* const __vt__8cM3dGAab[3] = {
	NULL, /* RTTI */
	NULL,
	NULL,
};

/* 80500E38-80500E4C 0014 .data      __vt__18mDoExt_3DlineMat_c                                   */
void* const __vt__18mDoExt_3DlineMat_c[5] = {
	NULL, /* RTTI */
	NULL,
	NULL,
	NULL,
	NULL,
};

/* 80500E4C-80500E58 000C .data      __vt__12daE_HB_HIO_c                                         */
void* const __vt__12daE_HB_HIO_c[3] = {
	NULL, /* RTTI */
	NULL,
	NULL,
};

/* 804FBD6C-804FBDB8 004C .text      __ct__12daE_HB_HIO_cFv                                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void __ct__12daE_HB_HIO_cFv() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/__ct__12daE_HB_HIO_cFv.s"
}
#pragma pop


/* ###################################################################################### */
/* 80500B34-80500B38 0004 .rodata    @3823                                                        */
SECTION_RODATA const u32 lit_3823 = 0xBF800000;

/* 80500B38-80500B3C 0004 .rodata    @3870                                                        */
SECTION_RODATA const u32 lit_3870 = 0x42480000;

/* 80500B3C-80500B40 0004 .rodata    @3871                                                        */
SECTION_RODATA const u32 lit_3871 = 0x44160000;

/* 80500B40-80500B44 0004 .rodata    @4035                                                        */
SECTION_RODATA const u32 lit_4035 = 0x41200000;

/* 80500B44-80500B48 0004 .rodata    @4036                                                        */
SECTION_RODATA const u32 lit_4036 = 0xC32A0000;

/* 80500B48-80500B4C 0004 .rodata    @4037                                                        */
SECTION_RODATA const u32 lit_4037 = 0x432A0000;

/* 80500B4C-80500B50 0004 .rodata    @4038                                                        */
SECTION_RODATA const u32 lit_4038 = 0x3E4CCCCD;

/* 80500B50-80500B54 0004 .rodata    @4039                                                        */
SECTION_RODATA const u32 lit_4039 = 0x3DCCCCCD;

/* 80500B54-80500B58 0004 .rodata    @4040                                                        */
SECTION_RODATA const u32 lit_4040 = 0x41A00000;

/* 80500B58-80500B5C 0004 .rodata    @4041                                                        */
SECTION_RODATA const u32 lit_4041 = 0x40800000;

/* 80500B5C-80500B60 0004 .rodata    @4042                                                        */
SECTION_RODATA const u32 lit_4042 = 0x3ECCCCCD;

/* 80500B60-80500B64 0004 .rodata    @4043                                                        */
SECTION_RODATA const u32 lit_4043 = 0x3CA3D70A;

/* 80500B64-80500B68 0004 .rodata    @4044                                                        */
SECTION_RODATA const u32 lit_4044 = 0x3D4CCCCD;

/* 80500B68-80500B6C 0004 .rodata    @4078                                                        */
SECTION_RODATA const u32 lit_4078 = 0x41F00000;

/* 80500B6C-80500B70 0004 .rodata    @4108                                                        */
SECTION_RODATA const u32 lit_4108 = 0x40A00000;

/* 80500B70-80500B74 0004 .rodata    @4109                                                        */
SECTION_RODATA const u32 lit_4109 = 0x41700000;

/* 80500B74-80500B78 0004 .rodata    @4110                                                        */
SECTION_RODATA const u32 lit_4110 = 0x42700000;

/* 80500B78-80500B7C 0004 .rodata    @4111                                                        */
SECTION_RODATA const u32 lit_4111 = 0x42200000;

/* 80500B7C-80500B80 0004 .rodata    @4112                                                        */
SECTION_RODATA const u32 lit_4112 = 0x43C80000;

/* 80500B80-80500B84 0004 .rodata    @4113                                                        */
SECTION_RODATA const u32 lit_4113 = 0x3E19999A;

/* 80500B84-80500B88 0004 .rodata    @4206                                                        */
SECTION_RODATA const u32 lit_4206 = 0x3F400000;

/* 80500B88-80500B8C 0004 .rodata    @4207                                                        */
SECTION_RODATA const u32 lit_4207 = 0x42B40000;

/* 80500B8C-80500B90 0004 .rodata    @4208                                                        */
SECTION_RODATA const u32 lit_4208 = 0xC2C80000;

/* 80500B90-80500B94 0004 .rodata    @4209                                                        */
SECTION_RODATA const u32 lit_4209 = 0x3E99999A;

/* 80500B94-80500B9C 0004 .rodata    @4210                                                        */
SECTION_RODATA const u32 lit_4210 = 0x442F0000;
/* padding 4 bytes */

/* 80500B9C-80500BA4 0008 .rodata    @4212                                                        */
SECTION_RODATA const u8 lit_4212[8] = {
	0x43, 0x30, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00,
};

/* 80500BA4-80500BA8 0004 .rodata    @4405                                                        */
SECTION_RODATA const u32 lit_4405 = 0x43AF0000;

/* 80500BA8-80500BAC 0004 .rodata    @4406                                                        */
SECTION_RODATA const u32 lit_4406 = 0x3F4CCCCD;

/* 80500BAC-80500BB0 0004 .rodata    @4407                                                        */
SECTION_RODATA const u32 lit_4407 = 0x40000000;

/* 80500BB0-80500BB4 0004 .rodata    @4408                                                        */
SECTION_RODATA const u32 lit_4408 = 0x44FA0000;

/* 80500BB4-80500BB8 0004 .rodata    @4409                                                        */
SECTION_RODATA const u32 lit_4409 = 0x428C0000;

/* 80500BB8-80500BBC 0004 .rodata    @4410                                                        */
SECTION_RODATA const u32 lit_4410 = 0xC2480000;

/* 80500BBC-80500BC0 0004 .rodata    @4411                                                        */
SECTION_RODATA const u32 lit_4411 = 0x43480000;

/* 80500BC0-80500BC4 0004 .rodata    @4464                                                        */
SECTION_RODATA const u32 lit_4464 = 0x43660000;

/* 80500BC4-80500BC8 0004 .rodata    @4465                                                        */
SECTION_RODATA const u32 lit_4465 = 0x40400000;

/* 80500BC8-80500BCC 0004 .rodata    @4510                                                        */
SECTION_RODATA const u32 lit_4510 = 0x437A0000;

/* 80500BCC-80500BD0 0004 .rodata    @4511                                                        */
SECTION_RODATA const u32 lit_4511 = 0x3F6B851F;

/* 80500BD0-80500BD4 0004 .rodata    @4588                                                        */
SECTION_RODATA const u32 lit_4588 = 0xC1A00000;

/* 80500BD4-80500BD8 0004 .rodata    @4589                                                        */
SECTION_RODATA const u32 lit_4589 = 0x43E10000;

/* 80500BD8-80500BDC 0004 .rodata    @4590                                                        */
SECTION_RODATA const u32 lit_4590 = 0xBDCCCCCD;

/* 80500BDC-80500BE0 0004 .rodata    @4669                                                        */
SECTION_RODATA const u32 lit_4669 = 0xC1F00000;

/* 80500BE0-80500BE4 0004 .rodata    @4670                                                        */
SECTION_RODATA const u32 lit_4670 = 0xC3480000;

/* 80500BE4-80500BE8 0004 .rodata    @4725                                                        */
SECTION_RODATA const u32 lit_4725 = 0x41300000;

/* 80500BE8-80500BEC 0004 .rodata    @4821                                                        */
SECTION_RODATA const u32 lit_4821 = 0xC1200000;

/* 80500BEC-80500BF0 0004 .rodata    @4822                                                        */
SECTION_RODATA const u32 lit_4822 = 0x461C4000;

/* 80500BF0-80500BF4 0004 .rodata    @4823                                                        */
SECTION_RODATA const u32 lit_4823 = 0x47800000;

/* 80500BF4-80500BF8 0004 .rodata    @4824                                                        */
SECTION_RODATA const u32 lit_4824 = 0xC0A00000;

/* 80500BF8-80500BFC 0004 .rodata    @4963                                                        */
SECTION_RODATA const u32 lit_4963 = 0x41C80000;

/* 80500BFC-80500C00 0004 .rodata    @4964                                                        */
SECTION_RODATA const u32 lit_4964 = 0xC6EA6000;

/* 80500C00-80500C04 0004 .rodata    @4965                                                        */
SECTION_RODATA const u32 lit_4965 = 0x48927C00;

/* 80500C04-80500C08 0004 .rodata    @4966                                                        */
SECTION_RODATA const u32 lit_4966 = 0x46EA6000;

/* 80500C08-80500C0C 0004 .rodata    @5136                                                        */
SECTION_RODATA const u32 lit_5136 = 0x41B00000;

/* 80500C0C-80500C10 0004 .rodata    @5137                                                        */
SECTION_RODATA const u32 lit_5137 = 0x41A80000;

/* 80500C10-80500C14 0004 .rodata    @5234                                                        */
SECTION_RODATA const u32 lit_5234 = 0xC69C4000;

/* 80500C14-80500C18 0004 .rodata    @5440                                                        */
SECTION_RODATA const u32 lit_5440 = 0x43FA0000;

/* 80500C18-80500C1C 0004 .rodata    @5441                                                        */
SECTION_RODATA const u32 lit_5441 = 0xC3960000;

/* 80500C1C-80500C20 0004 .rodata    @5442                                                        */
SECTION_RODATA const u32 lit_5442 = 0xC3C80000;

/* 80500C20-80500C24 0004 .rodata    @5443                                                        */
SECTION_RODATA const u32 lit_5443 = 0x43960000;

/* 80500C24-80500C2C 0004 .rodata    @5444                                                        */
SECTION_RODATA const u32 lit_5444 = 0x477FFF00;
/* padding 4 bytes */

/* 80500C2C-80500C34 0008 .rodata    @5446                                                        */
SECTION_RODATA const u8 lit_5446[8] = {
	0x43, 0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

/* 80500C34-80500C39 0005 .rodata    @stringBase0                                                 */
#pragma push
#pragma force_active on
#pragma section ".dead"
SECTION_DEAD const char* const stringBase_80500C34 = "E_hb";
#pragma pop

/* 804FBDB8-804FBE64 00AC .text      anm_init__FP10e_hb_classifUcf                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void anm_init__FP10e_hb_classifUcf() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/anm_init__FP10e_hb_classifUcf.s"
}
#pragma pop


/* 804FBE64-804FBF3C 00D8 .text      leaf_anm_init__FP10e_hb_classifUcf                           */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void leaf_anm_init__FP10e_hb_classifUcf() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/leaf_anm_init__FP10e_hb_classifUcf.s"
}
#pragma pop


/* 804FBF3C-804FC0C0 0184 .text      daE_HB_Draw__FP10e_hb_class                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void daE_HB_Draw__FP10e_hb_class() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/daE_HB_Draw__FP10e_hb_class.s"
}
#pragma pop


/* 804FC0C0-804FC118 0058 .text      pl_check__FP10e_hb_classf                                    */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void pl_check__FP10e_hb_classf() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/pl_check__FP10e_hb_classf.s"
}
#pragma pop


/* 804FC118-804FC504 03EC .text      damage_check__FP10e_hb_class                                 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void damage_check__FP10e_hb_class() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/damage_check__FP10e_hb_class.s"
}
#pragma pop


/* ###################################################################################### */
/* 80500E74-80500E78 0004 .bss       None                                                         */
u8 data_80500E74[4];

/* 80500E78-80500E84 000C .bss       @3804                                                        */
u8 lit_3804[12];

/* 80500E84-80500EA0 001C .bss       l_HIO                                                        */
u8 l_HIO[28];

/* 804FC504-804FC85C 0358 .text      e_hb_stay__FP10e_hb_class                                    */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void e_hb_stay__FP10e_hb_class() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/e_hb_stay__FP10e_hb_class.s"
}
#pragma pop


/* 804FC85C-804FCB1C 02C0 .text      e_hb_appear__FP10e_hb_class                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void e_hb_appear__FP10e_hb_class() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/e_hb_appear__FP10e_hb_class.s"
}
#pragma pop


/* 804FCB1C-804FCCE8 01CC .text      e_hb_appear_v__FP10e_hb_class                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void e_hb_appear_v__FP10e_hb_class() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/e_hb_appear_v__FP10e_hb_class.s"
}
#pragma pop


/* 804FCCE8-804FD230 0548 .text      e_hb_wait__FP10e_hb_class                                    */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void e_hb_wait__FP10e_hb_class() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/e_hb_wait__FP10e_hb_class.s"
}
#pragma pop


/* 804FD230-804FDC90 0A60 .text      e_hb_attack__FP10e_hb_class                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void e_hb_attack__FP10e_hb_class() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/e_hb_attack__FP10e_hb_class.s"
}
#pragma pop


/* 804FDC90-804FDF90 0300 .text      e_hb_chance__FP10e_hb_class                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void e_hb_chance__FP10e_hb_class() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/e_hb_chance__FP10e_hb_class.s"
}
#pragma pop


/* 804FDF90-804FE1E8 0258 .text      e_hb_s_damage__FP10e_hb_class                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void e_hb_s_damage__FP10e_hb_class() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/e_hb_s_damage__FP10e_hb_class.s"
}
#pragma pop


/* 804FE1E8-804FE5C8 03E0 .text      e_hb_damage__FP10e_hb_class                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void e_hb_damage__FP10e_hb_class() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/e_hb_damage__FP10e_hb_class.s"
}
#pragma pop


/* 804FE5C8-804FE8F8 0330 .text      kuki_control1__FP10e_hb_class                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void kuki_control1__FP10e_hb_class() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/kuki_control1__FP10e_hb_class.s"
}
#pragma pop


/* 804FE8F8-804FEA6C 0174 .text      kuki_control2__FP10e_hb_class                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void kuki_control2__FP10e_hb_class() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/kuki_control2__FP10e_hb_class.s"
}
#pragma pop


/* 804FEA6C-804FEB48 00DC .text      kuki_control3__FP10e_hb_class                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void kuki_control3__FP10e_hb_class() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/kuki_control3__FP10e_hb_class.s"
}
#pragma pop


/* 804FEB48-804FEC34 00EC .text      kuki_ha_set__FP10e_hb_class                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void kuki_ha_set__FP10e_hb_class() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/kuki_ha_set__FP10e_hb_class.s"
}
#pragma pop


/* 804FEC34-804FF214 05E0 .text      action__FP10e_hb_class                                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void action__FP10e_hb_class() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/action__FP10e_hb_class.s"
}
#pragma pop


/* 804FF214-804FF5DC 03C8 .text      eff_set__FP10e_hb_classi                                     */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void eff_set__FP10e_hb_classi() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/eff_set__FP10e_hb_classi.s"
}
#pragma pop


/* 804FF5DC-804FF744 0168 .text      anm_se_set__FP10e_hb_class                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void anm_se_set__FP10e_hb_class() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/anm_se_set__FP10e_hb_class.s"
}
#pragma pop


/* 804FF744-804FFAFC 03B8 .text      daE_HB_Execute__FP10e_hb_class                               */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void daE_HB_Execute__FP10e_hb_class() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/daE_HB_Execute__FP10e_hb_class.s"
}
#pragma pop


/* 804FFAFC-804FFB04 0008 .text      daE_HB_IsDelete__FP10e_hb_class                              */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void daE_HB_IsDelete__FP10e_hb_class() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/daE_HB_IsDelete__FP10e_hb_class.s"
}
#pragma pop


/* 804FFB04-804FFB6C 0068 .text      daE_HB_Delete__FP10e_hb_class                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void daE_HB_Delete__FP10e_hb_class() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/daE_HB_Delete__FP10e_hb_class.s"
}
#pragma pop


/* 804FFB6C-804FFD60 01F4 .text      useHeapInit__FP10fopAc_ac_c                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void useHeapInit__FP10fopAc_ac_c() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/useHeapInit__FP10fopAc_ac_c.s"
}
#pragma pop


/* 804FFD60-80500264 0504 .text      daE_HB_Create__FP10fopAc_ac_c                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void daE_HB_Create__FP10fopAc_ac_c() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/daE_HB_Create__FP10fopAc_ac_c.s"
}
#pragma pop


/* 80500264-805002D4 0070 .text      __dt__12dBgS_ObjAcchFv                                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void __dt__12dBgS_ObjAcchFv() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/__dt__12dBgS_ObjAcchFv.s"
}
#pragma pop


/* 805002D4-80500344 0070 .text      __dt__12dBgS_AcchCirFv                                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void __dt__12dBgS_AcchCirFv() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/__dt__12dBgS_AcchCirFv.s"
}
#pragma pop


/* 80500344-805003C8 0084 .text      __ct__8dCcD_SphFv                                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void __ct__8dCcD_SphFv() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/__ct__8dCcD_SphFv.s"
}
#pragma pop


/* 805003C8-80500494 00CC .text      __dt__8dCcD_SphFv                                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void __dt__8dCcD_SphFv() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/__dt__8dCcD_SphFv.s"
}
#pragma pop


/* 80500494-805004DC 0048 .text      __dt__8cM3dGSphFv                                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void __dt__8cM3dGSphFv() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/__dt__8cM3dGSphFv.s"
}
#pragma pop


/* 805004DC-80500524 0048 .text      __dt__8cM3dGAabFv                                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void __dt__8cM3dGAabFv() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/__dt__8cM3dGAabFv.s"
}
#pragma pop


/* 80500524-80500580 005C .text      __dt__10dCcD_GSttsFv                                         */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void __dt__10dCcD_GSttsFv() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/__dt__10dCcD_GSttsFv.s"
}
#pragma pop


/* 80500580-80500584 0004 .text      __ct__5csXyzFv                                               */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void __ct__5csXyzFv() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/__ct__5csXyzFv.s"
}
#pragma pop


/* 80500584-80500588 0004 .text      __ct__4cXyzFv                                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void __ct__4cXyzFv() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/__ct__4cXyzFv.s"
}
#pragma pop


/* 80500588-805005D0 0048 .text      __dt__10cCcD_GSttsFv                                         */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void __dt__10cCcD_GSttsFv() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/__dt__10cCcD_GSttsFv.s"
}
#pragma pop


/* 805005D0-80500618 0048 .text      __dt__12daE_HB_HIO_cFv                                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void __dt__12daE_HB_HIO_cFv() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/__dt__12daE_HB_HIO_cFv.s"
}
#pragma pop


/* 80500618-80500654 003C .text      __sinit_d_a_e_hb_cpp                                         */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void __sinit_d_a_e_hb_cpp() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/__sinit_d_a_e_hb_cpp.s"
}
#pragma pop


/* 80500654-8050065C 0008 .text      @36@__dt__12dBgS_ObjAcchFv                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void func_80500654() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/func_80500654.s"
}
#pragma pop


/* 8050065C-80500664 0008 .text      @20@__dt__12dBgS_ObjAcchFv                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void func_8050065C() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/func_8050065C.s"
}
#pragma pop


/* 80500664-80500A78 0414 .text      setMidnaBindEffect__FP13fopEn_enemy_cP15Z2CreatureEnemyP4cXyzP4cXyz */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void setMidnaBindEffect__FP13fopEn_enemy_cP15Z2CreatureEnemyP4cXyzP4cXyz() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/setMidnaBindEffect__FP13fopEn_enemy_cP15Z2CreatureEnemyP4cXyzP4cXyz.s"
}
#pragma pop


/* 80500A78-80500AB4 003C .text      __dt__5csXyzFv                                               */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void __dt__5csXyzFv() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/__dt__5csXyzFv.s"
}
#pragma pop


/* 80500AB4-80500AF0 003C .text      __dt__4cXyzFv                                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void __dt__4cXyzFv() {
	nofralloc
#include "asm/rel/d/a/e/d_a_e_hb/d_a_e_hb/__dt__4cXyzFv.s"
}
#pragma pop


