#
# Generate By: dol2asm
# Module: 600
#

SYMBOLS = {
	'_prolog': {'library': "d/a/obj/d_a_obj_rcircle", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80CB85E0, 'size': 0x002C, 'padding': 0x00, 'name': "_prolog", 'reference_count': 0, 'type': "Function"},
	'_epilog': {'library': "d/a/obj/d_a_obj_rcircle", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80CB860C, 'size': 0x002C, 'padding': 0x00, 'name': "_epilog", 'reference_count': 0, 'type': "Function"},
	'_unresolved': {'library': "d/a/obj/d_a_obj_rcircle", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80CB8638, 'size': 0x0020, 'padding': 0x00, 'name': "_unresolved", 'reference_count': 10, 'type': "Function"},
	'daObjRCircle_c_createHeap__FP10fopAc_ac_c': {'library': "d/a/obj/d_a_obj_rcircle", 'translation_unit': "d_a_obj_rcircle", 'section': ".text", 'addr': 0x80CB8658, 'size': 0x0020, 'padding': 0x00, 'name': "daObjRCircle_c_createHeap__FP10fopAc_ac_c", 'reference_count': 0, 'type': "Function"},
	'__ct__14daObjRCircle_cFv': {'library': "d/a/obj/d_a_obj_rcircle", 'translation_unit': "d_a_obj_rcircle", 'section': ".text", 'addr': 0x80CB8678, 'size': 0x008C, 'padding': 0x00, 'name': "__ct__14daObjRCircle_cFv", 'reference_count': 2, 'type': "Function"},
	'__dt__12J3DFrameCtrlFv': {'library': "d/a/obj/d_a_obj_rcircle", 'translation_unit': "d_a_obj_rcircle", 'section': ".text", 'addr': 0x80CB8704, 'size': 0x0048, 'padding': 0x00, 'name': "__dt__12J3DFrameCtrlFv", 'reference_count': 0, 'type': "Function"},
	'__dt__14daObjRCircle_cFv': {'library': "d/a/obj/d_a_obj_rcircle", 'translation_unit': "d_a_obj_rcircle", 'section': ".text", 'addr': 0x80CB874C, 'size': 0x00C8, 'padding': 0x00, 'name': "__dt__14daObjRCircle_cFv", 'reference_count': 0, 'type': "Function"},
	'createHeap__14daObjRCircle_cFv': {'library': "d/a/obj/d_a_obj_rcircle", 'translation_unit': "d_a_obj_rcircle", 'section': ".text", 'addr': 0x80CB8814, 'size': 0x0114, 'padding': 0x00, 'name': "createHeap__14daObjRCircle_cFv", 'reference_count': 1, 'type': "Function"},
	'create__14daObjRCircle_cFv': {'library': "d/a/obj/d_a_obj_rcircle", 'translation_unit': "d_a_obj_rcircle", 'section': ".text", 'addr': 0x80CB8928, 'size': 0x0100, 'padding': 0x00, 'name': "create__14daObjRCircle_cFv", 'reference_count': 1, 'type': "Function"},
	'Delete__14daObjRCircle_cFv': {'library': "d/a/obj/d_a_obj_rcircle", 'translation_unit': "d_a_obj_rcircle", 'section': ".text", 'addr': 0x80CB8A28, 'size': 0x0034, 'padding': 0x00, 'name': "Delete__14daObjRCircle_cFv", 'reference_count': 1, 'type': "Function"},
	'draw__14daObjRCircle_cFv': {'library': "d/a/obj/d_a_obj_rcircle", 'translation_unit': "d_a_obj_rcircle", 'section': ".text", 'addr': 0x80CB8A5C, 'size': 0x00CC, 'padding': 0x00, 'name': "draw__14daObjRCircle_cFv", 'reference_count': 1, 'type': "Function"},
	'execute__14daObjRCircle_cFv': {'library': "d/a/obj/d_a_obj_rcircle", 'translation_unit': "d_a_obj_rcircle", 'section': ".text", 'addr': 0x80CB8B28, 'size': 0x00BC, 'padding': 0x00, 'name': "execute__14daObjRCircle_cFv", 'reference_count': 1, 'type': "Function"},
	'init__14daObjRCircle_cFv': {'library': "d/a/obj/d_a_obj_rcircle", 'translation_unit': "d_a_obj_rcircle", 'section': ".text", 'addr': 0x80CB8BE4, 'size': 0x000C, 'padding': 0x00, 'name': "init__14daObjRCircle_cFv", 'reference_count': 1, 'type': "Function"},
	'setModelMtx__14daObjRCircle_cFv': {'library': "d/a/obj/d_a_obj_rcircle", 'translation_unit': "d_a_obj_rcircle", 'section': ".text", 'addr': 0x80CB8BF0, 'size': 0x0054, 'padding': 0x00, 'name': "setModelMtx__14daObjRCircle_cFv", 'reference_count': 1, 'type': "Function"},
	'daObjRCircle_create__FP14daObjRCircle_c': {'library': "d/a/obj/d_a_obj_rcircle", 'translation_unit': "d_a_obj_rcircle", 'section': ".text", 'addr': 0x80CB8C44, 'size': 0x0054, 'padding': 0x00, 'name': "daObjRCircle_create__FP14daObjRCircle_c", 'reference_count': 1, 'type': "Function"},
	'daObjRCircle_Delete__FP14daObjRCircle_c': {'library': "d/a/obj/d_a_obj_rcircle", 'translation_unit': "d_a_obj_rcircle", 'section': ".text", 'addr': 0x80CB8C98, 'size': 0x0020, 'padding': 0x00, 'name': "daObjRCircle_Delete__FP14daObjRCircle_c", 'reference_count': 1, 'type': "Function"},
	'daObjRCircle_execute__FP14daObjRCircle_c': {'library': "d/a/obj/d_a_obj_rcircle", 'translation_unit': "d_a_obj_rcircle", 'section': ".text", 'addr': 0x80CB8CB8, 'size': 0x0020, 'padding': 0x00, 'name': "daObjRCircle_execute__FP14daObjRCircle_c", 'reference_count': 1, 'type': "Function"},
	'daObjRCircle_draw__FP14daObjRCircle_c': {'library': "d/a/obj/d_a_obj_rcircle", 'translation_unit': "d_a_obj_rcircle", 'section': ".text", 'addr': 0x80CB8CD8, 'size': 0x0020, 'padding': 0x00, 'name': "daObjRCircle_draw__FP14daObjRCircle_c", 'reference_count': 1, 'type': "Function"},
	'data_80CB8CF8': {'library': "d/a/obj/d_a_obj_rcircle", 'translation_unit': "unknown_translation_unit_ctors", 'section': ".ctors", 'addr': 0x80CB8CF8, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'data_80CB8CFC': {'library': "d/a/obj/d_a_obj_rcircle", 'translation_unit': "unknown_translation_unit_dtors", 'section': ".dtors", 'addr': 0x80CB8CFC, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'lit_3701': {'library': "d/a/obj/d_a_obj_rcircle", 'translation_unit': "d_a_obj_rcircle", 'section': ".rodata", 'addr': 0x80CB8D04, 'size': 0x0004, 'padding': 0x00, 'name': "@3701", 'reference_count': 0, 'type': "Integer"},
	'lit_3702': {'library': "d/a/obj/d_a_obj_rcircle", 'translation_unit': "d_a_obj_rcircle", 'section': ".rodata", 'addr': 0x80CB8D08, 'size': 0x0004, 'padding': 0x00, 'name': "@3702", 'reference_count': 0, 'type': "InitData"},
	'stringBase0': {'library': "d/a/obj/d_a_obj_rcircle", 'translation_unit': "d_a_obj_rcircle", 'section': ".rodata", 'addr': 0x80CB8D0C, 'size': 0x0008, 'padding': 0x00, 'name': "@stringBase0", 'reference_count': 1, 'type': "StringBase"},
	'l_arcName': {'library': "d/a/obj/d_a_obj_rcircle", 'translation_unit': "d_a_obj_rcircle", 'section': ".data", 'addr': 0x80CB8D14, 'size': 0x0004, 'padding': 0x00, 'name': "l_arcName", 'reference_count': 0, 'type': "ReferenceArray"},
	'daObjRCircle_METHODS': {'library': "d/a/obj/d_a_obj_rcircle", 'translation_unit': "d_a_obj_rcircle", 'section': ".data", 'addr': 0x80CB8D18, 'size': 0x0020, 'padding': 0x00, 'name': "daObjRCircle_METHODS", 'reference_count': 1, 'type': "ReferenceArray"},
	'g_profile_Obj_RCircle': {'library': "d/a/obj/d_a_obj_rcircle", 'translation_unit': "d_a_obj_rcircle", 'section': ".data", 'addr': 0x80CB8D38, 'size': 0x0030, 'padding': 0x00, 'name': "g_profile_Obj_RCircle", 'reference_count': 0, 'type': "ReferenceArray"},
	'__vt__14daObjRCircle_c': {'library': "d/a/obj/d_a_obj_rcircle", 'translation_unit': "d_a_obj_rcircle", 'section': ".data", 'addr': 0x80CB8D68, 'size': 0x000C, 'padding': 0x00, 'name': "__vt__14daObjRCircle_c", 'reference_count': 0, 'type': "VirtualTable"},
	'__vt__12J3DFrameCtrl': {'library': "d/a/obj/d_a_obj_rcircle", 'translation_unit': "d_a_obj_rcircle", 'section': ".data", 'addr': 0x80CB8D74, 'size': 0x000C, 'padding': 0x00, 'name': "__vt__12J3DFrameCtrl", 'reference_count': 0, 'type': "VirtualTable"},
}
