#
# Generate By: dol2asm
# Module: 742
#

SYMBOLS = {
	'_prolog': {'library': "d/a/tag/d_a_tag_shop_item", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80D60B00, 'size': 0x002C, 'padding': 0x00, 'name': "_prolog", 'reference_count': 0, 'type': "Function"},
	'_epilog': {'library': "d/a/tag/d_a_tag_shop_item", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80D60B2C, 'size': 0x002C, 'padding': 0x00, 'name': "_epilog", 'reference_count': 0, 'type': "Function"},
	'_unresolved': {'library': "d/a/tag/d_a_tag_shop_item", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80D60B58, 'size': 0x0020, 'padding': 0x00, 'name': "_unresolved", 'reference_count': 7, 'type': "Function"},
	'create__16daTag_ShopItem_cFv': {'library': "d/a/tag/d_a_tag_shop_item", 'translation_unit': "d_a_tag_shop_item", 'section': ".text", 'addr': 0x80D60B78, 'size': 0x0200, 'padding': 0x00, 'name': "create__16daTag_ShopItem_cFv", 'reference_count': 1, 'type': "Function"},
	'Delete__16daTag_ShopItem_cFv': {'library': "d/a/tag/d_a_tag_shop_item", 'translation_unit': "d_a_tag_shop_item", 'section': ".text", 'addr': 0x80D60D78, 'size': 0x008C, 'padding': 0x00, 'name': "Delete__16daTag_ShopItem_cFv", 'reference_count': 1, 'type': "Function"},
	'Execute__16daTag_ShopItem_cFv': {'library': "d/a/tag/d_a_tag_shop_item", 'translation_unit': "d_a_tag_shop_item", 'section': ".text", 'addr': 0x80D60E04, 'size': 0x0220, 'padding': 0x00, 'name': "Execute__16daTag_ShopItem_cFv", 'reference_count': 1, 'type': "Function"},
	'Draw__16daTag_ShopItem_cFv': {'library': "d/a/tag/d_a_tag_shop_item", 'translation_unit': "d_a_tag_shop_item", 'section': ".text", 'addr': 0x80D61024, 'size': 0x0008, 'padding': 0x00, 'name': "Draw__16daTag_ShopItem_cFv", 'reference_count': 1, 'type': "Function"},
	'getType__16daTag_ShopItem_cFv': {'library': "d/a/tag/d_a_tag_shop_item", 'translation_unit': "d_a_tag_shop_item", 'section': ".text", 'addr': 0x80D6102C, 'size': 0x000C, 'padding': 0x00, 'name': "getType__16daTag_ShopItem_cFv", 'reference_count': 1, 'type': "Function"},
	'getGroupID__16daTag_ShopItem_cFv': {'library': "d/a/tag/d_a_tag_shop_item", 'translation_unit': "d_a_tag_shop_item", 'section': ".text", 'addr': 0x80D61038, 'size': 0x000C, 'padding': 0x00, 'name': "getGroupID__16daTag_ShopItem_cFv", 'reference_count': 3, 'type': "Function"},
	'getSwitchBit1__16daTag_ShopItem_cFv': {'library': "d/a/tag/d_a_tag_shop_item", 'translation_unit': "d_a_tag_shop_item", 'section': ".text", 'addr': 0x80D61044, 'size': 0x000C, 'padding': 0x00, 'name': "getSwitchBit1__16daTag_ShopItem_cFv", 'reference_count': 3, 'type': "Function"},
	'getSwitchBit2__16daTag_ShopItem_cFv': {'library': "d/a/tag/d_a_tag_shop_item", 'translation_unit': "d_a_tag_shop_item", 'section': ".text", 'addr': 0x80D61050, 'size': 0x000C, 'padding': 0x00, 'name': "getSwitchBit2__16daTag_ShopItem_cFv", 'reference_count': 3, 'type': "Function"},
	'initialize__16daTag_ShopItem_cFv': {'library': "d/a/tag/d_a_tag_shop_item", 'translation_unit': "d_a_tag_shop_item", 'section': ".text", 'addr': 0x80D6105C, 'size': 0x0084, 'padding': 0x00, 'name': "initialize__16daTag_ShopItem_cFv", 'reference_count': 1, 'type': "Function"},
	'daTag_ShopItem_Create__FPv': {'library': "d/a/tag/d_a_tag_shop_item", 'translation_unit': "d_a_tag_shop_item", 'section': ".text", 'addr': 0x80D610E0, 'size': 0x0020, 'padding': 0x00, 'name': "daTag_ShopItem_Create__FPv", 'reference_count': 1, 'type': "Function"},
	'daTag_ShopItem_Delete__FPv': {'library': "d/a/tag/d_a_tag_shop_item", 'translation_unit': "d_a_tag_shop_item", 'section': ".text", 'addr': 0x80D61100, 'size': 0x0020, 'padding': 0x00, 'name': "daTag_ShopItem_Delete__FPv", 'reference_count': 1, 'type': "Function"},
	'daTag_ShopItem_Execute__FPv': {'library': "d/a/tag/d_a_tag_shop_item", 'translation_unit': "d_a_tag_shop_item", 'section': ".text", 'addr': 0x80D61120, 'size': 0x0020, 'padding': 0x00, 'name': "daTag_ShopItem_Execute__FPv", 'reference_count': 1, 'type': "Function"},
	'daTag_ShopItem_Draw__FPv': {'library': "d/a/tag/d_a_tag_shop_item", 'translation_unit': "d_a_tag_shop_item", 'section': ".text", 'addr': 0x80D61140, 'size': 0x0020, 'padding': 0x00, 'name': "daTag_ShopItem_Draw__FPv", 'reference_count': 1, 'type': "Function"},
	'daTag_ShopItem_IsDelete__FPv': {'library': "d/a/tag/d_a_tag_shop_item", 'translation_unit': "d_a_tag_shop_item", 'section': ".text", 'addr': 0x80D61160, 'size': 0x0008, 'padding': 0x00, 'name': "daTag_ShopItem_IsDelete__FPv", 'reference_count': 1, 'type': "Function"},
	'__dt__16daTag_ShopItem_cFv': {'library': "d/a/tag/d_a_tag_shop_item", 'translation_unit': "d_a_tag_shop_item", 'section': ".text", 'addr': 0x80D61168, 'size': 0x0060, 'padding': 0x00, 'name': "__dt__16daTag_ShopItem_cFv", 'reference_count': 0, 'type': "Function"},
	'data_80D611C8': {'library': "d/a/tag/d_a_tag_shop_item", 'translation_unit': "unknown_translation_unit_ctors", 'section': ".ctors", 'addr': 0x80D611C8, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'data_80D611CC': {'library': "d/a/tag/d_a_tag_shop_item", 'translation_unit': "unknown_translation_unit_dtors", 'section': ".dtors", 'addr': 0x80D611CC, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'lit_3684': {'library': "d/a/tag/d_a_tag_shop_item", 'translation_unit': "d_a_tag_shop_item", 'section': ".rodata", 'addr': 0x80D611D4, 'size': 0x0004, 'padding': 0x00, 'name': "@3684", 'reference_count': 0, 'type': "Integer"},
	'lit_3685': {'library': "d/a/tag/d_a_tag_shop_item", 'translation_unit': "d_a_tag_shop_item", 'section': ".rodata", 'addr': 0x80D611D8, 'size': 0x0004, 'padding': 0x00, 'name': "@3685", 'reference_count': 0, 'type': "Integer"},
	'lit_3778': {'library': "d/a/tag/d_a_tag_shop_item", 'translation_unit': "d_a_tag_shop_item", 'section': ".rodata", 'addr': 0x80D611DC, 'size': 0x0004, 'padding': 0x00, 'name': "@3778", 'reference_count': 0, 'type': "Integer"},
	'lit_3779': {'library': "d/a/tag/d_a_tag_shop_item", 'translation_unit': "d_a_tag_shop_item", 'section': ".rodata", 'addr': 0x80D611E0, 'size': 0x0004, 'padding': 0x00, 'name': "@3779", 'reference_count': 0, 'type': "Integer"},
	'lit_3780': {'library': "d/a/tag/d_a_tag_shop_item", 'translation_unit': "d_a_tag_shop_item", 'section': ".rodata", 'addr': 0x80D611E4, 'size': 0x0004, 'padding': 0x00, 'name': "@3780", 'reference_count': 0, 'type': "Integer"},
	'lit_3781': {'library': "d/a/tag/d_a_tag_shop_item", 'translation_unit': "d_a_tag_shop_item", 'section': ".rodata", 'addr': 0x80D611E8, 'size': 0x0004, 'padding': 0x00, 'name': "@3781", 'reference_count': 0, 'type': "Integer"},
	'stringBase0': {'library': "d/a/tag/d_a_tag_shop_item", 'translation_unit': "d_a_tag_shop_item", 'section': ".rodata", 'addr': 0x80D611EC, 'size': 0x0008, 'padding': 0x00, 'name': "@stringBase0", 'reference_count': 0, 'type': "StringBase"},
	'daTag_ShopItem_MethodTable': {'library': "d/a/tag/d_a_tag_shop_item", 'translation_unit': "d_a_tag_shop_item", 'section': ".data", 'addr': 0x80D611F4, 'size': 0x0020, 'padding': 0x00, 'name': "daTag_ShopItem_MethodTable", 'reference_count': 1, 'type': "ReferenceArray"},
	'g_profile_TAG_SHOPITM': {'library': "d/a/tag/d_a_tag_shop_item", 'translation_unit': "d_a_tag_shop_item", 'section': ".data", 'addr': 0x80D61214, 'size': 0x0030, 'padding': 0x00, 'name': "g_profile_TAG_SHOPITM", 'reference_count': 0, 'type': "ReferenceArray"},
	'__vt__16daTag_ShopItem_c': {'library': "d/a/tag/d_a_tag_shop_item", 'translation_unit': "d_a_tag_shop_item", 'section': ".data", 'addr': 0x80D61244, 'size': 0x000C, 'padding': 0x00, 'name': "__vt__16daTag_ShopItem_c", 'reference_count': 0, 'type': "VirtualTable"},
}
