#
# Generate By: dol2asm
# Module: 733
#

SYMBOLS = {
	'_prolog': {'library': "d/a/tag/d_a_tag_poFire", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80D5D9E0, 'size': 0x002C, 'padding': 0x00, 'name': "_prolog", 'reference_count': 0, 'type': "Function"},
	'_epilog': {'library': "d/a/tag/d_a_tag_poFire", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80D5DA0C, 'size': 0x002C, 'padding': 0x00, 'name': "_epilog", 'reference_count': 0, 'type': "Function"},
	'_unresolved': {'library': "d/a/tag/d_a_tag_poFire", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80D5DA38, 'size': 0x0020, 'padding': 0x00, 'name': "_unresolved", 'reference_count': 7, 'type': "Function"},
	'__register_global_object': {'library': "Runtime.PPCEABI.H", 'translation_unit': "global_destructor_chain", 'section': ".text", 'addr': 0x80D5DA58, 'size': 0x001C, 'padding': 0x00, 'name': "__register_global_object", 'reference_count': 1, 'type': "Function"},
	'__destroy_global_chain': {'library': "Runtime.PPCEABI.H", 'translation_unit': "global_destructor_chain", 'section': ".text", 'addr': 0x80D5DA74, 'size': 0x0058, 'padding': 0x00, 'name': "__destroy_global_chain", 'reference_count': 2, 'type': "Function"},
	'__ct__17daTagPoFire_HIO_cFv': {'library': "d/a/tag/d_a_tag_poFire", 'translation_unit': "d_a_tag_poFire", 'section': ".text", 'addr': 0x80D5DACC, 'size': 0x0024, 'padding': 0x00, 'name': "__ct__17daTagPoFire_HIO_cFv", 'reference_count': 1, 'type': "Function"},
	'__dt__14mDoHIO_entry_cFv': {'library': "d/a/tag/d_a_tag_poFire", 'translation_unit': "d_a_tag_poFire", 'section': ".text", 'addr': 0x80D5DAF0, 'size': 0x0048, 'padding': 0x00, 'name': "__dt__14mDoHIO_entry_cFv", 'reference_count': 0, 'type': "Function"},
	'setBaseMtx__13daTagPoFire_cFv': {'library': "d/a/tag/d_a_tag_poFire", 'translation_unit': "d_a_tag_poFire", 'section': ".text", 'addr': 0x80D5DB38, 'size': 0x0058, 'padding': 0x00, 'name': "setBaseMtx__13daTagPoFire_cFv", 'reference_count': 1, 'type': "Function"},
	'create__13daTagPoFire_cFv': {'library': "d/a/tag/d_a_tag_poFire", 'translation_unit': "d_a_tag_poFire", 'section': ".text", 'addr': 0x80D5DB90, 'size': 0x0060, 'padding': 0x00, 'name': "create__13daTagPoFire_cFv", 'reference_count': 1, 'type': "Function"},
	'Execute__13daTagPoFire_cFv': {'library': "d/a/tag/d_a_tag_poFire", 'translation_unit': "d_a_tag_poFire", 'section': ".text", 'addr': 0x80D5DBF0, 'size': 0x0030, 'padding': 0x00, 'name': "Execute__13daTagPoFire_cFv", 'reference_count': 1, 'type': "Function"},
	'Draw__13daTagPoFire_cFv': {'library': "d/a/tag/d_a_tag_poFire", 'translation_unit': "d_a_tag_poFire", 'section': ".text", 'addr': 0x80D5DC20, 'size': 0x0008, 'padding': 0x00, 'name': "Draw__13daTagPoFire_cFv", 'reference_count': 1, 'type': "Function"},
	'Delete__13daTagPoFire_cFv': {'library': "d/a/tag/d_a_tag_poFire", 'translation_unit': "d_a_tag_poFire", 'section': ".text", 'addr': 0x80D5DC28, 'size': 0x0008, 'padding': 0x00, 'name': "Delete__13daTagPoFire_cFv", 'reference_count': 1, 'type': "Function"},
	'daTagPoFire_Draw__FP13daTagPoFire_c': {'library': "d/a/tag/d_a_tag_poFire", 'translation_unit': "d_a_tag_poFire", 'section': ".text", 'addr': 0x80D5DC30, 'size': 0x0020, 'padding': 0x00, 'name': "daTagPoFire_Draw__FP13daTagPoFire_c", 'reference_count': 1, 'type': "Function"},
	'daTagPoFire_Execute__FP13daTagPoFire_c': {'library': "d/a/tag/d_a_tag_poFire", 'translation_unit': "d_a_tag_poFire", 'section': ".text", 'addr': 0x80D5DC50, 'size': 0x0020, 'padding': 0x00, 'name': "daTagPoFire_Execute__FP13daTagPoFire_c", 'reference_count': 1, 'type': "Function"},
	'daTagPoFire_Delete__FP13daTagPoFire_c': {'library': "d/a/tag/d_a_tag_poFire", 'translation_unit': "d_a_tag_poFire", 'section': ".text", 'addr': 0x80D5DC70, 'size': 0x0020, 'padding': 0x00, 'name': "daTagPoFire_Delete__FP13daTagPoFire_c", 'reference_count': 1, 'type': "Function"},
	'daTagPoFire_Create__FP10fopAc_ac_c': {'library': "d/a/tag/d_a_tag_poFire", 'translation_unit': "d_a_tag_poFire", 'section': ".text", 'addr': 0x80D5DC90, 'size': 0x0020, 'padding': 0x00, 'name': "daTagPoFire_Create__FP10fopAc_ac_c", 'reference_count': 1, 'type': "Function"},
	'__dt__17daTagPoFire_HIO_cFv': {'library': "d/a/tag/d_a_tag_poFire", 'translation_unit': "d_a_tag_poFire", 'section': ".text", 'addr': 0x80D5DCB0, 'size': 0x005C, 'padding': 0x00, 'name': "__dt__17daTagPoFire_HIO_cFv", 'reference_count': 0, 'type': "Function"},
	'__sinit_d_a_tag_poFire_cpp': {'library': "d/a/tag/d_a_tag_poFire", 'translation_unit': "d_a_tag_poFire", 'section': ".text", 'addr': 0x80D5DD0C, 'size': 0x003C, 'padding': 0x00, 'name': "__sinit_d_a_tag_poFire_cpp", 'reference_count': 1, 'type': "Function"},
	'data_80D5DD48': {'library': "d/a/tag/d_a_tag_poFire", 'translation_unit': "unknown_translation_unit_ctors", 'section': ".ctors", 'addr': 0x80D5DD48, 'size': 0x0008, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "ReferenceArray"},
	'__destroy_global_chain_reference': {'library': "Runtime.PPCEABI.H", 'translation_unit': "global_destructor_chain", 'section': ".dtors", 'addr': 0x80D5DD50, 'size': 0x0004, 'padding': 0x00, 'name': "__destroy_global_chain_reference", 'reference_count': 0, 'type': "ReferenceArray"},
	'pad_80D5DD54': {'library': "Runtime.PPCEABI.H", 'translation_unit': "global_destructor_chain", 'section': ".dtors", 'addr': 0x80D5DD54, 'size': 0x0008, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "ReferenceArray"},
	'l_daTagPoFire_Method': {'library': "d/a/tag/d_a_tag_poFire", 'translation_unit': "d_a_tag_poFire", 'section': ".data", 'addr': 0x80D5DD5C, 'size': 0x0020, 'padding': 0x00, 'name': "l_daTagPoFire_Method", 'reference_count': 1, 'type': "ReferenceArray"},
	'g_profile_Tag_poFire': {'library': "d/a/tag/d_a_tag_poFire", 'translation_unit': "d_a_tag_poFire", 'section': ".data", 'addr': 0x80D5DD7C, 'size': 0x0030, 'padding': 0x00, 'name': "g_profile_Tag_poFire", 'reference_count': 0, 'type': "ReferenceArray"},
	'__vt__17daTagPoFire_HIO_c': {'library': "d/a/tag/d_a_tag_poFire", 'translation_unit': "d_a_tag_poFire", 'section': ".data", 'addr': 0x80D5DDAC, 'size': 0x000C, 'padding': 0x00, 'name': "__vt__17daTagPoFire_HIO_c", 'reference_count': 0, 'type': "VirtualTable"},
	'__vt__14mDoHIO_entry_c': {'library': "d/a/tag/d_a_tag_poFire", 'translation_unit': "d_a_tag_poFire", 'section': ".data", 'addr': 0x80D5DDB8, 'size': 0x000C, 'padding': 0x00, 'name': "__vt__14mDoHIO_entry_c", 'reference_count': 0, 'type': "VirtualTable"},
	'__global_destructor_chain': {'library': "Runtime.PPCEABI.H", 'translation_unit': "global_destructor_chain", 'section': ".bss", 'addr': 0x80D5DDD4, 'size': 0x0004, 'padding': 0x04, 'name': "__global_destructor_chain", 'reference_count': 0, 'type': "ZeroData"},
	'lit_3617': {'library': "d/a/tag/d_a_tag_poFire", 'translation_unit': "d_a_tag_poFire", 'section': ".bss", 'addr': 0x80D5DDDC, 'size': 0x000C, 'padding': 0x00, 'name': "@3617", 'reference_count': 0, 'type': "ZeroData"},
	'l_HIO': {'library': "d/a/tag/d_a_tag_poFire", 'translation_unit': "d_a_tag_poFire", 'section': ".bss", 'addr': 0x80D5DDE8, 'size': 0x0008, 'padding': 0x00, 'name': "l_HIO", 'reference_count': 0, 'type': "ZeroData"},
}
