#
# Generate By: dol2asm
# Module: 408
#

SYMBOLS = {
	'_prolog': {'library': "d/a/obj/d_a_obj_bk_leaf", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80BB6060, 'size': 0x002C, 'padding': 0x00, 'name': "_prolog", 'reference_count': 0, 'type': "Function"},
	'_epilog': {'library': "d/a/obj/d_a_obj_bk_leaf", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80BB608C, 'size': 0x002C, 'padding': 0x00, 'name': "_epilog", 'reference_count': 0, 'type': "Function"},
	'_unresolved': {'library': "d/a/obj/d_a_obj_bk_leaf", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80BB60B8, 'size': 0x0020, 'padding': 0x00, 'name': "_unresolved", 'reference_count': 11, 'type': "Function"},
	'CheckCreateHeap__FP10fopAc_ac_c': {'library': "d/a/obj/d_a_obj_bk_leaf", 'translation_unit': "d_a_obj_bk_leaf", 'section': ".text", 'addr': 0x80BB60D8, 'size': 0x0020, 'padding': 0x00, 'name': "CheckCreateHeap__FP10fopAc_ac_c", 'reference_count': 0, 'type': "Function"},
	'setBokkuri__10daBkLeaf_cFv': {'library': "d/a/obj/d_a_obj_bk_leaf", 'translation_unit': "d_a_obj_bk_leaf", 'section': ".text", 'addr': 0x80BB60F8, 'size': 0x0094, 'padding': 0x00, 'name': "setBokkuri__10daBkLeaf_cFv", 'reference_count': 2, 'type': "Function"},
	'initBaseMtx__10daBkLeaf_cFv': {'library': "d/a/obj/d_a_obj_bk_leaf", 'translation_unit': "d_a_obj_bk_leaf", 'section': ".text", 'addr': 0x80BB618C, 'size': 0x003C, 'padding': 0x00, 'name': "initBaseMtx__10daBkLeaf_cFv", 'reference_count': 1, 'type': "Function"},
	'setBaseMtx__10daBkLeaf_cFv': {'library': "d/a/obj/d_a_obj_bk_leaf", 'translation_unit': "d_a_obj_bk_leaf", 'section': ".text", 'addr': 0x80BB61C8, 'size': 0x0054, 'padding': 0x00, 'name': "setBaseMtx__10daBkLeaf_cFv", 'reference_count': 2, 'type': "Function"},
	'Create__10daBkLeaf_cFv': {'library': "d/a/obj/d_a_obj_bk_leaf", 'translation_unit': "d_a_obj_bk_leaf", 'section': ".text", 'addr': 0x80BB621C, 'size': 0x0080, 'padding': 0x00, 'name': "Create__10daBkLeaf_cFv", 'reference_count': 1, 'type': "Function"},
	'CreateHeap__10daBkLeaf_cFv': {'library': "d/a/obj/d_a_obj_bk_leaf", 'translation_unit': "d_a_obj_bk_leaf", 'section': ".text", 'addr': 0x80BB629C, 'size': 0x0110, 'padding': 0x00, 'name': "CreateHeap__10daBkLeaf_cFv", 'reference_count': 1, 'type': "Function"},
	'__dt__12J3DFrameCtrlFv': {'library': "d/a/obj/d_a_obj_bk_leaf", 'translation_unit': "d_a_obj_bk_leaf", 'section': ".text", 'addr': 0x80BB63AC, 'size': 0x0048, 'padding': 0x00, 'name': "__dt__12J3DFrameCtrlFv", 'reference_count': 0, 'type': "Function"},
	'create__10daBkLeaf_cFv': {'library': "d/a/obj/d_a_obj_bk_leaf", 'translation_unit': "d_a_obj_bk_leaf", 'section': ".text", 'addr': 0x80BB63F4, 'size': 0x00B4, 'padding': 0x00, 'name': "create__10daBkLeaf_cFv", 'reference_count': 1, 'type': "Function"},
	'execute__10daBkLeaf_cFv': {'library': "d/a/obj/d_a_obj_bk_leaf", 'translation_unit': "d_a_obj_bk_leaf", 'section': ".text", 'addr': 0x80BB64A8, 'size': 0x011C, 'padding': 0x00, 'name': "execute__10daBkLeaf_cFv", 'reference_count': 1, 'type': "Function"},
	'draw__10daBkLeaf_cFv': {'library': "d/a/obj/d_a_obj_bk_leaf", 'translation_unit': "d_a_obj_bk_leaf", 'section': ".text", 'addr': 0x80BB65C4, 'size': 0x0090, 'padding': 0x00, 'name': "draw__10daBkLeaf_cFv", 'reference_count': 1, 'type': "Function"},
	'_delete__10daBkLeaf_cFv': {'library': "d/a/obj/d_a_obj_bk_leaf", 'translation_unit': "d_a_obj_bk_leaf", 'section': ".text", 'addr': 0x80BB6654, 'size': 0x0034, 'padding': 0x00, 'name': "_delete__10daBkLeaf_cFv", 'reference_count': 1, 'type': "Function"},
	'daBkLeaf_Draw__FP10daBkLeaf_c': {'library': "d/a/obj/d_a_obj_bk_leaf", 'translation_unit': "d_a_obj_bk_leaf", 'section': ".text", 'addr': 0x80BB6688, 'size': 0x0020, 'padding': 0x00, 'name': "daBkLeaf_Draw__FP10daBkLeaf_c", 'reference_count': 1, 'type': "Function"},
	'daBkLeaf_Execute__FP10daBkLeaf_c': {'library': "d/a/obj/d_a_obj_bk_leaf", 'translation_unit': "d_a_obj_bk_leaf", 'section': ".text", 'addr': 0x80BB66A8, 'size': 0x0020, 'padding': 0x00, 'name': "daBkLeaf_Execute__FP10daBkLeaf_c", 'reference_count': 1, 'type': "Function"},
	'daBkLeaf_Delete__FP10daBkLeaf_c': {'library': "d/a/obj/d_a_obj_bk_leaf", 'translation_unit': "d_a_obj_bk_leaf", 'section': ".text", 'addr': 0x80BB66C8, 'size': 0x0020, 'padding': 0x00, 'name': "daBkLeaf_Delete__FP10daBkLeaf_c", 'reference_count': 1, 'type': "Function"},
	'daBkLeaf_Create__FP10fopAc_ac_c': {'library': "d/a/obj/d_a_obj_bk_leaf", 'translation_unit': "d_a_obj_bk_leaf", 'section': ".text", 'addr': 0x80BB66E8, 'size': 0x0020, 'padding': 0x00, 'name': "daBkLeaf_Create__FP10fopAc_ac_c", 'reference_count': 1, 'type': "Function"},
	'data_80BB6708': {'library': "d/a/obj/d_a_obj_bk_leaf", 'translation_unit': "unknown_translation_unit_ctors", 'section': ".ctors", 'addr': 0x80BB6708, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'data_80BB670C': {'library': "d/a/obj/d_a_obj_bk_leaf", 'translation_unit': "unknown_translation_unit_dtors", 'section': ".dtors", 'addr': 0x80BB670C, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'lit_3742': {'library': "d/a/obj/d_a_obj_bk_leaf", 'translation_unit': "d_a_obj_bk_leaf", 'section': ".rodata", 'addr': 0x80BB6714, 'size': 0x0004, 'padding': 0x00, 'name': "@3742", 'reference_count': 0, 'type': "Integer"},
	'lit_3811': {'library': "d/a/obj/d_a_obj_bk_leaf", 'translation_unit': "d_a_obj_bk_leaf", 'section': ".rodata", 'addr': 0x80BB6718, 'size': 0x0004, 'padding': 0x00, 'name': "@3811", 'reference_count': 0, 'type': "InitData"},
	'stringBase0': {'library': "d/a/obj/d_a_obj_bk_leaf", 'translation_unit': "d_a_obj_bk_leaf", 'section': ".rodata", 'addr': 0x80BB671C, 'size': 0x001D, 'padding': 0x00, 'name': "@stringBase0", 'reference_count': 3, 'type': "StringBase"},
	'cNullVec__6Z2Calc': {'library': "d/a/obj/d_a_obj_bk_leaf", 'translation_unit': "d_a_obj_bk_leaf", 'section': ".data", 'addr': 0x80BB673C, 'size': 0x000C, 'padding': 0x00, 'name': "cNullVec__6Z2Calc", 'reference_count': 0, 'type': "InitData"},
	'lit_1787': {'library': "d/a/obj/d_a_obj_bk_leaf", 'translation_unit': "d_a_obj_bk_leaf", 'section': ".data", 'addr': 0x80BB6748, 'size': 0x0004, 'padding': 0x10, 'name': "@1787", 'reference_count': 0, 'type': "Integer"},
	'l_arcName': {'library': "d/a/obj/d_a_obj_bk_leaf", 'translation_unit': "d_a_obj_bk_leaf", 'section': ".data", 'addr': 0x80BB675C, 'size': 0x0004, 'padding': 0x00, 'name': "l_arcName", 'reference_count': 0, 'type': "ReferenceArray"},
	'l_bmdName': {'library': "d/a/obj/d_a_obj_bk_leaf", 'translation_unit': "d_a_obj_bk_leaf", 'section': ".data", 'addr': 0x80BB6760, 'size': 0x0004, 'padding': 0x00, 'name': "l_bmdName", 'reference_count': 0, 'type': "ReferenceArray"},
	'l_bckName': {'library': "d/a/obj/d_a_obj_bk_leaf", 'translation_unit': "d_a_obj_bk_leaf", 'section': ".data", 'addr': 0x80BB6764, 'size': 0x0004, 'padding': 0x00, 'name': "l_bckName", 'reference_count': 0, 'type': "ReferenceArray"},
	'l_daBkLeaf_Method': {'library': "d/a/obj/d_a_obj_bk_leaf", 'translation_unit': "d_a_obj_bk_leaf", 'section': ".data", 'addr': 0x80BB6768, 'size': 0x0020, 'padding': 0x00, 'name': "l_daBkLeaf_Method", 'reference_count': 1, 'type': "ReferenceArray"},
	'g_profile_Obj_BkLeaf': {'library': "d/a/obj/d_a_obj_bk_leaf", 'translation_unit': "d_a_obj_bk_leaf", 'section': ".data", 'addr': 0x80BB6788, 'size': 0x0030, 'padding': 0x00, 'name': "g_profile_Obj_BkLeaf", 'reference_count': 0, 'type': "ReferenceArray"},
	'__vt__12J3DFrameCtrl': {'library': "d/a/obj/d_a_obj_bk_leaf", 'translation_unit': "d_a_obj_bk_leaf", 'section': ".data", 'addr': 0x80BB67B8, 'size': 0x000C, 'padding': 0x00, 'name': "__vt__12J3DFrameCtrl", 'reference_count': 0, 'type': "VirtualTable"},
}
