#
# Generate By: dol2asm
# Module: 22
#

SYMBOLS = {
	'_prolog': {'library': "d/a/obj/d_a_obj_timer", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80485120, 'size': 0x002C, 'padding': 0x00, 'name': "_prolog", 'reference_count': 0, 'type': "Function"},
	'_epilog': {'library': "d/a/obj/d_a_obj_timer", 'translation_unit': "executor", 'section': ".text", 'addr': 0x8048514C, 'size': 0x002C, 'padding': 0x00, 'name': "_epilog", 'reference_count': 0, 'type': "Function"},
	'_unresolved': {'library': "d/a/obj/d_a_obj_timer", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80485178, 'size': 0x0020, 'padding': 0x00, 'name': "_unresolved", 'reference_count': 6, 'type': "Function"},
	'_create__Q210daObjTimer5Act_cFv': {'library': "d/a/obj/d_a_obj_timer", 'translation_unit': "d_a_obj_timer", 'section': ".text", 'addr': 0x80485198, 'size': 0x00D4, 'padding': 0x00, 'name': "_create__Q210daObjTimer5Act_cFv", 'reference_count': 1, 'type': "Function"},
	'_delete__Q210daObjTimer5Act_cFv': {'library': "d/a/obj/d_a_obj_timer", 'translation_unit': "d_a_obj_timer", 'section': ".text", 'addr': 0x8048526C, 'size': 0x0008, 'padding': 0x00, 'name': "_delete__Q210daObjTimer5Act_cFv", 'reference_count': 1, 'type': "Function"},
	'mode_wait_init__Q210daObjTimer5Act_cFv': {'library': "d/a/obj/d_a_obj_timer", 'translation_unit': "d_a_obj_timer", 'section': ".text", 'addr': 0x80485274, 'size': 0x0010, 'padding': 0x00, 'name': "mode_wait_init__Q210daObjTimer5Act_cFv", 'reference_count': 2, 'type': "Function"},
	'mode_wait__Q210daObjTimer5Act_cFv': {'library': "d/a/obj/d_a_obj_timer", 'translation_unit': "d_a_obj_timer", 'section': ".text", 'addr': 0x80485284, 'size': 0x005C, 'padding': 0x00, 'name': "mode_wait__Q210daObjTimer5Act_cFv", 'reference_count': 1, 'type': "Function"},
	'mode_count_init__Q210daObjTimer5Act_cFv': {'library': "d/a/obj/d_a_obj_timer", 'translation_unit': "d_a_obj_timer", 'section': ".text", 'addr': 0x804852E0, 'size': 0x0044, 'padding': 0x00, 'name': "mode_count_init__Q210daObjTimer5Act_cFv", 'reference_count': 2, 'type': "Function"},
	'mode_count__Q210daObjTimer5Act_cFv': {'library': "d/a/obj/d_a_obj_timer", 'translation_unit': "d_a_obj_timer", 'section': ".text", 'addr': 0x80485324, 'size': 0x0198, 'padding': 0x00, 'name': "mode_count__Q210daObjTimer5Act_cFv", 'reference_count': 1, 'type': "Function"},
	'_execute__Q210daObjTimer5Act_cFv': {'library': "d/a/obj/d_a_obj_timer", 'translation_unit': "d_a_obj_timer", 'section': ".text", 'addr': 0x804854BC, 'size': 0x00E8, 'padding': 0x00, 'name': "_execute__Q210daObjTimer5Act_cFv", 'reference_count': 1, 'type': "Function"},
	'func_804855A4': {'library': "d/a/obj/d_a_obj_timer", 'translation_unit': "d_a_obj_timer", 'section': ".text", 'addr': 0x804855A4, 'size': 0x0020, 'padding': 0x00, 'name': "Mthd_Create__Q210daObjTimer27@unnamed@d_a_obj_timer_cpp@FPv", 'reference_count': 1, 'type': "Function"},
	'func_804855C4': {'library': "d/a/obj/d_a_obj_timer", 'translation_unit': "d_a_obj_timer", 'section': ".text", 'addr': 0x804855C4, 'size': 0x0024, 'padding': 0x00, 'name': "Mthd_Delete__Q210daObjTimer27@unnamed@d_a_obj_timer_cpp@FPv", 'reference_count': 1, 'type': "Function"},
	'func_804855E8': {'library': "d/a/obj/d_a_obj_timer", 'translation_unit': "d_a_obj_timer", 'section': ".text", 'addr': 0x804855E8, 'size': 0x0024, 'padding': 0x00, 'name': "Mthd_Execute__Q210daObjTimer27@unnamed@d_a_obj_timer_cpp@FPv", 'reference_count': 1, 'type': "Function"},
	'func_8048560C': {'library': "d/a/obj/d_a_obj_timer", 'translation_unit': "d_a_obj_timer", 'section': ".text", 'addr': 0x8048560C, 'size': 0x0008, 'padding': 0x00, 'name': "Mthd_Draw__Q210daObjTimer27@unnamed@d_a_obj_timer_cpp@FPv", 'reference_count': 1, 'type': "Function"},
	'func_80485614': {'library': "d/a/obj/d_a_obj_timer", 'translation_unit': "d_a_obj_timer", 'section': ".text", 'addr': 0x80485614, 'size': 0x0008, 'padding': 0x00, 'name': "Mthd_IsDelete__Q210daObjTimer27@unnamed@d_a_obj_timer_cpp@FPv", 'reference_count': 1, 'type': "Function"},
	'func_8048561C': {'library': "d/a/obj/d_a_obj_timer", 'translation_unit': "d_a_obj_timer", 'section': ".text", 'addr': 0x8048561C, 'size': 0x001C, 'padding': 0x00, 'name': "PrmAbstract<Q310daObjTimer5Act_c5Prm_e>__5daObjFPC10fopAc_ac_cQ310daObjTimer5Act_c5Prm_eQ310daObjTimer5Act_c5Prm_e", 'reference_count': 5, 'type': "Function"},
	'data_80485638': {'library': "d/a/obj/d_a_obj_timer", 'translation_unit': "unknown_translation_unit_ctors", 'section': ".ctors", 'addr': 0x80485638, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'data_8048563C': {'library': "d/a/obj/d_a_obj_timer", 'translation_unit': "unknown_translation_unit_dtors", 'section': ".dtors", 'addr': 0x8048563C, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'lit_3720': {'library': "d/a/obj/d_a_obj_timer", 'translation_unit': "d_a_obj_timer", 'section': ".rodata", 'addr': 0x80485644, 'size': 0x0004, 'padding': 0x00, 'name': "@3720", 'reference_count': 0, 'type': "Integer"},
	'lit_3721': {'library': "d/a/obj/d_a_obj_timer", 'translation_unit': "d_a_obj_timer", 'section': ".rodata", 'addr': 0x80485648, 'size': 0x0004, 'padding': 0x00, 'name': "@3721", 'reference_count': 0, 'type': "Integer"},
	'cNullVec__6Z2Calc': {'library': "d/a/obj/d_a_obj_timer", 'translation_unit': "d_a_obj_timer", 'section': ".data", 'addr': 0x8048564C, 'size': 0x000C, 'padding': 0x00, 'name': "cNullVec__6Z2Calc", 'reference_count': 0, 'type': "InitData"},
	'lit_1787': {'library': "d/a/obj/d_a_obj_timer", 'translation_unit': "d_a_obj_timer", 'section': ".data", 'addr': 0x80485658, 'size': 0x0004, 'padding': 0x10, 'name': "@1787", 'reference_count': 0, 'type': "Integer"},
	'lit_3726': {'library': "d/a/obj/d_a_obj_timer", 'translation_unit': "d_a_obj_timer", 'section': ".data", 'addr': 0x8048566C, 'size': 0x000C, 'padding': 0x00, 'name': "@3726", 'reference_count': 0, 'type': "ReferenceArray"},
	'lit_3727': {'library': "d/a/obj/d_a_obj_timer", 'translation_unit': "d_a_obj_timer", 'section': ".data", 'addr': 0x80485678, 'size': 0x000C, 'padding': 0x00, 'name': "@3727", 'reference_count': 0, 'type': "ReferenceArray"},
	'data_80485684': {'library': "d/a/obj/d_a_obj_timer", 'translation_unit': "d_a_obj_timer", 'section': ".data", 'addr': 0x80485684, 'size': 0x0018, 'padding': 0x00, 'name': "mode_proc$3725", 'reference_count': 0, 'type': "InitData"},
	'data_8048569C': {'library': "d/a/obj/d_a_obj_timer", 'translation_unit': "d_a_obj_timer", 'section': ".data", 'addr': 0x8048569C, 'size': 0x0020, 'padding': 0x00, 'name': "Mthd_Table__Q210daObjTimer27@unnamed@d_a_obj_timer_cpp@", 'reference_count': 1, 'type': "ReferenceArray"},
	'g_profile_Obj_Timer': {'library': "d/a/obj/d_a_obj_timer", 'translation_unit': "d_a_obj_timer", 'section': ".data", 'addr': 0x804856BC, 'size': 0x0030, 'padding': 0x00, 'name': "g_profile_Obj_Timer", 'reference_count': 0, 'type': "ReferenceArray"},
	'data_804856FC': {'library': "d/a/obj/d_a_obj_timer", 'translation_unit': "unknown_translation_unit_bss", 'section': ".bss", 'addr': 0x804856FC, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "ZeroData"},
}
