#
# Generate By: dol2asm
# Module: 535
#

SYMBOLS = {
	'_prolog': {'library': "d/a/obj/d_a_obj_lv4gear", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80C67EA0, 'size': 0x002C, 'padding': 0x00, 'name': "_prolog", 'reference_count': 0, 'type': "Function"},
	'_epilog': {'library': "d/a/obj/d_a_obj_lv4gear", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80C67ECC, 'size': 0x002C, 'padding': 0x00, 'name': "_epilog", 'reference_count': 0, 'type': "Function"},
	'_unresolved': {'library': "d/a/obj/d_a_obj_lv4gear", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80C67EF8, 'size': 0x0020, 'padding': 0x00, 'name': "_unresolved", 'reference_count': 10, 'type': "Function"},
	'CheckCreateHeap__FP10fopAc_ac_c': {'library': "d/a/obj/d_a_obj_lv4gear", 'translation_unit': "d_a_obj_lv4gear", 'section': ".text", 'addr': 0x80C67F18, 'size': 0x0020, 'padding': 0x00, 'name': "CheckCreateHeap__FP10fopAc_ac_c", 'reference_count': 0, 'type': "Function"},
	'searchSwSpinSub__FPvPv': {'library': "d/a/obj/d_a_obj_lv4gear", 'translation_unit': "d_a_obj_lv4gear", 'section': ".text", 'addr': 0x80C67F38, 'size': 0x007C, 'padding': 0x00, 'name': "searchSwSpinSub__FPvPv", 'reference_count': 0, 'type': "Function"},
	'initBaseMtx__14daObjLv4Gear_cFv': {'library': "d/a/obj/d_a_obj_lv4gear", 'translation_unit': "d_a_obj_lv4gear", 'section': ".text", 'addr': 0x80C67FB4, 'size': 0x003C, 'padding': 0x00, 'name': "initBaseMtx__14daObjLv4Gear_cFv", 'reference_count': 1, 'type': "Function"},
	'setBaseMtx__14daObjLv4Gear_cFv': {'library': "d/a/obj/d_a_obj_lv4gear", 'translation_unit': "d_a_obj_lv4gear", 'section': ".text", 'addr': 0x80C67FF0, 'size': 0x0060, 'padding': 0x00, 'name': "setBaseMtx__14daObjLv4Gear_cFv", 'reference_count': 2, 'type': "Function"},
	'Create__14daObjLv4Gear_cFv': {'library': "d/a/obj/d_a_obj_lv4gear", 'translation_unit': "d_a_obj_lv4gear", 'section': ".text", 'addr': 0x80C68050, 'size': 0x0054, 'padding': 0x00, 'name': "Create__14daObjLv4Gear_cFv", 'reference_count': 1, 'type': "Function"},
	'CreateHeap__14daObjLv4Gear_cFv': {'library': "d/a/obj/d_a_obj_lv4gear", 'translation_unit': "d_a_obj_lv4gear", 'section': ".text", 'addr': 0x80C680A4, 'size': 0x0080, 'padding': 0x00, 'name': "CreateHeap__14daObjLv4Gear_cFv", 'reference_count': 1, 'type': "Function"},
	'create__14daObjLv4Gear_cFv': {'library': "d/a/obj/d_a_obj_lv4gear", 'translation_unit': "d_a_obj_lv4gear", 'section': ".text", 'addr': 0x80C68124, 'size': 0x00D0, 'padding': 0x00, 'name': "create__14daObjLv4Gear_cFv", 'reference_count': 1, 'type': "Function"},
	'execute__14daObjLv4Gear_cFv': {'library': "d/a/obj/d_a_obj_lv4gear", 'translation_unit': "d_a_obj_lv4gear", 'section': ".text", 'addr': 0x80C681F4, 'size': 0x01EC, 'padding': 0x00, 'name': "execute__14daObjLv4Gear_cFv", 'reference_count': 1, 'type': "Function"},
	'draw__14daObjLv4Gear_cFv': {'library': "d/a/obj/d_a_obj_lv4gear", 'translation_unit': "d_a_obj_lv4gear", 'section': ".text", 'addr': 0x80C683E0, 'size': 0x0064, 'padding': 0x00, 'name': "draw__14daObjLv4Gear_cFv", 'reference_count': 1, 'type': "Function"},
	'_delete__14daObjLv4Gear_cFv': {'library': "d/a/obj/d_a_obj_lv4gear", 'translation_unit': "d_a_obj_lv4gear", 'section': ".text", 'addr': 0x80C68444, 'size': 0x0034, 'padding': 0x00, 'name': "_delete__14daObjLv4Gear_cFv", 'reference_count': 1, 'type': "Function"},
	'daObjLv4Gear_Draw__FP14daObjLv4Gear_c': {'library': "d/a/obj/d_a_obj_lv4gear", 'translation_unit': "d_a_obj_lv4gear", 'section': ".text", 'addr': 0x80C68478, 'size': 0x0020, 'padding': 0x00, 'name': "daObjLv4Gear_Draw__FP14daObjLv4Gear_c", 'reference_count': 1, 'type': "Function"},
	'daObjLv4Gear_Execute__FP14daObjLv4Gear_c': {'library': "d/a/obj/d_a_obj_lv4gear", 'translation_unit': "d_a_obj_lv4gear", 'section': ".text", 'addr': 0x80C68498, 'size': 0x0020, 'padding': 0x00, 'name': "daObjLv4Gear_Execute__FP14daObjLv4Gear_c", 'reference_count': 1, 'type': "Function"},
	'daObjLv4Gear_Delete__FP14daObjLv4Gear_c': {'library': "d/a/obj/d_a_obj_lv4gear", 'translation_unit': "d_a_obj_lv4gear", 'section': ".text", 'addr': 0x80C684B8, 'size': 0x0020, 'padding': 0x00, 'name': "daObjLv4Gear_Delete__FP14daObjLv4Gear_c", 'reference_count': 1, 'type': "Function"},
	'daObjLv4Gear_Create__FP14daObjLv4Gear_c': {'library': "d/a/obj/d_a_obj_lv4gear", 'translation_unit': "d_a_obj_lv4gear", 'section': ".text", 'addr': 0x80C684D8, 'size': 0x0020, 'padding': 0x00, 'name': "daObjLv4Gear_Create__FP14daObjLv4Gear_c", 'reference_count': 1, 'type': "Function"},
	'data_80C684F8': {'library': "d/a/obj/d_a_obj_lv4gear", 'translation_unit': "unknown_translation_unit_ctors", 'section': ".ctors", 'addr': 0x80C684F8, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'data_80C684FC': {'library': "d/a/obj/d_a_obj_lv4gear", 'translation_unit': "unknown_translation_unit_dtors", 'section': ".dtors", 'addr': 0x80C684FC, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'l_bmd': {'library': "d/a/obj/d_a_obj_lv4gear", 'translation_unit': "d_a_obj_lv4gear", 'section': ".rodata", 'addr': 0x80C68504, 'size': 0x0008, 'padding': 0x00, 'name': "l_bmd", 'reference_count': 0, 'type': "InitData"},
	'l_size': {'library': "d/a/obj/d_a_obj_lv4gear", 'translation_unit': "d_a_obj_lv4gear", 'section': ".rodata", 'addr': 0x80C6850C, 'size': 0x0008, 'padding': 0x00, 'name': "l_size", 'reference_count': 0, 'type': "InitData"},
	'l_rot_start_time': {'library': "d/a/obj/d_a_obj_lv4gear", 'translation_unit': "d_a_obj_lv4gear", 'section': ".rodata", 'addr': 0x80C68514, 'size': 0x0004, 'padding': 0x00, 'name': "l_rot_start_time", 'reference_count': 0, 'type': "Integer"},
	'l_heap_size': {'library': "d/a/obj/d_a_obj_lv4gear", 'translation_unit': "d_a_obj_lv4gear", 'section': ".rodata", 'addr': 0x80C68518, 'size': 0x0008, 'padding': 0x00, 'name': "l_heap_size", 'reference_count': 0, 'type': "InitData"},
	'lit_3773': {'library': "d/a/obj/d_a_obj_lv4gear", 'translation_unit': "d_a_obj_lv4gear", 'section': ".rodata", 'addr': 0x80C68520, 'size': 0x0004, 'padding': 0x00, 'name': "@3773", 'reference_count': 0, 'type': "Integer"},
	'lit_3774': {'library': "d/a/obj/d_a_obj_lv4gear", 'translation_unit': "d_a_obj_lv4gear", 'section': ".rodata", 'addr': 0x80C68524, 'size': 0x0004, 'padding': 0x00, 'name': "@3774", 'reference_count': 0, 'type': "Integer"},
	'stringBase0': {'library': "d/a/obj/d_a_obj_lv4gear", 'translation_unit': "d_a_obj_lv4gear", 'section': ".rodata", 'addr': 0x80C68528, 'size': 0x0007, 'padding': 0x00, 'name': "@stringBase0", 'reference_count': 1, 'type': "StringBase"},
	'l_arcName': {'library': "d/a/obj/d_a_obj_lv4gear", 'translation_unit': "d_a_obj_lv4gear", 'section': ".data", 'addr': 0x80C68534, 'size': 0x0004, 'padding': 0x00, 'name': "l_arcName", 'reference_count': 0, 'type': "ReferenceArray"},
	'l_daObjLv4Gear_Method': {'library': "d/a/obj/d_a_obj_lv4gear", 'translation_unit': "d_a_obj_lv4gear", 'section': ".data", 'addr': 0x80C68538, 'size': 0x0020, 'padding': 0x00, 'name': "l_daObjLv4Gear_Method", 'reference_count': 1, 'type': "ReferenceArray"},
	'g_profile_Obj_Lv4Gear': {'library': "d/a/obj/d_a_obj_lv4gear", 'translation_unit': "d_a_obj_lv4gear", 'section': ".data", 'addr': 0x80C68558, 'size': 0x0030, 'padding': 0x00, 'name': "g_profile_Obj_Lv4Gear", 'reference_count': 0, 'type': "ReferenceArray"},
}
