#
# Generate By: dol2asm
# Module: 47
#

SYMBOLS = {
	'_prolog': {'library': "d/a/d_a_crod", 'translation_unit': "executor", 'section': ".text", 'addr': 0x804A2DC0, 'size': 0x002C, 'padding': 0x00, 'name': "_prolog", 'reference_count': 0, 'type': "Function"},
	'_epilog': {'library': "d/a/d_a_crod", 'translation_unit': "executor", 'section': ".text", 'addr': 0x804A2DEC, 'size': 0x002C, 'padding': 0x00, 'name': "_epilog", 'reference_count': 0, 'type': "Function"},
	'_unresolved': {'library': "d/a/d_a_crod", 'translation_unit': "executor", 'section': ".text", 'addr': 0x804A2E18, 'size': 0x0020, 'padding': 0x00, 'name': "_unresolved", 'reference_count': 15, 'type': "Function"},
	'createHeap__8daCrod_cFv': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".text", 'addr': 0x804A2E38, 'size': 0x00C0, 'padding': 0x00, 'name': "createHeap__8daCrod_cFv", 'reference_count': 1, 'type': "Function"},
	'daCrod_createHeap__FP10fopAc_ac_c': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".text", 'addr': 0x804A2EF8, 'size': 0x0020, 'padding': 0x00, 'name': "daCrod_createHeap__FP10fopAc_ac_c", 'reference_count': 0, 'type': "Function"},
	'create__8daCrod_cFv': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".text", 'addr': 0x804A2F18, 'size': 0x02E0, 'padding': 0x00, 'name': "create__8daCrod_cFv", 'reference_count': 1, 'type': "Function"},
	'__dt__8cM3dGAabFv': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".text", 'addr': 0x804A31F8, 'size': 0x0048, 'padding': 0x00, 'name': "__dt__8cM3dGAabFv", 'reference_count': 0, 'type': "Function"},
	'__dt__10dCcD_GSttsFv': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".text", 'addr': 0x804A3240, 'size': 0x005C, 'padding': 0x00, 'name': "__dt__10dCcD_GSttsFv", 'reference_count': 0, 'type': "Function"},
	'__dt__12J3DFrameCtrlFv': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".text", 'addr': 0x804A329C, 'size': 0x0048, 'padding': 0x00, 'name': "__dt__12J3DFrameCtrlFv", 'reference_count': 0, 'type': "Function"},
	'daCrod_Create__FP10fopAc_ac_c': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".text", 'addr': 0x804A32E4, 'size': 0x0020, 'padding': 0x00, 'name': "daCrod_Create__FP10fopAc_ac_c", 'reference_count': 1, 'type': "Function"},
	'__dt__8daCrod_cFv': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".text", 'addr': 0x804A3304, 'size': 0x0184, 'padding': 0x00, 'name': "__dt__8daCrod_cFv", 'reference_count': 1, 'type': "Function"},
	'daCrod_Delete__FP8daCrod_c': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".text", 'addr': 0x804A3488, 'size': 0x0028, 'padding': 0x00, 'name': "daCrod_Delete__FP8daCrod_c", 'reference_count': 1, 'type': "Function"},
	'setRoomInfo__8daCrod_cFv': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".text", 'addr': 0x804A34B0, 'size': 0x0004, 'padding': 0x00, 'name': "setRoomInfo__8daCrod_cFv", 'reference_count': 2, 'type': "Function"},
	'setMatrix__8daCrod_cFv': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".text", 'addr': 0x804A34B4, 'size': 0x004C, 'padding': 0x00, 'name': "setMatrix__8daCrod_cFv", 'reference_count': 2, 'type': "Function"},
	'posMove__8daCrod_cFv': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".text", 'addr': 0x804A3500, 'size': 0x0080, 'padding': 0x00, 'name': "posMove__8daCrod_cFv", 'reference_count': 1, 'type': "Function"},
	'setBckAnm__8daCrod_cFUs': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".text", 'addr': 0x804A3580, 'size': 0x007C, 'padding': 0x00, 'name': "setBckAnm__8daCrod_cFUs", 'reference_count': 2, 'type': "Function"},
	'setReturn__8daCrod_cFv': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".text", 'addr': 0x804A35FC, 'size': 0x0060, 'padding': 0x00, 'name': "setReturn__8daCrod_cFv", 'reference_count': 1, 'type': "Function"},
	'setLightPower__8daCrod_cFv': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".text", 'addr': 0x804A365C, 'size': 0x007C, 'padding': 0x00, 'name': "setLightPower__8daCrod_cFv", 'reference_count': 2, 'type': "Function"},
	'execute__8daCrod_cFv': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".text", 'addr': 0x804A36D8, 'size': 0x08DC, 'padding': 0x00, 'name': "execute__8daCrod_cFv", 'reference_count': 1, 'type': "Function"},
	'daCrod_Execute__FP8daCrod_c': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".text", 'addr': 0x804A3FB4, 'size': 0x0020, 'padding': 0x00, 'name': "daCrod_Execute__FP8daCrod_c", 'reference_count': 1, 'type': "Function"},
	'draw__8daCrod_cFv': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".text", 'addr': 0x804A3FD4, 'size': 0x00A8, 'padding': 0x00, 'name': "draw__8daCrod_cFv", 'reference_count': 1, 'type': "Function"},
	'daCrod_Draw__FP8daCrod_c': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".text", 'addr': 0x804A407C, 'size': 0x0020, 'padding': 0x00, 'name': "daCrod_Draw__FP8daCrod_c", 'reference_count': 1, 'type': "Function"},
	'__dt__10cCcD_GSttsFv': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".text", 'addr': 0x804A409C, 'size': 0x0048, 'padding': 0x00, 'name': "__dt__10cCcD_GSttsFv", 'reference_count': 0, 'type': "Function"},
	'data_804A40E4': {'library': "d/a/d_a_crod", 'translation_unit': "unknown_translation_unit_ctors", 'section': ".ctors", 'addr': 0x804A40E4, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'data_804A40E8': {'library': "d/a/d_a_crod", 'translation_unit': "unknown_translation_unit_dtors", 'section': ".dtors", 'addr': 0x804A40E8, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'lit_3759': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".rodata", 'addr': 0x804A40EC, 'size': 0x000C, 'padding': 0x00, 'name': "@3759", 'reference_count': 0, 'type': "InitData"},
	'l_localRodPos': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".rodata", 'addr': 0x804A40F8, 'size': 0x000C, 'padding': 0x00, 'name': "l_localRodPos", 'reference_count': 0, 'type': "InitData"},
	'lit_4173': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".rodata", 'addr': 0x804A4104, 'size': 0x0004, 'padding': 0x00, 'name': "@4173", 'reference_count': 0, 'type': "Integer"},
	'lit_4489': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".rodata", 'addr': 0x804A4108, 'size': 0x0004, 'padding': 0x00, 'name': "@4489", 'reference_count': 0, 'type': "Integer"},
	'lit_4490': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".rodata", 'addr': 0x804A410C, 'size': 0x0004, 'padding': 0x00, 'name': "@4490", 'reference_count': 0, 'type': "Integer"},
	'lit_4491': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".rodata", 'addr': 0x804A4110, 'size': 0x0004, 'padding': 0x00, 'name': "@4491", 'reference_count': 0, 'type': "InitData"},
	'lit_4774': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".rodata", 'addr': 0x804A4114, 'size': 0x0004, 'padding': 0x00, 'name': "@4774", 'reference_count': 0, 'type': "Integer"},
	'lit_4775': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".rodata", 'addr': 0x804A4118, 'size': 0x0004, 'padding': 0x00, 'name': "@4775", 'reference_count': 0, 'type': "Integer"},
	'lit_4776': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".rodata", 'addr': 0x804A411C, 'size': 0x0004, 'padding': 0x04, 'name': "@4776", 'reference_count': 0, 'type': "Integer"},
	'lit_4777': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".rodata", 'addr': 0x804A4124, 'size': 0x0008, 'padding': 0x00, 'name': "@4777", 'reference_count': 0, 'type': "InitData"},
	'lit_4778': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".rodata", 'addr': 0x804A412C, 'size': 0x0008, 'padding': 0x00, 'name': "@4778", 'reference_count': 0, 'type': "InitData"},
	'lit_4779': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".rodata", 'addr': 0x804A4134, 'size': 0x0008, 'padding': 0x00, 'name': "@4779", 'reference_count': 0, 'type': "InitData"},
	'l_atCpsSrc': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".data", 'addr': 0x804A413C, 'size': 0x004C, 'padding': 0x00, 'name': "l_atCpsSrc", 'reference_count': 0, 'type': "InitData"},
	'data_804A4188': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".data", 'addr': 0x804A4188, 'size': 0x000C, 'padding': 0x00, 'name': "shootInitLocalPos$4524", 'reference_count': 0, 'type': "InitData"},
	'l_daCrod_Method': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".data", 'addr': 0x804A4194, 'size': 0x0020, 'padding': 0x00, 'name': "l_daCrod_Method", 'reference_count': 1, 'type': "ReferenceArray"},
	'g_profile_CROD': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".data", 'addr': 0x804A41B4, 'size': 0x0030, 'padding': 0x00, 'name': "g_profile_CROD", 'reference_count': 0, 'type': "ReferenceArray"},
	'__vt__10cCcD_GStts': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".data", 'addr': 0x804A41E4, 'size': 0x000C, 'padding': 0x00, 'name': "__vt__10cCcD_GStts", 'reference_count': 0, 'type': "VirtualTable"},
	'__vt__10dCcD_GStts': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".data", 'addr': 0x804A41F0, 'size': 0x000C, 'padding': 0x00, 'name': "__vt__10dCcD_GStts", 'reference_count': 0, 'type': "VirtualTable"},
	'__vt__8cM3dGAab': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".data", 'addr': 0x804A41FC, 'size': 0x000C, 'padding': 0x00, 'name': "__vt__8cM3dGAab", 'reference_count': 0, 'type': "VirtualTable"},
	'__vt__12J3DFrameCtrl': {'library': "d/a/d_a_crod", 'translation_unit': "d_a_crod", 'section': ".data", 'addr': 0x804A4208, 'size': 0x000C, 'padding': 0x00, 'name': "__vt__12J3DFrameCtrl", 'reference_count': 0, 'type': "VirtualTable"},
	'data_804A421C': {'library': "d/a/d_a_crod", 'translation_unit': "unknown_translation_unit_bss", 'section': ".bss", 'addr': 0x804A421C, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "ZeroData"},
}
