#
# Generate By: dol2asm
# Module: 67
#

SYMBOLS = {
	'_prolog': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "executor", 'section': ".text", 'addr': 0x804FB000, 'size': 0x002C, 'padding': 0x00, 'name': "_prolog", 'reference_count': 0, 'type': "Function"},
	'_epilog': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "executor", 'section': ".text", 'addr': 0x804FB02C, 'size': 0x002C, 'padding': 0x00, 'name': "_epilog", 'reference_count': 0, 'type': "Function"},
	'_unresolved': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "executor", 'section': ".text", 'addr': 0x804FB058, 'size': 0x0020, 'padding': 0x00, 'name': "_unresolved", 'reference_count': 11, 'type': "Function"},
	'__register_global_object': {'library': "Runtime.PPCEABI.H", 'translation_unit': "global_destructor_chain", 'section': ".text", 'addr': 0x804FB078, 'size': 0x001C, 'padding': 0x00, 'name': "__register_global_object", 'reference_count': 1, 'type': "Function"},
	'__destroy_global_chain': {'library': "Runtime.PPCEABI.H", 'translation_unit': "global_destructor_chain", 'section': ".text", 'addr': 0x804FB094, 'size': 0x0058, 'padding': 0x00, 'name': "__destroy_global_chain", 'reference_count': 2, 'type': "Function"},
	'__ct__12daE_Ga_HIO_cFv': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".text", 'addr': 0x804FB0EC, 'size': 0x0024, 'padding': 0x00, 'name': "__ct__12daE_Ga_HIO_cFv", 'reference_count': 1, 'type': "Function"},
	'daE_Ga_Draw__FP10e_ga_class': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".text", 'addr': 0x804FB110, 'size': 0x00A0, 'padding': 0x00, 'name': "daE_Ga_Draw__FP10e_ga_class", 'reference_count': 1, 'type': "Function"},
	'ga_fly__FP10e_ga_classP4ga_s': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".text", 'addr': 0x804FB1B0, 'size': 0x01F8, 'padding': 0x00, 'name': "ga_fly__FP10e_ga_classP4ga_s", 'reference_count': 1, 'type': "Function"},
	'bt_fly__FP10e_ga_classP4ga_s': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".text", 'addr': 0x804FB3A8, 'size': 0x0218, 'padding': 0x00, 'name': "bt_fly__FP10e_ga_classP4ga_s", 'reference_count': 1, 'type': "Function"},
	'ga_control__FP10e_ga_class': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".text", 'addr': 0x804FB5C0, 'size': 0x0138, 'padding': 0x00, 'name': "ga_control__FP10e_ga_class", 'reference_count': 1, 'type': "Function"},
	'daE_Ga_Execute__FP10e_ga_class': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".text", 'addr': 0x804FB6F8, 'size': 0x0024, 'padding': 0x00, 'name': "daE_Ga_Execute__FP10e_ga_class", 'reference_count': 2, 'type': "Function"},
	'daE_Ga_IsDelete__FP10e_ga_class': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".text", 'addr': 0x804FB71C, 'size': 0x0008, 'padding': 0x00, 'name': "daE_Ga_IsDelete__FP10e_ga_class", 'reference_count': 1, 'type': "Function"},
	'daE_Ga_Delete__FP10e_ga_class': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".text", 'addr': 0x804FB724, 'size': 0x00A0, 'padding': 0x00, 'name': "daE_Ga_Delete__FP10e_ga_class", 'reference_count': 1, 'type': "Function"},
	'useHeapInit__FP10fopAc_ac_c': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".text", 'addr': 0x804FB7C4, 'size': 0x00B0, 'padding': 0x00, 'name': "useHeapInit__FP10fopAc_ac_c", 'reference_count': 0, 'type': "Function"},
	'daE_Ga_Create__FP10fopAc_ac_c': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".text", 'addr': 0x804FB874, 'size': 0x0244, 'padding': 0x00, 'name': "daE_Ga_Create__FP10fopAc_ac_c", 'reference_count': 1, 'type': "Function"},
	'__dt__4ga_sFv': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".text", 'addr': 0x804FBAB8, 'size': 0x003C, 'padding': 0x00, 'name': "__dt__4ga_sFv", 'reference_count': 0, 'type': "Function"},
	'__ct__4ga_sFv': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".text", 'addr': 0x804FBAF4, 'size': 0x0004, 'padding': 0x00, 'name': "__ct__4ga_sFv", 'reference_count': 0, 'type': "Function"},
	'__dt__12daE_Ga_HIO_cFv': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".text", 'addr': 0x804FBAF8, 'size': 0x0048, 'padding': 0x00, 'name': "__dt__12daE_Ga_HIO_cFv", 'reference_count': 0, 'type': "Function"},
	'__sinit_d_a_e_ga_cpp': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".text", 'addr': 0x804FBB40, 'size': 0x003C, 'padding': 0x00, 'name': "__sinit_d_a_e_ga_cpp", 'reference_count': 1, 'type': "Function"},
	'data_804FBB7C': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "unknown_translation_unit_ctors", 'section': ".ctors", 'addr': 0x804FBB7C, 'size': 0x0008, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "ReferenceArray"},
	'__destroy_global_chain_reference': {'library': "Runtime.PPCEABI.H", 'translation_unit': "global_destructor_chain", 'section': ".dtors", 'addr': 0x804FBB84, 'size': 0x0004, 'padding': 0x00, 'name': "__destroy_global_chain_reference", 'reference_count': 0, 'type': "ReferenceArray"},
	'pad_804FBB88': {'library': "Runtime.PPCEABI.H", 'translation_unit': "global_destructor_chain", 'section': ".dtors", 'addr': 0x804FBB88, 'size': 0x0008, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "ReferenceArray"},
	'lit_3646': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".rodata", 'addr': 0x804FBB94, 'size': 0x0004, 'padding': 0x00, 'name': "@3646", 'reference_count': 0, 'type': "Integer"},
	'lit_3713': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".rodata", 'addr': 0x804FBB98, 'size': 0x0004, 'padding': 0x00, 'name': "@3713", 'reference_count': 0, 'type': "Integer"},
	'lit_3714': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".rodata", 'addr': 0x804FBB9C, 'size': 0x0004, 'padding': 0x00, 'name': "@3714", 'reference_count': 0, 'type': "Integer"},
	'lit_3715': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".rodata", 'addr': 0x804FBBA0, 'size': 0x0004, 'padding': 0x00, 'name': "@3715", 'reference_count': 0, 'type': "Integer"},
	'lit_3716': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".rodata", 'addr': 0x804FBBA4, 'size': 0x0004, 'padding': 0x04, 'name': "@3716", 'reference_count': 0, 'type': "InitData"},
	'lit_3718': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".rodata", 'addr': 0x804FBBAC, 'size': 0x0008, 'padding': 0x00, 'name': "@3718", 'reference_count': 0, 'type': "InitData"},
	'lit_3759': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".rodata", 'addr': 0x804FBBB4, 'size': 0x0004, 'padding': 0x00, 'name': "@3759", 'reference_count': 0, 'type': "Integer"},
	'lit_3760': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".rodata", 'addr': 0x804FBBB8, 'size': 0x0004, 'padding': 0x00, 'name': "@3760", 'reference_count': 0, 'type': "Integer"},
	'lit_3796': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".rodata", 'addr': 0x804FBBBC, 'size': 0x0004, 'padding': 0x00, 'name': "@3796", 'reference_count': 0, 'type': "Integer"},
	'lit_3797': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".rodata", 'addr': 0x804FBBC0, 'size': 0x0004, 'padding': 0x00, 'name': "@3797", 'reference_count': 0, 'type': "Integer"},
	'data_804FBBC4': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".rodata", 'addr': 0x804FBBC4, 'size': 0x0004, 'padding': 0x00, 'name': "l_bmdidx$3809", 'reference_count': 0, 'type': "InitData"},
	'lit_3912': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".rodata", 'addr': 0x804FBBC8, 'size': 0x0004, 'padding': 0x00, 'name': "@3912", 'reference_count': 0, 'type': "Integer"},
	'lit_3913': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".rodata", 'addr': 0x804FBBCC, 'size': 0x0004, 'padding': 0x00, 'name': "@3913", 'reference_count': 0, 'type': "Integer"},
	'lit_3914': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".rodata", 'addr': 0x804FBBD0, 'size': 0x0004, 'padding': 0x00, 'name': "@3914", 'reference_count': 0, 'type': "Integer"},
	'lit_3915': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".rodata", 'addr': 0x804FBBD4, 'size': 0x0004, 'padding': 0x00, 'name': "@3915", 'reference_count': 0, 'type': "Integer"},
	'stringBase0': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".rodata", 'addr': 0x804FBBD8, 'size': 0x000A, 'padding': 0x00, 'name': "@stringBase0", 'reference_count': 0, 'type': "StringBase"},
	'l_daE_Ga_Method': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".data", 'addr': 0x804FBBE4, 'size': 0x0020, 'padding': 0x00, 'name': "l_daE_Ga_Method", 'reference_count': 1, 'type': "ReferenceArray"},
	'g_profile_E_GA': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".data", 'addr': 0x804FBC04, 'size': 0x0030, 'padding': 0x00, 'name': "g_profile_E_GA", 'reference_count': 0, 'type': "ReferenceArray"},
	'__vt__12daE_Ga_HIO_c': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".data", 'addr': 0x804FBC34, 'size': 0x000C, 'padding': 0x00, 'name': "__vt__12daE_Ga_HIO_c", 'reference_count': 0, 'type': "VirtualTable"},
	'__global_destructor_chain': {'library': "Runtime.PPCEABI.H", 'translation_unit': "global_destructor_chain", 'section': ".bss", 'addr': 0x804FBC4C, 'size': 0x0004, 'padding': 0x04, 'name': "__global_destructor_chain", 'reference_count': 0, 'type': "ZeroData"},
	'data_804FBC54': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".bss", 'addr': 0x804FBC54, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "ZeroData"},
	'lit_3641': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".bss", 'addr': 0x804FBC58, 'size': 0x000C, 'padding': 0x00, 'name': "@3641", 'reference_count': 0, 'type': "ZeroData"},
	'l_HIO': {'library': "d/a/e/d_a_e_ga", 'translation_unit': "d_a_e_ga", 'section': ".bss", 'addr': 0x804FBC64, 'size': 0x000C, 'padding': 0x00, 'name': "l_HIO", 'reference_count': 0, 'type': "ZeroData"},
}
