#
# Generate By: dol2asm
# Module: 16
#

SYMBOLS = {
	'_prolog': {'library': "d/a/obj/d_a_obj_brakeeff", 'translation_unit': "executor", 'section': ".text", 'addr': 0x8046DC40, 'size': 0x002C, 'padding': 0x00, 'name': "_prolog", 'reference_count': 0, 'type': "Function"},
	'_epilog': {'library': "d/a/obj/d_a_obj_brakeeff", 'translation_unit': "executor", 'section': ".text", 'addr': 0x8046DC6C, 'size': 0x002C, 'padding': 0x00, 'name': "_epilog", 'reference_count': 0, 'type': "Function"},
	'_unresolved': {'library': "d/a/obj/d_a_obj_brakeeff", 'translation_unit': "executor", 'section': ".text", 'addr': 0x8046DC98, 'size': 0x0020, 'padding': 0x00, 'name': "_unresolved", 'reference_count': 11, 'type': "Function"},
	'daObj_Brakeeff_Draw__FP18obj_brakeeff_class': {'library': "d/a/obj/d_a_obj_brakeeff", 'translation_unit': "d_a_obj_brakeeff", 'section': ".text", 'addr': 0x8046DCB8, 'size': 0x0080, 'padding': 0x00, 'name': "daObj_Brakeeff_Draw__FP18obj_brakeeff_class", 'reference_count': 1, 'type': "Function"},
	'obj_brakeeff_1__FP18obj_brakeeff_class': {'library': "d/a/obj/d_a_obj_brakeeff", 'translation_unit': "d_a_obj_brakeeff", 'section': ".text", 'addr': 0x8046DD38, 'size': 0x0248, 'padding': 0x00, 'name': "obj_brakeeff_1__FP18obj_brakeeff_class", 'reference_count': 1, 'type': "Function"},
	'action__FP18obj_brakeeff_class': {'library': "d/a/obj/d_a_obj_brakeeff", 'translation_unit': "d_a_obj_brakeeff", 'section': ".text", 'addr': 0x8046DF80, 'size': 0x0030, 'padding': 0x00, 'name': "action__FP18obj_brakeeff_class", 'reference_count': 1, 'type': "Function"},
	'daObj_Brakeeff_Execute__FP18obj_brakeeff_class': {'library': "d/a/obj/d_a_obj_brakeeff", 'translation_unit': "d_a_obj_brakeeff", 'section': ".text", 'addr': 0x8046DFB0, 'size': 0x00E8, 'padding': 0x00, 'name': "daObj_Brakeeff_Execute__FP18obj_brakeeff_class", 'reference_count': 2, 'type': "Function"},
	'daObj_Brakeeff_IsDelete__FP18obj_brakeeff_class': {'library': "d/a/obj/d_a_obj_brakeeff", 'translation_unit': "d_a_obj_brakeeff", 'section': ".text", 'addr': 0x8046E098, 'size': 0x0008, 'padding': 0x00, 'name': "daObj_Brakeeff_IsDelete__FP18obj_brakeeff_class", 'reference_count': 1, 'type': "Function"},
	'daObj_Brakeeff_Delete__FP18obj_brakeeff_class': {'library': "d/a/obj/d_a_obj_brakeeff", 'translation_unit': "d_a_obj_brakeeff", 'section': ".text", 'addr': 0x8046E0A0, 'size': 0x0050, 'padding': 0x00, 'name': "daObj_Brakeeff_Delete__FP18obj_brakeeff_class", 'reference_count': 1, 'type': "Function"},
	'useHeapInit__FP10fopAc_ac_c': {'library': "d/a/obj/d_a_obj_brakeeff", 'translation_unit': "d_a_obj_brakeeff", 'section': ".text", 'addr': 0x8046E0F0, 'size': 0x01C0, 'padding': 0x00, 'name': "useHeapInit__FP10fopAc_ac_c", 'reference_count': 0, 'type': "Function"},
	'__dt__12J3DFrameCtrlFv': {'library': "d/a/obj/d_a_obj_brakeeff", 'translation_unit': "d_a_obj_brakeeff", 'section': ".text", 'addr': 0x8046E2B0, 'size': 0x0048, 'padding': 0x00, 'name': "__dt__12J3DFrameCtrlFv", 'reference_count': 0, 'type': "Function"},
	'daObj_Brakeeff_Create__FP10fopAc_ac_c': {'library': "d/a/obj/d_a_obj_brakeeff", 'translation_unit': "d_a_obj_brakeeff", 'section': ".text", 'addr': 0x8046E2F8, 'size': 0x0198, 'padding': 0x00, 'name': "daObj_Brakeeff_Create__FP10fopAc_ac_c", 'reference_count': 1, 'type': "Function"},
	'__dt__8cM3dGSphFv': {'library': "d/a/obj/d_a_obj_brakeeff", 'translation_unit': "d_a_obj_brakeeff", 'section': ".text", 'addr': 0x8046E490, 'size': 0x0048, 'padding': 0x00, 'name': "__dt__8cM3dGSphFv", 'reference_count': 0, 'type': "Function"},
	'__dt__8cM3dGAabFv': {'library': "d/a/obj/d_a_obj_brakeeff", 'translation_unit': "d_a_obj_brakeeff", 'section': ".text", 'addr': 0x8046E4D8, 'size': 0x0048, 'padding': 0x00, 'name': "__dt__8cM3dGAabFv", 'reference_count': 0, 'type': "Function"},
	'data_8046E520': {'library': "d/a/obj/d_a_obj_brakeeff", 'translation_unit': "unknown_translation_unit_ctors", 'section': ".ctors", 'addr': 0x8046E520, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'data_8046E524': {'library': "d/a/obj/d_a_obj_brakeeff", 'translation_unit': "unknown_translation_unit_dtors", 'section': ".dtors", 'addr': 0x8046E524, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'lit_3879': {'library': "d/a/obj/d_a_obj_brakeeff", 'translation_unit': "d_a_obj_brakeeff", 'section': ".rodata", 'addr': 0x8046E52C, 'size': 0x0004, 'padding': 0x00, 'name': "@3879", 'reference_count': 0, 'type': "Integer"},
	'lit_3880': {'library': "d/a/obj/d_a_obj_brakeeff", 'translation_unit': "d_a_obj_brakeeff", 'section': ".rodata", 'addr': 0x8046E530, 'size': 0x0004, 'padding': 0x00, 'name': "@3880", 'reference_count': 0, 'type': "Integer"},
	'lit_3881': {'library': "d/a/obj/d_a_obj_brakeeff", 'translation_unit': "d_a_obj_brakeeff", 'section': ".rodata", 'addr': 0x8046E534, 'size': 0x0004, 'padding': 0x00, 'name': "@3881", 'reference_count': 0, 'type': "Integer"},
	'lit_3882': {'library': "d/a/obj/d_a_obj_brakeeff", 'translation_unit': "d_a_obj_brakeeff", 'section': ".rodata", 'addr': 0x8046E538, 'size': 0x0004, 'padding': 0x00, 'name': "@3882", 'reference_count': 0, 'type': "Integer"},
	'stringBase0': {'library': "d/a/obj/d_a_obj_brakeeff", 'translation_unit': "d_a_obj_brakeeff", 'section': ".rodata", 'addr': 0x8046E53C, 'size': 0x0008, 'padding': 0x00, 'name': "@stringBase0", 'reference_count': 0, 'type': "StringBase"},
	'e_name': {'library': "d/a/obj/d_a_obj_brakeeff", 'translation_unit': "d_a_obj_brakeeff", 'section': ".data", 'addr': 0x8046E544, 'size': 0x000A, 'padding': 0x02, 'name': "e_name", 'reference_count': 0, 'type': "InitData"},
	'bef_bmd': {'library': "d/a/obj/d_a_obj_brakeeff", 'translation_unit': "d_a_obj_brakeeff", 'section': ".data", 'addr': 0x8046E550, 'size': 0x0008, 'padding': 0x00, 'name': "bef_bmd", 'reference_count': 0, 'type': "InitData"},
	'bef_brk': {'library': "d/a/obj/d_a_obj_brakeeff", 'translation_unit': "d_a_obj_brakeeff", 'section': ".data", 'addr': 0x8046E558, 'size': 0x0008, 'padding': 0x00, 'name': "bef_brk", 'reference_count': 0, 'type': "InitData"},
	'data_8046E560': {'library': "d/a/obj/d_a_obj_brakeeff", 'translation_unit': "d_a_obj_brakeeff", 'section': ".data", 'addr': 0x8046E560, 'size': 0x0040, 'padding': 0x00, 'name': "cc_sph_src$4003", 'reference_count': 0, 'type': "InitData"},
	'l_daObj_Brakeeff_Method': {'library': "d/a/obj/d_a_obj_brakeeff", 'translation_unit': "d_a_obj_brakeeff", 'section': ".data", 'addr': 0x8046E5A0, 'size': 0x0020, 'padding': 0x00, 'name': "l_daObj_Brakeeff_Method", 'reference_count': 1, 'type': "ReferenceArray"},
	'g_profile_OBJ_BEF': {'library': "d/a/obj/d_a_obj_brakeeff", 'translation_unit': "d_a_obj_brakeeff", 'section': ".data", 'addr': 0x8046E5C0, 'size': 0x0030, 'padding': 0x00, 'name': "g_profile_OBJ_BEF", 'reference_count': 0, 'type': "ReferenceArray"},
	'__vt__8cM3dGSph': {'library': "d/a/obj/d_a_obj_brakeeff", 'translation_unit': "d_a_obj_brakeeff", 'section': ".data", 'addr': 0x8046E5F0, 'size': 0x000C, 'padding': 0x00, 'name': "__vt__8cM3dGSph", 'reference_count': 0, 'type': "VirtualTable"},
	'__vt__8cM3dGAab': {'library': "d/a/obj/d_a_obj_brakeeff", 'translation_unit': "d_a_obj_brakeeff", 'section': ".data", 'addr': 0x8046E5FC, 'size': 0x000C, 'padding': 0x00, 'name': "__vt__8cM3dGAab", 'reference_count': 0, 'type': "VirtualTable"},
	'__vt__12J3DFrameCtrl': {'library': "d/a/obj/d_a_obj_brakeeff", 'translation_unit': "d_a_obj_brakeeff", 'section': ".data", 'addr': 0x8046E608, 'size': 0x000C, 'padding': 0x00, 'name': "__vt__12J3DFrameCtrl", 'reference_count': 0, 'type': "VirtualTable"},
}
