#
# Generate By: dol2asm
# Module: 692
#

SYMBOLS = {
	'_prolog': {'library': "d/a/obj/d_a_obj_wsword", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80D3B900, 'size': 0x002C, 'padding': 0x00, 'name': "_prolog", 'reference_count': 0, 'type': "Function"},
	'_epilog': {'library': "d/a/obj/d_a_obj_wsword", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80D3B92C, 'size': 0x002C, 'padding': 0x00, 'name': "_epilog", 'reference_count': 0, 'type': "Function"},
	'_unresolved': {'library': "d/a/obj/d_a_obj_wsword", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80D3B958, 'size': 0x0020, 'padding': 0x00, 'name': "_unresolved", 'reference_count': 12, 'type': "Function"},
	'CheckCreateHeap__FP10fopAc_ac_c': {'library': "d/a/obj/d_a_obj_wsword", 'translation_unit': "d_a_obj_wsword", 'section': ".text", 'addr': 0x80D3B978, 'size': 0x0020, 'padding': 0x00, 'name': "CheckCreateHeap__FP10fopAc_ac_c", 'reference_count': 0, 'type': "Function"},
	'initBaseMtx__13daObjWSword_cFv': {'library': "d/a/obj/d_a_obj_wsword", 'translation_unit': "d_a_obj_wsword", 'section': ".text", 'addr': 0x80D3B998, 'size': 0x003C, 'padding': 0x00, 'name': "initBaseMtx__13daObjWSword_cFv", 'reference_count': 1, 'type': "Function"},
	'setBaseMtx__13daObjWSword_cFv': {'library': "d/a/obj/d_a_obj_wsword", 'translation_unit': "d_a_obj_wsword", 'section': ".text", 'addr': 0x80D3B9D4, 'size': 0x006C, 'padding': 0x00, 'name': "setBaseMtx__13daObjWSword_cFv", 'reference_count': 2, 'type': "Function"},
	'Create__13daObjWSword_cFv': {'library': "d/a/obj/d_a_obj_wsword", 'translation_unit': "d_a_obj_wsword", 'section': ".text", 'addr': 0x80D3BA40, 'size': 0x0078, 'padding': 0x00, 'name': "Create__13daObjWSword_cFv", 'reference_count': 1, 'type': "Function"},
	'CreateHeap__13daObjWSword_cFv': {'library': "d/a/obj/d_a_obj_wsword", 'translation_unit': "d_a_obj_wsword", 'section': ".text", 'addr': 0x80D3BAB8, 'size': 0x0070, 'padding': 0x00, 'name': "CreateHeap__13daObjWSword_cFv", 'reference_count': 1, 'type': "Function"},
	'create__13daObjWSword_cFv': {'library': "d/a/obj/d_a_obj_wsword", 'translation_unit': "d_a_obj_wsword", 'section': ".text", 'addr': 0x80D3BB28, 'size': 0x0178, 'padding': 0x00, 'name': "create__13daObjWSword_cFv", 'reference_count': 1, 'type': "Function"},
	'__dt__8cM3dGCylFv': {'library': "d/a/obj/d_a_obj_wsword", 'translation_unit': "d_a_obj_wsword", 'section': ".text", 'addr': 0x80D3BCA0, 'size': 0x0048, 'padding': 0x00, 'name': "__dt__8cM3dGCylFv", 'reference_count': 0, 'type': "Function"},
	'__dt__8cM3dGAabFv': {'library': "d/a/obj/d_a_obj_wsword", 'translation_unit': "d_a_obj_wsword", 'section': ".text", 'addr': 0x80D3BCE8, 'size': 0x0048, 'padding': 0x00, 'name': "__dt__8cM3dGAabFv", 'reference_count': 0, 'type': "Function"},
	'__dt__12dBgS_ObjAcchFv': {'library': "d/a/obj/d_a_obj_wsword", 'translation_unit': "d_a_obj_wsword", 'section': ".text", 'addr': 0x80D3BD30, 'size': 0x0070, 'padding': 0x00, 'name': "__dt__12dBgS_ObjAcchFv", 'reference_count': 2, 'type': "Function"},
	'execute__13daObjWSword_cFv': {'library': "d/a/obj/d_a_obj_wsword", 'translation_unit': "d_a_obj_wsword", 'section': ".text", 'addr': 0x80D3BDA0, 'size': 0x0050, 'padding': 0x00, 'name': "execute__13daObjWSword_cFv", 'reference_count': 1, 'type': "Function"},
	'draw__13daObjWSword_cFv': {'library': "d/a/obj/d_a_obj_wsword", 'translation_unit': "d_a_obj_wsword", 'section': ".text", 'addr': 0x80D3BDF0, 'size': 0x0064, 'padding': 0x00, 'name': "draw__13daObjWSword_cFv", 'reference_count': 1, 'type': "Function"},
	'_delete__13daObjWSword_cFv': {'library': "d/a/obj/d_a_obj_wsword", 'translation_unit': "d_a_obj_wsword", 'section': ".text", 'addr': 0x80D3BE54, 'size': 0x0034, 'padding': 0x00, 'name': "_delete__13daObjWSword_cFv", 'reference_count': 1, 'type': "Function"},
	'daObjWSword_Draw__FP13daObjWSword_c': {'library': "d/a/obj/d_a_obj_wsword", 'translation_unit': "d_a_obj_wsword", 'section': ".text", 'addr': 0x80D3BE88, 'size': 0x0020, 'padding': 0x00, 'name': "daObjWSword_Draw__FP13daObjWSword_c", 'reference_count': 1, 'type': "Function"},
	'daObjWSword_Execute__FP13daObjWSword_c': {'library': "d/a/obj/d_a_obj_wsword", 'translation_unit': "d_a_obj_wsword", 'section': ".text", 'addr': 0x80D3BEA8, 'size': 0x0020, 'padding': 0x00, 'name': "daObjWSword_Execute__FP13daObjWSword_c", 'reference_count': 1, 'type': "Function"},
	'daObjWSword_Delete__FP13daObjWSword_c': {'library': "d/a/obj/d_a_obj_wsword", 'translation_unit': "d_a_obj_wsword", 'section': ".text", 'addr': 0x80D3BEC8, 'size': 0x0020, 'padding': 0x00, 'name': "daObjWSword_Delete__FP13daObjWSword_c", 'reference_count': 1, 'type': "Function"},
	'daObjWSword_Create__FP10fopAc_ac_c': {'library': "d/a/obj/d_a_obj_wsword", 'translation_unit': "d_a_obj_wsword", 'section': ".text", 'addr': 0x80D3BEE8, 'size': 0x0020, 'padding': 0x00, 'name': "daObjWSword_Create__FP10fopAc_ac_c", 'reference_count': 1, 'type': "Function"},
	'func_80D3BF08': {'library': "d/a/obj/d_a_obj_wsword", 'translation_unit': "d_a_obj_wsword", 'section': ".text", 'addr': 0x80D3BF08, 'size': 0x0008, 'padding': 0x00, 'name': "@36@__dt__12dBgS_ObjAcchFv", 'reference_count': 0, 'type': "Function"},
	'func_80D3BF10': {'library': "d/a/obj/d_a_obj_wsword", 'translation_unit': "d_a_obj_wsword", 'section': ".text", 'addr': 0x80D3BF10, 'size': 0x0008, 'padding': 0x00, 'name': "@20@__dt__12dBgS_ObjAcchFv", 'reference_count': 0, 'type': "Function"},
	'data_80D3BF18': {'library': "d/a/obj/d_a_obj_wsword", 'translation_unit': "unknown_translation_unit_ctors", 'section': ".ctors", 'addr': 0x80D3BF18, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'data_80D3BF1C': {'library': "d/a/obj/d_a_obj_wsword", 'translation_unit': "unknown_translation_unit_dtors", 'section': ".dtors", 'addr': 0x80D3BF1C, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'stringBase0': {'library': "d/a/obj/d_a_obj_wsword", 'translation_unit': "d_a_obj_wsword", 'section': ".rodata", 'addr': 0x80D3BF24, 'size': 0x000A, 'padding': 0x02, 'name': "@stringBase0", 'reference_count': 1, 'type': "StringBase"},
	'l_arcName': {'library': "d/a/obj/d_a_obj_wsword", 'translation_unit': "d_a_obj_wsword", 'section': ".data", 'addr': 0x80D3BF34, 'size': 0x0004, 'padding': 0x00, 'name': "l_arcName", 'reference_count': 0, 'type': "ReferenceArray"},
	'l_cyl_src': {'library': "d/a/obj/d_a_obj_wsword", 'translation_unit': "d_a_obj_wsword", 'section': ".data", 'addr': 0x80D3BF38, 'size': 0x0044, 'padding': 0x00, 'name': "l_cyl_src", 'reference_count': 0, 'type': "InitData"},
	'l_daObjWSword_Method': {'library': "d/a/obj/d_a_obj_wsword", 'translation_unit': "d_a_obj_wsword", 'section': ".data", 'addr': 0x80D3BF7C, 'size': 0x0020, 'padding': 0x00, 'name': "l_daObjWSword_Method", 'reference_count': 1, 'type': "ReferenceArray"},
	'g_profile_Obj_WoodenSword': {'library': "d/a/obj/d_a_obj_wsword", 'translation_unit': "d_a_obj_wsword", 'section': ".data", 'addr': 0x80D3BF9C, 'size': 0x0030, 'padding': 0x00, 'name': "g_profile_Obj_WoodenSword", 'reference_count': 0, 'type': "ReferenceArray"},
	'__vt__8cM3dGCyl': {'library': "d/a/obj/d_a_obj_wsword", 'translation_unit': "d_a_obj_wsword", 'section': ".data", 'addr': 0x80D3BFCC, 'size': 0x000C, 'padding': 0x00, 'name': "__vt__8cM3dGCyl", 'reference_count': 0, 'type': "VirtualTable"},
	'__vt__8cM3dGAab': {'library': "d/a/obj/d_a_obj_wsword", 'translation_unit': "d_a_obj_wsword", 'section': ".data", 'addr': 0x80D3BFD8, 'size': 0x000C, 'padding': 0x00, 'name': "__vt__8cM3dGAab", 'reference_count': 0, 'type': "VirtualTable"},
	'__vt__12dBgS_ObjAcch': {'library': "d/a/obj/d_a_obj_wsword", 'translation_unit': "d_a_obj_wsword", 'section': ".data", 'addr': 0x80D3BFE4, 'size': 0x0024, 'padding': 0x00, 'name': "__vt__12dBgS_ObjAcch", 'reference_count': 0, 'type': "VirtualTable"},
}
