#
# Generate By: dol2asm
# Module: 527
#

SYMBOLS = {
	'_prolog': {'library': "d/a/obj/d_a_obj_lv4HsTarget", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80C5F540, 'size': 0x002C, 'padding': 0x00, 'name': "_prolog", 'reference_count': 0, 'type': "Function"},
	'_epilog': {'library': "d/a/obj/d_a_obj_lv4HsTarget", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80C5F56C, 'size': 0x002C, 'padding': 0x00, 'name': "_epilog", 'reference_count': 0, 'type': "Function"},
	'_unresolved': {'library': "d/a/obj/d_a_obj_lv4HsTarget", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80C5F598, 'size': 0x0020, 'padding': 0x00, 'name': "_unresolved", 'reference_count': 11, 'type': "Function"},
	'__register_global_object': {'library': "Runtime.PPCEABI.H", 'translation_unit': "global_destructor_chain", 'section': ".text", 'addr': 0x80C5F5B8, 'size': 0x001C, 'padding': 0x00, 'name': "__register_global_object", 'reference_count': 1, 'type': "Function"},
	'__destroy_global_chain': {'library': "Runtime.PPCEABI.H", 'translation_unit': "global_destructor_chain", 'section': ".text", 'addr': 0x80C5F5D4, 'size': 0x0058, 'padding': 0x00, 'name': "__destroy_global_chain", 'reference_count': 2, 'type': "Function"},
	'__ct__19daLv4HsTarget_HIO_cFv': {'library': "d/a/obj/d_a_obj_lv4HsTarget", 'translation_unit': "d_a_obj_lv4HsTarget", 'section': ".text", 'addr': 0x80C5F62C, 'size': 0x001C, 'padding': 0x00, 'name': "__ct__19daLv4HsTarget_HIO_cFv", 'reference_count': 1, 'type': "Function"},
	'__dt__14mDoHIO_entry_cFv': {'library': "d/a/obj/d_a_obj_lv4HsTarget", 'translation_unit': "d_a_obj_lv4HsTarget", 'section': ".text", 'addr': 0x80C5F648, 'size': 0x0048, 'padding': 0x00, 'name': "__dt__14mDoHIO_entry_cFv", 'reference_count': 0, 'type': "Function"},
	'setBaseMtx__15daLv4HsTarget_cFv': {'library': "d/a/obj/d_a_obj_lv4HsTarget", 'translation_unit': "d_a_obj_lv4HsTarget", 'section': ".text", 'addr': 0x80C5F690, 'size': 0x0088, 'padding': 0x00, 'name': "setBaseMtx__15daLv4HsTarget_cFv", 'reference_count': 1, 'type': "Function"},
	'CreateHeap__15daLv4HsTarget_cFv': {'library': "d/a/obj/d_a_obj_lv4HsTarget", 'translation_unit': "d_a_obj_lv4HsTarget", 'section': ".text", 'addr': 0x80C5F718, 'size': 0x006C, 'padding': 0x00, 'name': "CreateHeap__15daLv4HsTarget_cFv", 'reference_count': 0, 'type': "Function"},
	'create__15daLv4HsTarget_cFv': {'library': "d/a/obj/d_a_obj_lv4HsTarget", 'translation_unit': "d_a_obj_lv4HsTarget", 'section': ".text", 'addr': 0x80C5F784, 'size': 0x00D8, 'padding': 0x00, 'name': "create__15daLv4HsTarget_cFv", 'reference_count': 1, 'type': "Function"},
	'Execute__15daLv4HsTarget_cFPPA3_A4_f': {'library': "d/a/obj/d_a_obj_lv4HsTarget", 'translation_unit': "d_a_obj_lv4HsTarget", 'section': ".text", 'addr': 0x80C5F85C, 'size': 0x0014, 'padding': 0x00, 'name': "Execute__15daLv4HsTarget_cFPPA3_A4_f", 'reference_count': 0, 'type': "Function"},
	'Draw__15daLv4HsTarget_cFv': {'library': "d/a/obj/d_a_obj_lv4HsTarget", 'translation_unit': "d_a_obj_lv4HsTarget", 'section': ".text", 'addr': 0x80C5F870, 'size': 0x0064, 'padding': 0x00, 'name': "Draw__15daLv4HsTarget_cFv", 'reference_count': 0, 'type': "Function"},
	'Delete__15daLv4HsTarget_cFv': {'library': "d/a/obj/d_a_obj_lv4HsTarget", 'translation_unit': "d_a_obj_lv4HsTarget", 'section': ".text", 'addr': 0x80C5F8D4, 'size': 0x0030, 'padding': 0x00, 'name': "Delete__15daLv4HsTarget_cFv", 'reference_count': 0, 'type': "Function"},
	'daLv4HsTarget_Draw__FP15daLv4HsTarget_c': {'library': "d/a/obj/d_a_obj_lv4HsTarget", 'translation_unit': "d_a_obj_lv4HsTarget", 'section': ".text", 'addr': 0x80C5F904, 'size': 0x002C, 'padding': 0x00, 'name': "daLv4HsTarget_Draw__FP15daLv4HsTarget_c", 'reference_count': 1, 'type': "Function"},
	'daLv4HsTarget_Execute__FP15daLv4HsTarget_c': {'library': "d/a/obj/d_a_obj_lv4HsTarget", 'translation_unit': "d_a_obj_lv4HsTarget", 'section': ".text", 'addr': 0x80C5F930, 'size': 0x0020, 'padding': 0x00, 'name': "daLv4HsTarget_Execute__FP15daLv4HsTarget_c", 'reference_count': 1, 'type': "Function"},
	'daLv4HsTarget_Delete__FP15daLv4HsTarget_c': {'library': "d/a/obj/d_a_obj_lv4HsTarget", 'translation_unit': "d_a_obj_lv4HsTarget", 'section': ".text", 'addr': 0x80C5F950, 'size': 0x0020, 'padding': 0x00, 'name': "daLv4HsTarget_Delete__FP15daLv4HsTarget_c", 'reference_count': 1, 'type': "Function"},
	'daLv4HsTarget_Create__FP10fopAc_ac_c': {'library': "d/a/obj/d_a_obj_lv4HsTarget", 'translation_unit': "d_a_obj_lv4HsTarget", 'section': ".text", 'addr': 0x80C5F970, 'size': 0x0020, 'padding': 0x00, 'name': "daLv4HsTarget_Create__FP10fopAc_ac_c", 'reference_count': 1, 'type': "Function"},
	'__dt__19daLv4HsTarget_HIO_cFv': {'library': "d/a/obj/d_a_obj_lv4HsTarget", 'translation_unit': "d_a_obj_lv4HsTarget", 'section': ".text", 'addr': 0x80C5F990, 'size': 0x005C, 'padding': 0x00, 'name': "__dt__19daLv4HsTarget_HIO_cFv", 'reference_count': 0, 'type': "Function"},
	'__sinit_d_a_obj_lv4HsTarget_cpp': {'library': "d/a/obj/d_a_obj_lv4HsTarget", 'translation_unit': "d_a_obj_lv4HsTarget", 'section': ".text", 'addr': 0x80C5F9EC, 'size': 0x003C, 'padding': 0x00, 'name': "__sinit_d_a_obj_lv4HsTarget_cpp", 'reference_count': 1, 'type': "Function"},
	'data_80C5FA28': {'library': "d/a/obj/d_a_obj_lv4HsTarget", 'translation_unit': "unknown_translation_unit_ctors", 'section': ".ctors", 'addr': 0x80C5FA28, 'size': 0x0008, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "ReferenceArray"},
	'__destroy_global_chain_reference': {'library': "Runtime.PPCEABI.H", 'translation_unit': "global_destructor_chain", 'section': ".dtors", 'addr': 0x80C5FA30, 'size': 0x0004, 'padding': 0x00, 'name': "__destroy_global_chain_reference", 'reference_count': 0, 'type': "ReferenceArray"},
	'pad_80C5FA34': {'library': "Runtime.PPCEABI.H", 'translation_unit': "global_destructor_chain", 'section': ".dtors", 'addr': 0x80C5FA34, 'size': 0x0008, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "ReferenceArray"},
	'stringBase0': {'library': "d/a/obj/d_a_obj_lv4HsTarget", 'translation_unit': "d_a_obj_lv4HsTarget", 'section': ".rodata", 'addr': 0x80C5FA3C, 'size': 0x0009, 'padding': 0x03, 'name': "@stringBase0", 'reference_count': 0, 'type': "StringBase"},
	'l_daLv4HsTarget_Method': {'library': "d/a/obj/d_a_obj_lv4HsTarget", 'translation_unit': "d_a_obj_lv4HsTarget", 'section': ".data", 'addr': 0x80C5FA4C, 'size': 0x0020, 'padding': 0x00, 'name': "l_daLv4HsTarget_Method", 'reference_count': 1, 'type': "ReferenceArray"},
	'g_profile_Obj_Lv4HsTarget': {'library': "d/a/obj/d_a_obj_lv4HsTarget", 'translation_unit': "d_a_obj_lv4HsTarget", 'section': ".data", 'addr': 0x80C5FA6C, 'size': 0x0030, 'padding': 0x00, 'name': "g_profile_Obj_Lv4HsTarget", 'reference_count': 0, 'type': "ReferenceArray"},
	'__vt__15daLv4HsTarget_c': {'library': "d/a/obj/d_a_obj_lv4HsTarget", 'translation_unit': "d_a_obj_lv4HsTarget", 'section': ".data", 'addr': 0x80C5FA9C, 'size': 0x0028, 'padding': 0x00, 'name': "__vt__15daLv4HsTarget_c", 'reference_count': 0, 'type': "VirtualTable"},
	'__vt__19daLv4HsTarget_HIO_c': {'library': "d/a/obj/d_a_obj_lv4HsTarget", 'translation_unit': "d_a_obj_lv4HsTarget", 'section': ".data", 'addr': 0x80C5FAC4, 'size': 0x000C, 'padding': 0x00, 'name': "__vt__19daLv4HsTarget_HIO_c", 'reference_count': 0, 'type': "VirtualTable"},
	'__vt__14mDoHIO_entry_c': {'library': "d/a/obj/d_a_obj_lv4HsTarget", 'translation_unit': "d_a_obj_lv4HsTarget", 'section': ".data", 'addr': 0x80C5FAD0, 'size': 0x000C, 'padding': 0x00, 'name': "__vt__14mDoHIO_entry_c", 'reference_count': 0, 'type': "VirtualTable"},
	'__global_destructor_chain': {'library': "Runtime.PPCEABI.H", 'translation_unit': "global_destructor_chain", 'section': ".bss", 'addr': 0x80C5FAEC, 'size': 0x0004, 'padding': 0x04, 'name': "__global_destructor_chain", 'reference_count': 0, 'type': "ZeroData"},
	'lit_3618': {'library': "d/a/obj/d_a_obj_lv4HsTarget", 'translation_unit': "d_a_obj_lv4HsTarget", 'section': ".bss", 'addr': 0x80C5FAF4, 'size': 0x000C, 'padding': 0x00, 'name': "@3618", 'reference_count': 0, 'type': "ZeroData"},
	'l_HIO': {'library': "d/a/obj/d_a_obj_lv4HsTarget", 'translation_unit': "d_a_obj_lv4HsTarget", 'section': ".bss", 'addr': 0x80C5FB00, 'size': 0x0004, 'padding': 0x00, 'name': "l_HIO", 'reference_count': 0, 'type': "ZeroData"},
}
