#
# Generate By: dol2asm
# Module: 636
#

SYMBOLS = {
	'_prolog': {'library': "d/a/obj/d_a_obj_suisya", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80CF0000, 'size': 0x002C, 'padding': 0x00, 'name': "_prolog", 'reference_count': 0, 'type': "Function"},
	'_epilog': {'library': "d/a/obj/d_a_obj_suisya", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80CF002C, 'size': 0x002C, 'padding': 0x00, 'name': "_epilog", 'reference_count': 0, 'type': "Function"},
	'_unresolved': {'library': "d/a/obj/d_a_obj_suisya", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80CF0058, 'size': 0x0020, 'padding': 0x00, 'name': "_unresolved", 'reference_count': 8, 'type': "Function"},
	'draw__14daObj_Suisya_cFv': {'library': "d/a/obj/d_a_obj_suisya", 'translation_unit': "d_a_obj_suisya", 'section': ".text", 'addr': 0x80CF0078, 'size': 0x00D0, 'padding': 0x00, 'name': "draw__14daObj_Suisya_cFv", 'reference_count': 1, 'type': "Function"},
	'daObj_Suisya_Draw__FP14daObj_Suisya_c': {'library': "d/a/obj/d_a_obj_suisya", 'translation_unit': "d_a_obj_suisya", 'section': ".text", 'addr': 0x80CF0148, 'size': 0x0020, 'padding': 0x00, 'name': "daObj_Suisya_Draw__FP14daObj_Suisya_c", 'reference_count': 1, 'type': "Function"},
	'execute__14daObj_Suisya_cFv': {'library': "d/a/obj/d_a_obj_suisya", 'translation_unit': "d_a_obj_suisya", 'section': ".text", 'addr': 0x80CF0168, 'size': 0x00A4, 'padding': 0x00, 'name': "execute__14daObj_Suisya_cFv", 'reference_count': 1, 'type': "Function"},
	'daObj_Suisya_Execute__FP14daObj_Suisya_c': {'library': "d/a/obj/d_a_obj_suisya", 'translation_unit': "d_a_obj_suisya", 'section': ".text", 'addr': 0x80CF020C, 'size': 0x0020, 'padding': 0x00, 'name': "daObj_Suisya_Execute__FP14daObj_Suisya_c", 'reference_count': 2, 'type': "Function"},
	'daObj_Suisya_IsDelete__FP14daObj_Suisya_c': {'library': "d/a/obj/d_a_obj_suisya", 'translation_unit': "d_a_obj_suisya", 'section': ".text", 'addr': 0x80CF022C, 'size': 0x0008, 'padding': 0x00, 'name': "daObj_Suisya_IsDelete__FP14daObj_Suisya_c", 'reference_count': 1, 'type': "Function"},
	'_delete__14daObj_Suisya_cFv': {'library': "d/a/obj/d_a_obj_suisya", 'translation_unit': "d_a_obj_suisya", 'section': ".text", 'addr': 0x80CF0234, 'size': 0x0030, 'padding': 0x00, 'name': "_delete__14daObj_Suisya_cFv", 'reference_count': 1, 'type': "Function"},
	'daObj_Suisya_Delete__FP14daObj_Suisya_c': {'library': "d/a/obj/d_a_obj_suisya", 'translation_unit': "d_a_obj_suisya", 'section': ".text", 'addr': 0x80CF0264, 'size': 0x0020, 'padding': 0x00, 'name': "daObj_Suisya_Delete__FP14daObj_Suisya_c", 'reference_count': 1, 'type': "Function"},
	'CreateHeap__14daObj_Suisya_cFv': {'library': "d/a/obj/d_a_obj_suisya", 'translation_unit': "d_a_obj_suisya", 'section': ".text", 'addr': 0x80CF0284, 'size': 0x006C, 'padding': 0x00, 'name': "CreateHeap__14daObj_Suisya_cFv", 'reference_count': 1, 'type': "Function"},
	'useHeapInit__FP10fopAc_ac_c': {'library': "d/a/obj/d_a_obj_suisya", 'translation_unit': "d_a_obj_suisya", 'section': ".text", 'addr': 0x80CF02F0, 'size': 0x0020, 'padding': 0x00, 'name': "useHeapInit__FP10fopAc_ac_c", 'reference_count': 0, 'type': "Function"},
	'create__14daObj_Suisya_cFv': {'library': "d/a/obj/d_a_obj_suisya", 'translation_unit': "d_a_obj_suisya", 'section': ".text", 'addr': 0x80CF0310, 'size': 0x0168, 'padding': 0x00, 'name': "create__14daObj_Suisya_cFv", 'reference_count': 1, 'type': "Function"},
	'__dt__12dBgS_ObjAcchFv': {'library': "d/a/obj/d_a_obj_suisya", 'translation_unit': "d_a_obj_suisya", 'section': ".text", 'addr': 0x80CF0478, 'size': 0x0070, 'padding': 0x00, 'name': "__dt__12dBgS_ObjAcchFv", 'reference_count': 2, 'type': "Function"},
	'daObj_Suisya_Create__FP14daObj_Suisya_c': {'library': "d/a/obj/d_a_obj_suisya", 'translation_unit': "d_a_obj_suisya", 'section': ".text", 'addr': 0x80CF04E8, 'size': 0x0020, 'padding': 0x00, 'name': "daObj_Suisya_Create__FP14daObj_Suisya_c", 'reference_count': 1, 'type': "Function"},
	'func_80CF0508': {'library': "d/a/obj/d_a_obj_suisya", 'translation_unit': "d_a_obj_suisya", 'section': ".text", 'addr': 0x80CF0508, 'size': 0x0008, 'padding': 0x00, 'name': "@36@__dt__12dBgS_ObjAcchFv", 'reference_count': 0, 'type': "Function"},
	'func_80CF0510': {'library': "d/a/obj/d_a_obj_suisya", 'translation_unit': "d_a_obj_suisya", 'section': ".text", 'addr': 0x80CF0510, 'size': 0x0008, 'padding': 0x00, 'name': "@20@__dt__12dBgS_ObjAcchFv", 'reference_count': 0, 'type': "Function"},
	'data_80CF0518': {'library': "d/a/obj/d_a_obj_suisya", 'translation_unit': "unknown_translation_unit_ctors", 'section': ".ctors", 'addr': 0x80CF0518, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'data_80CF051C': {'library': "d/a/obj/d_a_obj_suisya", 'translation_unit': "unknown_translation_unit_dtors", 'section': ".dtors", 'addr': 0x80CF051C, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'lit_3662': {'library': "d/a/obj/d_a_obj_suisya", 'translation_unit': "d_a_obj_suisya", 'section': ".rodata", 'addr': 0x80CF0524, 'size': 0x0004, 'padding': 0x00, 'name': "@3662", 'reference_count': 0, 'type': "Integer"},
	'lit_3663': {'library': "d/a/obj/d_a_obj_suisya", 'translation_unit': "d_a_obj_suisya", 'section': ".rodata", 'addr': 0x80CF0528, 'size': 0x0004, 'padding': 0x00, 'name': "@3663", 'reference_count': 0, 'type': "Integer"},
	'lit_3664': {'library': "d/a/obj/d_a_obj_suisya", 'translation_unit': "d_a_obj_suisya", 'section': ".rodata", 'addr': 0x80CF052C, 'size': 0x0004, 'padding': 0x00, 'name': "@3664", 'reference_count': 0, 'type': "InitData"},
	'lit_3665': {'library': "d/a/obj/d_a_obj_suisya", 'translation_unit': "d_a_obj_suisya", 'section': ".rodata", 'addr': 0x80CF0530, 'size': 0x0004, 'padding': 0x00, 'name': "@3665", 'reference_count': 0, 'type': "Integer"},
	'lit_3682': {'library': "d/a/obj/d_a_obj_suisya", 'translation_unit': "d_a_obj_suisya", 'section': ".rodata", 'addr': 0x80CF0534, 'size': 0x0004, 'padding': 0x00, 'name': "@3682", 'reference_count': 0, 'type': "Integer"},
	'lit_3749': {'library': "d/a/obj/d_a_obj_suisya", 'translation_unit': "d_a_obj_suisya", 'section': ".rodata", 'addr': 0x80CF0538, 'size': 0x0004, 'padding': 0x00, 'name': "@3749", 'reference_count': 0, 'type': "Integer"},
	'lit_3750': {'library': "d/a/obj/d_a_obj_suisya", 'translation_unit': "d_a_obj_suisya", 'section': ".rodata", 'addr': 0x80CF053C, 'size': 0x0004, 'padding': 0x00, 'name': "@3750", 'reference_count': 0, 'type': "Integer"},
	'lit_3751': {'library': "d/a/obj/d_a_obj_suisya", 'translation_unit': "d_a_obj_suisya", 'section': ".rodata", 'addr': 0x80CF0540, 'size': 0x0004, 'padding': 0x00, 'name': "@3751", 'reference_count': 0, 'type': "Integer"},
	'lit_3752': {'library': "d/a/obj/d_a_obj_suisya", 'translation_unit': "d_a_obj_suisya", 'section': ".rodata", 'addr': 0x80CF0544, 'size': 0x0004, 'padding': 0x00, 'name': "@3752", 'reference_count': 0, 'type': "Integer"},
	'stringBase0': {'library': "d/a/obj/d_a_obj_suisya", 'translation_unit': "d_a_obj_suisya", 'section': ".rodata", 'addr': 0x80CF0548, 'size': 0x0008, 'padding': 0x00, 'name': "@stringBase0", 'reference_count': 0, 'type': "StringBase"},
	'l_daObj_Suisya_Method': {'library': "d/a/obj/d_a_obj_suisya", 'translation_unit': "d_a_obj_suisya", 'section': ".data", 'addr': 0x80CF0554, 'size': 0x0020, 'padding': 0x00, 'name': "l_daObj_Suisya_Method", 'reference_count': 1, 'type': "ReferenceArray"},
	'g_profile_OBJ_SUISYA': {'library': "d/a/obj/d_a_obj_suisya", 'translation_unit': "d_a_obj_suisya", 'section': ".data", 'addr': 0x80CF0574, 'size': 0x0030, 'padding': 0x00, 'name': "g_profile_OBJ_SUISYA", 'reference_count': 0, 'type': "ReferenceArray"},
	'__vt__12dBgS_ObjAcch': {'library': "d/a/obj/d_a_obj_suisya", 'translation_unit': "d_a_obj_suisya", 'section': ".data", 'addr': 0x80CF05A4, 'size': 0x0024, 'padding': 0x00, 'name': "__vt__12dBgS_ObjAcch", 'reference_count': 0, 'type': "VirtualTable"},
}
