#
# Generate By: dol2asm
# Module: 662
#

SYMBOLS = {
	'_prolog': {'library': "d/a/obj/d_a_obj_toaru_maki", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80D13000, 'size': 0x002C, 'padding': 0x00, 'name': "_prolog", 'reference_count': 0, 'type': "Function"},
	'_epilog': {'library': "d/a/obj/d_a_obj_toaru_maki", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80D1302C, 'size': 0x002C, 'padding': 0x00, 'name': "_epilog", 'reference_count': 0, 'type': "Function"},
	'_unresolved': {'library': "d/a/obj/d_a_obj_toaru_maki", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80D13058, 'size': 0x0020, 'padding': 0x00, 'name': "_unresolved", 'reference_count': 9, 'type': "Function"},
	'daObjToaruMaki_c_createHeap__FP10fopAc_ac_c': {'library': "d/a/obj/d_a_obj_toaru_maki", 'translation_unit': "d_a_obj_toaru_maki", 'section': ".text", 'addr': 0x80D13078, 'size': 0x0020, 'padding': 0x00, 'name': "daObjToaruMaki_c_createHeap__FP10fopAc_ac_c", 'reference_count': 0, 'type': "Function"},
	'__ct__16daObjToaruMaki_cFv': {'library': "d/a/obj/d_a_obj_toaru_maki", 'translation_unit': "d_a_obj_toaru_maki", 'section': ".text", 'addr': 0x80D13098, 'size': 0x0048, 'padding': 0x00, 'name': "__ct__16daObjToaruMaki_cFv", 'reference_count': 2, 'type': "Function"},
	'__dt__16daObjToaruMaki_cFv': {'library': "d/a/obj/d_a_obj_toaru_maki", 'translation_unit': "d_a_obj_toaru_maki", 'section': ".text", 'addr': 0x80D130E0, 'size': 0x008C, 'padding': 0x00, 'name': "__dt__16daObjToaruMaki_cFv", 'reference_count': 0, 'type': "Function"},
	'createHeap__16daObjToaruMaki_cFv': {'library': "d/a/obj/d_a_obj_toaru_maki", 'translation_unit': "d_a_obj_toaru_maki", 'section': ".text", 'addr': 0x80D1316C, 'size': 0x0148, 'padding': 0x00, 'name': "createHeap__16daObjToaruMaki_cFv", 'reference_count': 1, 'type': "Function"},
	'create__16daObjToaruMaki_cFv': {'library': "d/a/obj/d_a_obj_toaru_maki", 'translation_unit': "d_a_obj_toaru_maki", 'section': ".text", 'addr': 0x80D132B4, 'size': 0x010C, 'padding': 0x00, 'name': "create__16daObjToaruMaki_cFv", 'reference_count': 1, 'type': "Function"},
	'Delete__16daObjToaruMaki_cFv': {'library': "d/a/obj/d_a_obj_toaru_maki", 'translation_unit': "d_a_obj_toaru_maki", 'section': ".text", 'addr': 0x80D133C0, 'size': 0x007C, 'padding': 0x00, 'name': "Delete__16daObjToaruMaki_cFv", 'reference_count': 1, 'type': "Function"},
	'setModelMtx__16daObjToaruMaki_cFv': {'library': "d/a/obj/d_a_obj_toaru_maki", 'translation_unit': "d_a_obj_toaru_maki", 'section': ".text", 'addr': 0x80D1343C, 'size': 0x0064, 'padding': 0x00, 'name': "setModelMtx__16daObjToaruMaki_cFv", 'reference_count': 2, 'type': "Function"},
	'draw__16daObjToaruMaki_cFv': {'library': "d/a/obj/d_a_obj_toaru_maki", 'translation_unit': "d_a_obj_toaru_maki", 'section': ".text", 'addr': 0x80D134A0, 'size': 0x0084, 'padding': 0x00, 'name': "draw__16daObjToaruMaki_cFv", 'reference_count': 1, 'type': "Function"},
	'execute__16daObjToaruMaki_cFv': {'library': "d/a/obj/d_a_obj_toaru_maki", 'translation_unit': "d_a_obj_toaru_maki", 'section': ".text", 'addr': 0x80D13524, 'size': 0x0024, 'padding': 0x00, 'name': "execute__16daObjToaruMaki_cFv", 'reference_count': 1, 'type': "Function"},
	'daObjToaruMaki_create__FP16daObjToaruMaki_c': {'library': "d/a/obj/d_a_obj_toaru_maki", 'translation_unit': "d_a_obj_toaru_maki", 'section': ".text", 'addr': 0x80D13548, 'size': 0x0054, 'padding': 0x00, 'name': "daObjToaruMaki_create__FP16daObjToaruMaki_c", 'reference_count': 1, 'type': "Function"},
	'daObjToaruMaki_Delete__FP16daObjToaruMaki_c': {'library': "d/a/obj/d_a_obj_toaru_maki", 'translation_unit': "d_a_obj_toaru_maki", 'section': ".text", 'addr': 0x80D1359C, 'size': 0x0020, 'padding': 0x00, 'name': "daObjToaruMaki_Delete__FP16daObjToaruMaki_c", 'reference_count': 1, 'type': "Function"},
	'daObjToaruMaki_execute__FP16daObjToaruMaki_c': {'library': "d/a/obj/d_a_obj_toaru_maki", 'translation_unit': "d_a_obj_toaru_maki", 'section': ".text", 'addr': 0x80D135BC, 'size': 0x0020, 'padding': 0x00, 'name': "daObjToaruMaki_execute__FP16daObjToaruMaki_c", 'reference_count': 1, 'type': "Function"},
	'daObjToaruMaki_draw__FP16daObjToaruMaki_c': {'library': "d/a/obj/d_a_obj_toaru_maki", 'translation_unit': "d_a_obj_toaru_maki", 'section': ".text", 'addr': 0x80D135DC, 'size': 0x0020, 'padding': 0x00, 'name': "daObjToaruMaki_draw__FP16daObjToaruMaki_c", 'reference_count': 1, 'type': "Function"},
	'data_80D135FC': {'library': "d/a/obj/d_a_obj_toaru_maki", 'translation_unit': "unknown_translation_unit_ctors", 'section': ".ctors", 'addr': 0x80D135FC, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'data_80D13600': {'library': "d/a/obj/d_a_obj_toaru_maki", 'translation_unit': "unknown_translation_unit_dtors", 'section': ".dtors", 'addr': 0x80D13600, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'l_bmdIdx': {'library': "d/a/obj/d_a_obj_toaru_maki", 'translation_unit': "d_a_obj_toaru_maki", 'section': ".rodata", 'addr': 0x80D13604, 'size': 0x0008, 'padding': 0x00, 'name': "l_bmdIdx", 'reference_count': 0, 'type': "InitData"},
	'l_heapSize': {'library': "d/a/obj/d_a_obj_toaru_maki", 'translation_unit': "d_a_obj_toaru_maki", 'section': ".rodata", 'addr': 0x80D1360C, 'size': 0x0008, 'padding': 0x00, 'name': "l_heapSize", 'reference_count': 0, 'type': "InitData"},
	'stringBase0': {'library': "d/a/obj/d_a_obj_toaru_maki", 'translation_unit': "d_a_obj_toaru_maki", 'section': ".rodata", 'addr': 0x80D13614, 'size': 0x0010, 'padding': 0x00, 'name': "@stringBase0", 'reference_count': 1, 'type': "StringBase"},
	'l_arcName': {'library': "d/a/obj/d_a_obj_toaru_maki", 'translation_unit': "d_a_obj_toaru_maki", 'section': ".data", 'addr': 0x80D13624, 'size': 0x0008, 'padding': 0x00, 'name': "l_arcName", 'reference_count': 0, 'type': "ReferenceArray"},
	'daObjToaruMaki_METHODS': {'library': "d/a/obj/d_a_obj_toaru_maki", 'translation_unit': "d_a_obj_toaru_maki", 'section': ".data", 'addr': 0x80D1362C, 'size': 0x0020, 'padding': 0x00, 'name': "daObjToaruMaki_METHODS", 'reference_count': 1, 'type': "ReferenceArray"},
	'g_profile_Obj_ToaruMaki': {'library': "d/a/obj/d_a_obj_toaru_maki", 'translation_unit': "d_a_obj_toaru_maki", 'section': ".data", 'addr': 0x80D1364C, 'size': 0x0030, 'padding': 0x00, 'name': "g_profile_Obj_ToaruMaki", 'reference_count': 0, 'type': "ReferenceArray"},
	'__vt__16daObjToaruMaki_c': {'library': "d/a/obj/d_a_obj_toaru_maki", 'translation_unit': "d_a_obj_toaru_maki", 'section': ".data", 'addr': 0x80D1367C, 'size': 0x000C, 'padding': 0x00, 'name': "__vt__16daObjToaruMaki_c", 'reference_count': 0, 'type': "VirtualTable"},
}
