#
# Generate By: dol2asm
# Module: 36
#

SYMBOLS = {
	'_prolog': {'library': "d/a/tag/d_a_tag_lantern", 'translation_unit': "executor", 'section': ".text", 'addr': 0x8048EBC0, 'size': 0x002C, 'padding': 0x00, 'name': "_prolog", 'reference_count': 0, 'type': "Function"},
	'_epilog': {'library': "d/a/tag/d_a_tag_lantern", 'translation_unit': "executor", 'section': ".text", 'addr': 0x8048EBEC, 'size': 0x002C, 'padding': 0x00, 'name': "_epilog", 'reference_count': 0, 'type': "Function"},
	'_unresolved': {'library': "d/a/tag/d_a_tag_lantern", 'translation_unit': "executor", 'section': ".text", 'addr': 0x8048EC18, 'size': 0x0020, 'padding': 0x00, 'name': "_unresolved", 'reference_count': 7, 'type': "Function"},
	'__register_global_object': {'library': "Runtime.PPCEABI.H", 'translation_unit': "global_destructor_chain", 'section': ".text", 'addr': 0x8048EC38, 'size': 0x001C, 'padding': 0x00, 'name': "__register_global_object", 'reference_count': 1, 'type': "Function"},
	'__destroy_global_chain': {'library': "Runtime.PPCEABI.H", 'translation_unit': "global_destructor_chain", 'section': ".text", 'addr': 0x8048EC54, 'size': 0x0058, 'padding': 0x00, 'name': "__destroy_global_chain", 'reference_count': 2, 'type': "Function"},
	'__dt__15daTag_Lantern_cFv': {'library': "d/a/tag/d_a_tag_lantern", 'translation_unit': "d_a_tag_lantern", 'section': ".text", 'addr': 0x8048ECAC, 'size': 0x007C, 'padding': 0x00, 'name': "__dt__15daTag_Lantern_cFv", 'reference_count': 0, 'type': "Function"},
	'create__15daTag_Lantern_cFv': {'library': "d/a/tag/d_a_tag_lantern", 'translation_unit': "d_a_tag_lantern", 'section': ".text", 'addr': 0x8048ED28, 'size': 0x0080, 'padding': 0x00, 'name': "create__15daTag_Lantern_cFv", 'reference_count': 1, 'type': "Function"},
	'Delete__15daTag_Lantern_cFv': {'library': "d/a/tag/d_a_tag_lantern", 'translation_unit': "d_a_tag_lantern", 'section': ".text", 'addr': 0x8048EDA8, 'size': 0x0034, 'padding': 0x00, 'name': "Delete__15daTag_Lantern_cFv", 'reference_count': 1, 'type': "Function"},
	'Execute__15daTag_Lantern_cFv': {'library': "d/a/tag/d_a_tag_lantern", 'translation_unit': "d_a_tag_lantern", 'section': ".text", 'addr': 0x8048EDDC, 'size': 0x0190, 'padding': 0x00, 'name': "Execute__15daTag_Lantern_cFv", 'reference_count': 2, 'type': "Function"},
	'Draw__15daTag_Lantern_cFv': {'library': "d/a/tag/d_a_tag_lantern", 'translation_unit': "d_a_tag_lantern", 'section': ".text", 'addr': 0x8048EF6C, 'size': 0x0008, 'padding': 0x00, 'name': "Draw__15daTag_Lantern_cFv", 'reference_count': 1, 'type': "Function"},
	'initialize__15daTag_Lantern_cFv': {'library': "d/a/tag/d_a_tag_lantern", 'translation_unit': "d_a_tag_lantern", 'section': ".text", 'addr': 0x8048EF74, 'size': 0x00B0, 'padding': 0x00, 'name': "initialize__15daTag_Lantern_cFv", 'reference_count': 1, 'type': "Function"},
	'daTag_Lantern_Create__FPv': {'library': "d/a/tag/d_a_tag_lantern", 'translation_unit': "d_a_tag_lantern", 'section': ".text", 'addr': 0x8048F024, 'size': 0x0020, 'padding': 0x00, 'name': "daTag_Lantern_Create__FPv", 'reference_count': 1, 'type': "Function"},
	'daTag_Lantern_Delete__FPv': {'library': "d/a/tag/d_a_tag_lantern", 'translation_unit': "d_a_tag_lantern", 'section': ".text", 'addr': 0x8048F044, 'size': 0x0020, 'padding': 0x00, 'name': "daTag_Lantern_Delete__FPv", 'reference_count': 1, 'type': "Function"},
	'daTag_Lantern_Execute__FPv': {'library': "d/a/tag/d_a_tag_lantern", 'translation_unit': "d_a_tag_lantern", 'section': ".text", 'addr': 0x8048F064, 'size': 0x0020, 'padding': 0x00, 'name': "daTag_Lantern_Execute__FPv", 'reference_count': 1, 'type': "Function"},
	'daTag_Lantern_Draw__FPv': {'library': "d/a/tag/d_a_tag_lantern", 'translation_unit': "d_a_tag_lantern", 'section': ".text", 'addr': 0x8048F084, 'size': 0x0020, 'padding': 0x00, 'name': "daTag_Lantern_Draw__FPv", 'reference_count': 1, 'type': "Function"},
	'daTag_Lantern_IsDelete__FPv': {'library': "d/a/tag/d_a_tag_lantern", 'translation_unit': "d_a_tag_lantern", 'section': ".text", 'addr': 0x8048F0A4, 'size': 0x0008, 'padding': 0x00, 'name': "daTag_Lantern_IsDelete__FPv", 'reference_count': 1, 'type': "Function"},
	'__sinit_d_a_tag_lantern_cpp': {'library': "d/a/tag/d_a_tag_lantern", 'translation_unit': "d_a_tag_lantern", 'section': ".text", 'addr': 0x8048F0AC, 'size': 0x0040, 'padding': 0x00, 'name': "__sinit_d_a_tag_lantern_cpp", 'reference_count': 1, 'type': "Function"},
	'__dt__21daTag_Lantern_Param_cFv': {'library': "d/a/tag/d_a_tag_lantern", 'translation_unit': "d_a_tag_lantern", 'section': ".text", 'addr': 0x8048F0EC, 'size': 0x0048, 'padding': 0x00, 'name': "__dt__21daTag_Lantern_Param_cFv", 'reference_count': 0, 'type': "Function"},
	'data_8048F134': {'library': "d/a/tag/d_a_tag_lantern", 'translation_unit': "unknown_translation_unit_ctors", 'section': ".ctors", 'addr': 0x8048F134, 'size': 0x0008, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "ReferenceArray"},
	'__destroy_global_chain_reference': {'library': "Runtime.PPCEABI.H", 'translation_unit': "global_destructor_chain", 'section': ".dtors", 'addr': 0x8048F13C, 'size': 0x0004, 'padding': 0x00, 'name': "__destroy_global_chain_reference", 'reference_count': 0, 'type': "ReferenceArray"},
	'pad_8048F140': {'library': "Runtime.PPCEABI.H", 'translation_unit': "global_destructor_chain", 'section': ".dtors", 'addr': 0x8048F140, 'size': 0x0008, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "ReferenceArray"},
	'lit_3683': {'library': "d/a/tag/d_a_tag_lantern", 'translation_unit': "d_a_tag_lantern", 'section': ".rodata", 'addr': 0x8048F14C, 'size': 0x0004, 'padding': 0x00, 'name': "@3683", 'reference_count': 0, 'type': "Integer"},
	'lit_3697': {'library': "d/a/tag/d_a_tag_lantern", 'translation_unit': "d_a_tag_lantern", 'section': ".rodata", 'addr': 0x8048F150, 'size': 0x0004, 'padding': 0x00, 'name': "@3697", 'reference_count': 0, 'type': "InitData"},
	'lit_3698': {'library': "d/a/tag/d_a_tag_lantern", 'translation_unit': "d_a_tag_lantern", 'section': ".rodata", 'addr': 0x8048F154, 'size': 0x0004, 'padding': 0x00, 'name': "@3698", 'reference_count': 0, 'type': "Integer"},
	'daTag_Lantern_MethodTable': {'library': "d/a/tag/d_a_tag_lantern", 'translation_unit': "d_a_tag_lantern", 'section': ".data", 'addr': 0x8048F15C, 'size': 0x0020, 'padding': 0x00, 'name': "daTag_Lantern_MethodTable", 'reference_count': 1, 'type': "ReferenceArray"},
	'g_profile_TAG_LANTERN': {'library': "d/a/tag/d_a_tag_lantern", 'translation_unit': "d_a_tag_lantern", 'section': ".data", 'addr': 0x8048F17C, 'size': 0x0030, 'padding': 0x00, 'name': "g_profile_TAG_LANTERN", 'reference_count': 0, 'type': "ReferenceArray"},
	'__vt__15daTag_Lantern_c': {'library': "d/a/tag/d_a_tag_lantern", 'translation_unit': "d_a_tag_lantern", 'section': ".data", 'addr': 0x8048F1AC, 'size': 0x000C, 'padding': 0x00, 'name': "__vt__15daTag_Lantern_c", 'reference_count': 0, 'type': "VirtualTable"},
	'__vt__21daTag_Lantern_Param_c': {'library': "d/a/tag/d_a_tag_lantern", 'translation_unit': "d_a_tag_lantern", 'section': ".data", 'addr': 0x8048F1B8, 'size': 0x000C, 'padding': 0x00, 'name': "__vt__21daTag_Lantern_Param_c", 'reference_count': 0, 'type': "VirtualTable"},
	'__global_destructor_chain': {'library': "Runtime.PPCEABI.H", 'translation_unit': "global_destructor_chain", 'section': ".bss", 'addr': 0x8048F1CC, 'size': 0x0004, 'padding': 0x04, 'name': "__global_destructor_chain", 'reference_count': 0, 'type': "ZeroData"},
	'lit_3622': {'library': "d/a/tag/d_a_tag_lantern", 'translation_unit': "d_a_tag_lantern", 'section': ".bss", 'addr': 0x8048F1D4, 'size': 0x000C, 'padding': 0x00, 'name': "@3622", 'reference_count': 0, 'type': "ZeroData"},
	'l_HIO': {'library': "d/a/tag/d_a_tag_lantern", 'translation_unit': "d_a_tag_lantern", 'section': ".bss", 'addr': 0x8048F1E0, 'size': 0x0004, 'padding': 0x00, 'name': "l_HIO", 'reference_count': 0, 'type': "ZeroData"},
}
