#
# Generate By: dol2asm
# Module: 197
#

SYMBOLS = {
	'_prolog': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "executor", 'section': ".text", 'addr': 0x806DF380, 'size': 0x002C, 'padding': 0x00, 'name': "_prolog", 'reference_count': 0, 'type': "Function"},
	'_epilog': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "executor", 'section': ".text", 'addr': 0x806DF3AC, 'size': 0x002C, 'padding': 0x00, 'name': "_epilog", 'reference_count': 0, 'type': "Function"},
	'_unresolved': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "executor", 'section': ".text", 'addr': 0x806DF3D8, 'size': 0x0020, 'padding': 0x00, 'name': "_unresolved", 'reference_count': 11, 'type': "Function"},
	'__register_global_object': {'library': "Runtime.PPCEABI.H", 'translation_unit': "global_destructor_chain", 'section': ".text", 'addr': 0x806DF3F8, 'size': 0x001C, 'padding': 0x00, 'name': "__register_global_object", 'reference_count': 1, 'type': "Function"},
	'__destroy_global_chain': {'library': "Runtime.PPCEABI.H", 'translation_unit': "global_destructor_chain", 'section': ".text", 'addr': 0x806DF414, 'size': 0x0058, 'padding': 0x00, 'name': "__destroy_global_chain", 'reference_count': 2, 'type': "Function"},
	'__ct__12daE_GS_HIO_cFv': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".text", 'addr': 0x806DF46C, 'size': 0x0048, 'padding': 0x00, 'name': "__ct__12daE_GS_HIO_cFv", 'reference_count': 1, 'type': "Function"},
	'anm_init__FP10e_gs_classifUcf': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".text", 'addr': 0x806DF4B4, 'size': 0x00AC, 'padding': 0x00, 'name': "anm_init__FP10e_gs_classifUcf", 'reference_count': 1, 'type': "Function"},
	'daE_GS_Draw__FP10e_gs_class': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".text", 'addr': 0x806DF560, 'size': 0x0100, 'padding': 0x00, 'name': "daE_GS_Draw__FP10e_gs_class", 'reference_count': 1, 'type': "Function"},
	'e_gs_wait__FP10e_gs_class': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".text", 'addr': 0x806DF660, 'size': 0x016C, 'padding': 0x00, 'name': "e_gs_wait__FP10e_gs_class", 'reference_count': 1, 'type': "Function"},
	'action__FP10e_gs_class': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".text", 'addr': 0x806DF7CC, 'size': 0x00A8, 'padding': 0x00, 'name': "action__FP10e_gs_class", 'reference_count': 1, 'type': "Function"},
	'daE_GS_Execute__FP10e_gs_class': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".text", 'addr': 0x806DF874, 'size': 0x01D4, 'padding': 0x00, 'name': "daE_GS_Execute__FP10e_gs_class", 'reference_count': 2, 'type': "Function"},
	'daE_GS_IsDelete__FP10e_gs_class': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".text", 'addr': 0x806DFA48, 'size': 0x0008, 'padding': 0x00, 'name': "daE_GS_IsDelete__FP10e_gs_class", 'reference_count': 1, 'type': "Function"},
	'daE_GS_Delete__FP10e_gs_class': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".text", 'addr': 0x806DFA50, 'size': 0x0068, 'padding': 0x00, 'name': "daE_GS_Delete__FP10e_gs_class", 'reference_count': 1, 'type': "Function"},
	'useHeapInit__FP10fopAc_ac_c': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".text", 'addr': 0x806DFAB8, 'size': 0x0148, 'padding': 0x00, 'name': "useHeapInit__FP10fopAc_ac_c", 'reference_count': 0, 'type': "Function"},
	'daE_GS_Create__FP10fopAc_ac_c': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".text", 'addr': 0x806DFC00, 'size': 0x015C, 'padding': 0x00, 'name': "daE_GS_Create__FP10fopAc_ac_c", 'reference_count': 1, 'type': "Function"},
	'__dt__12daE_GS_HIO_cFv': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".text", 'addr': 0x806DFD5C, 'size': 0x0048, 'padding': 0x00, 'name': "__dt__12daE_GS_HIO_cFv", 'reference_count': 0, 'type': "Function"},
	'__sinit_d_a_e_gs_cpp': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".text", 'addr': 0x806DFDA4, 'size': 0x003C, 'padding': 0x00, 'name': "__sinit_d_a_e_gs_cpp", 'reference_count': 1, 'type': "Function"},
	'data_806DFDE0': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "unknown_translation_unit_ctors", 'section': ".ctors", 'addr': 0x806DFDE0, 'size': 0x0008, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "ReferenceArray"},
	'__destroy_global_chain_reference': {'library': "Runtime.PPCEABI.H", 'translation_unit': "global_destructor_chain", 'section': ".dtors", 'addr': 0x806DFDE8, 'size': 0x0004, 'padding': 0x00, 'name': "__destroy_global_chain_reference", 'reference_count': 0, 'type': "ReferenceArray"},
	'pad_806DFDEC': {'library': "Runtime.PPCEABI.H", 'translation_unit': "global_destructor_chain", 'section': ".dtors", 'addr': 0x806DFDEC, 'size': 0x0008, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "ReferenceArray"},
	'lit_3646': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".rodata", 'addr': 0x806DFDF4, 'size': 0x0004, 'padding': 0x00, 'name': "@3646", 'reference_count': 0, 'type': "Integer"},
	'lit_3647': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".rodata", 'addr': 0x806DFDF8, 'size': 0x0004, 'padding': 0x00, 'name': "@3647", 'reference_count': 0, 'type': "Integer"},
	'lit_3648': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".rodata", 'addr': 0x806DFDFC, 'size': 0x0004, 'padding': 0x00, 'name': "@3648", 'reference_count': 0, 'type': "Integer"},
	'lit_3649': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".rodata", 'addr': 0x806DFE00, 'size': 0x0004, 'padding': 0x00, 'name': "@3649", 'reference_count': 0, 'type': "Integer"},
	'lit_3663': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".rodata", 'addr': 0x806DFE04, 'size': 0x0004, 'padding': 0x00, 'name': "@3663", 'reference_count': 0, 'type': "InitData"},
	'lit_3664': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".rodata", 'addr': 0x806DFE08, 'size': 0x0004, 'padding': 0x00, 'name': "@3664", 'reference_count': 0, 'type': "Integer"},
	'lit_3687': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".rodata", 'addr': 0x806DFE0C, 'size': 0x0004, 'padding': 0x00, 'name': "@3687", 'reference_count': 0, 'type': "Integer"},
	'lit_3715': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".rodata", 'addr': 0x806DFE10, 'size': 0x0004, 'padding': 0x00, 'name': "@3715", 'reference_count': 0, 'type': "Integer"},
	'lit_3716': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".rodata", 'addr': 0x806DFE14, 'size': 0x0004, 'padding': 0x00, 'name': "@3716", 'reference_count': 0, 'type': "Integer"},
	'lit_3717': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".rodata", 'addr': 0x806DFE18, 'size': 0x0004, 'padding': 0x00, 'name': "@3717", 'reference_count': 0, 'type': "Integer"},
	'lit_3718': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".rodata", 'addr': 0x806DFE1C, 'size': 0x0004, 'padding': 0x00, 'name': "@3718", 'reference_count': 0, 'type': "Integer"},
	'lit_3789': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".rodata", 'addr': 0x806DFE20, 'size': 0x0004, 'padding': 0x00, 'name': "@3789", 'reference_count': 0, 'type': "Integer"},
	'lit_3893': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".rodata", 'addr': 0x806DFE24, 'size': 0x0004, 'padding': 0x00, 'name': "@3893", 'reference_count': 0, 'type': "Integer"},
	'lit_3894': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".rodata", 'addr': 0x806DFE28, 'size': 0x0004, 'padding': 0x00, 'name': "@3894", 'reference_count': 0, 'type': "Integer"},
	'stringBase0': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".rodata", 'addr': 0x806DFE2C, 'size': 0x0005, 'padding': 0x00, 'name': "@stringBase0", 'reference_count': 0, 'type': "StringBase"},
	'l_daE_GS_Method': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".data", 'addr': 0x806DFE34, 'size': 0x0020, 'padding': 0x00, 'name': "l_daE_GS_Method", 'reference_count': 1, 'type': "ReferenceArray"},
	'g_profile_E_GS': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".data", 'addr': 0x806DFE54, 'size': 0x0030, 'padding': 0x00, 'name': "g_profile_E_GS", 'reference_count': 0, 'type': "ReferenceArray"},
	'__vt__12daE_GS_HIO_c': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".data", 'addr': 0x806DFE84, 'size': 0x000C, 'padding': 0x00, 'name': "__vt__12daE_GS_HIO_c", 'reference_count': 0, 'type': "VirtualTable"},
	'__global_destructor_chain': {'library': "Runtime.PPCEABI.H", 'translation_unit': "global_destructor_chain", 'section': ".bss", 'addr': 0x806DFEAC, 'size': 0x0004, 'padding': 0x04, 'name': "__global_destructor_chain", 'reference_count': 0, 'type': "ZeroData"},
	'data_806DFEB4': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".bss", 'addr': 0x806DFEB4, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "ZeroData"},
	'lit_3641': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".bss", 'addr': 0x806DFEB8, 'size': 0x000C, 'padding': 0x00, 'name': "@3641", 'reference_count': 0, 'type': "ZeroData"},
	'l_HIO': {'library': "d/a/e/d_a_e_gs", 'translation_unit': "d_a_e_gs", 'section': ".bss", 'addr': 0x806DFEC4, 'size': 0x001C, 'padding': 0x00, 'name': "l_HIO", 'reference_count': 0, 'type': "ZeroData"},
}
