#
# Generate By: dol2asm
# Module: 441
#

SYMBOLS = {
	'_prolog': {'library': "d/a/obj/d_a_obj_enemy_create", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80BE3100, 'size': 0x002C, 'padding': 0x00, 'name': "_prolog", 'reference_count': 0, 'type': "Function"},
	'_epilog': {'library': "d/a/obj/d_a_obj_enemy_create", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80BE312C, 'size': 0x002C, 'padding': 0x00, 'name': "_epilog", 'reference_count': 0, 'type': "Function"},
	'_unresolved': {'library': "d/a/obj/d_a_obj_enemy_create", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80BE3158, 'size': 0x0020, 'padding': 0x00, 'name': "_unresolved", 'reference_count': 6, 'type': "Function"},
	'daObjE_CREATE_Create__FP10fopAc_ac_c': {'library': "d/a/obj/d_a_obj_enemy_create", 'translation_unit': "d_a_obj_enemy_create", 'section': ".text", 'addr': 0x80BE3178, 'size': 0x0020, 'padding': 0x00, 'name': "daObjE_CREATE_Create__FP10fopAc_ac_c", 'reference_count': 1, 'type': "Function"},
	'daObjE_CREATE_Delete__FP15daObjE_CREATE_c': {'library': "d/a/obj/d_a_obj_enemy_create", 'translation_unit': "d_a_obj_enemy_create", 'section': ".text", 'addr': 0x80BE3198, 'size': 0x0024, 'padding': 0x00, 'name': "daObjE_CREATE_Delete__FP15daObjE_CREATE_c", 'reference_count': 1, 'type': "Function"},
	'NormalAction__15daObjE_CREATE_cFv': {'library': "d/a/obj/d_a_obj_enemy_create", 'translation_unit': "d_a_obj_enemy_create", 'section': ".text", 'addr': 0x80BE31BC, 'size': 0x02A0, 'padding': 0x00, 'name': "NormalAction__15daObjE_CREATE_cFv", 'reference_count': 3, 'type': "Function"},
	'SearchAction__15daObjE_CREATE_cFv': {'library': "d/a/obj/d_a_obj_enemy_create", 'translation_unit': "d_a_obj_enemy_create", 'section': ".text", 'addr': 0x80BE345C, 'size': 0x0044, 'padding': 0x00, 'name': "SearchAction__15daObjE_CREATE_cFv", 'reference_count': 1, 'type': "Function"},
	'LoopAction__15daObjE_CREATE_cFv': {'library': "d/a/obj/d_a_obj_enemy_create", 'translation_unit': "d_a_obj_enemy_create", 'section': ".text", 'addr': 0x80BE34A0, 'size': 0x00A4, 'padding': 0x00, 'name': "LoopAction__15daObjE_CREATE_cFv", 'reference_count': 1, 'type': "Function"},
	'Action__15daObjE_CREATE_cFv': {'library': "d/a/obj/d_a_obj_enemy_create", 'translation_unit': "d_a_obj_enemy_create", 'section': ".text", 'addr': 0x80BE3544, 'size': 0x0058, 'padding': 0x00, 'name': "Action__15daObjE_CREATE_cFv", 'reference_count': 1, 'type': "Function"},
	'Execute__15daObjE_CREATE_cFv': {'library': "d/a/obj/d_a_obj_enemy_create", 'translation_unit': "d_a_obj_enemy_create", 'section': ".text", 'addr': 0x80BE359C, 'size': 0x0024, 'padding': 0x00, 'name': "Execute__15daObjE_CREATE_cFv", 'reference_count': 1, 'type': "Function"},
	'Delete__15daObjE_CREATE_cFv': {'library': "d/a/obj/d_a_obj_enemy_create", 'translation_unit': "d_a_obj_enemy_create", 'section': ".text", 'addr': 0x80BE35C0, 'size': 0x0030, 'padding': 0x00, 'name': "Delete__15daObjE_CREATE_cFv", 'reference_count': 1, 'type': "Function"},
	'daObjE_CREATE_Draw__FP15daObjE_CREATE_c': {'library': "d/a/obj/d_a_obj_enemy_create", 'translation_unit': "d_a_obj_enemy_create", 'section': ".text", 'addr': 0x80BE35F0, 'size': 0x0008, 'padding': 0x00, 'name': "daObjE_CREATE_Draw__FP15daObjE_CREATE_c", 'reference_count': 1, 'type': "Function"},
	'daObjE_CREATE_Execute__FP15daObjE_CREATE_c': {'library': "d/a/obj/d_a_obj_enemy_create", 'translation_unit': "d_a_obj_enemy_create", 'section': ".text", 'addr': 0x80BE35F8, 'size': 0x0020, 'padding': 0x00, 'name': "daObjE_CREATE_Execute__FP15daObjE_CREATE_c", 'reference_count': 1, 'type': "Function"},
	'NameChk__15daObjE_CREATE_cFv': {'library': "d/a/obj/d_a_obj_enemy_create", 'translation_unit': "d_a_obj_enemy_create", 'section': ".text", 'addr': 0x80BE3618, 'size': 0x0158, 'padding': 0x00, 'name': "NameChk__15daObjE_CREATE_cFv", 'reference_count': 2, 'type': "Function"},
	'create__15daObjE_CREATE_cFv': {'library': "d/a/obj/d_a_obj_enemy_create", 'translation_unit': "d_a_obj_enemy_create", 'section': ".text", 'addr': 0x80BE3770, 'size': 0x0108, 'padding': 0x00, 'name': "create__15daObjE_CREATE_cFv", 'reference_count': 1, 'type': "Function"},
	'daObjE_CREATE_IsDelete__FP15daObjE_CREATE_c': {'library': "d/a/obj/d_a_obj_enemy_create", 'translation_unit': "d_a_obj_enemy_create", 'section': ".text", 'addr': 0x80BE3878, 'size': 0x0008, 'padding': 0x00, 'name': "daObjE_CREATE_IsDelete__FP15daObjE_CREATE_c", 'reference_count': 1, 'type': "Function"},
	'data_80BE3880': {'library': "d/a/obj/d_a_obj_enemy_create", 'translation_unit': "unknown_translation_unit_ctors", 'section': ".ctors", 'addr': 0x80BE3880, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'data_80BE3884': {'library': "d/a/obj/d_a_obj_enemy_create", 'translation_unit': "unknown_translation_unit_dtors", 'section': ".dtors", 'addr': 0x80BE3884, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'lit_3720': {'library': "d/a/obj/d_a_obj_enemy_create", 'translation_unit': "d_a_obj_enemy_create", 'section': ".rodata", 'addr': 0x80BE388C, 'size': 0x0004, 'padding': 0x00, 'name': "@3720", 'reference_count': 0, 'type': "InitData"},
	'lit_3721': {'library': "d/a/obj/d_a_obj_enemy_create", 'translation_unit': "d_a_obj_enemy_create", 'section': ".rodata", 'addr': 0x80BE3890, 'size': 0x0004, 'padding': 0x00, 'name': "@3721", 'reference_count': 0, 'type': "Integer"},
	'lit_3722': {'library': "d/a/obj/d_a_obj_enemy_create", 'translation_unit': "d_a_obj_enemy_create", 'section': ".rodata", 'addr': 0x80BE3894, 'size': 0x0004, 'padding': 0x04, 'name': "@3722", 'reference_count': 0, 'type': "Integer"},
	'lit_3724': {'library': "d/a/obj/d_a_obj_enemy_create", 'translation_unit': "d_a_obj_enemy_create", 'section': ".rodata", 'addr': 0x80BE389C, 'size': 0x0008, 'padding': 0x00, 'name': "@3724", 'reference_count': 0, 'type': "InitData"},
	'lit_3838': {'library': "d/a/obj/d_a_obj_enemy_create", 'translation_unit': "d_a_obj_enemy_create", 'section': ".data", 'addr': 0x80BE38A4, 'size': 0x0034, 'padding': 0x00, 'name': "@3838", 'reference_count': 0, 'type': "ReferenceArray"},
	'l_daObjE_CREATE_Method': {'library': "d/a/obj/d_a_obj_enemy_create", 'translation_unit': "d_a_obj_enemy_create", 'section': ".data", 'addr': 0x80BE38D8, 'size': 0x0020, 'padding': 0x00, 'name': "l_daObjE_CREATE_Method", 'reference_count': 1, 'type': "ReferenceArray"},
	'g_profile_Obj_E_CREATE': {'library': "d/a/obj/d_a_obj_enemy_create", 'translation_unit': "d_a_obj_enemy_create", 'section': ".data", 'addr': 0x80BE38F8, 'size': 0x0030, 'padding': 0x00, 'name': "g_profile_Obj_E_CREATE", 'reference_count': 0, 'type': "ReferenceArray"},
}
