#
# Generate By: dol2asm
# Module: 708
#

SYMBOLS = {
	'_prolog': {'library': "d/a/d_a_swLBall", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80D4EA80, 'size': 0x002C, 'padding': 0x00, 'name': "_prolog", 'reference_count': 0, 'type': "Function"},
	'_epilog': {'library': "d/a/d_a_swLBall", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80D4EAAC, 'size': 0x002C, 'padding': 0x00, 'name': "_epilog", 'reference_count': 0, 'type': "Function"},
	'_unresolved': {'library': "d/a/d_a_swLBall", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80D4EAD8, 'size': 0x0020, 'padding': 0x00, 'name': "_unresolved", 'reference_count': 11, 'type': "Function"},
	's_lb_sub__FPvPv': {'library': "d/a/d_a_swLBall", 'translation_unit': "d_a_swLBall", 'section': ".text", 'addr': 0x80D4EAF8, 'size': 0x0094, 'padding': 0x00, 'name': "s_lb_sub__FPvPv", 'reference_count': 0, 'type': "Function"},
	'checkArea_sub__11daSwLBall_cFP10fopAc_ac_c': {'library': "d/a/d_a_swLBall", 'translation_unit': "d_a_swLBall", 'section': ".text", 'addr': 0x80D4EB8C, 'size': 0x0140, 'padding': 0x00, 'name': "checkArea_sub__11daSwLBall_cFP10fopAc_ac_c", 'reference_count': 2, 'type': "Function"},
	'checkArea__11daSwLBall_cFv': {'library': "d/a/d_a_swLBall", 'translation_unit': "d_a_swLBall", 'section': ".text", 'addr': 0x80D4ECCC, 'size': 0x00B4, 'padding': 0x00, 'name': "checkArea__11daSwLBall_cFv", 'reference_count': 1, 'type': "Function"},
	'search_lb__11daSwLBall_cFv': {'library': "d/a/d_a_swLBall", 'translation_unit': "d_a_swLBall", 'section': ".text", 'addr': 0x80D4ED80, 'size': 0x012C, 'padding': 0x00, 'name': "search_lb__11daSwLBall_cFv", 'reference_count': 2, 'type': "Function"},
	'Create__11daSwLBall_cFv': {'library': "d/a/d_a_swLBall", 'translation_unit': "d_a_swLBall", 'section': ".text", 'addr': 0x80D4EEAC, 'size': 0x004C, 'padding': 0x00, 'name': "Create__11daSwLBall_cFv", 'reference_count': 1, 'type': "Function"},
	'create__11daSwLBall_cFv': {'library': "d/a/d_a_swLBall", 'translation_unit': "d_a_swLBall", 'section': ".text", 'addr': 0x80D4EEF8, 'size': 0x0068, 'padding': 0x00, 'name': "create__11daSwLBall_cFv", 'reference_count': 1, 'type': "Function"},
	'execute__11daSwLBall_cFv': {'library': "d/a/d_a_swLBall", 'translation_unit': "d_a_swLBall", 'section': ".text", 'addr': 0x80D4EF60, 'size': 0x00A8, 'padding': 0x00, 'name': "execute__11daSwLBall_cFv", 'reference_count': 2, 'type': "Function"},
	'actionInit__11daSwLBall_cFv': {'library': "d/a/d_a_swLBall", 'translation_unit': "d_a_swLBall", 'section': ".text", 'addr': 0x80D4F008, 'size': 0x0078, 'padding': 0x00, 'name': "actionInit__11daSwLBall_cFv", 'reference_count': 1, 'type': "Function"},
	'actionRun__11daSwLBall_cFv': {'library': "d/a/d_a_swLBall", 'translation_unit': "d_a_swLBall", 'section': ".text", 'addr': 0x80D4F080, 'size': 0x01A0, 'padding': 0x00, 'name': "actionRun__11daSwLBall_cFv", 'reference_count': 1, 'type': "Function"},
	'actionStop__11daSwLBall_cFv': {'library': "d/a/d_a_swLBall", 'translation_unit': "d_a_swLBall", 'section': ".text", 'addr': 0x80D4F220, 'size': 0x0004, 'padding': 0x00, 'name': "actionStop__11daSwLBall_cFv", 'reference_count': 1, 'type': "Function"},
	'PutCrrPos__11daSwLBall_cFv': {'library': "d/a/d_a_swLBall", 'translation_unit': "d_a_swLBall", 'section': ".text", 'addr': 0x80D4F224, 'size': 0x0220, 'padding': 0x00, 'name': "PutCrrPos__11daSwLBall_cFv", 'reference_count': 1, 'type': "Function"},
	'_delete__11daSwLBall_cFv': {'library': "d/a/d_a_swLBall", 'translation_unit': "d_a_swLBall", 'section': ".text", 'addr': 0x80D4F444, 'size': 0x0008, 'padding': 0x00, 'name': "_delete__11daSwLBall_cFv", 'reference_count': 1, 'type': "Function"},
	'daSwLBall_Execute__FP11daSwLBall_c': {'library': "d/a/d_a_swLBall", 'translation_unit': "d_a_swLBall", 'section': ".text", 'addr': 0x80D4F44C, 'size': 0x0020, 'padding': 0x00, 'name': "daSwLBall_Execute__FP11daSwLBall_c", 'reference_count': 1, 'type': "Function"},
	'daSwLBall_Delete__FP11daSwLBall_c': {'library': "d/a/d_a_swLBall", 'translation_unit': "d_a_swLBall", 'section': ".text", 'addr': 0x80D4F46C, 'size': 0x0020, 'padding': 0x00, 'name': "daSwLBall_Delete__FP11daSwLBall_c", 'reference_count': 1, 'type': "Function"},
	'daSwLBall_Create__FP10fopAc_ac_c': {'library': "d/a/d_a_swLBall", 'translation_unit': "d_a_swLBall", 'section': ".text", 'addr': 0x80D4F48C, 'size': 0x0020, 'padding': 0x00, 'name': "daSwLBall_Create__FP10fopAc_ac_c", 'reference_count': 1, 'type': "Function"},
	'func_80D4F4AC': {'library': "d/a/d_a_swLBall", 'translation_unit': "d_a_swLBall", 'section': ".text", 'addr': 0x80D4F4AC, 'size': 0x001C, 'padding': 0x00, 'name': "cLib_calcTimer<Uc>__FPUc", 'reference_count': 1, 'type': "Function"},
	'data_80D4F4C8': {'library': "d/a/d_a_swLBall", 'translation_unit': "unknown_translation_unit_ctors", 'section': ".ctors", 'addr': 0x80D4F4C8, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'data_80D4F4CC': {'library': "d/a/d_a_swLBall", 'translation_unit': "unknown_translation_unit_dtors", 'section': ".dtors", 'addr': 0x80D4F4CC, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'lit_3723': {'library': "d/a/d_a_swLBall", 'translation_unit': "d_a_swLBall", 'section': ".rodata", 'addr': 0x80D4F4D4, 'size': 0x0004, 'padding': 0x00, 'name': "@3723", 'reference_count': 0, 'type': "Integer"},
	'lit_3724': {'library': "d/a/d_a_swLBall", 'translation_unit': "d_a_swLBall", 'section': ".rodata", 'addr': 0x80D4F4D8, 'size': 0x0004, 'padding': 0x00, 'name': "@3724", 'reference_count': 0, 'type': "Integer"},
	'lit_3725': {'library': "d/a/d_a_swLBall", 'translation_unit': "d_a_swLBall", 'section': ".rodata", 'addr': 0x80D4F4DC, 'size': 0x0004, 'padding': 0x00, 'name': "@3725", 'reference_count': 0, 'type': "Integer"},
	'lit_3726': {'library': "d/a/d_a_swLBall", 'translation_unit': "d_a_swLBall", 'section': ".rodata", 'addr': 0x80D4F4E0, 'size': 0x0004, 'padding': 0x00, 'name': "@3726", 'reference_count': 0, 'type': "InitData"},
	'lit_4000': {'library': "d/a/d_a_swLBall", 'translation_unit': "d_a_swLBall", 'section': ".rodata", 'addr': 0x80D4F4E4, 'size': 0x0004, 'padding': 0x00, 'name': "@4000", 'reference_count': 0, 'type': "Integer"},
	'cNullVec__6Z2Calc': {'library': "d/a/d_a_swLBall", 'translation_unit': "d_a_swLBall", 'section': ".data", 'addr': 0x80D4F4EC, 'size': 0x000C, 'padding': 0x00, 'name': "cNullVec__6Z2Calc", 'reference_count': 0, 'type': "InitData"},
	'lit_1787': {'library': "d/a/d_a_swLBall", 'translation_unit': "d_a_swLBall", 'section': ".data", 'addr': 0x80D4F4F8, 'size': 0x0004, 'padding': 0x10, 'name': "@1787", 'reference_count': 0, 'type': "Integer"},
	'lit_3835': {'library': "d/a/d_a_swLBall", 'translation_unit': "d_a_swLBall", 'section': ".data", 'addr': 0x80D4F50C, 'size': 0x000C, 'padding': 0x00, 'name': "@3835", 'reference_count': 0, 'type': "ReferenceArray"},
	'lit_3836': {'library': "d/a/d_a_swLBall", 'translation_unit': "d_a_swLBall", 'section': ".data", 'addr': 0x80D4F518, 'size': 0x000C, 'padding': 0x00, 'name': "@3836", 'reference_count': 0, 'type': "ReferenceArray"},
	'lit_3837': {'library': "d/a/d_a_swLBall", 'translation_unit': "d_a_swLBall", 'section': ".data", 'addr': 0x80D4F524, 'size': 0x000C, 'padding': 0x00, 'name': "@3837", 'reference_count': 0, 'type': "ReferenceArray"},
	'data_80D4F530': {'library': "d/a/d_a_swLBall", 'translation_unit': "d_a_swLBall", 'section': ".data", 'addr': 0x80D4F530, 'size': 0x0024, 'padding': 0x00, 'name': "l_func$3834", 'reference_count': 0, 'type': "InitData"},
	'l_daSwLBall_Method': {'library': "d/a/d_a_swLBall", 'translation_unit': "d_a_swLBall", 'section': ".data", 'addr': 0x80D4F554, 'size': 0x0020, 'padding': 0x00, 'name': "l_daSwLBall_Method", 'reference_count': 1, 'type': "ReferenceArray"},
	'g_profile_SwLBall': {'library': "d/a/d_a_swLBall", 'translation_unit': "d_a_swLBall", 'section': ".data", 'addr': 0x80D4F574, 'size': 0x0030, 'padding': 0x00, 'name': "g_profile_SwLBall", 'reference_count': 0, 'type': "ReferenceArray"},
	'l_target_info': {'library': "d/a/d_a_swLBall", 'translation_unit': "d_a_swLBall", 'section': ".bss", 'addr': 0x80D4F5BC, 'size': 0x0008, 'padding': 0x00, 'name': "l_target_info", 'reference_count': 0, 'type': "ZeroData"},
	'l_target_info_count': {'library': "d/a/d_a_swLBall", 'translation_unit': "d_a_swLBall", 'section': ".bss", 'addr': 0x80D4F5C4, 'size': 0x0004, 'padding': 0x00, 'name': "l_target_info_count", 'reference_count': 0, 'type': "ZeroData"},
	'data_80D4F5C8': {'library': "d/a/d_a_swLBall", 'translation_unit': "d_a_swLBall", 'section': ".bss", 'addr': 0x80D4F5C8, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "ZeroData"},
}
