#
# Generate By: dol2asm
# Module: 106
#

SYMBOLS = {
	'_prolog': {'library': "d/a/obj/d_a_obj_metalbox", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80592E20, 'size': 0x002C, 'padding': 0x00, 'name': "_prolog", 'reference_count': 0, 'type': "Function"},
	'_epilog': {'library': "d/a/obj/d_a_obj_metalbox", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80592E4C, 'size': 0x002C, 'padding': 0x00, 'name': "_epilog", 'reference_count': 0, 'type': "Function"},
	'_unresolved': {'library': "d/a/obj/d_a_obj_metalbox", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80592E78, 'size': 0x0020, 'padding': 0x00, 'name': "_unresolved", 'reference_count': 13, 'type': "Function"},
	'initBaseMtx__11daObjMBox_cFv': {'library': "d/a/obj/d_a_obj_metalbox", 'translation_unit': "d_a_obj_metalbox", 'section': ".text", 'addr': 0x80592E98, 'size': 0x003C, 'padding': 0x00, 'name': "initBaseMtx__11daObjMBox_cFv", 'reference_count': 1, 'type': "Function"},
	'setBaseMtx__11daObjMBox_cFv': {'library': "d/a/obj/d_a_obj_metalbox", 'translation_unit': "d_a_obj_metalbox", 'section': ".text", 'addr': 0x80592ED4, 'size': 0x0074, 'padding': 0x00, 'name': "setBaseMtx__11daObjMBox_cFv", 'reference_count': 2, 'type': "Function"},
	'Create__11daObjMBox_cFv': {'library': "d/a/obj/d_a_obj_metalbox", 'translation_unit': "d_a_obj_metalbox", 'section': ".text", 'addr': 0x80592F48, 'size': 0x008C, 'padding': 0x00, 'name': "Create__11daObjMBox_cFv", 'reference_count': 0, 'type': "Function"},
	'CreateHeap__11daObjMBox_cFv': {'library': "d/a/obj/d_a_obj_metalbox", 'translation_unit': "d_a_obj_metalbox", 'section': ".text", 'addr': 0x80592FD4, 'size': 0x0070, 'padding': 0x00, 'name': "CreateHeap__11daObjMBox_cFv", 'reference_count': 0, 'type': "Function"},
	'create__11daObjMBox_cFv': {'library': "d/a/obj/d_a_obj_metalbox", 'translation_unit': "d_a_obj_metalbox", 'section': ".text", 'addr': 0x80593044, 'size': 0x0180, 'padding': 0x00, 'name': "create__11daObjMBox_cFv", 'reference_count': 1, 'type': "Function"},
	'__dt__8cM3dGCylFv': {'library': "d/a/obj/d_a_obj_metalbox", 'translation_unit': "d_a_obj_metalbox", 'section': ".text", 'addr': 0x805931C4, 'size': 0x0048, 'padding': 0x00, 'name': "__dt__8cM3dGCylFv", 'reference_count': 0, 'type': "Function"},
	'__dt__8cM3dGAabFv': {'library': "d/a/obj/d_a_obj_metalbox", 'translation_unit': "d_a_obj_metalbox", 'section': ".text", 'addr': 0x8059320C, 'size': 0x0048, 'padding': 0x00, 'name': "__dt__8cM3dGAabFv", 'reference_count': 0, 'type': "Function"},
	'__dt__12dBgS_ObjAcchFv': {'library': "d/a/obj/d_a_obj_metalbox", 'translation_unit': "d_a_obj_metalbox", 'section': ".text", 'addr': 0x80593254, 'size': 0x0070, 'padding': 0x00, 'name': "__dt__12dBgS_ObjAcchFv", 'reference_count': 2, 'type': "Function"},
	'Execute__11daObjMBox_cFPPA3_A4_f': {'library': "d/a/obj/d_a_obj_metalbox", 'translation_unit': "d_a_obj_metalbox", 'section': ".text", 'addr': 0x805932C4, 'size': 0x002C, 'padding': 0x00, 'name': "Execute__11daObjMBox_cFPPA3_A4_f", 'reference_count': 0, 'type': "Function"},
	'Draw__11daObjMBox_cFv': {'library': "d/a/obj/d_a_obj_metalbox", 'translation_unit': "d_a_obj_metalbox", 'section': ".text", 'addr': 0x805932F0, 'size': 0x00A4, 'padding': 0x00, 'name': "Draw__11daObjMBox_cFv", 'reference_count': 0, 'type': "Function"},
	'Delete__11daObjMBox_cFv': {'library': "d/a/obj/d_a_obj_metalbox", 'translation_unit': "d_a_obj_metalbox", 'section': ".text", 'addr': 0x80593394, 'size': 0x0034, 'padding': 0x00, 'name': "Delete__11daObjMBox_cFv", 'reference_count': 0, 'type': "Function"},
	'daObjMBox_Draw__FP11daObjMBox_c': {'library': "d/a/obj/d_a_obj_metalbox", 'translation_unit': "d_a_obj_metalbox", 'section': ".text", 'addr': 0x805933C8, 'size': 0x002C, 'padding': 0x00, 'name': "daObjMBox_Draw__FP11daObjMBox_c", 'reference_count': 1, 'type': "Function"},
	'daObjMBox_Execute__FP11daObjMBox_c': {'library': "d/a/obj/d_a_obj_metalbox", 'translation_unit': "d_a_obj_metalbox", 'section': ".text", 'addr': 0x805933F4, 'size': 0x0020, 'padding': 0x00, 'name': "daObjMBox_Execute__FP11daObjMBox_c", 'reference_count': 1, 'type': "Function"},
	'daObjMBox_Delete__FP11daObjMBox_c': {'library': "d/a/obj/d_a_obj_metalbox", 'translation_unit': "d_a_obj_metalbox", 'section': ".text", 'addr': 0x80593414, 'size': 0x0020, 'padding': 0x00, 'name': "daObjMBox_Delete__FP11daObjMBox_c", 'reference_count': 1, 'type': "Function"},
	'daObjMBox_Create__FP10fopAc_ac_c': {'library': "d/a/obj/d_a_obj_metalbox", 'translation_unit': "d_a_obj_metalbox", 'section': ".text", 'addr': 0x80593434, 'size': 0x0020, 'padding': 0x00, 'name': "daObjMBox_Create__FP10fopAc_ac_c", 'reference_count': 1, 'type': "Function"},
	'func_80593454': {'library': "d/a/obj/d_a_obj_metalbox", 'translation_unit': "d_a_obj_metalbox", 'section': ".text", 'addr': 0x80593454, 'size': 0x0008, 'padding': 0x00, 'name': "@36@__dt__12dBgS_ObjAcchFv", 'reference_count': 0, 'type': "Function"},
	'func_8059345C': {'library': "d/a/obj/d_a_obj_metalbox", 'translation_unit': "d_a_obj_metalbox", 'section': ".text", 'addr': 0x8059345C, 'size': 0x0008, 'padding': 0x00, 'name': "@20@__dt__12dBgS_ObjAcchFv", 'reference_count': 0, 'type': "Function"},
	'data_80593464': {'library': "d/a/obj/d_a_obj_metalbox", 'translation_unit': "unknown_translation_unit_ctors", 'section': ".ctors", 'addr': 0x80593464, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'data_80593468': {'library': "d/a/obj/d_a_obj_metalbox", 'translation_unit': "unknown_translation_unit_dtors", 'section': ".dtors", 'addr': 0x80593468, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'lit_3655': {'library': "d/a/obj/d_a_obj_metalbox", 'translation_unit': "d_a_obj_metalbox", 'section': ".rodata", 'addr': 0x8059346C, 'size': 0x0004, 'padding': 0x00, 'name': "@3655", 'reference_count': 0, 'type': "Integer"},
	'stringBase0': {'library': "d/a/obj/d_a_obj_metalbox", 'translation_unit': "d_a_obj_metalbox", 'section': ".rodata", 'addr': 0x80593470, 'size': 0x000A, 'padding': 0x00, 'name': "@stringBase0", 'reference_count': 1, 'type': "StringBase"},
	'l_arcName': {'library': "d/a/obj/d_a_obj_metalbox", 'translation_unit': "d_a_obj_metalbox", 'section': ".data", 'addr': 0x8059347C, 'size': 0x0004, 'padding': 0x00, 'name': "l_arcName", 'reference_count': 0, 'type': "ReferenceArray"},
	'l_daObjMBox_Method': {'library': "d/a/obj/d_a_obj_metalbox", 'translation_unit': "d_a_obj_metalbox", 'section': ".data", 'addr': 0x80593480, 'size': 0x0020, 'padding': 0x00, 'name': "l_daObjMBox_Method", 'reference_count': 1, 'type': "ReferenceArray"},
	'g_profile_Obj_MetalBox': {'library': "d/a/obj/d_a_obj_metalbox", 'translation_unit': "d_a_obj_metalbox", 'section': ".data", 'addr': 0x805934A0, 'size': 0x0030, 'padding': 0x00, 'name': "g_profile_Obj_MetalBox", 'reference_count': 0, 'type': "ReferenceArray"},
	'__vt__8cM3dGCyl': {'library': "d/a/obj/d_a_obj_metalbox", 'translation_unit': "d_a_obj_metalbox", 'section': ".data", 'addr': 0x805934D0, 'size': 0x000C, 'padding': 0x00, 'name': "__vt__8cM3dGCyl", 'reference_count': 0, 'type': "VirtualTable"},
	'__vt__8cM3dGAab': {'library': "d/a/obj/d_a_obj_metalbox", 'translation_unit': "d_a_obj_metalbox", 'section': ".data", 'addr': 0x805934DC, 'size': 0x000C, 'padding': 0x00, 'name': "__vt__8cM3dGAab", 'reference_count': 0, 'type': "VirtualTable"},
	'__vt__12dBgS_ObjAcch': {'library': "d/a/obj/d_a_obj_metalbox", 'translation_unit': "d_a_obj_metalbox", 'section': ".data", 'addr': 0x805934E8, 'size': 0x0024, 'padding': 0x00, 'name': "__vt__12dBgS_ObjAcch", 'reference_count': 0, 'type': "VirtualTable"},
	'__vt__11daObjMBox_c': {'library': "d/a/obj/d_a_obj_metalbox", 'translation_unit': "d_a_obj_metalbox", 'section': ".data", 'addr': 0x8059350C, 'size': 0x0028, 'padding': 0x00, 'name': "__vt__11daObjMBox_c", 'reference_count': 0, 'type': "VirtualTable"},
}
