#
# Generate By: dol2asm
# Module: 136
#

SYMBOLS = {
	'_prolog': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "executor", 'section': ".text", 'addr': 0x805AA580, 'size': 0x002C, 'padding': 0x00, 'name': "_prolog", 'reference_count': 0, 'type': "Function"},
	'_epilog': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "executor", 'section': ".text", 'addr': 0x805AA5AC, 'size': 0x002C, 'padding': 0x00, 'name': "_epilog", 'reference_count': 0, 'type': "Function"},
	'_unresolved': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "executor", 'section': ".text", 'addr': 0x805AA5D8, 'size': 0x0020, 'padding': 0x00, 'name': "_unresolved", 'reference_count': 10, 'type': "Function"},
	'setAction__11daL7lowDr_cFM11daL7lowDr_cFPCvPv_v': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".text", 'addr': 0x805AA5F8, 'size': 0x00A4, 'padding': 0x00, 'name': "setAction__11daL7lowDr_cFM11daL7lowDr_cFPCvPv_v", 'reference_count': 1, 'type': "Function"},
	'action__11daL7lowDr_cFv': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".text", 'addr': 0x805AA69C, 'size': 0x00AC, 'padding': 0x00, 'name': "action__11daL7lowDr_cFv", 'reference_count': 1, 'type': "Function"},
	'_delete__11daL7lowDr_cFv': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".text", 'addr': 0x805AA748, 'size': 0x0050, 'padding': 0x00, 'name': "_delete__11daL7lowDr_cFv", 'reference_count': 1, 'type': "Function"},
	'daL7lowDr_Delete__FP11daL7lowDr_c': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".text", 'addr': 0x805AA798, 'size': 0x0020, 'padding': 0x00, 'name': "daL7lowDr_Delete__FP11daL7lowDr_c", 'reference_count': 1, 'type': "Function"},
	'mtx_set__11daL7lowDr_cFv': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".text", 'addr': 0x805AA7B8, 'size': 0x0070, 'padding': 0x00, 'name': "mtx_set__11daL7lowDr_cFv", 'reference_count': 1, 'type': "Function"},
	'fly__11daL7lowDr_cFv': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".text", 'addr': 0x805AA828, 'size': 0x03D0, 'padding': 0x00, 'name': "fly__11daL7lowDr_cFv", 'reference_count': 1, 'type': "Function"},
	'execute__11daL7lowDr_cFv': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".text", 'addr': 0x805AABF8, 'size': 0x0024, 'padding': 0x00, 'name': "execute__11daL7lowDr_cFv", 'reference_count': 1, 'type': "Function"},
	'daL7lowDr_Execute__FP11daL7lowDr_c': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".text", 'addr': 0x805AAC1C, 'size': 0x0020, 'padding': 0x00, 'name': "daL7lowDr_Execute__FP11daL7lowDr_c", 'reference_count': 2, 'type': "Function"},
	'useHeapInit__FP10fopAc_ac_c': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".text", 'addr': 0x805AAC3C, 'size': 0x0020, 'padding': 0x00, 'name': "useHeapInit__FP10fopAc_ac_c", 'reference_count': 0, 'type': "Function"},
	'CreateHeap__11daL7lowDr_cFv': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".text", 'addr': 0x805AAC5C, 'size': 0x00FC, 'padding': 0x00, 'name': "CreateHeap__11daL7lowDr_cFv", 'reference_count': 1, 'type': "Function"},
	'create__11daL7lowDr_cFv': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".text", 'addr': 0x805AAD58, 'size': 0x0130, 'padding': 0x00, 'name': "create__11daL7lowDr_cFv", 'reference_count': 1, 'type': "Function"},
	'daL7lowDr_Create__FP11daL7lowDr_c': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".text", 'addr': 0x805AAE88, 'size': 0x0020, 'padding': 0x00, 'name': "daL7lowDr_Create__FP11daL7lowDr_c", 'reference_count': 1, 'type': "Function"},
	'draw__11daL7lowDr_cFv': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".text", 'addr': 0x805AAEA8, 'size': 0x009C, 'padding': 0x00, 'name': "draw__11daL7lowDr_cFv", 'reference_count': 1, 'type': "Function"},
	'daL7lowDr_Draw__FP11daL7lowDr_c': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".text", 'addr': 0x805AAF44, 'size': 0x0020, 'padding': 0x00, 'name': "daL7lowDr_Draw__FP11daL7lowDr_c", 'reference_count': 1, 'type': "Function"},
	'daL7lowDr_IsDelete__FP11daL7lowDr_c': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".text", 'addr': 0x805AAF64, 'size': 0x0008, 'padding': 0x00, 'name': "daL7lowDr_IsDelete__FP11daL7lowDr_c", 'reference_count': 1, 'type': "Function"},
	'data_805AAF6C': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "unknown_translation_unit_ctors", 'section': ".ctors", 'addr': 0x805AAF6C, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'data_805AAF70': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "unknown_translation_unit_dtors", 'section': ".dtors", 'addr': 0x805AAF70, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'lit_3769': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".rodata", 'addr': 0x805AAF74, 'size': 0x0004, 'padding': 0x00, 'name': "@3769", 'reference_count': 0, 'type': "Integer"},
	'lit_3770': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".rodata", 'addr': 0x805AAF78, 'size': 0x0004, 'padding': 0x00, 'name': "@3770", 'reference_count': 0, 'type': "Integer"},
	'lit_3771': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".rodata", 'addr': 0x805AAF7C, 'size': 0x0004, 'padding': 0x00, 'name': "@3771", 'reference_count': 0, 'type': "Integer"},
	'lit_3772': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".rodata", 'addr': 0x805AAF80, 'size': 0x0004, 'padding': 0x00, 'name': "@3772", 'reference_count': 0, 'type': "Integer"},
	'lit_3773': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".rodata", 'addr': 0x805AAF84, 'size': 0x0004, 'padding': 0x00, 'name': "@3773", 'reference_count': 0, 'type': "Integer"},
	'lit_3774': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".rodata", 'addr': 0x805AAF88, 'size': 0x0004, 'padding': 0x00, 'name': "@3774", 'reference_count': 0, 'type': "InitData"},
	'lit_3775': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".rodata", 'addr': 0x805AAF8C, 'size': 0x0004, 'padding': 0x00, 'name': "@3775", 'reference_count': 0, 'type': "Integer"},
	'lit_3776': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".rodata", 'addr': 0x805AAF90, 'size': 0x0004, 'padding': 0x00, 'name': "@3776", 'reference_count': 0, 'type': "Integer"},
	'lit_3777': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".rodata", 'addr': 0x805AAF94, 'size': 0x0004, 'padding': 0x00, 'name': "@3777", 'reference_count': 0, 'type': "Integer"},
	'lit_3778': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".rodata", 'addr': 0x805AAF98, 'size': 0x0004, 'padding': 0x00, 'name': "@3778", 'reference_count': 0, 'type': "Integer"},
	'lit_3779': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".rodata", 'addr': 0x805AAF9C, 'size': 0x0004, 'padding': 0x00, 'name': "@3779", 'reference_count': 0, 'type': "Integer"},
	'lit_3780': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".rodata", 'addr': 0x805AAFA0, 'size': 0x0004, 'padding': 0x00, 'name': "@3780", 'reference_count': 0, 'type': "Integer"},
	'lit_3781': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".rodata", 'addr': 0x805AAFA4, 'size': 0x0004, 'padding': 0x00, 'name': "@3781", 'reference_count': 0, 'type': "Integer"},
	'lit_3782': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".rodata", 'addr': 0x805AAFA8, 'size': 0x0004, 'padding': 0x00, 'name': "@3782", 'reference_count': 0, 'type': "Integer"},
	'lit_3783': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".rodata", 'addr': 0x805AAFAC, 'size': 0x0004, 'padding': 0x00, 'name': "@3783", 'reference_count': 0, 'type': "Integer"},
	'stringBase0': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".rodata", 'addr': 0x805AAFB0, 'size': 0x0008, 'padding': 0x00, 'name': "@stringBase0", 'reference_count': 0, 'type': "StringBase"},
	'lit_3832': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".data", 'addr': 0x805AAFBC, 'size': 0x000C, 'padding': 0x00, 'name': "@3832", 'reference_count': 0, 'type': "ReferenceArray"},
	'l_daL7lowDr_Method': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".data", 'addr': 0x805AAFC8, 'size': 0x0020, 'padding': 0x00, 'name': "l_daL7lowDr_Method", 'reference_count': 1, 'type': "ReferenceArray"},
	'g_profile_L7lowDr': {'library': "d/a/d_a_L7low_dr", 'translation_unit': "d_a_L7low_dr", 'section': ".data", 'addr': 0x805AAFE8, 'size': 0x0030, 'padding': 0x00, 'name': "g_profile_L7lowDr", 'reference_count': 0, 'type': "ReferenceArray"},
}
