#
# Generate By: dol2asm
# Module: 536
#

SYMBOLS = {
	'_prolog': {'library': "d/a/obj/d_a_obj_lv4prelvtr", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80C68580, 'size': 0x002C, 'padding': 0x00, 'name': "_prolog", 'reference_count': 0, 'type': "Function"},
	'_epilog': {'library': "d/a/obj/d_a_obj_lv4prelvtr", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80C685AC, 'size': 0x002C, 'padding': 0x00, 'name': "_epilog", 'reference_count': 0, 'type': "Function"},
	'_unresolved': {'library': "d/a/obj/d_a_obj_lv4prelvtr", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80C685D8, 'size': 0x0020, 'padding': 0x00, 'name': "_unresolved", 'reference_count': 14, 'type': "Function"},
	'create1st__14daObjPRElvtr_cFv': {'library': "d/a/obj/d_a_obj_lv4prelvtr", 'translation_unit': "d_a_obj_lv4prelvtr", 'section': ".text", 'addr': 0x80C685F8, 'size': 0x0090, 'padding': 0x00, 'name': "create1st__14daObjPRElvtr_cFv", 'reference_count': 1, 'type': "Function"},
	'setMtx__14daObjPRElvtr_cFv': {'library': "d/a/obj/d_a_obj_lv4prelvtr", 'translation_unit': "d_a_obj_lv4prelvtr", 'section': ".text", 'addr': 0x80C68688, 'size': 0x0070, 'padding': 0x00, 'name': "setMtx__14daObjPRElvtr_cFv", 'reference_count': 2, 'type': "Function"},
	'CreateHeap__14daObjPRElvtr_cFv': {'library': "d/a/obj/d_a_obj_lv4prelvtr", 'translation_unit': "d_a_obj_lv4prelvtr", 'section': ".text", 'addr': 0x80C686F8, 'size': 0x0070, 'padding': 0x00, 'name': "CreateHeap__14daObjPRElvtr_cFv", 'reference_count': 0, 'type': "Function"},
	'Create__14daObjPRElvtr_cFv': {'library': "d/a/obj/d_a_obj_lv4prelvtr", 'translation_unit': "d_a_obj_lv4prelvtr", 'section': ".text", 'addr': 0x80C68768, 'size': 0x0068, 'padding': 0x00, 'name': "Create__14daObjPRElvtr_cFv", 'reference_count': 0, 'type': "Function"},
	'searchObjSwTurn__FPvPv': {'library': "d/a/obj/d_a_obj_lv4prelvtr", 'translation_unit': "d_a_obj_lv4prelvtr", 'section': ".text", 'addr': 0x80C687D0, 'size': 0x0074, 'padding': 0x00, 'name': "searchObjSwTurn__FPvPv", 'reference_count': 0, 'type': "Function"},
	'Execute__14daObjPRElvtr_cFPPA3_A4_f': {'library': "d/a/obj/d_a_obj_lv4prelvtr", 'translation_unit': "d_a_obj_lv4prelvtr", 'section': ".text", 'addr': 0x80C68844, 'size': 0x0100, 'padding': 0x00, 'name': "Execute__14daObjPRElvtr_cFPPA3_A4_f", 'reference_count': 0, 'type': "Function"},
	'Draw__14daObjPRElvtr_cFv': {'library': "d/a/obj/d_a_obj_lv4prelvtr", 'translation_unit': "d_a_obj_lv4prelvtr", 'section': ".text", 'addr': 0x80C68944, 'size': 0x00A4, 'padding': 0x00, 'name': "Draw__14daObjPRElvtr_cFv", 'reference_count': 0, 'type': "Function"},
	'Delete__14daObjPRElvtr_cFv': {'library': "d/a/obj/d_a_obj_lv4prelvtr", 'translation_unit': "d_a_obj_lv4prelvtr", 'section': ".text", 'addr': 0x80C689E8, 'size': 0x003C, 'padding': 0x00, 'name': "Delete__14daObjPRElvtr_cFv", 'reference_count': 0, 'type': "Function"},
	'daObjPRElvtr_create1st__FP14daObjPRElvtr_c': {'library': "d/a/obj/d_a_obj_lv4prelvtr", 'translation_unit': "d_a_obj_lv4prelvtr", 'section': ".text", 'addr': 0x80C68A24, 'size': 0x0060, 'padding': 0x00, 'name': "daObjPRElvtr_create1st__FP14daObjPRElvtr_c", 'reference_count': 1, 'type': "Function"},
	'daObjPRElvtr_MoveBGDelete__FP14daObjPRElvtr_c': {'library': "d/a/obj/d_a_obj_lv4prelvtr", 'translation_unit': "d_a_obj_lv4prelvtr", 'section': ".text", 'addr': 0x80C68A84, 'size': 0x0020, 'padding': 0x00, 'name': "daObjPRElvtr_MoveBGDelete__FP14daObjPRElvtr_c", 'reference_count': 1, 'type': "Function"},
	'daObjPRElvtr_MoveBGExecute__FP14daObjPRElvtr_c': {'library': "d/a/obj/d_a_obj_lv4prelvtr", 'translation_unit': "d_a_obj_lv4prelvtr", 'section': ".text", 'addr': 0x80C68AA4, 'size': 0x0020, 'padding': 0x00, 'name': "daObjPRElvtr_MoveBGExecute__FP14daObjPRElvtr_c", 'reference_count': 1, 'type': "Function"},
	'daObjPRElvtr_MoveBGDraw__FP14daObjPRElvtr_c': {'library': "d/a/obj/d_a_obj_lv4prelvtr", 'translation_unit': "d_a_obj_lv4prelvtr", 'section': ".text", 'addr': 0x80C68AC4, 'size': 0x002C, 'padding': 0x00, 'name': "daObjPRElvtr_MoveBGDraw__FP14daObjPRElvtr_c", 'reference_count': 1, 'type': "Function"},
	'__dt__14daObjPRElvtr_cFv': {'library': "d/a/obj/d_a_obj_lv4prelvtr", 'translation_unit': "d_a_obj_lv4prelvtr", 'section': ".text", 'addr': 0x80C68AF0, 'size': 0x0070, 'padding': 0x00, 'name': "__dt__14daObjPRElvtr_cFv", 'reference_count': 0, 'type': "Function"},
	'data_80C68B60': {'library': "d/a/obj/d_a_obj_lv4prelvtr", 'translation_unit': "unknown_translation_unit_ctors", 'section': ".ctors", 'addr': 0x80C68B60, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'data_80C68B64': {'library': "d/a/obj/d_a_obj_lv4prelvtr", 'translation_unit': "unknown_translation_unit_dtors", 'section': ".dtors", 'addr': 0x80C68B64, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'l_cull_box': {'library': "d/a/obj/d_a_obj_lv4prelvtr", 'translation_unit': "d_a_obj_lv4prelvtr", 'section': ".rodata", 'addr': 0x80C68B6C, 'size': 0x0018, 'padding': 0x00, 'name': "l_cull_box", 'reference_count': 0, 'type': "InitData"},
	'lit_3694': {'library': "d/a/obj/d_a_obj_lv4prelvtr", 'translation_unit': "d_a_obj_lv4prelvtr", 'section': ".rodata", 'addr': 0x80C68B84, 'size': 0x0004, 'padding': 0x00, 'name': "@3694", 'reference_count': 0, 'type': "Integer"},
	'lit_3695': {'library': "d/a/obj/d_a_obj_lv4prelvtr", 'translation_unit': "d_a_obj_lv4prelvtr", 'section': ".rodata", 'addr': 0x80C68B88, 'size': 0x0004, 'padding': 0x00, 'name': "@3695", 'reference_count': 0, 'type': "Integer"},
	'lit_3697': {'library': "d/a/obj/d_a_obj_lv4prelvtr", 'translation_unit': "d_a_obj_lv4prelvtr", 'section': ".rodata", 'addr': 0x80C68B8C, 'size': 0x0008, 'padding': 0x00, 'name': "@3697", 'reference_count': 0, 'type': "InitData"},
	'stringBase0': {'library': "d/a/obj/d_a_obj_lv4prelvtr", 'translation_unit': "d_a_obj_lv4prelvtr", 'section': ".rodata", 'addr': 0x80C68B94, 'size': 0x0008, 'padding': 0x00, 'name': "@stringBase0", 'reference_count': 1, 'type': "StringBase"},
	'l_arcName': {'library': "d/a/obj/d_a_obj_lv4prelvtr", 'translation_unit': "d_a_obj_lv4prelvtr", 'section': ".data", 'addr': 0x80C68B9C, 'size': 0x0004, 'padding': 0x00, 'name': "l_arcName", 'reference_count': 0, 'type': "ReferenceArray"},
	'daObjPRElvtr_METHODS': {'library': "d/a/obj/d_a_obj_lv4prelvtr", 'translation_unit': "d_a_obj_lv4prelvtr", 'section': ".data", 'addr': 0x80C68BA0, 'size': 0x0020, 'padding': 0x00, 'name': "daObjPRElvtr_METHODS", 'reference_count': 1, 'type': "ReferenceArray"},
	'g_profile_Obj_PRElvtr': {'library': "d/a/obj/d_a_obj_lv4prelvtr", 'translation_unit': "d_a_obj_lv4prelvtr", 'section': ".data", 'addr': 0x80C68BC0, 'size': 0x0030, 'padding': 0x00, 'name': "g_profile_Obj_PRElvtr", 'reference_count': 0, 'type': "ReferenceArray"},
	'__vt__14daObjPRElvtr_c': {'library': "d/a/obj/d_a_obj_lv4prelvtr", 'translation_unit': "d_a_obj_lv4prelvtr", 'section': ".data", 'addr': 0x80C68BF0, 'size': 0x002C, 'padding': 0x00, 'name': "__vt__14daObjPRElvtr_c", 'reference_count': 0, 'type': "VirtualTable"},
}
