#
# Generate By: dol2asm
# Module: 521
#

SYMBOLS = {
	'_prolog': {'library': "d/a/obj/d_a_obj_lv3saka00", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80C5BDE0, 'size': 0x002C, 'padding': 0x00, 'name': "_prolog", 'reference_count': 0, 'type': "Function"},
	'_epilog': {'library': "d/a/obj/d_a_obj_lv3saka00", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80C5BE0C, 'size': 0x002C, 'padding': 0x00, 'name': "_epilog", 'reference_count': 0, 'type': "Function"},
	'_unresolved': {'library': "d/a/obj/d_a_obj_lv3saka00", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80C5BE38, 'size': 0x0020, 'padding': 0x00, 'name': "_unresolved", 'reference_count': 13, 'type': "Function"},
	'initBaseMtx__14daObjLv3saka_cFv': {'library': "d/a/obj/d_a_obj_lv3saka00", 'translation_unit': "d_a_obj_lv3saka00", 'section': ".text", 'addr': 0x80C5BE58, 'size': 0x0020, 'padding': 0x00, 'name': "initBaseMtx__14daObjLv3saka_cFv", 'reference_count': 1, 'type': "Function"},
	'setBaseMtx__14daObjLv3saka_cFv': {'library': "d/a/obj/d_a_obj_lv3saka00", 'translation_unit': "d_a_obj_lv3saka00", 'section': ".text", 'addr': 0x80C5BE78, 'size': 0x0060, 'padding': 0x00, 'name': "setBaseMtx__14daObjLv3saka_cFv", 'reference_count': 2, 'type': "Function"},
	'Create__14daObjLv3saka_cFv': {'library': "d/a/obj/d_a_obj_lv3saka00", 'translation_unit': "d_a_obj_lv3saka00", 'section': ".text", 'addr': 0x80C5BED8, 'size': 0x00C8, 'padding': 0x00, 'name': "Create__14daObjLv3saka_cFv", 'reference_count': 0, 'type': "Function"},
	'CreateHeap__14daObjLv3saka_cFv': {'library': "d/a/obj/d_a_obj_lv3saka00", 'translation_unit': "d_a_obj_lv3saka00", 'section': ".text", 'addr': 0x80C5BFA0, 'size': 0x00B8, 'padding': 0x00, 'name': "CreateHeap__14daObjLv3saka_cFv", 'reference_count': 0, 'type': "Function"},
	'create1st__14daObjLv3saka_cFv': {'library': "d/a/obj/d_a_obj_lv3saka00", 'translation_unit': "d_a_obj_lv3saka00", 'section': ".text", 'addr': 0x80C5C058, 'size': 0x00A4, 'padding': 0x00, 'name': "create1st__14daObjLv3saka_cFv", 'reference_count': 1, 'type': "Function"},
	'Execute__14daObjLv3saka_cFPPA3_A4_f': {'library': "d/a/obj/d_a_obj_lv3saka00", 'translation_unit': "d_a_obj_lv3saka00", 'section': ".text", 'addr': 0x80C5C0FC, 'size': 0x0080, 'padding': 0x00, 'name': "Execute__14daObjLv3saka_cFPPA3_A4_f", 'reference_count': 0, 'type': "Function"},
	'setNrmDzb__14daObjLv3saka_cFv': {'library': "d/a/obj/d_a_obj_lv3saka00", 'translation_unit': "d_a_obj_lv3saka00", 'section': ".text", 'addr': 0x80C5C17C, 'size': 0x007C, 'padding': 0x00, 'name': "setNrmDzb__14daObjLv3saka_cFv", 'reference_count': 1, 'type': "Function"},
	'setWtrDzb__14daObjLv3saka_cFv': {'library': "d/a/obj/d_a_obj_lv3saka00", 'translation_unit': "d_a_obj_lv3saka00", 'section': ".text", 'addr': 0x80C5C1F8, 'size': 0x007C, 'padding': 0x00, 'name': "setWtrDzb__14daObjLv3saka_cFv", 'reference_count': 1, 'type': "Function"},
	'Draw__14daObjLv3saka_cFv': {'library': "d/a/obj/d_a_obj_lv3saka00", 'translation_unit': "d_a_obj_lv3saka00", 'section': ".text", 'addr': 0x80C5C274, 'size': 0x0008, 'padding': 0x00, 'name': "Draw__14daObjLv3saka_cFv", 'reference_count': 0, 'type': "Function"},
	'Delete__14daObjLv3saka_cFv': {'library': "d/a/obj/d_a_obj_lv3saka00", 'translation_unit': "d_a_obj_lv3saka00", 'section': ".text", 'addr': 0x80C5C27C, 'size': 0x0074, 'padding': 0x00, 'name': "Delete__14daObjLv3saka_cFv", 'reference_count': 0, 'type': "Function"},
	'daObjLv3saka_create1st__FP14daObjLv3saka_c': {'library': "d/a/obj/d_a_obj_lv3saka00", 'translation_unit': "d_a_obj_lv3saka00", 'section': ".text", 'addr': 0x80C5C2F0, 'size': 0x0060, 'padding': 0x00, 'name': "daObjLv3saka_create1st__FP14daObjLv3saka_c", 'reference_count': 1, 'type': "Function"},
	'daObjLv3saka_MoveBGDelete__FP14daObjLv3saka_c': {'library': "d/a/obj/d_a_obj_lv3saka00", 'translation_unit': "d_a_obj_lv3saka00", 'section': ".text", 'addr': 0x80C5C350, 'size': 0x0020, 'padding': 0x00, 'name': "daObjLv3saka_MoveBGDelete__FP14daObjLv3saka_c", 'reference_count': 1, 'type': "Function"},
	'daObjLv3saka_MoveBGExecute__FP14daObjLv3saka_c': {'library': "d/a/obj/d_a_obj_lv3saka00", 'translation_unit': "d_a_obj_lv3saka00", 'section': ".text", 'addr': 0x80C5C370, 'size': 0x0020, 'padding': 0x00, 'name': "daObjLv3saka_MoveBGExecute__FP14daObjLv3saka_c", 'reference_count': 1, 'type': "Function"},
	'daObjLv3saka_MoveBGDraw__FP14daObjLv3saka_c': {'library': "d/a/obj/d_a_obj_lv3saka00", 'translation_unit': "d_a_obj_lv3saka00", 'section': ".text", 'addr': 0x80C5C390, 'size': 0x002C, 'padding': 0x00, 'name': "daObjLv3saka_MoveBGDraw__FP14daObjLv3saka_c", 'reference_count': 1, 'type': "Function"},
	'data_80C5C3BC': {'library': "d/a/obj/d_a_obj_lv3saka00", 'translation_unit': "unknown_translation_unit_ctors", 'section': ".ctors", 'addr': 0x80C5C3BC, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'data_80C5C3C0': {'library': "d/a/obj/d_a_obj_lv3saka00", 'translation_unit': "unknown_translation_unit_dtors", 'section': ".dtors", 'addr': 0x80C5C3C0, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'l_dzbIdx': {'library': "d/a/obj/d_a_obj_lv3saka00", 'translation_unit': "d_a_obj_lv3saka00", 'section': ".rodata", 'addr': 0x80C5C3C4, 'size': 0x0008, 'padding': 0x00, 'name': "l_dzbIdx", 'reference_count': 0, 'type': "InitData"},
	'l_dzbIdx2': {'library': "d/a/obj/d_a_obj_lv3saka00", 'translation_unit': "d_a_obj_lv3saka00", 'section': ".rodata", 'addr': 0x80C5C3CC, 'size': 0x0008, 'padding': 0x00, 'name': "l_dzbIdx2", 'reference_count': 0, 'type': "InitData"},
	'l_heap_size': {'library': "d/a/obj/d_a_obj_lv3saka00", 'translation_unit': "d_a_obj_lv3saka00", 'section': ".rodata", 'addr': 0x80C5C3D4, 'size': 0x0008, 'padding': 0x00, 'name': "l_heap_size", 'reference_count': 0, 'type': "InitData"},
	'stringBase0': {'library': "d/a/obj/d_a_obj_lv3saka00", 'translation_unit': "d_a_obj_lv3saka00", 'section': ".rodata", 'addr': 0x80C5C3DC, 'size': 0x0013, 'padding': 0x00, 'name': "@stringBase0", 'reference_count': 1, 'type': "StringBase"},
	'l_arcName': {'library': "d/a/obj/d_a_obj_lv3saka00", 'translation_unit': "d_a_obj_lv3saka00", 'section': ".data", 'addr': 0x80C5C3F4, 'size': 0x0008, 'padding': 0x00, 'name': "l_arcName", 'reference_count': 0, 'type': "ReferenceArray"},
	'daObjLv3saka_METHODS': {'library': "d/a/obj/d_a_obj_lv3saka00", 'translation_unit': "d_a_obj_lv3saka00", 'section': ".data", 'addr': 0x80C5C3FC, 'size': 0x0020, 'padding': 0x00, 'name': "daObjLv3saka_METHODS", 'reference_count': 1, 'type': "ReferenceArray"},
	'g_profile_Obj_Lv3R10Saka': {'library': "d/a/obj/d_a_obj_lv3saka00", 'translation_unit': "d_a_obj_lv3saka00", 'section': ".data", 'addr': 0x80C5C41C, 'size': 0x0030, 'padding': 0x00, 'name': "g_profile_Obj_Lv3R10Saka", 'reference_count': 0, 'type': "ReferenceArray"},
	'__vt__14daObjLv3saka_c': {'library': "d/a/obj/d_a_obj_lv3saka00", 'translation_unit': "d_a_obj_lv3saka00", 'section': ".data", 'addr': 0x80C5C44C, 'size': 0x0028, 'padding': 0x00, 'name': "__vt__14daObjLv3saka_c", 'reference_count': 0, 'type': "VirtualTable"},
}
