#
# Generate By: dol2asm
# Module: 574
#

SYMBOLS = {
	'_prolog': {'library': "d/a/obj/mirror/d_a_obj_mirror_sand", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80C98160, 'size': 0x002C, 'padding': 0x00, 'name': "_prolog", 'reference_count': 0, 'type': "Function"},
	'_epilog': {'library': "d/a/obj/mirror/d_a_obj_mirror_sand", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80C9818C, 'size': 0x002C, 'padding': 0x00, 'name': "_epilog", 'reference_count': 0, 'type': "Function"},
	'_unresolved': {'library': "d/a/obj/mirror/d_a_obj_mirror_sand", 'translation_unit': "executor", 'section': ".text", 'addr': 0x80C981B8, 'size': 0x0020, 'padding': 0x00, 'name': "_unresolved", 'reference_count': 10, 'type': "Function"},
	'createSolidHeap__FP10fopAc_ac_c': {'library': "d/a/obj/mirror/d_a_obj_mirror_sand", 'translation_unit': "d_a_obj_mirror_sand", 'section': ".text", 'addr': 0x80C981D8, 'size': 0x02E8, 'padding': 0x00, 'name': "createSolidHeap__FP10fopAc_ac_c", 'reference_count': 0, 'type': "Function"},
	'__dt__12J3DFrameCtrlFv': {'library': "d/a/obj/mirror/d_a_obj_mirror_sand", 'translation_unit': "d_a_obj_mirror_sand", 'section': ".text", 'addr': 0x80C984C0, 'size': 0x0048, 'padding': 0x00, 'name': "__dt__12J3DFrameCtrlFv", 'reference_count': 0, 'type': "Function"},
	'initBaseMtx__17daObjMirrorSand_cFv': {'library': "d/a/obj/mirror/d_a_obj_mirror_sand", 'translation_unit': "d_a_obj_mirror_sand", 'section': ".text", 'addr': 0x80C98508, 'size': 0x002C, 'padding': 0x00, 'name': "initBaseMtx__17daObjMirrorSand_cFv", 'reference_count': 1, 'type': "Function"},
	'setBaseMtx__17daObjMirrorSand_cFv': {'library': "d/a/obj/mirror/d_a_obj_mirror_sand", 'translation_unit': "d_a_obj_mirror_sand", 'section': ".text", 'addr': 0x80C98534, 'size': 0x0064, 'padding': 0x00, 'name': "setBaseMtx__17daObjMirrorSand_cFv", 'reference_count': 1, 'type': "Function"},
	'daObjMirrorSand_Draw__FP17daObjMirrorSand_c': {'library': "d/a/obj/mirror/d_a_obj_mirror_sand", 'translation_unit': "d_a_obj_mirror_sand", 'section': ".text", 'addr': 0x80C98598, 'size': 0x00D0, 'padding': 0x00, 'name': "daObjMirrorSand_Draw__FP17daObjMirrorSand_c", 'reference_count': 1, 'type': "Function"},
	'daObjMirrorSand_Execute__FP17daObjMirrorSand_c': {'library': "d/a/obj/mirror/d_a_obj_mirror_sand", 'translation_unit': "d_a_obj_mirror_sand", 'section': ".text", 'addr': 0x80C98668, 'size': 0x0098, 'padding': 0x00, 'name': "daObjMirrorSand_Execute__FP17daObjMirrorSand_c", 'reference_count': 1, 'type': "Function"},
	'daObjMirrorSand_IsDelete__FP17daObjMirrorSand_c': {'library': "d/a/obj/mirror/d_a_obj_mirror_sand", 'translation_unit': "d_a_obj_mirror_sand", 'section': ".text", 'addr': 0x80C98700, 'size': 0x0008, 'padding': 0x00, 'name': "daObjMirrorSand_IsDelete__FP17daObjMirrorSand_c", 'reference_count': 1, 'type': "Function"},
	'daObjMirrorSand_Delete__FP17daObjMirrorSand_c': {'library': "d/a/obj/mirror/d_a_obj_mirror_sand", 'translation_unit': "d_a_obj_mirror_sand", 'section': ".text", 'addr': 0x80C98708, 'size': 0x00B0, 'padding': 0x00, 'name': "daObjMirrorSand_Delete__FP17daObjMirrorSand_c", 'reference_count': 1, 'type': "Function"},
	'__dt__4dBgWFv': {'library': "d/a/obj/mirror/d_a_obj_mirror_sand", 'translation_unit': "d_a_obj_mirror_sand", 'section': ".text", 'addr': 0x80C987B8, 'size': 0x0060, 'padding': 0x00, 'name': "__dt__4dBgWFv", 'reference_count': 0, 'type': "Function"},
	'daObjMirrorSand_Create__FP10fopAc_ac_c': {'library': "d/a/obj/mirror/d_a_obj_mirror_sand", 'translation_unit': "d_a_obj_mirror_sand", 'section': ".text", 'addr': 0x80C98818, 'size': 0x01B8, 'padding': 0x00, 'name': "daObjMirrorSand_Create__FP10fopAc_ac_c", 'reference_count': 1, 'type': "Function"},
	'data_80C989D0': {'library': "d/a/obj/mirror/d_a_obj_mirror_sand", 'translation_unit': "unknown_translation_unit_ctors", 'section': ".ctors", 'addr': 0x80C989D0, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'data_80C989D4': {'library': "d/a/obj/mirror/d_a_obj_mirror_sand", 'translation_unit': "unknown_translation_unit_dtors", 'section': ".dtors", 'addr': 0x80C989D4, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'lit_3729': {'library': "d/a/obj/mirror/d_a_obj_mirror_sand", 'translation_unit': "d_a_obj_mirror_sand", 'section': ".rodata", 'addr': 0x80C989DC, 'size': 0x0004, 'padding': 0x00, 'name': "@3729", 'reference_count': 0, 'type': "Integer"},
	'lit_3730': {'library': "d/a/obj/mirror/d_a_obj_mirror_sand", 'translation_unit': "d_a_obj_mirror_sand", 'section': ".rodata", 'addr': 0x80C989E0, 'size': 0x0004, 'padding': 0x00, 'name': "@3730", 'reference_count': 0, 'type': "InitData"},
	'lit_3732': {'library': "d/a/obj/mirror/d_a_obj_mirror_sand", 'translation_unit': "d_a_obj_mirror_sand", 'section': ".rodata", 'addr': 0x80C989E4, 'size': 0x0008, 'padding': 0x00, 'name': "@3732", 'reference_count': 0, 'type': "InitData"},
	'stringBase0': {'library': "d/a/obj/mirror/d_a_obj_mirror_sand", 'translation_unit': "d_a_obj_mirror_sand", 'section': ".rodata", 'addr': 0x80C989EC, 'size': 0x0008, 'padding': 0x00, 'name': "@stringBase0", 'reference_count': 1, 'type': "StringBase"},
	'l_arcName': {'library': "d/a/obj/mirror/d_a_obj_mirror_sand", 'translation_unit': "d_a_obj_mirror_sand", 'section': ".data", 'addr': 0x80C989F4, 'size': 0x0004, 'padding': 0x00, 'name': "l_arcName", 'reference_count': 0, 'type': "ReferenceArray"},
	'l_daObjMirrorSand_Method': {'library': "d/a/obj/mirror/d_a_obj_mirror_sand", 'translation_unit': "d_a_obj_mirror_sand", 'section': ".data", 'addr': 0x80C989F8, 'size': 0x0020, 'padding': 0x00, 'name': "l_daObjMirrorSand_Method", 'reference_count': 1, 'type': "ReferenceArray"},
	'g_profile_Obj_MirrorSand': {'library': "d/a/obj/mirror/d_a_obj_mirror_sand", 'translation_unit': "d_a_obj_mirror_sand", 'section': ".data", 'addr': 0x80C98A18, 'size': 0x0030, 'padding': 0x00, 'name': "g_profile_Obj_MirrorSand", 'reference_count': 0, 'type': "ReferenceArray"},
	'__vt__12J3DFrameCtrl': {'library': "d/a/obj/mirror/d_a_obj_mirror_sand", 'translation_unit': "d_a_obj_mirror_sand", 'section': ".data", 'addr': 0x80C98A48, 'size': 0x000C, 'padding': 0x00, 'name': "__vt__12J3DFrameCtrl", 'reference_count': 0, 'type': "VirtualTable"},
}
