#
# Generate By: dol2asm
# Module: 234
#

SYMBOLS = {
	'_prolog': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "executor", 'section': ".text", 'addr': 0x807A6EE0, 'size': 0x002C, 'padding': 0x00, 'name': "_prolog", 'reference_count': 0, 'type': "Function"},
	'_epilog': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "executor", 'section': ".text", 'addr': 0x807A6F0C, 'size': 0x002C, 'padding': 0x00, 'name': "_epilog", 'reference_count': 0, 'type': "Function"},
	'_unresolved': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "executor", 'section': ".text", 'addr': 0x807A6F38, 'size': 0x0020, 'padding': 0x00, 'name': "_unresolved", 'reference_count': 6, 'type': "Function"},
	'daE_ST_LINE_Draw__FP15e_st_line_class': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".text", 'addr': 0x807A6F58, 'size': 0x0008, 'padding': 0x00, 'name': "daE_ST_LINE_Draw__FP15e_st_line_class", 'reference_count': 1, 'type': "Function"},
	'__dt__4cXyzFv': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".text", 'addr': 0x807A6F60, 'size': 0x003C, 'padding': 0x00, 'name': "__dt__4cXyzFv", 'reference_count': 0, 'type': "Function"},
	'daE_ST_LINE_Execute__FP15e_st_line_class': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".text", 'addr': 0x807A6F9C, 'size': 0x0008, 'padding': 0x00, 'name': "daE_ST_LINE_Execute__FP15e_st_line_class", 'reference_count': 2, 'type': "Function"},
	'daE_ST_LINE_IsDelete__FP15e_st_line_class': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".text", 'addr': 0x807A6FA4, 'size': 0x0008, 'padding': 0x00, 'name': "daE_ST_LINE_IsDelete__FP15e_st_line_class", 'reference_count': 1, 'type': "Function"},
	'daE_ST_LINE_Delete__FP15e_st_line_class': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".text", 'addr': 0x807A6FAC, 'size': 0x005C, 'padding': 0x00, 'name': "daE_ST_LINE_Delete__FP15e_st_line_class", 'reference_count': 1, 'type': "Function"},
	'useHeapInit__FP10fopAc_ac_c': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".text", 'addr': 0x807A7008, 'size': 0x0074, 'padding': 0x00, 'name': "useHeapInit__FP10fopAc_ac_c", 'reference_count': 0, 'type': "Function"},
	'daE_ST_LINE_Create__FP10fopAc_ac_c': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".text", 'addr': 0x807A707C, 'size': 0x01A4, 'padding': 0x00, 'name': "daE_ST_LINE_Create__FP10fopAc_ac_c", 'reference_count': 1, 'type': "Function"},
	'__ct__4cXyzFv': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".text", 'addr': 0x807A7220, 'size': 0x0004, 'padding': 0x00, 'name': "__ct__4cXyzFv", 'reference_count': 0, 'type': "Function"},
	'data_807A7224': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "unknown_translation_unit_ctors", 'section': ".ctors", 'addr': 0x807A7224, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'data_807A7228': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "unknown_translation_unit_dtors", 'section': ".dtors", 'addr': 0x807A7228, 'size': 0x0004, 'padding': 0x00, 'name': None, 'reference_count': 0, 'type': "InitData"},
	'lit_3704': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".rodata", 'addr': 0x807A722C, 'size': 0x0004, 'padding': 0x00, 'name': "@3704", 'reference_count': 0, 'type': "Integer"},
	'lit_3705': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".rodata", 'addr': 0x807A7230, 'size': 0x0004, 'padding': 0x00, 'name': "@3705", 'reference_count': 0, 'type': "InitData"},
	'lit_3706': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".rodata", 'addr': 0x807A7234, 'size': 0x0004, 'padding': 0x00, 'name': "@3706", 'reference_count': 0, 'type': "Integer"},
	'lit_3735': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".rodata", 'addr': 0x807A7238, 'size': 0x0004, 'padding': 0x00, 'name': "@3735", 'reference_count': 0, 'type': "Integer"},
	'lit_3759': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".rodata", 'addr': 0x807A723C, 'size': 0x0004, 'padding': 0x04, 'name': "@3759", 'reference_count': 0, 'type': "Integer"},
	'lit_3938': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".rodata", 'addr': 0x807A7244, 'size': 0x0008, 'padding': 0x00, 'name': "@3938", 'reference_count': 0, 'type': "InitData"},
	'lit_3939': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".rodata", 'addr': 0x807A724C, 'size': 0x0008, 'padding': 0x00, 'name': "@3939", 'reference_count': 0, 'type': "InitData"},
	'lit_3940': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".rodata", 'addr': 0x807A7254, 'size': 0x0008, 'padding': 0x00, 'name': "@3940", 'reference_count': 0, 'type': "InitData"},
	'lit_3941': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".rodata", 'addr': 0x807A725C, 'size': 0x0004, 'padding': 0x00, 'name': "@3941", 'reference_count': 0, 'type': "Integer"},
	'lit_3942': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".rodata", 'addr': 0x807A7260, 'size': 0x0004, 'padding': 0x00, 'name': "@3942", 'reference_count': 0, 'type': "Integer"},
	'lit_3943': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".rodata", 'addr': 0x807A7264, 'size': 0x0004, 'padding': 0x00, 'name': "@3943", 'reference_count': 0, 'type': "Integer"},
	'lit_3944': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".rodata", 'addr': 0x807A7268, 'size': 0x0004, 'padding': 0x00, 'name': "@3944", 'reference_count': 0, 'type': "Integer"},
	'lit_3945': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".rodata", 'addr': 0x807A726C, 'size': 0x0004, 'padding': 0x00, 'name': "@3945", 'reference_count': 0, 'type': "Integer"},
	'lit_3946': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".rodata", 'addr': 0x807A7270, 'size': 0x0004, 'padding': 0x00, 'name': "@3946", 'reference_count': 0, 'type': "Integer"},
	'lit_3947': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".rodata", 'addr': 0x807A7274, 'size': 0x0004, 'padding': 0x00, 'name': "@3947", 'reference_count': 0, 'type': "Integer"},
	'lit_4003': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".rodata", 'addr': 0x807A7278, 'size': 0x0004, 'padding': 0x00, 'name': "@4003", 'reference_count': 0, 'type': "Integer"},
	'lit_4004': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".rodata", 'addr': 0x807A727C, 'size': 0x0004, 'padding': 0x00, 'name': "@4004", 'reference_count': 0, 'type': "Integer"},
	'lit_4069': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".rodata", 'addr': 0x807A7280, 'size': 0x0004, 'padding': 0x00, 'name': "@4069", 'reference_count': 0, 'type': "Integer"},
	'lit_4070': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".rodata", 'addr': 0x807A7284, 'size': 0x0004, 'padding': 0x00, 'name': "@4070", 'reference_count': 0, 'type': "Integer"},
	'lit_4071': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".rodata", 'addr': 0x807A7288, 'size': 0x0004, 'padding': 0x00, 'name': "@4071", 'reference_count': 0, 'type': "Integer"},
	'lit_4072': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".rodata", 'addr': 0x807A728C, 'size': 0x0004, 'padding': 0x00, 'name': "@4072", 'reference_count': 0, 'type': "Integer"},
	'lit_4073': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".rodata", 'addr': 0x807A7290, 'size': 0x0004, 'padding': 0x00, 'name': "@4073", 'reference_count': 0, 'type': "Integer"},
	'lit_4169': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".rodata", 'addr': 0x807A7294, 'size': 0x0004, 'padding': 0x00, 'name': "@4169", 'reference_count': 0, 'type': "Integer"},
	'lit_4170': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".rodata", 'addr': 0x807A7298, 'size': 0x0004, 'padding': 0x00, 'name': "@4170", 'reference_count': 0, 'type': "Integer"},
	'stringBase0': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".rodata", 'addr': 0x807A729C, 'size': 0x0005, 'padding': 0x00, 'name': "@stringBase0", 'reference_count': 0, 'type': "StringBase"},
	'l_daE_ST_LINE_Method': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".data", 'addr': 0x807A72A4, 'size': 0x0020, 'padding': 0x00, 'name': "l_daE_ST_LINE_Method", 'reference_count': 1, 'type': "ReferenceArray"},
	'g_profile_E_ST_LINE': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".data", 'addr': 0x807A72C4, 'size': 0x0030, 'padding': 0x00, 'name': "g_profile_E_ST_LINE", 'reference_count': 0, 'type': "ReferenceArray"},
	'__vt__18mDoExt_3DlineMat_c': {'library': "d/a/e/d_a_e_st_line", 'translation_unit': "d_a_e_st_line", 'section': ".data", 'addr': 0x807A72F4, 'size': 0x0014, 'padding': 0x00, 'name': "__vt__18mDoExt_3DlineMat_c", 'reference_count': 0, 'type': "VirtualTable"},
}
