// 
// Generated By: dol2asm
// 

#include "dolphin/types.h"

// 
// Additional Symbols:
// 

extern "C" {
extern void _prolog();
extern void _epilog();
extern void _unresolved();
extern const u8 unknown_translation_unit_ctors__data_80485638[4];
extern const u8 unknown_translation_unit_dtors__data_8048563C[4];
SECTION_RODATA extern const u8 LIT_3720[4];
SECTION_RODATA extern const u8 LIT_3721[4];
SECTION_DATA extern u8 cNullVec__6Z2Calc[12];
SECTION_BSS extern u8 unknown_translation_unit_bss__data_804856FC[4];
}


/* ###################################################################################### */
/*                                         .text                                          */
/* ###################################################################################### */

/* 80485120-8048514C 002C .text      _prolog                                                      */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void _prolog() {
	nofralloc
#include "asm/rel/d_a_obj_timer/executor/_prolog.s"
}
#pragma pop

/* 8048514C-80485178 002C .text      _epilog                                                      */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void _epilog() {
	nofralloc
#include "asm/rel/d_a_obj_timer/executor/_epilog.s"
}
#pragma pop

/* 80485178-80485198 0020 .text      _unresolved                                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void _unresolved() {
	nofralloc
#include "asm/rel/d_a_obj_timer/executor/_unresolved.s"
}
#pragma pop


