// 
// Generated By: dol2asm
// 

#include "dolphin/types.h"

// 
// Additional Symbols:
// 

extern "C" {
/* Function             */
extern void TRKSaveExtended1Block();
/* Function             */
extern void TRKRestoreExtended1Block();
/* InitializedData      */
SECTION_DATA extern u8 gTRKRestoreFlags[12];
/* ZeroInitializedData  */
SECTION_BSS extern u8 gTRKCPUState[1072];
}


/* ###################################################################################### */
/*                                         .text                                          */
/* ###################################################################################### */

extern "C" {
/* 803711F0-803713A8 01B8 .text      TRKSaveExtended1Block                                        Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void TRKSaveExtended1Block() {
	nofralloc
#include "_include/TRK_MINNOW_DOLPHIN/ppc/Generic/mpc_7xx_603e/TRKSaveExtended1Block.s"
}
#pragma pop

/* 803713A8-80371560 01B8 .text      TRKRestoreExtended1Block                                     Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void TRKRestoreExtended1Block() {
	nofralloc
#include "_include/TRK_MINNOW_DOLPHIN/ppc/Generic/mpc_7xx_603e/TRKRestoreExtended1Block.s"
}
#pragma pop

}

