// 
// Generated By: dol2asm
// 

#include "dolphin/types.h"

// 
// Additional Symbols:
// 

extern "C" {
/* Function             */
SECTION_INIT extern void memset();
/* Function             */
extern void TRKConstructEvent();
/* Function             */
extern void TRKPostEvent();
/* Function             */
extern void TRKReadBuffer_ui32();
/* Function             */
extern void TRKReadBuffer1_ui64();
/* Function             */
extern void TRKAppendBuffer_ui32();
/* Function             */
extern void TRKAppendBuffer_ui8();
/* Function             */
extern void TRKAppendBuffer1_ui64();
/* Function             */
extern void HandlePositionFileSupportRequest();
/* Function             */
extern void HandleCloseFileSupportRequest();
/* Function             */
extern void HandleOpenFileSupportRequest();
/* Function             */
extern void TRKSuppAccessFile();
/* Function             */
extern void TRKDoNotifyStopped();
/* Function             */
extern void TRK_flush_cache();
/* Function             */
extern void __TRK_get_MSR();
/* Function             */
extern void __TRK_set_MSR();
/* Function             */
extern void TRK_ppc_memcpy();
/* Function             */
extern void TRKInterruptHandler();
/* Function             */
extern void TRKExceptionHandler();
/* Function             */
extern void TRKSwapAndGo();
/* Function             */
extern void TRKInterruptHandlerEnableInterrupts();
/* Function             */
extern void ReadFPSCR();
/* Function             */
extern void WriteFPSCR();
/* Function             */
extern void TRKTargetAccessARAM();
/* Function             */
extern void TRKTargetSetInputPendingPtr();
/* Function             */
extern void TRKTargetStop();
/* Function             */
extern void TRKTargetSetStopped();
/* Function             */
extern void TRKTargetStopped();
/* Function             */
extern void TRKTargetSupportRequest();
/* Function             */
extern void TRKTargetGetPC();
/* Function             */
extern void TRKTargetStepOutOfRange();
/* Function             */
extern void TRKTargetSingleStep();
/* Function             */
extern void TRKTargetAddExceptionInfo();
/* Function             */
extern void TRKTargetAddStopInfo();
/* Function             */
extern void TRKTargetInterrupt();
/* Function             */
extern void TRKPostInterruptEvent();
/* Function             */
extern void TRKTargetAccessExtended2();
/* Function             */
extern void TRKTargetAccessExtended1();
/* Function             */
extern void TRKTargetAccessFP();
/* Function             */
extern void TRKTargetAccessDefault();
/* Function             */
extern void TRKTargetReadInstruction();
/* Function             */
extern void TRKTargetAccessMemory();
/* Function             */
extern void TRKValidMemory32();
/* Function             */
extern void TRKSaveExtended1Block();
/* Function             */
extern void TRKRestoreExtended1Block();
/* Function             */
extern void TRK__write_aram();
/* Function             */
extern void TRK__read_aram();
/* Function             */
extern void TRKTargetTranslate();
/* ReturnFunction       */
extern void TRKUARTInterruptHandler();
/* Function             */
extern void MWTRACE();
/* InitializedData      */
SECTION_RODATA extern const u8 gTRKMemMap[16];
/* InitializedData      */
SECTION_RODATA extern const u8 ppc_Generic_targimpl__LIT_276[40];
/* InitializedData      */
SECTION_RODATA extern const u8 LIT_283[40];
/* InitializedData      */
SECTION_RODATA extern const u8 ppc_Generic_targimpl__LIT_290[40];
/* InitializedData      */
SECTION_RODATA extern const u8 LIT_422[16];
/* InitializedData      */
SECTION_DATA extern u8 gTRKRestoreFlags[12];
/* InitializedData      */
SECTION_DATA extern u8 gTRKExceptionStatus[16];
/* InitializedData      */
SECTION_DATA extern u8 gTRKStepStatus[20];
/* ZeroInitializedData  */
SECTION_BSS extern u8 TRK_saved_exceptionID[2 + 2 /* padding */];
/* ZeroInitializedData  */
SECTION_BSS extern u8 gTRKState[164];
/* ZeroInitializedData  */
SECTION_BSS extern u8 gTRKCPUState[1072];
/* ZeroInitializedData  */
SECTION_BSS extern u8 gTRKSaveState[148];
/* ZeroInitializedData  */
SECTION_BSS extern u8 TRKvalue128_temp[16 + 4 /* padding */];
}


/* ###################################################################################### */
/*                                        .rodata                                         */
/* ###################################################################################### */

extern "C" {
/* 803A2B60-803A2B70 0010 .rodata    gTRKMemMap                                                   InitializedData */
SECTION_RODATA const u8 gTRKMemMap[16] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01,
};
/* 803A2B70-803A2B98 0028 .rodata    @276                                                         InitializedData */
SECTION_RODATA const u8 ppc_Generic_targimpl__LIT_276[40] = {
	0x60, 0x00, 0x00, 0x00, 0x60, 0x00, 0x00, 0x00, 0x60, 0x00, 0x00, 0x00, 0x60, 0x00, 0x00, 0x00,
	0x60, 0x00, 0x00, 0x00, 0x60, 0x00, 0x00, 0x00, 0x60, 0x00, 0x00, 0x00, 0x60, 0x00, 0x00, 0x00,
	0x60, 0x00, 0x00, 0x00, 0x60, 0x00, 0x00, 0x00,
};
/* 803A2B98-803A2BC0 0028 .rodata    @283                                                         InitializedData */
SECTION_RODATA const u8 LIT_283[40] = {
	0x60, 0x00, 0x00, 0x00, 0x60, 0x00, 0x00, 0x00, 0x60, 0x00, 0x00, 0x00, 0x60, 0x00, 0x00, 0x00,
	0x60, 0x00, 0x00, 0x00, 0x60, 0x00, 0x00, 0x00, 0x60, 0x00, 0x00, 0x00, 0x60, 0x00, 0x00, 0x00,
	0x60, 0x00, 0x00, 0x00, 0x60, 0x00, 0x00, 0x00,
};
/* 803A2BC0-803A2BE8 0028 .rodata    @290                                                         InitializedData */
SECTION_RODATA const u8 ppc_Generic_targimpl__LIT_290[40] = {
	0x60, 0x00, 0x00, 0x00, 0x60, 0x00, 0x00, 0x00, 0x60, 0x00, 0x00, 0x00, 0x60, 0x00, 0x00, 0x00,
	0x60, 0x00, 0x00, 0x00, 0x60, 0x00, 0x00, 0x00, 0x60, 0x00, 0x00, 0x00, 0x60, 0x00, 0x00, 0x00,
	0x60, 0x00, 0x00, 0x00, 0x60, 0x00, 0x00, 0x00,
};
/* 803A2BE8-803A2BF8 0010 .rodata    @422                                                         InitializedData */
SECTION_RODATA const u8 LIT_422[16] = {
	0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x44, 0x6F, 0x53, 0x74, 0x65, 0x70, 0x28, 0x29, 0x0A, 0x00,
};
}


/* ###################################################################################### */
/*                                         .data                                          */
/* ###################################################################################### */

extern "C" {
/* 803D3238-803D3244 0009 .data      gTRKRestoreFlags                                             InitializedData */
SECTION_DATA u8 gTRKRestoreFlags[12] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	/* padding */
	0x00, 0x00, 0x00,
};
/* 803D3244-803D3254 0010 .data      gTRKExceptionStatus                                          InitializedData */
SECTION_DATA u8 gTRKExceptionStatus[16] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
};
/* 803D3254-803D3268 0014 .data      gTRKStepStatus                                               InitializedData */
SECTION_DATA u8 gTRKStepStatus[20] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00,
};
}


/* ###################################################################################### */
/*                                          .bss                                          */
/* ###################################################################################### */

extern "C" {
/* 8044F290-8044F294 0002 .bss       TRK_saved_exceptionID                                        ZeroInitializedData */
SECTION_BSS u8 TRK_saved_exceptionID[2 + 2 /* padding */];
/* 8044F294-8044F338 00A4 .bss       gTRKState                                                    ZeroInitializedData */
SECTION_BSS u8 gTRKState[164];
/* 8044F338-8044F768 0430 .bss       gTRKCPUState                                                 ZeroInitializedData */
SECTION_BSS u8 gTRKCPUState[1072];
/* 8044F768-8044F7FC 0094 .bss       gTRKSaveState                                                ZeroInitializedData */
SECTION_BSS u8 gTRKSaveState[148];
/* 8044F7FC-8044F810 0010 .bss       TRKvalue128_temp                                             ZeroInitializedData */
SECTION_BSS u8 TRKvalue128_temp[16 + 4 /* padding */];
}


/* ###################################################################################### */
/*                                         .text                                          */
/* ###################################################################################### */

extern "C" {
/* 8036F638-8036F640 0008 .text      __TRK_get_MSR                                                Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __TRK_get_MSR() {
	nofralloc
#include "_include/TRK_MINNOW_DOLPHIN/ppc/Generic/targimpl/__TRK_get_MSR.s"
}
#pragma pop

/* 8036F640-8036F648 0008 .text      __TRK_set_MSR                                                Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __TRK_set_MSR() {
	nofralloc
#include "_include/TRK_MINNOW_DOLPHIN/ppc/Generic/targimpl/__TRK_set_MSR.s"
}
#pragma pop

/* 8036F648-8036F684 003C .text      TRK_ppc_memcpy                                               Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void TRK_ppc_memcpy() {
	nofralloc
#include "_include/TRK_MINNOW_DOLPHIN/ppc/Generic/targimpl/TRK_ppc_memcpy.s"
}
#pragma pop

/* 8036F684-8036F818 0194 .text      TRKInterruptHandler                                          Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void TRKInterruptHandler() {
	nofralloc
#include "_include/TRK_MINNOW_DOLPHIN/ppc/Generic/targimpl/TRKInterruptHandler.s"
}
#pragma pop

/* 8036F818-8036F8B4 009C .text      TRKExceptionHandler                                          Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void TRKExceptionHandler() {
	nofralloc
#include "_include/TRK_MINNOW_DOLPHIN/ppc/Generic/targimpl/TRKExceptionHandler.s"
}
#pragma pop

/* 8036F8B4-8036F978 00C4 .text      TRKSwapAndGo                                                 Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void TRKSwapAndGo() {
	nofralloc
#include "_include/TRK_MINNOW_DOLPHIN/ppc/Generic/targimpl/TRKSwapAndGo.s"
}
#pragma pop

/* 8036F978-8036F9CC 0054 .text      TRKInterruptHandlerEnableInterrupts                          Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void TRKInterruptHandlerEnableInterrupts() {
	nofralloc
#include "_include/TRK_MINNOW_DOLPHIN/ppc/Generic/targimpl/TRKInterruptHandlerEnableInterrupts.s"
}
#pragma pop

/* 8036F9CC-8036F9F0 0024 .text      ReadFPSCR                                                    Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void ReadFPSCR() {
	nofralloc
#include "_include/TRK_MINNOW_DOLPHIN/ppc/Generic/targimpl/ReadFPSCR.s"
}
#pragma pop

/* 8036F9F0-8036FA14 0024 .text      WriteFPSCR                                                   Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void WriteFPSCR() {
	nofralloc
#include "_include/TRK_MINNOW_DOLPHIN/ppc/Generic/targimpl/WriteFPSCR.s"
}
#pragma pop

/* 8036FA14-8036FAD8 00C4 .text      TRKTargetAccessARAM                                          Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void TRKTargetAccessARAM() {
	nofralloc
#include "_include/TRK_MINNOW_DOLPHIN/ppc/Generic/targimpl/TRKTargetAccessARAM.s"
}
#pragma pop

/* 8036FAD8-8036FAE8 0010 .text      TRKTargetSetInputPendingPtr                                  Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void TRKTargetSetInputPendingPtr() {
	nofralloc
#include "_include/TRK_MINNOW_DOLPHIN/ppc/Generic/targimpl/TRKTargetSetInputPendingPtr.s"
}
#pragma pop

/* 8036FAE8-8036FB00 0018 .text      TRKTargetStop                                                Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void TRKTargetStop() {
	nofralloc
#include "_include/TRK_MINNOW_DOLPHIN/ppc/Generic/targimpl/TRKTargetStop.s"
}
#pragma pop

/* 8036FB00-8036FB10 0010 .text      TRKTargetSetStopped                                          Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void TRKTargetSetStopped() {
	nofralloc
#include "_include/TRK_MINNOW_DOLPHIN/ppc/Generic/targimpl/TRKTargetSetStopped.s"
}
#pragma pop

/* 8036FB10-8036FB20 0010 .text      TRKTargetStopped                                             Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void TRKTargetStopped() {
	nofralloc
#include "_include/TRK_MINNOW_DOLPHIN/ppc/Generic/targimpl/TRKTargetStopped.s"
}
#pragma pop

/* 8036FB20-8036FD20 0200 .text      TRKTargetSupportRequest                                      Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void TRKTargetSupportRequest() {
	nofralloc
#include "_include/TRK_MINNOW_DOLPHIN/ppc/Generic/targimpl/TRKTargetSupportRequest.s"
}
#pragma pop

/* 8036FD20-8036FD30 0010 .text      TRKTargetGetPC                                               Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void TRKTargetGetPC() {
	nofralloc
#include "_include/TRK_MINNOW_DOLPHIN/ppc/Generic/targimpl/TRKTargetGetPC.s"
}
#pragma pop

/* 8036FD30-8036FDE8 00B8 .text      TRKTargetStepOutOfRange                                      Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void TRKTargetStepOutOfRange() {
	nofralloc
#include "_include/TRK_MINNOW_DOLPHIN/ppc/Generic/targimpl/TRKTargetStepOutOfRange.s"
}
#pragma pop

/* 8036FDE8-8036FE94 00AC .text      TRKTargetSingleStep                                          Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void TRKTargetSingleStep() {
	nofralloc
#include "_include/TRK_MINNOW_DOLPHIN/ppc/Generic/targimpl/TRKTargetSingleStep.s"
}
#pragma pop

/* 8036FE94-8036FF18 0084 .text      TRKTargetAddExceptionInfo                                    Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void TRKTargetAddExceptionInfo() {
	nofralloc
#include "_include/TRK_MINNOW_DOLPHIN/ppc/Generic/targimpl/TRKTargetAddExceptionInfo.s"
}
#pragma pop

/* 8036FF18-8036FFA4 008C .text      TRKTargetAddStopInfo                                         Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void TRKTargetAddStopInfo() {
	nofralloc
#include "_include/TRK_MINNOW_DOLPHIN/ppc/Generic/targimpl/TRKTargetAddStopInfo.s"
}
#pragma pop

/* 8036FFA4-80370134 0190 .text      TRKTargetInterrupt                                           Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void TRKTargetInterrupt() {
	nofralloc
#include "_include/TRK_MINNOW_DOLPHIN/ppc/Generic/targimpl/TRKTargetInterrupt.s"
}
#pragma pop

/* 80370134-803701E0 00AC .text      TRKPostInterruptEvent                                        Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void TRKPostInterruptEvent() {
	nofralloc
#include "_include/TRK_MINNOW_DOLPHIN/ppc/Generic/targimpl/TRKPostInterruptEvent.s"
}
#pragma pop

/* 803701E0-80370618 0438 .text      TRKTargetAccessExtended2                                     Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void TRKTargetAccessExtended2() {
	nofralloc
#include "_include/TRK_MINNOW_DOLPHIN/ppc/Generic/targimpl/TRKTargetAccessExtended2.s"
}
#pragma pop

/* 80370618-80370788 0170 .text      TRKTargetAccessExtended1                                     Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void TRKTargetAccessExtended1() {
	nofralloc
#include "_include/TRK_MINNOW_DOLPHIN/ppc/Generic/targimpl/TRKTargetAccessExtended1.s"
}
#pragma pop

/* 80370788-80370C94 050C .text      TRKTargetAccessFP                                            Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void TRKTargetAccessFP() {
	nofralloc
#include "_include/TRK_MINNOW_DOLPHIN/ppc/Generic/targimpl/TRKTargetAccessFP.s"
}
#pragma pop

/* 80370C94-80370D88 00F4 .text      TRKTargetAccessDefault                                       Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void TRKTargetAccessDefault() {
	nofralloc
#include "_include/TRK_MINNOW_DOLPHIN/ppc/Generic/targimpl/TRKTargetAccessDefault.s"
}
#pragma pop

/* 80370D88-80370DD4 004C .text      TRKTargetReadInstruction                                     Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void TRKTargetReadInstruction() {
	nofralloc
#include "_include/TRK_MINNOW_DOLPHIN/ppc/Generic/targimpl/TRKTargetReadInstruction.s"
}
#pragma pop

/* 80370DD4-80370F20 014C .text      TRKTargetAccessMemory                                        Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void TRKTargetAccessMemory() {
	nofralloc
#include "_include/TRK_MINNOW_DOLPHIN/ppc/Generic/targimpl/TRKTargetAccessMemory.s"
}
#pragma pop

/* 80370F20-803711C4 02A4 .text      TRKValidMemory32                                             Function */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void TRKValidMemory32() {
	nofralloc
#include "_include/TRK_MINNOW_DOLPHIN/ppc/Generic/targimpl/TRKValidMemory32.s"
}
#pragma pop

}

