// 
// Generated By: dol2asm
// Translation Unit: unknown_translation_unit_ctors
// 

#include "dol2asm.h"
#include "dolphin/types.h"
#include "rel/d/a/e/d_a_e_gb/unknown_translation_unit_ctors.h"

// 
// Forward References:
// 


extern void* data_806C74D4[2];

// 
// External References:
// 


extern "C" void __sinit_d_a_e_gb_cpp(); // 1

// 
// Declarations:
// 

/* ############################################################################################## */
#pragma section ".ctors$10"
