// 
// Generated By: dol2asm
// 

#include "dolphin/types.h"

// 
// Additional Symbols:
// 

extern "C" {
extern void PPCMtdec();
extern void __OSSetExceptionHandler();
extern void __OSGetExceptionHandler();
extern void OSInitAlarm();
extern void OSCreateAlarm();
extern void InsertAlarm();
extern void OSSetAlarm();
extern void OSSetPeriodicAlarm();
extern void OSCancelAlarm();
extern void DecrementerExceptionCallback();
extern void DecrementerExceptionHandler();
extern void OSAlarm__OnReset();
extern void OSSetCurrentContext();
extern void OSLoadContext();
extern void OSClearContext();
extern void OSDisableInterrupts();
extern void OSRestoreInterrupts();
extern void OSRegisterResetFunction();
extern void OSDisableScheduler();
extern void OSEnableScheduler();
extern void __OSReschedule();
extern void __OSGetSystemTime();
extern void __OSTimeToSystemTime();
extern void __DVDTestAlarm();
extern void __div2i();
SECTION_DATA extern void* OSAlarm__ResetFunctionInfo[4];
SECTION_SBSS extern u8 AlarmQueue[8];
}


/* ###################################################################################### */
/*                                         .data                                          */
/* ###################################################################################### */

extern "C" {
/* 803CF480-803CF490 0010 .data      ResetFunctionInfo                                            */
SECTION_DATA void* OSAlarm__ResetFunctionInfo[4] = {
	(void*)OSAlarm__OnReset,
	(void*)0xFFFFFFFF,
	NULL,
	NULL,
};
}


/* ###################################################################################### */
/*                                         .sbss                                          */
/* ###################################################################################### */

extern "C" {
/* 80451638-80451640 0008 .sbss      AlarmQueue                                                   */
SECTION_SBSS u8 AlarmQueue[8];
}


/* ###################################################################################### */
/*                                         .text                                          */
/* ###################################################################################### */

/* 8033A8A0-8033A8F8 0058 .text      OSInitAlarm                                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void OSInitAlarm() {
	nofralloc
#include "asm/dolphin/os/OSAlarm/OSInitAlarm.s"
}
#pragma pop

/* 8033A8F8-8033A908 0010 .text      OSCreateAlarm                                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void OSCreateAlarm() {
	nofralloc
#include "asm/dolphin/os/OSAlarm/OSCreateAlarm.s"
}
#pragma pop

/* 8033A908-8033AB58 0250 .text      InsertAlarm                                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void InsertAlarm() {
	nofralloc
#include "asm/dolphin/os/OSAlarm/InsertAlarm.s"
}
#pragma pop

/* 8033AB58-8033ABC0 0068 .text      OSSetAlarm                                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void OSSetAlarm() {
	nofralloc
#include "asm/dolphin/os/OSAlarm/OSSetAlarm.s"
}
#pragma pop

/* 8033ABC0-8033AC3C 007C .text      OSSetPeriodicAlarm                                           */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void OSSetPeriodicAlarm() {
	nofralloc
#include "asm/dolphin/os/OSAlarm/OSSetPeriodicAlarm.s"
}
#pragma pop

/* 8033AC3C-8033AD58 011C .text      OSCancelAlarm                                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void OSCancelAlarm() {
	nofralloc
#include "asm/dolphin/os/OSAlarm/OSCancelAlarm.s"
}
#pragma pop

/* 8033AD58-8033AF88 0230 .text      DecrementerExceptionCallback                                 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void DecrementerExceptionCallback() {
	nofralloc
#include "asm/dolphin/os/OSAlarm/DecrementerExceptionCallback.s"
}
#pragma pop

/* 8033AF88-8033AFD8 0050 .text      DecrementerExceptionHandler                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void DecrementerExceptionHandler() {
	nofralloc
#include "asm/dolphin/os/OSAlarm/DecrementerExceptionHandler.s"
}
#pragma pop

/* 8033AFD8-8033B078 00A0 .text      OnReset                                                      */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void OSAlarm__OnReset() {
	nofralloc
#include "asm/dolphin/os/OSAlarm/OSAlarm__OnReset.s"
}
#pragma pop


