// 
// Generated By: dol2asm
// 

#include "dolphin/types.h"

// 
// Additional Symbols:
// 

extern "C" {
extern const u8 unknown_translation_unit_ctors__data_80C8E648[8];
}


/* ###################################################################################### */
/*                                         .ctors                                         */
/* ###################################################################################### */

extern "C" {
#pragma section ".ctors$10"
}

