// 
// Generated By: dol2asm
// 

#include "dolphin/types.h"

// 
// Additional Symbols:
// 

extern "C" {
extern void _unresolved();
extern void daPPolamp_c_createHeap__FP10fopAc_ac_c();
extern void __dt__11daPPolamp_cFv();
extern void create__11daPPolamp_cFv();
extern void execute__11daPPolamp_cFv();
extern void draw__11daPPolamp_cFv();
extern void Delete__11daPPolamp_cFv();
extern void setModelMtx__11daPPolamp_cFv();
extern void setPclModelMtx__11daPPolamp_cFv();
extern void createHeap__11daPPolamp_cFv();
extern void moveSwing__11daPPolamp_cFv();
extern void initParam__11daPPolamp_cFv();
extern void daPPolamp_create__FP11daPPolamp_c();
extern void __dt__12J3DFrameCtrlFv();
extern void daPPolamp_Delete__FP11daPPolamp_c();
extern void daPPolamp_execute__FP11daPPolamp_c();
extern void daPPolamp_draw__FP11daPPolamp_c();
extern const u8 unknown_translation_unit_ctors__data_80D4D274[4];
extern const u8 unknown_translation_unit_dtors__data_80D4D278[4];
SECTION_RODATA extern const u8 LIT_3757[12];
SECTION_RODATA extern const u8 LIT_3797[8];
SECTION_RODATA extern const u8 LIT_3802[8];
SECTION_RODATA extern const u8 LIT_3859[12];
SECTION_RODATA extern const u8 LIT_3909[4];
SECTION_RODATA extern const u8 LIT_3922[4];
SECTION_RODATA extern const u8 LIT_3923[4];
SECTION_RODATA extern const u8 LIT_3924[4];
SECTION_RODATA extern const u8 LIT_3925[4];
SECTION_RODATA extern const u8 LIT_3926[4];
SECTION_RODATA extern const u8 LIT_3928[8];
SECTION_RODATA extern const u8 LIT_3936[4];
SECTION_RODATA extern const u8 stringBase0[8];
SECTION_DATA extern u8 l_arcName[4];
SECTION_DATA extern u8 daPPolamp_METHODS[32];
SECTION_DATA extern u8 g_profile_PPolamp[48];
SECTION_DATA extern void* __vt__12J3DFrameCtrl[3];
SECTION_DATA extern void* __vt__11daPPolamp_c[3];
SECTION_BSS extern u8 LIT_1109[1 + 3 /* padding */];
SECTION_BSS extern u8 LIT_1107[1 + 3 /* padding */];
SECTION_BSS extern u8 LIT_1105[1 + 3 /* padding */];
SECTION_BSS extern u8 LIT_1104[1 + 3 /* padding */];
SECTION_BSS extern u8 LIT_1099[1 + 3 /* padding */];
SECTION_BSS extern u8 LIT_1097[1 + 3 /* padding */];
SECTION_BSS extern u8 LIT_1095[1 + 3 /* padding */];
SECTION_BSS extern u8 LIT_1094[1 + 3 /* padding */];
SECTION_BSS extern u8 LIT_1057[1 + 3 /* padding */];
SECTION_BSS extern u8 LIT_1055[1 + 3 /* padding */];
SECTION_BSS extern u8 LIT_1053[1 + 3 /* padding */];
SECTION_BSS extern u8 LIT_1052[1 + 3 /* padding */];
SECTION_BSS extern u8 LIT_1014[1 + 3 /* padding */];
SECTION_BSS extern u8 LIT_1012[1 + 3 /* padding */];
SECTION_BSS extern u8 LIT_1010[1 + 3 /* padding */];
SECTION_BSS extern u8 LIT_1009[1 + 3 /* padding */];
SECTION_BSS extern u8 data_80D4D39C[8 + 4 /* padding */];
SECTION_BSS extern u8 data_80D4D3A8[8];
SECTION_BSS extern u8 data_80D4D3B0[4];
SECTION_BSS extern u8 data_80D4D3B4[4];
SECTION_BSS extern u8 data_80D4D3B8[4];
SECTION_BSS extern u8 data_80D4D3BC[4];
SECTION_BSS extern u8 data_80D4D3C0[4];
SECTION_BSS extern u8 data_80D4D3C4[4];
SECTION_BSS extern u8 data_80D4D3C8[4];
SECTION_BSS extern u8 data_80D4D3CC[4];
SECTION_BSS extern u8 data_80D4D3D0[4];
SECTION_BSS extern u8 data_80D4D3D4[4];
SECTION_BSS extern u8 data_80D4D3D8[4];
SECTION_BSS extern u8 data_80D4D3DC[4];
SECTION_BSS extern u8 data_80D4D3E0[4];
SECTION_BSS extern u8 data_80D4D3E4[4];
SECTION_BSS extern u8 data_80D4D3E8[4];
SECTION_BSS extern u8 data_80D4D3EC[4];
SECTION_BSS extern u8 data_80D4D3F0[4];
SECTION_BSS extern u8 data_80D4D3F4[4];
SECTION_BSS extern u8 data_80D4D3F8[4];
SECTION_BSS extern u8 data_80D4D3FC[4];
SECTION_BSS extern u8 data_80D4D400[4];
SECTION_BSS extern u8 data_80D4D404[4];
SECTION_BSS extern u8 data_80D4D408[4];
SECTION_BSS extern u8 data_80D4D40C[4];
SECTION_BSS extern u8 data_80D4D410[4];
}


/* ###################################################################################### */
/*                                        .rodata                                         */
/* ###################################################################################### */

extern "C" {
/* 80D4D2C8-80D4D2D0 0008 .rodata    @stringBase0                                                 */
#pragma push
#pragma force_active on
#pragma section ".dead"
SECTION_DEAD const char* const stringBase_80D4D2C8 = "PPolamp";
#pragma pop
/* 80D4D27C-80D4D27C 0000 .rodata    ...rodata.0                                                  */
/* 80D4D27C-80D4D288 000C .rodata    @3757                                                        */
SECTION_RODATA const u8 LIT_3757[12] = {
	0x00, 0x00, 0x00, 0x00, 0xC2, 0x34, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80D4D288-80D4D290 0008 .rodata    @3797                                                        */
SECTION_RODATA const u8 LIT_3797[8] = {
	0x00, 0x48, 0x00, 0x85, 0x00, 0xFF, 0x00, 0xFF,
};
/* 80D4D290-80D4D298 0008 .rodata    @3802                                                        */
SECTION_RODATA const u8 LIT_3802[8] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x00, 0xFF,
};
/* 80D4D298-80D4D2A4 000C .rodata    @3859                                                        */
SECTION_RODATA const u8 LIT_3859[12] = {
	0x00, 0x00, 0x00, 0x00, 0xC2, 0x34, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80D4D2A4-80D4D2A8 0004 .rodata    @3909                                                        */
SECTION_RODATA const u8 LIT_3909[4] = {
	0x3F, 0x80, 0x00, 0x00,
};
/* 80D4D2A8-80D4D2AC 0004 .rodata    @3922                                                        */
SECTION_RODATA const u8 LIT_3922[4] = {
	0x43, 0xE1, 0x00, 0x00,
};
/* 80D4D2AC-80D4D2B0 0004 .rodata    @3923                                                        */
SECTION_RODATA const u8 LIT_3923[4] = {
	0x3D, 0xCC, 0xCC, 0xCD,
};
/* 80D4D2B0-80D4D2B4 0004 .rodata    @3924                                                        */
SECTION_RODATA const u8 LIT_3924[4] = {
	0x3F, 0x8C, 0xCC, 0xCD,
};
/* 80D4D2B4-80D4D2B8 0004 .rodata    @3925                                                        */
SECTION_RODATA const u8 LIT_3925[4] = {
	0x3D, 0xF5, 0xC2, 0x8F,
};
/* 80D4D2B8-80D4D2BC 0004 .rodata    @3926                                                        */
SECTION_RODATA const u8 LIT_3926[4] = {
	0x42, 0xA0, 0x00, 0x00,
};
/* 80D4D2BC-80D4D2C4 0008 .rodata    @3928                                                        */
SECTION_RODATA const u8 LIT_3928[8] = {
	0x43, 0x30, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00,
};
/* 80D4D2C4-80D4D2C8 0004 .rodata    @3936                                                        */
SECTION_RODATA const u8 LIT_3936[4] = {
	0x3E, 0x4C, 0xCC, 0xCD,
};
}


/* ###################################################################################### */
/*                                         .data                                          */
/* ###################################################################################### */

extern "C" {
/* 80D4D2D4-80D4D2D8 0004 .data      l_arcName                                                    */
SECTION_DATA u8 l_arcName[4] = {
	0x00, 0x00, 0x00, 0x00,
};
/* 80D4D2D8-80D4D2F8 0020 .data      daPPolamp_METHODS                                            */
SECTION_DATA u8 daPPolamp_METHODS[32] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80D4D2F8-80D4D328 0030 .data      g_profile_PPolamp                                            */
SECTION_DATA u8 g_profile_PPolamp[48] = {
	0xFF, 0xFF, 0xFF, 0xFD, 0x00, 0x07, 0xFF, 0xFD, 0x01, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x05, 0xAC, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x02, 0xD7, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x01, 0x80, 0x03, 0x0C, 0x00, 0x00,
};
/* 80D4D328-80D4D334 000C .data      __vt__12J3DFrameCtrl                                         */
SECTION_DATA void* __vt__12J3DFrameCtrl[3] = {
	NULL, /* RTTI */
	NULL,
	NULL,
};
/* 80D4D334-80D4D340 000C .data      __vt__11daPPolamp_c                                          */
SECTION_DATA void* __vt__11daPPolamp_c[3] = {
	NULL, /* RTTI */
	NULL,
	NULL,
};
}


/* ###################################################################################### */
/*                                          .bss                                          */
/* ###################################################################################### */

extern "C" {
/* 80D4D35C-80D4D35C 0000 .bss       ...bss.0                                                     */
/* 80D4D35C-80D4D360 0001 .bss       @1109                                                        */
SECTION_BSS u8 LIT_1109[1 + 3 /* padding */];
/* 80D4D360-80D4D364 0001 .bss       @1107                                                        */
SECTION_BSS u8 LIT_1107[1 + 3 /* padding */];
/* 80D4D364-80D4D368 0001 .bss       @1105                                                        */
SECTION_BSS u8 LIT_1105[1 + 3 /* padding */];
/* 80D4D368-80D4D36C 0001 .bss       @1104                                                        */
SECTION_BSS u8 LIT_1104[1 + 3 /* padding */];
/* 80D4D36C-80D4D370 0001 .bss       @1099                                                        */
SECTION_BSS u8 LIT_1099[1 + 3 /* padding */];
/* 80D4D370-80D4D374 0001 .bss       @1097                                                        */
SECTION_BSS u8 LIT_1097[1 + 3 /* padding */];
/* 80D4D374-80D4D378 0001 .bss       @1095                                                        */
SECTION_BSS u8 LIT_1095[1 + 3 /* padding */];
/* 80D4D378-80D4D37C 0001 .bss       @1094                                                        */
SECTION_BSS u8 LIT_1094[1 + 3 /* padding */];
/* 80D4D37C-80D4D380 0001 .bss       @1057                                                        */
SECTION_BSS u8 LIT_1057[1 + 3 /* padding */];
/* 80D4D380-80D4D384 0001 .bss       @1055                                                        */
SECTION_BSS u8 LIT_1055[1 + 3 /* padding */];
/* 80D4D384-80D4D388 0001 .bss       @1053                                                        */
SECTION_BSS u8 LIT_1053[1 + 3 /* padding */];
/* 80D4D388-80D4D38C 0001 .bss       @1052                                                        */
SECTION_BSS u8 LIT_1052[1 + 3 /* padding */];
/* 80D4D38C-80D4D390 0001 .bss       @1014                                                        */
SECTION_BSS u8 LIT_1014[1 + 3 /* padding */];
/* 80D4D390-80D4D394 0001 .bss       @1012                                                        */
SECTION_BSS u8 LIT_1012[1 + 3 /* padding */];
/* 80D4D394-80D4D398 0001 .bss       @1010                                                        */
SECTION_BSS u8 LIT_1010[1 + 3 /* padding */];
/* 80D4D398-80D4D39C 0001 .bss       @1009                                                        */
SECTION_BSS u8 LIT_1009[1 + 3 /* padding */];
/* 80D4D39C-80D4D3A8 0008 .bss       TEV_COLOR_1$3795                                             */
SECTION_BSS u8 data_80D4D39C[8 + 4 /* padding */];
/* 80D4D3A8-80D4D3B0 0008 .bss       TEV_COLOR_2$3800                                             */
SECTION_BSS u8 data_80D4D3A8[8];
/* 80D4D3B0-80D4D3B4 0004 .bss       sInstance__40JASGlobalInstance<19JASDefaultBankTable>        */
SECTION_BSS u8 data_80D4D3B0[4];
/* 80D4D3B4-80D4D3B8 0004 .bss       sInstance__35JASGlobalInstance<14JASAudioThread>             */
SECTION_BSS u8 data_80D4D3B4[4];
/* 80D4D3B8-80D4D3BC 0004 .bss       sInstance__27JASGlobalInstance<7Z2SeMgr>                     */
SECTION_BSS u8 data_80D4D3B8[4];
/* 80D4D3BC-80D4D3C0 0004 .bss       sInstance__28JASGlobalInstance<8Z2SeqMgr>                    */
SECTION_BSS u8 data_80D4D3BC[4];
/* 80D4D3C0-80D4D3C4 0004 .bss       sInstance__31JASGlobalInstance<10Z2SceneMgr>                 */
SECTION_BSS u8 data_80D4D3C0[4];
/* 80D4D3C4-80D4D3C8 0004 .bss       sInstance__32JASGlobalInstance<11Z2StatusMgr>                */
SECTION_BSS u8 data_80D4D3C4[4];
/* 80D4D3C8-80D4D3CC 0004 .bss       sInstance__31JASGlobalInstance<10Z2DebugSys>                 */
SECTION_BSS u8 data_80D4D3C8[4];
/* 80D4D3CC-80D4D3D0 0004 .bss       sInstance__36JASGlobalInstance<15JAISoundStarter>            */
SECTION_BSS u8 data_80D4D3CC[4];
/* 80D4D3D0-80D4D3D4 0004 .bss       sInstance__35JASGlobalInstance<14Z2SoundStarter>             */
SECTION_BSS u8 data_80D4D3D0[4];
/* 80D4D3D4-80D4D3D8 0004 .bss       sInstance__33JASGlobalInstance<12Z2SpeechMgr2>               */
SECTION_BSS u8 data_80D4D3D4[4];
/* 80D4D3D8-80D4D3DC 0004 .bss       sInstance__28JASGlobalInstance<8JAISeMgr>                    */
SECTION_BSS u8 data_80D4D3D8[4];
/* 80D4D3DC-80D4D3E0 0004 .bss       sInstance__29JASGlobalInstance<9JAISeqMgr>                   */
SECTION_BSS u8 data_80D4D3DC[4];
/* 80D4D3E0-80D4D3E4 0004 .bss       sInstance__33JASGlobalInstance<12JAIStreamMgr>               */
SECTION_BSS u8 data_80D4D3E0[4];
/* 80D4D3E4-80D4D3E8 0004 .bss       sInstance__31JASGlobalInstance<10Z2SoundMgr>                 */
SECTION_BSS u8 data_80D4D3E4[4];
/* 80D4D3E8-80D4D3EC 0004 .bss       sInstance__33JASGlobalInstance<12JAISoundInfo>               */
SECTION_BSS u8 data_80D4D3E8[4];
/* 80D4D3EC-80D4D3F0 0004 .bss       sInstance__34JASGlobalInstance<13JAUSoundTable>              */
SECTION_BSS u8 data_80D4D3EC[4];
/* 80D4D3F0-80D4D3F4 0004 .bss       sInstance__38JASGlobalInstance<17JAUSoundNameTable>          */
SECTION_BSS u8 data_80D4D3F0[4];
/* 80D4D3F4-80D4D3F8 0004 .bss       sInstance__33JASGlobalInstance<12JAUSoundInfo>               */
SECTION_BSS u8 data_80D4D3F4[4];
/* 80D4D3F8-80D4D3FC 0004 .bss       sInstance__32JASGlobalInstance<11Z2SoundInfo>                */
SECTION_BSS u8 data_80D4D3F8[4];
/* 80D4D3FC-80D4D400 0004 .bss       sInstance__34JASGlobalInstance<13Z2SoundObjMgr>              */
SECTION_BSS u8 data_80D4D3FC[4];
/* 80D4D400-80D4D404 0004 .bss       sInstance__31JASGlobalInstance<10Z2Audience>                 */
SECTION_BSS u8 data_80D4D400[4];
/* 80D4D404-80D4D408 0004 .bss       sInstance__32JASGlobalInstance<11Z2FxLineMgr>                */
SECTION_BSS u8 data_80D4D404[4];
/* 80D4D408-80D4D40C 0004 .bss       sInstance__31JASGlobalInstance<10Z2EnvSeMgr>                 */
SECTION_BSS u8 data_80D4D408[4];
/* 80D4D40C-80D4D410 0004 .bss       sInstance__32JASGlobalInstance<11Z2SpeechMgr>                */
SECTION_BSS u8 data_80D4D40C[4];
/* 80D4D410-80D4D414 0004 .bss       sInstance__34JASGlobalInstance<13Z2WolfHowlMgr>              */
SECTION_BSS u8 data_80D4D410[4];
}


/* ###################################################################################### */
/*                                         .text                                          */
/* ###################################################################################### */

/* 80D4C938-80D4C958 0020 .text      daPPolamp_c_createHeap__FP10fopAc_ac_c                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daPPolamp_c_createHeap__FP10fopAc_ac_c() {
	nofralloc
#include "asm/rel/d_a_ppolamp/d_a_ppolamp/daPPolamp_c_createHeap__FP10fopAc_ac_c.s"
}
#pragma pop

/* 80D4C958-80D4C9FC 00A4 .text      __dt__11daPPolamp_cFv                                        */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__11daPPolamp_cFv() {
	nofralloc
#include "asm/rel/d_a_ppolamp/d_a_ppolamp/__dt__11daPPolamp_cFv.s"
}
#pragma pop

/* 80D4C9FC-80D4CB24 0128 .text      create__11daPPolamp_cFv                                      */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void create__11daPPolamp_cFv() {
	nofralloc
#include "asm/rel/d_a_ppolamp/d_a_ppolamp/create__11daPPolamp_cFv.s"
}
#pragma pop

/* 80D4CB24-80D4CB84 0060 .text      execute__11daPPolamp_cFv                                     */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void execute__11daPPolamp_cFv() {
	nofralloc
#include "asm/rel/d_a_ppolamp/d_a_ppolamp/execute__11daPPolamp_cFv.s"
}
#pragma pop

/* 80D4CB84-80D4CCF0 016C .text      draw__11daPPolamp_cFv                                        */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void draw__11daPPolamp_cFv() {
	nofralloc
#include "asm/rel/d_a_ppolamp/d_a_ppolamp/draw__11daPPolamp_cFv.s"
}
#pragma pop

/* 80D4CCF0-80D4CD24 0034 .text      Delete__11daPPolamp_cFv                                      */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void Delete__11daPPolamp_cFv() {
	nofralloc
#include "asm/rel/d_a_ppolamp/d_a_ppolamp/Delete__11daPPolamp_cFv.s"
}
#pragma pop

/* 80D4CD24-80D4CDA8 0084 .text      setModelMtx__11daPPolamp_cFv                                 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void setModelMtx__11daPPolamp_cFv() {
	nofralloc
#include "asm/rel/d_a_ppolamp/d_a_ppolamp/setModelMtx__11daPPolamp_cFv.s"
}
#pragma pop

/* 80D4CDA8-80D4CE9C 00F4 .text      setPclModelMtx__11daPPolamp_cFv                              */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void setPclModelMtx__11daPPolamp_cFv() {
	nofralloc
#include "asm/rel/d_a_ppolamp/d_a_ppolamp/setPclModelMtx__11daPPolamp_cFv.s"
}
#pragma pop

/* 80D4CE9C-80D4CFB0 0114 .text      createHeap__11daPPolamp_cFv                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void createHeap__11daPPolamp_cFv() {
	nofralloc
#include "asm/rel/d_a_ppolamp/d_a_ppolamp/createHeap__11daPPolamp_cFv.s"
}
#pragma pop

/* 80D4CFB0-80D4D10C 015C .text      moveSwing__11daPPolamp_cFv                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void moveSwing__11daPPolamp_cFv() {
	nofralloc
#include "asm/rel/d_a_ppolamp/d_a_ppolamp/moveSwing__11daPPolamp_cFv.s"
}
#pragma pop

/* 80D4D10C-80D4D140 0034 .text      initParam__11daPPolamp_cFv                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void initParam__11daPPolamp_cFv() {
	nofralloc
#include "asm/rel/d_a_ppolamp/d_a_ppolamp/initParam__11daPPolamp_cFv.s"
}
#pragma pop

/* 80D4D140-80D4D1CC 008C .text      daPPolamp_create__FP11daPPolamp_c                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daPPolamp_create__FP11daPPolamp_c() {
	nofralloc
#include "asm/rel/d_a_ppolamp/d_a_ppolamp/daPPolamp_create__FP11daPPolamp_c.s"
}
#pragma pop

/* 80D4D1CC-80D4D214 0048 .text      __dt__12J3DFrameCtrlFv                                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__12J3DFrameCtrlFv() {
	nofralloc
#include "asm/rel/d_a_ppolamp/d_a_ppolamp/__dt__12J3DFrameCtrlFv.s"
}
#pragma pop

/* 80D4D214-80D4D234 0020 .text      daPPolamp_Delete__FP11daPPolamp_c                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daPPolamp_Delete__FP11daPPolamp_c() {
	nofralloc
#include "asm/rel/d_a_ppolamp/d_a_ppolamp/daPPolamp_Delete__FP11daPPolamp_c.s"
}
#pragma pop

/* 80D4D234-80D4D254 0020 .text      daPPolamp_execute__FP11daPPolamp_c                           */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daPPolamp_execute__FP11daPPolamp_c() {
	nofralloc
#include "asm/rel/d_a_ppolamp/d_a_ppolamp/daPPolamp_execute__FP11daPPolamp_c.s"
}
#pragma pop

/* 80D4D254-80D4D274 0020 .text      daPPolamp_draw__FP11daPPolamp_c                              */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daPPolamp_draw__FP11daPPolamp_c() {
	nofralloc
#include "asm/rel/d_a_ppolamp/d_a_ppolamp/daPPolamp_draw__FP11daPPolamp_c.s"
}
#pragma pop


