// 
// Generated By: dol2asm
// Translation Unit: MSL_Common/Src/FILE_POS
// 

#include "dolphin/types.h"

// 
// Forward References:
// 

extern "C" void fseek(); // 1
extern "C" static void _fseek(); // 1
extern "C" void ftell(); // 1

extern "C" void fseek(); // 1
extern "C" static void _fseek(); // 1
extern "C" void ftell(); // 1

// 
// External References:
// 

extern "C" void __flush_buffer(); // 1
extern "C" void __end_critical_region(); // 1
extern "C" void __begin_critical_region(); // 1

extern "C" void __flush_buffer(); // 1
extern "C" void __end_critical_region(); // 1
extern "C" void __begin_critical_region(); // 1
extern "C" extern u8 errno[4 + 4 /* padding */];

// 
// Declarations:
// 

/* 80365BB4-80365C20 006C+00 rc=2 efc=2 rfr=False None .text      fseek                                                        */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void fseek() {
	nofralloc
#include "asm/MSL_C.PPCEABI.bare.H/MSL_Common/Src/FILE_POS/fseek.s"
}
#pragma pop


/* 80365C20-80365E90 0270+00 rc=1 efc=0 rfr=False None .text      _fseek                                                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm static void _fseek() {
	nofralloc
#include "asm/MSL_C.PPCEABI.bare.H/MSL_Common/Src/FILE_POS/_fseek.s"
}
#pragma pop


/* 80365E90-80365F74 00E4+00 rc=2 efc=2 rfr=False None .text      ftell                                                        */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void ftell() {
	nofralloc
#include "asm/MSL_C.PPCEABI.bare.H/MSL_Common/Src/FILE_POS/ftell.s"
}
#pragma pop


