// 
// Generated By: dol2asm
// Translation Unit: unknown_translation_unit_ctors
// 

#include "dol2asm.h"
#include "dolphin/types.h"
#include "rel/d/a/b/d_a_b_tn/unknown_translation_unit_ctors.h"

// 
// Forward References:
// 


extern u8 data_8062E620[8];

// 
// External References:
// 



// 
// Declarations:
// 

/* ############################################################################################## */
#pragma section ".ctors$10"
