// 
// Generated By: dol2asm
// 

#include "dolphin/types.h"

// 
// Additional Symbols:
// 

extern "C" {
extern void _unresolved();
extern void __register_global_object();
extern void __ct__12daE_SF_HIO_cFv();
extern void anm_init__FP10e_sf_classifUcf();
extern void nodeCallBack__FP8J3DJointi();
extern void daE_SF_Draw__FP10e_sf_class();
extern void other_bg_check__FP10e_sf_classP10fopAc_ac_c();
extern void player_way_check__FP10e_sf_class();
extern void way_bg_check__FP10e_sf_classff();
extern void pl_check__FP10e_sf_classfs();
extern void e_sf_normal__FP10e_sf_class();
extern void e_sf_drawback__FP10e_sf_class();
extern void e_sf_fight_run__FP10e_sf_class();
extern void at_hit_check__FP10e_sf_class();
extern void e_sf_attack_0__FP10e_sf_class();
extern void e_sf_attack__FP10e_sf_class();
extern void e_sf_guard__FP10e_sf_class();
extern void e_sf_s_damage__FP10e_sf_class();
extern void e_sf_crash__FP10e_sf_class();
extern void e_sf_crashwait__FP10e_sf_class();
extern void e_sf_sitwait__FP10e_sf_class();
extern void e_sf_getup__FP10e_sf_class();
extern void crash_eff__FP10e_sf_class();
extern void damage_check__FP10e_sf_class();
extern void action__FP10e_sf_class();
extern void anm_se_set__FP10e_sf_class();
extern void demo_camera__FP10e_sf_class();
extern void daE_SF_Execute__FP10e_sf_class();
extern void daE_SF_IsDelete__FP10e_sf_class();
extern void daE_SF_Delete__FP10e_sf_class();
extern void useHeapInit__FP10fopAc_ac_c();
extern void daE_SF_Create__FP10fopAc_ac_c();
extern void __dt__8cM3dGSphFv();
extern void __dt__8cM3dGAabFv();
extern void __dt__8dCcD_SphFv();
extern void __ct__8dCcD_SphFv();
extern void __dt__10dCcD_GSttsFv();
extern void __dt__12dBgS_ObjAcchFv();
extern void __dt__12dBgS_AcchCirFv();
extern void __dt__10cCcD_GSttsFv();
extern void __dt__12daE_SF_HIO_cFv();
extern void __sinit_d_a_e_sf_cpp();
extern void func_80789800();
extern void func_80789808();
extern void setMidnaBindEffect__FP13fopEn_enemy_cP15Z2CreatureEnemyP4cXyzP4cXyz();
extern const u8 unknown_translation_unit_ctors__data_80789C24[8];
extern const void* __destroy_global_chain_reference;
SECTION_RODATA extern const u8 LIT_3908[4];
SECTION_RODATA extern const u8 LIT_3909[4];
SECTION_RODATA extern const u8 LIT_3910[8];
SECTION_RODATA extern const u8 LIT_3911[8];
SECTION_RODATA extern const u8 LIT_3912[8];
SECTION_RODATA extern const u8 LIT_3913[8];
SECTION_RODATA extern const u8 LIT_3914[4];
SECTION_RODATA extern const u8 LIT_3929[4];
SECTION_RODATA extern const u8 LIT_3930[4];
SECTION_RODATA extern const u8 LIT_3931[4];
SECTION_RODATA extern const u8 LIT_3932[4];
SECTION_RODATA extern const u8 LIT_3933[4];
SECTION_RODATA extern const u8 LIT_3934[4];
SECTION_RODATA extern const u8 LIT_3948[4];
SECTION_RODATA extern const u8 LIT_4069[4];
SECTION_RODATA extern const u8 LIT_4070[4];
SECTION_RODATA extern const u8 LIT_4234[4];
SECTION_RODATA extern const u8 LIT_4235[4];
SECTION_RODATA extern const u8 LIT_4236[4];
SECTION_RODATA extern const u8 LIT_4237[4];
SECTION_RODATA extern const u8 LIT_4238[4];
SECTION_RODATA extern const u8 LIT_4239[4];
SECTION_RODATA extern const u8 LIT_4262[4];
SECTION_RODATA extern const u8 LIT_4263[4];
SECTION_RODATA extern const u8 LIT_4349[4];
SECTION_RODATA extern const u8 LIT_4350[4];
SECTION_RODATA extern const u8 LIT_4351[4];
SECTION_RODATA extern const u8 LIT_4352[4];
SECTION_RODATA extern const u8 LIT_4396[4];
SECTION_RODATA extern const u8 LIT_4458[4];
SECTION_RODATA extern const u8 LIT_4509[4];
SECTION_RODATA extern const u8 LIT_4510[4];
SECTION_RODATA extern const u8 LIT_4556[4];
SECTION_RODATA extern const u8 LIT_4663[4];
SECTION_RODATA extern const u8 LIT_4665[8];
SECTION_RODATA extern const u8 LIT_4790[4];
SECTION_RODATA extern const u8 LIT_4878[4];
SECTION_RODATA extern const u8 LIT_5196[4];
SECTION_RODATA extern const u8 LIT_5197[4];
SECTION_RODATA extern const u8 LIT_5198[4];
SECTION_RODATA extern const u8 LIT_5199[4];
SECTION_RODATA extern const u8 LIT_5200[4];
SECTION_RODATA extern const u8 LIT_5201[4];
SECTION_RODATA extern const u8 LIT_5202[4];
SECTION_RODATA extern const u8 LIT_5203[4];
SECTION_RODATA extern const u8 LIT_5204[8];
SECTION_RODATA extern const u8 LIT_5207[8];
SECTION_RODATA extern const u8 LIT_5267[4];
SECTION_RODATA extern const u8 LIT_5268[4];
SECTION_RODATA extern const u8 LIT_5269[4];
SECTION_RODATA extern const u8 LIT_5270[4];
SECTION_RODATA extern const u8 LIT_5271[4];
SECTION_RODATA extern const u8 LIT_5272[4];
SECTION_RODATA extern const u8 LIT_5273[4];
SECTION_RODATA extern const u8 LIT_5274[4];
SECTION_RODATA extern const u8 LIT_5275[4];
SECTION_RODATA extern const u8 LIT_5276[4];
SECTION_RODATA extern const u8 LIT_5447[4];
SECTION_RODATA extern const u8 LIT_5448[4];
SECTION_RODATA extern const u8 LIT_5449[4];
SECTION_RODATA extern const u8 LIT_5450[4];
SECTION_RODATA extern const u8 LIT_5451[4];
SECTION_RODATA extern const u8 LIT_5452[4];
SECTION_RODATA extern const u8 LIT_5453[4];
SECTION_RODATA extern const u8 LIT_5454[4];
SECTION_RODATA extern const u8 LIT_5676[4];
SECTION_RODATA extern const u8 LIT_5677[4];
SECTION_RODATA extern const u8 LIT_5678[4];
SECTION_RODATA extern const u8 LIT_5679[4];
SECTION_RODATA extern const u8 LIT_5680[4];
SECTION_RODATA extern const u8 LIT_5681[4];
SECTION_RODATA extern const u8 LIT_5682[4];
SECTION_RODATA extern const u8 LIT_5683[4];
SECTION_RODATA extern const u8 LIT_5684[4];
SECTION_RODATA extern const u8 LIT_5929[4];
SECTION_RODATA extern const u8 LIT_5930[4];
SECTION_RODATA extern const u8 stringBase0[12];
SECTION_DATA extern u8 cNullVec__6Z2Calc[12];
SECTION_DATA extern u8 LIT_1787[20];
SECTION_DATA extern u8 data_80789DB4[8];
SECTION_DATA extern u8 data_80789DBC[8];
SECTION_DATA extern u8 data_80789DC4[8];
SECTION_DATA extern u8 LIT_4353[56];
SECTION_DATA extern u8 data_80789E04[8];
SECTION_DATA extern u8 data_80789E0C[8];
SECTION_DATA extern u8 LIT_5205[136];
SECTION_DATA extern u8 data_80789E9C[4];
SECTION_DATA extern u8 data_80789EA0[8];
SECTION_DATA extern u8 data_80789EA8[8];
SECTION_DATA extern u8 data_80789EB0[64];
SECTION_DATA extern u8 data_80789EF0[64];
SECTION_DATA extern u8 data_80789F30[64];
SECTION_DATA extern u8 l_daE_SF_Method[32];
SECTION_DATA extern u8 g_profile_E_SF[48];
SECTION_DATA extern void* __vt__12dBgS_AcchCir[3];
SECTION_DATA extern void* __vt__10cCcD_GStts[3];
SECTION_DATA extern void* __vt__10dCcD_GStts[3];
SECTION_DATA extern void* __vt__8cM3dGSph[3];
SECTION_DATA extern void* __vt__8cM3dGAab[3];
SECTION_DATA extern void* __vt__12dBgS_ObjAcch[9];
SECTION_DATA extern void* __vt__12daE_SF_HIO_c[3];
SECTION_BSS extern u8 __global_destructor_chain[4 + 4 /* padding */];
SECTION_BSS extern u8 LIT_1109[1 + 3 /* padding */];
SECTION_BSS extern u8 LIT_1107[1 + 3 /* padding */];
SECTION_BSS extern u8 LIT_1105[1 + 3 /* padding */];
SECTION_BSS extern u8 LIT_1104[1 + 3 /* padding */];
SECTION_BSS extern u8 LIT_1099[1 + 3 /* padding */];
SECTION_BSS extern u8 LIT_1097[1 + 3 /* padding */];
SECTION_BSS extern u8 LIT_1095[1 + 3 /* padding */];
SECTION_BSS extern u8 LIT_1094[1 + 3 /* padding */];
SECTION_BSS extern u8 LIT_1057[1 + 3 /* padding */];
SECTION_BSS extern u8 LIT_1055[1 + 3 /* padding */];
SECTION_BSS extern u8 LIT_1053[1 + 3 /* padding */];
SECTION_BSS extern u8 LIT_1052[1 + 3 /* padding */];
SECTION_BSS extern u8 LIT_1014[1 + 3 /* padding */];
SECTION_BSS extern u8 LIT_1012[1 + 3 /* padding */];
SECTION_BSS extern u8 LIT_1010[1 + 3 /* padding */];
SECTION_BSS extern u8 struct_8078A070[4];
SECTION_BSS extern u8 LIT_3924[12];
SECTION_BSS extern u8 l_HIO[40];
SECTION_BSS extern u8 target_info[40];
SECTION_BSS extern u8 target_info_count[4];
SECTION_BSS extern u8 ret_ct[4];
SECTION_BSS extern u8 data_8078A0D8[4];
SECTION_BSS extern u8 data_8078A0DC[4];
SECTION_BSS extern u8 data_8078A0E0[4];
SECTION_BSS extern u8 data_8078A0E4[4];
SECTION_BSS extern u8 data_8078A0E8[4];
SECTION_BSS extern u8 data_8078A0EC[4];
SECTION_BSS extern u8 data_8078A0F0[4];
SECTION_BSS extern u8 data_8078A0F4[4];
SECTION_BSS extern u8 data_8078A0F8[4];
SECTION_BSS extern u8 data_8078A0FC[4];
SECTION_BSS extern u8 data_8078A100[4];
SECTION_BSS extern u8 data_8078A104[4];
SECTION_BSS extern u8 data_8078A108[4];
SECTION_BSS extern u8 data_8078A10C[4];
SECTION_BSS extern u8 data_8078A110[4];
SECTION_BSS extern u8 data_8078A114[4];
SECTION_BSS extern u8 data_8078A118[4];
SECTION_BSS extern u8 data_8078A11C[4];
SECTION_BSS extern u8 data_8078A120[4];
SECTION_BSS extern u8 data_8078A124[4];
SECTION_BSS extern u8 data_8078A128[4];
SECTION_BSS extern u8 data_8078A12C[4];
SECTION_BSS extern u8 data_8078A130[4];
SECTION_BSS extern u8 data_8078A134[4];
SECTION_BSS extern u8 data_8078A138[4];
}


/* ###################################################################################### */
/*                                        .rodata                                         */
/* ###################################################################################### */

extern "C" {
/* 80789D88-80789D94 000C .rodata    @stringBase0                                                 */
#pragma push
#pragma force_active on
#pragma section ".dead"
SECTION_DEAD const char* const stringBase_80789D88 = "E_sf";
SECTION_DEAD const char* const stringBase_80789D8D = "D_MN10";
#pragma pop
/* 80789C3C-80789C3C 0000 .rodata    ...rodata.0                                                  */
/* 80789C3C-80789C40 0004 .rodata    @3908                                                        */
SECTION_RODATA const u8 LIT_3908[4] = {
	0x42, 0xC8, 0x00, 0x00,
};
/* 80789C40-80789C44 0004 .rodata    @3909                                                        */
SECTION_RODATA const u8 LIT_3909[4] = {
	0x00, 0x00, 0x00, 0x00,
};
/* 80789C44-80789C4C 0004 .rodata    @3910                                                        */
SECTION_RODATA const u8 LIT_3910[8] = {
	0x3F, 0x80, 0x00, 0x00,
	/* padding */
	0x00, 0x00, 0x00, 0x00,
};
/* 80789C4C-80789C54 0008 .rodata    @3911                                                        */
SECTION_RODATA const u8 LIT_3911[8] = {
	0x3F, 0xE0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80789C54-80789C5C 0008 .rodata    @3912                                                        */
SECTION_RODATA const u8 LIT_3912[8] = {
	0x40, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80789C5C-80789C64 0008 .rodata    @3913                                                        */
SECTION_RODATA const u8 LIT_3913[8] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80789C64-80789C68 0004 .rodata    @3914                                                        */
SECTION_RODATA const u8 LIT_3914[4] = {
	0x3C, 0x23, 0xD7, 0x0A,
};
/* 80789C68-80789C6C 0004 .rodata    @3929                                                        */
SECTION_RODATA const u8 LIT_3929[4] = {
	0x3F, 0x99, 0x99, 0x9A,
};
/* 80789C6C-80789C70 0004 .rodata    @3930                                                        */
SECTION_RODATA const u8 LIT_3930[4] = {
	0x40, 0xA0, 0x00, 0x00,
};
/* 80789C70-80789C74 0004 .rodata    @3931                                                        */
SECTION_RODATA const u8 LIT_3931[4] = {
	0x45, 0x3B, 0x80, 0x00,
};
/* 80789C74-80789C78 0004 .rodata    @3932                                                        */
SECTION_RODATA const u8 LIT_3932[4] = {
	0x41, 0x20, 0x00, 0x00,
};
/* 80789C78-80789C7C 0004 .rodata    @3933                                                        */
SECTION_RODATA const u8 LIT_3933[4] = {
	0x43, 0x7A, 0x00, 0x00,
};
/* 80789C7C-80789C80 0004 .rodata    @3934                                                        */
SECTION_RODATA const u8 LIT_3934[4] = {
	0x43, 0x96, 0x00, 0x00,
};
/* 80789C80-80789C84 0004 .rodata    @3948                                                        */
SECTION_RODATA const u8 LIT_3948[4] = {
	0xBF, 0x80, 0x00, 0x00,
};
/* 80789C84-80789C88 0004 .rodata    @4069                                                        */
SECTION_RODATA const u8 LIT_4069[4] = {
	0x42, 0x48, 0x00, 0x00,
};
/* 80789C88-80789C8C 0004 .rodata    @4070                                                        */
SECTION_RODATA const u8 LIT_4070[4] = {
	0x44, 0x61, 0x00, 0x00,
};
/* 80789C8C-80789C90 0004 .rodata    @4234                                                        */
SECTION_RODATA const u8 LIT_4234[4] = {
	0x43, 0x48, 0x00, 0x00,
};
/* 80789C90-80789C94 0004 .rodata    @4235                                                        */
SECTION_RODATA const u8 LIT_4235[4] = {
	0x47, 0x00, 0x00, 0x00,
};
/* 80789C94-80789C98 0004 .rodata    @4236                                                        */
SECTION_RODATA const u8 LIT_4236[4] = {
	0x46, 0x1C, 0x40, 0x00,
};
/* 80789C98-80789C9C 0004 .rodata    @4237                                                        */
SECTION_RODATA const u8 LIT_4237[4] = {
	0x44, 0x16, 0x00, 0x00,
};
/* 80789C9C-80789CA0 0004 .rodata    @4238                                                        */
SECTION_RODATA const u8 LIT_4238[4] = {
	0x40, 0x40, 0x00, 0x00,
};
/* 80789CA0-80789CA4 0004 .rodata    @4239                                                        */
SECTION_RODATA const u8 LIT_4239[4] = {
	0x44, 0xFA, 0x00, 0x00,
};
/* 80789CA4-80789CA8 0004 .rodata    @4262                                                        */
SECTION_RODATA const u8 LIT_4262[4] = {
	0xC0, 0xA0, 0x00, 0x00,
};
/* 80789CA8-80789CAC 0004 .rodata    @4263                                                        */
SECTION_RODATA const u8 LIT_4263[4] = {
	0x3D, 0xCC, 0xCC, 0xCD,
};
/* 80789CAC-80789CB0 0004 .rodata    @4349                                                        */
SECTION_RODATA const u8 LIT_4349[4] = {
	0x41, 0x70, 0x00, 0x00,
};
/* 80789CB0-80789CB4 0004 .rodata    @4350                                                        */
SECTION_RODATA const u8 LIT_4350[4] = {
	0x3D, 0x4C, 0xCC, 0xCD,
};
/* 80789CB4-80789CB8 0004 .rodata    @4351                                                        */
SECTION_RODATA const u8 LIT_4351[4] = {
	0x41, 0xA0, 0x00, 0x00,
};
/* 80789CB8-80789CBC 0004 .rodata    @4352                                                        */
SECTION_RODATA const u8 LIT_4352[4] = {
	0x3F, 0x00, 0x00, 0x00,
};
/* 80789CBC-80789CC0 0004 .rodata    @4396                                                        */
SECTION_RODATA const u8 LIT_4396[4] = {
	0x42, 0x20, 0x00, 0x00,
};
/* 80789CC0-80789CC4 0004 .rodata    @4458                                                        */
SECTION_RODATA const u8 LIT_4458[4] = {
	0x40, 0xC0, 0x00, 0x00,
};
/* 80789CC4-80789CC8 0004 .rodata    @4509                                                        */
SECTION_RODATA const u8 LIT_4509[4] = {
	0x41, 0x00, 0x00, 0x00,
};
/* 80789CC8-80789CCC 0004 .rodata    @4510                                                        */
SECTION_RODATA const u8 LIT_4510[4] = {
	0x42, 0x5C, 0x00, 0x00,
};
/* 80789CCC-80789CD0 0004 .rodata    @4556                                                        */
SECTION_RODATA const u8 LIT_4556[4] = {
	0x40, 0x00, 0x00, 0x00,
};
/* 80789CD0-80789CD4 0004 .rodata    @4663                                                        */
SECTION_RODATA const u8 LIT_4663[4] = {
	0x42, 0x1C, 0x00, 0x00,
};
/* 80789CD4-80789CDC 0008 .rodata    @4665                                                        */
SECTION_RODATA const u8 LIT_4665[8] = {
	0x43, 0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80789CDC-80789CE0 0004 .rodata    @4790                                                        */
SECTION_RODATA const u8 LIT_4790[4] = {
	0x3F, 0xC0, 0x00, 0x00,
};
/* 80789CE0-80789CE4 0004 .rodata    @4878                                                        */
SECTION_RODATA const u8 LIT_4878[4] = {
	0x41, 0xC8, 0x00, 0x00,
};
/* 80789CE4-80789CE8 0004 .rodata    @5196                                                        */
SECTION_RODATA const u8 LIT_5196[4] = {
	0x3E, 0x4C, 0xCC, 0xCD,
};
/* 80789CE8-80789CEC 0004 .rodata    @5197                                                        */
SECTION_RODATA const u8 LIT_5197[4] = {
	0xC0, 0x80, 0x00, 0x00,
};
/* 80789CEC-80789CF0 0004 .rodata    @5198                                                        */
SECTION_RODATA const u8 LIT_5198[4] = {
	0xC2, 0xF0, 0x00, 0x00,
};
/* 80789CF0-80789CF4 0004 .rodata    @5199                                                        */
SECTION_RODATA const u8 LIT_5199[4] = {
	0x40, 0xE0, 0x00, 0x00,
};
/* 80789CF4-80789CF8 0004 .rodata    @5200                                                        */
SECTION_RODATA const u8 LIT_5200[4] = {
	0x3E, 0x99, 0x99, 0x9A,
};
/* 80789CF8-80789CFC 0004 .rodata    @5201                                                        */
SECTION_RODATA const u8 LIT_5201[4] = {
	0x45, 0x1C, 0x40, 0x00,
};
/* 80789CFC-80789D00 0004 .rodata    @5202                                                        */
SECTION_RODATA const u8 LIT_5202[4] = {
	0xC3, 0x16, 0x00, 0x00,
};
/* 80789D00-80789D04 0004 .rodata    @5203                                                        */
SECTION_RODATA const u8 LIT_5203[4] = {
	0x45, 0x7A, 0x00, 0x00,
};
/* 80789D04-80789D0C 0004 .rodata    @5204                                                        */
SECTION_RODATA const u8 LIT_5204[8] = {
	0xCE, 0x6E, 0x6B, 0x28,
	/* padding */
	0x00, 0x00, 0x00, 0x00,
};
/* 80789D0C-80789D14 0008 .rodata    @5207                                                        */
SECTION_RODATA const u8 LIT_5207[8] = {
	0x43, 0x30, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00,
};
/* 80789D14-80789D18 0004 .rodata    @5267                                                        */
SECTION_RODATA const u8 LIT_5267[4] = {
	0x42, 0xA6, 0x00, 0x00,
};
/* 80789D18-80789D1C 0004 .rodata    @5268                                                        */
SECTION_RODATA const u8 LIT_5268[4] = {
	0x40, 0x60, 0x00, 0x00,
};
/* 80789D1C-80789D20 0004 .rodata    @5269                                                        */
SECTION_RODATA const u8 LIT_5269[4] = {
	0x40, 0x80, 0x00, 0x00,
};
/* 80789D20-80789D24 0004 .rodata    @5270                                                        */
SECTION_RODATA const u8 LIT_5270[4] = {
	0x41, 0x50, 0x00, 0x00,
};
/* 80789D24-80789D28 0004 .rodata    @5271                                                        */
SECTION_RODATA const u8 LIT_5271[4] = {
	0x41, 0xC0, 0x00, 0x00,
};
/* 80789D28-80789D2C 0004 .rodata    @5272                                                        */
SECTION_RODATA const u8 LIT_5272[4] = {
	0x42, 0x18, 0x00, 0x00,
};
/* 80789D2C-80789D30 0004 .rodata    @5273                                                        */
SECTION_RODATA const u8 LIT_5273[4] = {
	0x42, 0x64, 0x00, 0x00,
};
/* 80789D30-80789D34 0004 .rodata    @5274                                                        */
SECTION_RODATA const u8 LIT_5274[4] = {
	0x41, 0xB0, 0x00, 0x00,
};
/* 80789D34-80789D38 0004 .rodata    @5275                                                        */
SECTION_RODATA const u8 LIT_5275[4] = {
	0x41, 0x30, 0x00, 0x00,
};
/* 80789D38-80789D3C 0004 .rodata    @5276                                                        */
SECTION_RODATA const u8 LIT_5276[4] = {
	0x41, 0x90, 0x00, 0x00,
};
/* 80789D3C-80789D40 0004 .rodata    @5447                                                        */
SECTION_RODATA const u8 LIT_5447[4] = {
	0x42, 0x96, 0x00, 0x00,
};
/* 80789D40-80789D44 0004 .rodata    @5448                                                        */
SECTION_RODATA const u8 LIT_5448[4] = {
	0x43, 0xC8, 0x00, 0x00,
};
/* 80789D44-80789D48 0004 .rodata    @5449                                                        */
SECTION_RODATA const u8 LIT_5449[4] = {
	0x42, 0xB4, 0x00, 0x00,
};
/* 80789D48-80789D4C 0004 .rodata    @5450                                                        */
SECTION_RODATA const u8 LIT_5450[4] = {
	0x3E, 0x80, 0x00, 0x00,
};
/* 80789D4C-80789D50 0004 .rodata    @5451                                                        */
SECTION_RODATA const u8 LIT_5451[4] = {
	0xC6, 0x0B, 0x58, 0x00,
};
/* 80789D50-80789D54 0004 .rodata    @5452                                                        */
SECTION_RODATA const u8 LIT_5452[4] = {
	0xC3, 0xE7, 0x00, 0x00,
};
/* 80789D54-80789D58 0004 .rodata    @5453                                                        */
SECTION_RODATA const u8 LIT_5453[4] = {
	0x44, 0x2F, 0x00, 0x00,
};
/* 80789D58-80789D5C 0004 .rodata    @5454                                                        */
SECTION_RODATA const u8 LIT_5454[4] = {
	0xC3, 0x7A, 0x00, 0x00,
};
/* 80789D5C-80789D60 0004 .rodata    @5676                                                        */
SECTION_RODATA const u8 LIT_5676[4] = {
	0xC8, 0x43, 0x50, 0x00,
};
/* 80789D60-80789D64 0004 .rodata    @5677                                                        */
SECTION_RODATA const u8 LIT_5677[4] = {
	0xC8, 0x12, 0x7C, 0x00,
};
/* 80789D64-80789D68 0004 .rodata    @5678                                                        */
SECTION_RODATA const u8 LIT_5678[4] = {
	0xC1, 0xA0, 0x00, 0x00,
};
/* 80789D68-80789D6C 0004 .rodata    @5679                                                        */
SECTION_RODATA const u8 LIT_5679[4] = {
	0xC1, 0xF0, 0x00, 0x00,
};
/* 80789D6C-80789D70 0004 .rodata    @5680                                                        */
SECTION_RODATA const u8 LIT_5680[4] = {
	0x41, 0xF0, 0x00, 0x00,
};
/* 80789D70-80789D74 0004 .rodata    @5681                                                        */
SECTION_RODATA const u8 LIT_5681[4] = {
	0x42, 0xA0, 0x00, 0x00,
};
/* 80789D74-80789D78 0004 .rodata    @5682                                                        */
SECTION_RODATA const u8 LIT_5682[4] = {
	0x42, 0x0C, 0x00, 0x00,
};
/* 80789D78-80789D7C 0004 .rodata    @5683                                                        */
SECTION_RODATA const u8 LIT_5683[4] = {
	0xC2, 0x70, 0x00, 0x00,
};
/* 80789D7C-80789D80 0004 .rodata    @5684                                                        */
SECTION_RODATA const u8 LIT_5684[4] = {
	0x43, 0x34, 0x00, 0x00,
};
/* 80789D80-80789D84 0004 .rodata    @5929                                                        */
SECTION_RODATA const u8 LIT_5929[4] = {
	0xC3, 0x48, 0x00, 0x00,
};
/* 80789D84-80789D88 0004 .rodata    @5930                                                        */
SECTION_RODATA const u8 LIT_5930[4] = {
	0x47, 0x7F, 0xFF, 0x00,
};
}


/* ###################################################################################### */
/*                                         .data                                          */
/* ###################################################################################### */

extern "C" {
/* 80789D94-80789D94 0000 .data      ...data.0                                                    */
/* 80789D94-80789DA0 000C .data      cNullVec__6Z2Calc                                            */
SECTION_DATA u8 cNullVec__6Z2Calc[12] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80789DA0-80789DB4 0004 .data      @1787                                                        */
SECTION_DATA u8 LIT_1787[20] = {
	0x02, 0x00, 0x02, 0x01,
	/* padding */
	0x40, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x3F, 0xE0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80789DB4-80789DBC 0008 .data      e_prim$3787                                                  */
SECTION_DATA u8 data_80789DB4[8] = {
	0xFF, 0x78, 0x00, 0x00, 0xFF, 0x64, 0x78, 0x00,
};
/* 80789DBC-80789DC4 0008 .data      e_env$3788                                                   */
SECTION_DATA u8 data_80789DBC[8] = {
	0x5A, 0x2D, 0x2D, 0x00, 0x3C, 0x1E, 0x1E, 0x00,
};
/* 80789DC4-80789DCC 0006 .data      eff_id$3796                                                  */
SECTION_DATA u8 data_80789DC4[8] = {
	0x02, 0x9D, 0x02, 0x9E, 0x02, 0x9F,
	/* padding */
	0x00, 0x00,
};
/* 80789DCC-80789E04 0038 .data      @4353                                                        */
SECTION_DATA u8 LIT_4353[56] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80789E04-80789E0C 0006 .data      ap_name$4773                                                 */
SECTION_DATA u8 data_80789E04[8] = {
	0x81, 0xDA, 0x81, 0xDB, 0x81, 0xDC,
	/* padding */
	0x00, 0x00,
};
/* 80789E0C-80789E14 0008 .data      foot_idx$4976                                                */
SECTION_DATA u8 data_80789E0C[8] = {
	0x00, 0x00, 0x00, 0x14, 0x00, 0x00, 0x00, 0x18,
};
/* 80789E14-80789E9C 0088 .data      @5205                                                        */
SECTION_DATA u8 LIT_5205[136] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80789E9C-80789EA0 0004 .data      p_name$5509                                                  */
SECTION_DATA u8 data_80789E9C[4] = {
	0x81, 0xCB, 0x81, 0xCC,
};
/* 80789EA0-80789EA8 0008 .data      wepon_data$5714                                              */
SECTION_DATA u8 data_80789EA0[8] = {
	0x00, 0x00, 0x00, 0x16, 0x00, 0x00, 0x00, 0x17,
};
/* 80789EA8-80789EB0 0008 .data      tate_data$5715                                               */
SECTION_DATA u8 data_80789EA8[8] = {
	0x00, 0x00, 0x00, 0x14, 0x00, 0x00, 0x00, 0x15,
};
/* 80789EB0-80789EF0 0040 .data      cc_sph_src$5780                                              */
SECTION_DATA u8 data_80789EB0[64] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0xD8, 0xFB, 0xFD, 0xFF, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x75, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x42, 0x20, 0x00, 0x00,
};
/* 80789EF0-80789F30 0040 .data      at_sph_src$5781                                              */
SECTION_DATA u8 data_80789EF0[64] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0D,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x09, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x42, 0x0C, 0x00, 0x00,
};
/* 80789F30-80789F70 0040 .data      tate_sph_src$5782                                            */
SECTION_DATA u8 data_80789F30[64] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0xD8, 0xFB, 0xFD, 0xFF, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x0A, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x42, 0xC8, 0x00, 0x00,
};
/* 80789F70-80789F90 0020 .data      l_daE_SF_Method                                              */
SECTION_DATA u8 l_daE_SF_Method[32] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80789F90-80789FC0 0030 .data      g_profile_E_SF                                               */
SECTION_DATA u8 g_profile_E_SF[48] = {
	0xFF, 0xFF, 0xFF, 0xFD, 0x00, 0x07, 0xFF, 0xFD, 0x01, 0xB8, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x7B, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x02, 0x0E, 0x00, 0x00,
};
/* 80789FC0-80789FCC 000C .data      __vt__12dBgS_AcchCir                                         */
SECTION_DATA void* __vt__12dBgS_AcchCir[3] = {
	NULL, /* RTTI */
	NULL,
	NULL,
};
/* 80789FCC-80789FD8 000C .data      __vt__10cCcD_GStts                                           */
SECTION_DATA void* __vt__10cCcD_GStts[3] = {
	NULL, /* RTTI */
	NULL,
	NULL,
};
/* 80789FD8-80789FE4 000C .data      __vt__10dCcD_GStts                                           */
SECTION_DATA void* __vt__10dCcD_GStts[3] = {
	NULL, /* RTTI */
	NULL,
	NULL,
};
/* 80789FE4-80789FF0 000C .data      __vt__8cM3dGSph                                              */
SECTION_DATA void* __vt__8cM3dGSph[3] = {
	NULL, /* RTTI */
	NULL,
	NULL,
};
/* 80789FF0-80789FFC 000C .data      __vt__8cM3dGAab                                              */
SECTION_DATA void* __vt__8cM3dGAab[3] = {
	NULL, /* RTTI */
	NULL,
	NULL,
};
/* 80789FFC-8078A020 0024 .data      __vt__12dBgS_ObjAcch                                         */
SECTION_DATA void* __vt__12dBgS_ObjAcch[9] = {
	NULL, /* RTTI */
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
};
/* 8078A020-8078A02C 000C .data      __vt__12daE_SF_HIO_c                                         */
SECTION_DATA void* __vt__12daE_SF_HIO_c[3] = {
	NULL, /* RTTI */
	NULL,
	NULL,
};
}


/* ###################################################################################### */
/*                                          .bss                                          */
/* ###################################################################################### */

extern "C" {
/* 8078A034-8078A034 0000 .bss       ...bss.0                                                     */
/* 8078A034-8078A038 0001 .bss       @1109                                                        */
SECTION_BSS u8 LIT_1109[1 + 3 /* padding */];
/* 8078A038-8078A03C 0001 .bss       @1107                                                        */
SECTION_BSS u8 LIT_1107[1 + 3 /* padding */];
/* 8078A03C-8078A040 0001 .bss       @1105                                                        */
SECTION_BSS u8 LIT_1105[1 + 3 /* padding */];
/* 8078A040-8078A044 0001 .bss       @1104                                                        */
SECTION_BSS u8 LIT_1104[1 + 3 /* padding */];
/* 8078A044-8078A048 0001 .bss       @1099                                                        */
SECTION_BSS u8 LIT_1099[1 + 3 /* padding */];
/* 8078A048-8078A04C 0001 .bss       @1097                                                        */
SECTION_BSS u8 LIT_1097[1 + 3 /* padding */];
/* 8078A04C-8078A050 0001 .bss       @1095                                                        */
SECTION_BSS u8 LIT_1095[1 + 3 /* padding */];
/* 8078A050-8078A054 0001 .bss       @1094                                                        */
SECTION_BSS u8 LIT_1094[1 + 3 /* padding */];
/* 8078A054-8078A058 0001 .bss       @1057                                                        */
SECTION_BSS u8 LIT_1057[1 + 3 /* padding */];
/* 8078A058-8078A05C 0001 .bss       @1055                                                        */
SECTION_BSS u8 LIT_1055[1 + 3 /* padding */];
/* 8078A05C-8078A060 0001 .bss       @1053                                                        */
SECTION_BSS u8 LIT_1053[1 + 3 /* padding */];
/* 8078A060-8078A064 0001 .bss       @1052                                                        */
SECTION_BSS u8 LIT_1052[1 + 3 /* padding */];
/* 8078A064-8078A068 0001 .bss       @1014                                                        */
SECTION_BSS u8 LIT_1014[1 + 3 /* padding */];
/* 8078A068-8078A06C 0001 .bss       @1012                                                        */
SECTION_BSS u8 LIT_1012[1 + 3 /* padding */];
/* 8078A06C-8078A070 0001 .bss       @1010                                                        */
SECTION_BSS u8 LIT_1010[1 + 3 /* padding */];
/* 8078A070-8078A074 0004 .bss       None                                                         */
SECTION_BSS u8 struct_8078A070[4];
/* 8078A070 0001 data_8078A070 */
/* 8078A071 0000 data_8078A071 */
/* 8078A071 0003 data_8078A071 */
/* 8078A074-8078A080 000C .bss       @3924                                                        */
SECTION_BSS u8 LIT_3924[12];
/* 8078A080-8078A0A8 0028 .bss       l_HIO                                                        */
SECTION_BSS u8 l_HIO[40];
/* 8078A0A8-8078A0D0 0028 .bss       target_info                                                  */
SECTION_BSS u8 target_info[40];
/* 8078A0D0-8078A0D4 0004 .bss       target_info_count                                            */
SECTION_BSS u8 target_info_count[4];
/* 8078A0D4-8078A0D8 0004 .bss       ret_ct                                                       */
SECTION_BSS u8 ret_ct[4];
/* 8078A0D8-8078A0DC 0004 .bss       sInstance__40JASGlobalInstance<19JASDefaultBankTable>        */
SECTION_BSS u8 data_8078A0D8[4];
/* 8078A0DC-8078A0E0 0004 .bss       sInstance__35JASGlobalInstance<14JASAudioThread>             */
SECTION_BSS u8 data_8078A0DC[4];
/* 8078A0E0-8078A0E4 0004 .bss       sInstance__27JASGlobalInstance<7Z2SeMgr>                     */
SECTION_BSS u8 data_8078A0E0[4];
/* 8078A0E4-8078A0E8 0004 .bss       sInstance__28JASGlobalInstance<8Z2SeqMgr>                    */
SECTION_BSS u8 data_8078A0E4[4];
/* 8078A0E8-8078A0EC 0004 .bss       sInstance__31JASGlobalInstance<10Z2SceneMgr>                 */
SECTION_BSS u8 data_8078A0E8[4];
/* 8078A0EC-8078A0F0 0004 .bss       sInstance__32JASGlobalInstance<11Z2StatusMgr>                */
SECTION_BSS u8 data_8078A0EC[4];
/* 8078A0F0-8078A0F4 0004 .bss       sInstance__31JASGlobalInstance<10Z2DebugSys>                 */
SECTION_BSS u8 data_8078A0F0[4];
/* 8078A0F4-8078A0F8 0004 .bss       sInstance__36JASGlobalInstance<15JAISoundStarter>            */
SECTION_BSS u8 data_8078A0F4[4];
/* 8078A0F8-8078A0FC 0004 .bss       sInstance__35JASGlobalInstance<14Z2SoundStarter>             */
SECTION_BSS u8 data_8078A0F8[4];
/* 8078A0FC-8078A100 0004 .bss       sInstance__33JASGlobalInstance<12Z2SpeechMgr2>               */
SECTION_BSS u8 data_8078A0FC[4];
/* 8078A100-8078A104 0004 .bss       sInstance__28JASGlobalInstance<8JAISeMgr>                    */
SECTION_BSS u8 data_8078A100[4];
/* 8078A104-8078A108 0004 .bss       sInstance__29JASGlobalInstance<9JAISeqMgr>                   */
SECTION_BSS u8 data_8078A104[4];
/* 8078A108-8078A10C 0004 .bss       sInstance__33JASGlobalInstance<12JAIStreamMgr>               */
SECTION_BSS u8 data_8078A108[4];
/* 8078A10C-8078A110 0004 .bss       sInstance__31JASGlobalInstance<10Z2SoundMgr>                 */
SECTION_BSS u8 data_8078A10C[4];
/* 8078A110-8078A114 0004 .bss       sInstance__33JASGlobalInstance<12JAISoundInfo>               */
SECTION_BSS u8 data_8078A110[4];
/* 8078A114-8078A118 0004 .bss       sInstance__34JASGlobalInstance<13JAUSoundTable>              */
SECTION_BSS u8 data_8078A114[4];
/* 8078A118-8078A11C 0004 .bss       sInstance__38JASGlobalInstance<17JAUSoundNameTable>          */
SECTION_BSS u8 data_8078A118[4];
/* 8078A11C-8078A120 0004 .bss       sInstance__33JASGlobalInstance<12JAUSoundInfo>               */
SECTION_BSS u8 data_8078A11C[4];
/* 8078A120-8078A124 0004 .bss       sInstance__32JASGlobalInstance<11Z2SoundInfo>                */
SECTION_BSS u8 data_8078A120[4];
/* 8078A124-8078A128 0004 .bss       sInstance__34JASGlobalInstance<13Z2SoundObjMgr>              */
SECTION_BSS u8 data_8078A124[4];
/* 8078A128-8078A12C 0004 .bss       sInstance__31JASGlobalInstance<10Z2Audience>                 */
SECTION_BSS u8 data_8078A128[4];
/* 8078A12C-8078A130 0004 .bss       sInstance__32JASGlobalInstance<11Z2FxLineMgr>                */
SECTION_BSS u8 data_8078A12C[4];
/* 8078A130-8078A134 0004 .bss       sInstance__31JASGlobalInstance<10Z2EnvSeMgr>                 */
SECTION_BSS u8 data_8078A130[4];
/* 8078A134-8078A138 0004 .bss       sInstance__32JASGlobalInstance<11Z2SpeechMgr>                */
SECTION_BSS u8 data_8078A134[4];
/* 8078A138-8078A13C 0004 .bss       sInstance__34JASGlobalInstance<13Z2WolfHowlMgr>              */
SECTION_BSS u8 data_8078A138[4];
}


/* ###################################################################################### */
/*                                         .text                                          */
/* ###################################################################################### */

/* 8078512C-80785188 005C .text      __ct__12daE_SF_HIO_cFv                                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __ct__12daE_SF_HIO_cFv() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/__ct__12daE_SF_HIO_cFv.s"
}
#pragma pop

/* 80785188-80785234 00AC .text      anm_init__FP10e_sf_classifUcf                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void anm_init__FP10e_sf_classifUcf() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/anm_init__FP10e_sf_classifUcf.s"
}
#pragma pop

/* 80785234-8078545C 0228 .text      nodeCallBack__FP8J3DJointi                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void nodeCallBack__FP8J3DJointi() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/nodeCallBack__FP8J3DJointi.s"
}
#pragma pop

/* 8078545C-80785654 01F8 .text      daE_SF_Draw__FP10e_sf_class                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daE_SF_Draw__FP10e_sf_class() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/daE_SF_Draw__FP10e_sf_class.s"
}
#pragma pop

/* 80785654-8078572C 00D8 .text      other_bg_check__FP10e_sf_classP10fopAc_ac_c                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void other_bg_check__FP10e_sf_classP10fopAc_ac_c() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/other_bg_check__FP10e_sf_classP10fopAc_ac_c.s"
}
#pragma pop

/* 8078572C-80785770 0044 .text      player_way_check__FP10e_sf_class                             */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void player_way_check__FP10e_sf_class() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/player_way_check__FP10e_sf_class.s"
}
#pragma pop

/* 80785770-80785880 0110 .text      way_bg_check__FP10e_sf_classff                               */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void way_bg_check__FP10e_sf_classff() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/way_bg_check__FP10e_sf_classff.s"
}
#pragma pop

/* 80785880-80785944 00C4 .text      pl_check__FP10e_sf_classfs                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void pl_check__FP10e_sf_classfs() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/pl_check__FP10e_sf_classfs.s"
}
#pragma pop

/* 80785944-80785BF8 02B4 .text      e_sf_normal__FP10e_sf_class                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void e_sf_normal__FP10e_sf_class() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/e_sf_normal__FP10e_sf_class.s"
}
#pragma pop

/* 80785BF8-80785D30 0138 .text      e_sf_drawback__FP10e_sf_class                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void e_sf_drawback__FP10e_sf_class() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/e_sf_drawback__FP10e_sf_class.s"
}
#pragma pop

/* 80785D30-807860F4 03C4 .text      e_sf_fight_run__FP10e_sf_class                               */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void e_sf_fight_run__FP10e_sf_class() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/e_sf_fight_run__FP10e_sf_class.s"
}
#pragma pop

/* 807860F4-80786154 0060 .text      at_hit_check__FP10e_sf_class                                 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void at_hit_check__FP10e_sf_class() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/at_hit_check__FP10e_sf_class.s"
}
#pragma pop

/* 80786154-8078632C 01D8 .text      e_sf_attack_0__FP10e_sf_class                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void e_sf_attack_0__FP10e_sf_class() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/e_sf_attack_0__FP10e_sf_class.s"
}
#pragma pop

/* 8078632C-80786524 01F8 .text      e_sf_attack__FP10e_sf_class                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void e_sf_attack__FP10e_sf_class() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/e_sf_attack__FP10e_sf_class.s"
}
#pragma pop

/* 80786524-807866F8 01D4 .text      e_sf_guard__FP10e_sf_class                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void e_sf_guard__FP10e_sf_class() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/e_sf_guard__FP10e_sf_class.s"
}
#pragma pop

/* 807866F8-80786844 014C .text      e_sf_s_damage__FP10e_sf_class                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void e_sf_s_damage__FP10e_sf_class() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/e_sf_s_damage__FP10e_sf_class.s"
}
#pragma pop

/* 80786844-80786B70 032C .text      e_sf_crash__FP10e_sf_class                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void e_sf_crash__FP10e_sf_class() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/e_sf_crash__FP10e_sf_class.s"
}
#pragma pop

/* 80786B70-80786C50 00E0 .text      e_sf_crashwait__FP10e_sf_class                               */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void e_sf_crashwait__FP10e_sf_class() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/e_sf_crashwait__FP10e_sf_class.s"
}
#pragma pop

/* 80786C50-80786DC0 0170 .text      e_sf_sitwait__FP10e_sf_class                                 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void e_sf_sitwait__FP10e_sf_class() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/e_sf_sitwait__FP10e_sf_class.s"
}
#pragma pop

/* 80786DC0-80787018 0258 .text      e_sf_getup__FP10e_sf_class                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void e_sf_getup__FP10e_sf_class() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/e_sf_getup__FP10e_sf_class.s"
}
#pragma pop

/* 80787018-807870D0 00B8 .text      crash_eff__FP10e_sf_class                                    */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void crash_eff__FP10e_sf_class() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/crash_eff__FP10e_sf_class.s"
}
#pragma pop

/* 807870D0-807873C0 02F0 .text      damage_check__FP10e_sf_class                                 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void damage_check__FP10e_sf_class() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/damage_check__FP10e_sf_class.s"
}
#pragma pop

/* 807873C0-80787DD8 0A18 .text      action__FP10e_sf_class                                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void action__FP10e_sf_class() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/action__FP10e_sf_class.s"
}
#pragma pop

/* 80787DD8-80787FE0 0208 .text      anm_se_set__FP10e_sf_class                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void anm_se_set__FP10e_sf_class() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/anm_se_set__FP10e_sf_class.s"
}
#pragma pop

/* 80787FE0-80788568 0588 .text      demo_camera__FP10e_sf_class                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void demo_camera__FP10e_sf_class() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/demo_camera__FP10e_sf_class.s"
}
#pragma pop

/* 80788568-80788D38 07D0 .text      daE_SF_Execute__FP10e_sf_class                               */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daE_SF_Execute__FP10e_sf_class() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/daE_SF_Execute__FP10e_sf_class.s"
}
#pragma pop

/* 80788D38-80788D40 0008 .text      daE_SF_IsDelete__FP10e_sf_class                              */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daE_SF_IsDelete__FP10e_sf_class() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/daE_SF_IsDelete__FP10e_sf_class.s"
}
#pragma pop

/* 80788D40-80788DA8 0068 .text      daE_SF_Delete__FP10e_sf_class                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daE_SF_Delete__FP10e_sf_class() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/daE_SF_Delete__FP10e_sf_class.s"
}
#pragma pop

/* 80788DA8-80788F88 01E0 .text      useHeapInit__FP10fopAc_ac_c                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void useHeapInit__FP10fopAc_ac_c() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/useHeapInit__FP10fopAc_ac_c.s"
}
#pragma pop

/* 80788F88-80789418 0490 .text      daE_SF_Create__FP10fopAc_ac_c                                */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daE_SF_Create__FP10fopAc_ac_c() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/daE_SF_Create__FP10fopAc_ac_c.s"
}
#pragma pop

/* 80789418-80789460 0048 .text      __dt__8cM3dGSphFv                                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__8cM3dGSphFv() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/__dt__8cM3dGSphFv.s"
}
#pragma pop

/* 80789460-807894A8 0048 .text      __dt__8cM3dGAabFv                                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__8cM3dGAabFv() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/__dt__8cM3dGAabFv.s"
}
#pragma pop

/* 807894A8-80789574 00CC .text      __dt__8dCcD_SphFv                                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__8dCcD_SphFv() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/__dt__8dCcD_SphFv.s"
}
#pragma pop

/* 80789574-807895F8 0084 .text      __ct__8dCcD_SphFv                                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __ct__8dCcD_SphFv() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/__ct__8dCcD_SphFv.s"
}
#pragma pop

/* 807895F8-80789654 005C .text      __dt__10dCcD_GSttsFv                                         */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__10dCcD_GSttsFv() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/__dt__10dCcD_GSttsFv.s"
}
#pragma pop

/* 80789654-807896C4 0070 .text      __dt__12dBgS_ObjAcchFv                                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__12dBgS_ObjAcchFv() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/__dt__12dBgS_ObjAcchFv.s"
}
#pragma pop

/* 807896C4-80789734 0070 .text      __dt__12dBgS_AcchCirFv                                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__12dBgS_AcchCirFv() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/__dt__12dBgS_AcchCirFv.s"
}
#pragma pop

/* 80789734-8078977C 0048 .text      __dt__10cCcD_GSttsFv                                         */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__10cCcD_GSttsFv() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/__dt__10cCcD_GSttsFv.s"
}
#pragma pop

/* 8078977C-807897C4 0048 .text      __dt__12daE_SF_HIO_cFv                                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__12daE_SF_HIO_cFv() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/__dt__12daE_SF_HIO_cFv.s"
}
#pragma pop

/* 807897C4-80789800 003C .text      __sinit_d_a_e_sf_cpp                                         */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __sinit_d_a_e_sf_cpp() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/__sinit_d_a_e_sf_cpp.s"
}
#pragma pop

/* 80789800-80789808 0008 .text      @36@__dt__12dBgS_ObjAcchFv                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void func_80789800() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/func_80789800.s"
}
#pragma pop

/* 80789808-80789810 0008 .text      @20@__dt__12dBgS_ObjAcchFv                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void func_80789808() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/func_80789808.s"
}
#pragma pop

/* 80789810-80789C24 0414 .text      setMidnaBindEffect__FP13fopEn_enemy_cP15Z2CreatureEnemyP4cXyzP4cXyz */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void setMidnaBindEffect__FP13fopEn_enemy_cP15Z2CreatureEnemyP4cXyzP4cXyz() {
	nofralloc
#include "asm/rel/d_a_e_sf/d_a_e_sf/setMidnaBindEffect__FP13fopEn_enemy_cP15Z2CreatureEnemyP4cXyzP4cXyz.s"
}
#pragma pop


