// 
// Generated By: dol2asm
// Translation Unit: JAISoundHandles
// 

#include "dolphin/types.h"

// 
// Forward References:
// 

extern "C" extern void getHandleSoundID__15JAISoundHandlesF10JAISoundID();
extern "C" extern void getFreeHandle__15JAISoundHandlesFv();

// 
// External References:
// 


// 
// Declarations:
// 

/* 802A2C98-802A2CF4 005C+00 .text      getHandleSoundID__15JAISoundHandlesF10JAISoundID             */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
ASM_FUNCTION(getHandleSoundID__15JAISoundHandlesF10JAISoundID) {
	nofralloc
#include "asm/JSystem/JAudio2/JAISoundHandles/getHandleSoundID__15JAISoundHandlesF10JAISoundID.s"
}
#pragma pop


/* 802A2CF4-802A2D34 0040+00 .text      getFreeHandle__15JAISoundHandlesFv                           */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
ASM_FUNCTION(getFreeHandle__15JAISoundHandlesFv) {
	nofralloc
#include "asm/JSystem/JAudio2/JAISoundHandles/getFreeHandle__15JAISoundHandlesFv.s"
}
#pragma pop


/* ############################################################################################## */
