// 
// Generated By: dol2asm
// 

#include "dolphin/types.h"

// 
// Additional Symbols:
// 

extern "C" {
extern void cAPIGph_Painter__Fv();
extern void cAPIGph_BeforeOfDraw__Fv();
extern void cAPIGph_AfterOfDraw__Fv();
SECTION_DATA extern void* g_cAPI_Interface[6];
}


/* ###################################################################################### */
/*                                         .text                                          */
/* ###################################################################################### */

/* 802632C8-802632F8 0030 .text      cAPIGph_Painter__Fv                                          */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void cAPIGph_Painter__Fv() {
	nofralloc
#include "asm/SSystem/SComponent/c_API_graphic/cAPIGph_Painter__Fv.s"
}
#pragma pop

/* 802632F8-80263328 0030 .text      cAPIGph_BeforeOfDraw__Fv                                     */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void cAPIGph_BeforeOfDraw__Fv() {
	nofralloc
#include "asm/SSystem/SComponent/c_API_graphic/cAPIGph_BeforeOfDraw__Fv.s"
}
#pragma pop

/* 80263328-80263358 0030 .text      cAPIGph_AfterOfDraw__Fv                                      */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void cAPIGph_AfterOfDraw__Fv() {
	nofralloc
#include "asm/SSystem/SComponent/c_API_graphic/cAPIGph_AfterOfDraw__Fv.s"
}
#pragma pop


