// 
// Generated By: dol2asm
// Translation Unit: c_counter
// 

#include "dol2asm.h"
#include "dolphin/types.h"
#include "SSystem/SComponent/c_counter.h"

// 
// Forward References:
// 

void cCt_Counter(int); // 2

extern "C" void cCt_Counter__Fi(); // 1
extern "C" extern u8 g_Counter[12 + 4 /* padding */];

// 
// External References:
// 



// 
// Declarations:
// 

/* ############################################################################################## */
/* 80430CD8-80430CE8 000C+04 rc=13 efc=12 rfr=False None .bss       g_Counter                                                    */
u8 g_Counter[12 + 4 /* padding */];

/* 80265E1C-80265E64 0048+00 rc=1 efc=1 rfr=False None .text      cCt_Counter__Fi                                              */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void cCt_Counter(int field_0) {
	nofralloc
#include "asm/SSystem/SComponent/c_counter/cCt_Counter__Fi.s"
}
#pragma pop


