// 
// Generated By: dol2asm
// 

#include "dolphin/types.h"

// 
// Forward References:
// 

extern "C" extern void ModuleProlog();
extern "C" extern void ModuleEpilog();
extern "C" extern void ModuleUnresolved();
extern "C" extern void ModuleConstructorsX();
extern "C" extern void ModuleDestructorsX();
extern "C" extern void _prolog();
extern "C" extern void _epilog();
extern "C" extern void _unresolved();
extern const void* const data_8097F534[2];
extern const u8 data_8097F53C[4];

// 
// Functions:
// 

/* 80978C60-80978C8C 002C .text      _prolog                                                      */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void _prolog() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_cdn3/executor/_prolog.s"
}
#pragma pop


/* 80978C8C-80978CB8 002C .text      _epilog                                                      */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void _epilog() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_cdn3/executor/_epilog.s"
}
#pragma pop


/* 80978CB8-80978CD8 0020 .text      _unresolved                                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
extern "C" asm void _unresolved() {
	nofralloc
#include "asm/rel/d/a/npc/d_a_npc_cdn3/executor/_unresolved.s"
}
#pragma pop


