// 
// Generated By: dol2asm
// Translation Unit: CARDCheck
// 

#include "dolphin/types.h"

// 
// Forward References:
// 

extern "C" extern void __CARDCheckSum();
extern "C" extern void VerifyID();
extern "C" extern void VerifyDir();
extern "C" extern void VerifyFAT();
extern "C" extern void __CARDVerify();
extern "C" extern void CARDCheckExAsync();
extern "C" extern void CARDCheck();

// 
// External References:
// 

SECTION_INIT extern void memset();
SECTION_INIT extern void memcpy();
extern "C" extern void OSDisableInterrupts();
extern "C" extern void OSRestoreInterrupts();
extern "C" extern void __OSLockSramEx();
extern "C" extern void __OSUnlockSramEx();
extern "C" extern void __CARDSyncCallback();
extern "C" extern void __CARDGetFontEncode();
extern "C" extern void __CARDGetControlBlock();
extern "C" extern void __CARDPutControlBlock();
extern "C" extern void __CARDSync();
extern "C" extern void __CARDUpdateFatBlock();
extern "C" extern void __CARDUpdateDir();
extern "C" extern void __shr2i();
SECTION_BSS extern u8 __CARDBlock[544];

// 
// Declarations:
// 

/* 803559E0-80355B90 01B0+00 .text      __CARDCheckSum                                               */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
ASM_FUNCTION(__CARDCheckSum) {
	nofralloc
#include "asm/dolphin/card/CARDCheck/__CARDCheckSum.s"
}
#pragma pop


/* 80355B90-80355E14 0284+00 .text      VerifyID                                                     */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
ASM_FUNCTION(VerifyID) {
	nofralloc
#include "asm/dolphin/card/CARDCheck/VerifyID.s"
}
#pragma pop


/* 80355E14-80356054 0240+00 .text      VerifyDir                                                    */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
ASM_FUNCTION(VerifyDir) {
	nofralloc
#include "asm/dolphin/card/CARDCheck/VerifyDir.s"
}
#pragma pop


/* 80356054-803562D8 0284+00 .text      VerifyFAT                                                    */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
ASM_FUNCTION(VerifyFAT) {
	nofralloc
#include "asm/dolphin/card/CARDCheck/VerifyFAT.s"
}
#pragma pop


/* 803562D8-80356364 008C+00 .text      __CARDVerify                                                 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
ASM_FUNCTION(__CARDVerify) {
	nofralloc
#include "asm/dolphin/card/CARDCheck/__CARDVerify.s"
}
#pragma pop


/* 80356364-803568F4 0590+00 .text      CARDCheckExAsync                                             */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
ASM_FUNCTION(CARDCheckExAsync) {
	nofralloc
#include "asm/dolphin/card/CARDCheck/CARDCheckExAsync.s"
}
#pragma pop


/* 803568F4-80356948 0054+00 .text      CARDCheck                                                    */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
ASM_FUNCTION(CARDCheck) {
	nofralloc
#include "asm/dolphin/card/CARDCheck/CARDCheck.s"
}
#pragma pop


/* ############################################################################################## */
