// 
// Generated By: dol2asm
// Translation Unit: PPCArch
// 

#include "dolphin/types.h"

// 
// Forward References:
// 

extern "C" extern void PPCMfmsr();
extern "C" extern void PPCMtmsr();
extern "C" extern void PPCMfhid0();
extern "C" extern void PPCMthid0();
extern "C" extern void PPCMfl2cr();
extern "C" extern void PPCMtl2cr();
extern "C" extern void PPCMtdec();
extern "C" extern void PPCSync();
extern "C" extern void PPCHalt();
extern "C" extern void PPCMtmmcr0();
extern "C" extern void PPCMtmmcr1();
extern "C" extern void PPCMtpmc1();
extern "C" extern void PPCMtpmc2();
extern "C" extern void PPCMtpmc3();
extern "C" extern void PPCMtpmc4();
extern "C" extern void PPCMffpscr();
extern "C" extern void PPCMtfpscr();
extern "C" extern void PPCMfhid2();
extern "C" extern void PPCMthid2();
extern "C" extern void PPCMtwpar();
extern "C" extern void PPCDisableSpeculation();
extern "C" extern void PPCSetFpNonIEEEMode();

// 
// External References:
// 


// 
// Declarations:
// 

/* 80339CC0-80339CC8 0008+00 .text      PPCMfmsr                                                     */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
ASM_FUNCTION(PPCMfmsr) {
	nofralloc
#include "asm/dolphin/base/PPCArch/PPCMfmsr.s"
}
#pragma pop


/* 80339CC8-80339CD0 0008+00 .text      PPCMtmsr                                                     */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
ASM_FUNCTION(PPCMtmsr) {
	nofralloc
#include "asm/dolphin/base/PPCArch/PPCMtmsr.s"
}
#pragma pop


/* 80339CD0-80339CD8 0008+00 .text      PPCMfhid0                                                    */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
ASM_FUNCTION(PPCMfhid0) {
	nofralloc
#include "asm/dolphin/base/PPCArch/PPCMfhid0.s"
}
#pragma pop


/* 80339CD8-80339CE0 0008+00 .text      PPCMthid0                                                    */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
ASM_FUNCTION(PPCMthid0) {
	nofralloc
#include "asm/dolphin/base/PPCArch/PPCMthid0.s"
}
#pragma pop


/* 80339CE0-80339CE8 0008+00 .text      PPCMfl2cr                                                    */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
ASM_FUNCTION(PPCMfl2cr) {
	nofralloc
#include "asm/dolphin/base/PPCArch/PPCMfl2cr.s"
}
#pragma pop


/* 80339CE8-80339CF0 0008+00 .text      PPCMtl2cr                                                    */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
ASM_FUNCTION(PPCMtl2cr) {
	nofralloc
#include "asm/dolphin/base/PPCArch/PPCMtl2cr.s"
}
#pragma pop


/* 80339CF0-80339CF8 0008+00 .text      PPCMtdec                                                     */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
ASM_FUNCTION(PPCMtdec) {
	nofralloc
#include "asm/dolphin/base/PPCArch/PPCMtdec.s"
}
#pragma pop


/* 80339CF8-80339D00 0008+00 .text      PPCSync                                                      */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
ASM_FUNCTION(PPCSync) {
	nofralloc
#include "asm/dolphin/base/PPCArch/PPCSync.s"
}
#pragma pop


/* 80339D00-80339D14 0014+00 .text      PPCHalt                                                      */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
ASM_FUNCTION(PPCHalt) {
	nofralloc
#include "asm/dolphin/base/PPCArch/PPCHalt.s"
}
#pragma pop


/* 80339D14-80339D1C 0008+00 .text      PPCMtmmcr0                                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
ASM_FUNCTION(PPCMtmmcr0) {
	nofralloc
#include "asm/dolphin/base/PPCArch/PPCMtmmcr0.s"
}
#pragma pop


/* 80339D1C-80339D24 0008+00 .text      PPCMtmmcr1                                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
ASM_FUNCTION(PPCMtmmcr1) {
	nofralloc
#include "asm/dolphin/base/PPCArch/PPCMtmmcr1.s"
}
#pragma pop


/* 80339D24-80339D2C 0008+00 .text      PPCMtpmc1                                                    */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
ASM_FUNCTION(PPCMtpmc1) {
	nofralloc
#include "asm/dolphin/base/PPCArch/PPCMtpmc1.s"
}
#pragma pop


/* 80339D2C-80339D34 0008+00 .text      PPCMtpmc2                                                    */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
ASM_FUNCTION(PPCMtpmc2) {
	nofralloc
#include "asm/dolphin/base/PPCArch/PPCMtpmc2.s"
}
#pragma pop


/* 80339D34-80339D3C 0008+00 .text      PPCMtpmc3                                                    */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
ASM_FUNCTION(PPCMtpmc3) {
	nofralloc
#include "asm/dolphin/base/PPCArch/PPCMtpmc3.s"
}
#pragma pop


/* 80339D3C-80339D44 0008+00 .text      PPCMtpmc4                                                    */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
ASM_FUNCTION(PPCMtpmc4) {
	nofralloc
#include "asm/dolphin/base/PPCArch/PPCMtpmc4.s"
}
#pragma pop


/* 80339D44-80339D64 0020+00 .text      PPCMffpscr                                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
ASM_FUNCTION(PPCMffpscr) {
	nofralloc
#include "asm/dolphin/base/PPCArch/PPCMffpscr.s"
}
#pragma pop


/* 80339D64-80339D8C 0028+00 .text      PPCMtfpscr                                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
ASM_FUNCTION(PPCMtfpscr) {
	nofralloc
#include "asm/dolphin/base/PPCArch/PPCMtfpscr.s"
}
#pragma pop


/* 80339D8C-80339D94 0008+00 .text      PPCMfhid2                                                    */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
ASM_FUNCTION(PPCMfhid2) {
	nofralloc
#include "asm/dolphin/base/PPCArch/PPCMfhid2.s"
}
#pragma pop


/* 80339D94-80339D9C 0008+00 .text      PPCMthid2                                                    */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
ASM_FUNCTION(PPCMthid2) {
	nofralloc
#include "asm/dolphin/base/PPCArch/PPCMthid2.s"
}
#pragma pop


/* 80339D9C-80339DA4 0008+00 .text      PPCMtwpar                                                    */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
ASM_FUNCTION(PPCMtwpar) {
	nofralloc
#include "asm/dolphin/base/PPCArch/PPCMtwpar.s"
}
#pragma pop


/* 80339DA4-80339DCC 0028+00 .text      PPCDisableSpeculation                                        */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
ASM_FUNCTION(PPCDisableSpeculation) {
	nofralloc
#include "asm/dolphin/base/PPCArch/PPCDisableSpeculation.s"
}
#pragma pop


/* 80339DCC-80339DD4 0008+00 .text      PPCSetFpNonIEEEMode                                          */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
ASM_FUNCTION(PPCSetFpNonIEEEMode) {
	nofralloc
#include "asm/dolphin/base/PPCArch/PPCSetFpNonIEEEMode.s"
}
#pragma pop


/* ############################################################################################## */
