// 
// Generated By: dol2asm
// 

#include "dolphin/types.h"

// 
// Additional Symbols:
// 

struct csXyz;
struct Vec;

extern void cM3d_CalcVecZAngle(const Vec&, csXyz*); /* cM3d_CalcVecZAngle__FRC3VecP5csXyz */
extern void cLib_distanceAngleS(short, short); /* cLib_distanceAngleS__Fss */
extern void operator delete(void*); /* __dl__FPv */

extern "C" {
/* Function             */
extern void ZXYrotS__14mDoMtx_stack_cFRC5csXyz();
/* Function             */
extern void __dt__4dCcSFv();
/* Function             */
extern void getHitmarkPosAndAngle__9dJntCol_cCFPC4cXyzPC5csXyzP4cXyzP5csXyzi();
/* Function             */
extern void setHitMark__13dPa_control_cFUsP10fopAc_ac_cPC4cXyzPC5csXyzPC4cXyzUl();
/* Function             */
extern void SetHitApid__22dCcD_GAtTgCoCommonBaseFUi();
/* Function             */
extern void SetEffCounterTimer__22dCcD_GAtTgCoCommonBaseFv();
/* Function             */
extern void ChkEffCounter__22dCcD_GAtTgCoCommonBaseFv();
/* Function             */
extern void ChkAtNoGuard__12dCcD_GObjInfFv();
/* Function             */
extern void Ct__12dCcMassS_MngFv();
/* Function             */
extern void Clear__12dCcMassS_MngFv();
/* Function             */
extern void Ct__4dCcSFv();
/* Function             */
extern void Dt__4dCcSFv();
/* Function             */
extern void ChkShieldFrontRange__4dCcSFP8cCcD_ObjP8cCcD_ObjiPC4cXyz();
/* Function             */
extern void ChkShield__4dCcSFP8cCcD_ObjP8cCcD_ObjP12dCcD_GObjInfP12dCcD_GObjInfPC4cXyz();
/* ReturnFunction       */
extern void CalcTgPlusDmg__4dCcSFP8cCcD_ObjP8cCcD_ObjP9cCcD_SttsP9cCcD_Stts();
/* Function             */
extern void ChkAtTgHitAfterCross__4dCcSFbbPC12cCcD_GObjInfPC12cCcD_GObjInfP9cCcD_SttsP9cCcD_SttsP10cCcD_GSttsP10cCcD_GStts();
/* Function             */
extern void SetCoGObjInf__4dCcSFbbP12cCcD_GObjInfP12cCcD_GObjInfP9cCcD_SttsP9cCcD_SttsP10cCcD_GSttsP10cCcD_GStts();
/* Function             */
extern void GetRank__4dCcSFUc();
/* ReturnIntegerFunction */
extern  int ChkNoHitGCo__4dCcSFP8cCcD_ObjP8cCcD_Obj();
/* Function             */
extern void SetPosCorrect__4dCcSFP8cCcD_ObjP4cXyzP8cCcD_ObjP4cXyzf();
/* Function             */
extern void CalcParticleAngle__4dCcSFP12dCcD_GObjInfP9cCcD_SttsP9cCcD_SttsP5csXyz();
/* Function             */
extern void ProcAtTgHitmark__4dCcSFbbP8cCcD_ObjP8cCcD_ObjP12dCcD_GObjInfP12dCcD_GObjInfP9cCcD_SttsP9cCcD_SttsP10dCcD_GSttsP10dCcD_GSttsP4cXyzb();
/* Function             */
extern void SetAtTgGObjInf__4dCcSFbbP8cCcD_ObjP8cCcD_ObjP12cCcD_GObjInfP12cCcD_GObjInfP9cCcD_SttsP9cCcD_SttsP10cCcD_GSttsP10cCcD_GSttsP4cXyz();
/* Function             */
extern void ChkCamera__4dCcSFR4cXyzR4cXyzfP10fopAc_ac_cP10fopAc_ac_cP10fopAc_ac_c();
/* Function             */
extern void chkCameraPoint__4dCcSFRC4cXyzPQ214cCcD_ShapeAttr5ShapeP10fopAc_ac_cP10fopAc_ac_c();
/* Function             */
extern void __dt__12cCcD_SphAttrFv();
/* ReturnFunction       */
extern void MoveAfterCheck__4dCcSFv();
/* ReturnFunction       */
extern void DrawAfter__4dCcSFv();
/* Function             */
extern void Move__4dCcSFv();
/* Function             */
extern void Draw__4dCcSFv();
/* Function             */
extern void MassClear__4dCcSFv();
/* Function             */
extern void ChkAtTgMtrlHit__4dCcSFUcUc();
/* Function             */
extern void ChkNoHitGAtTg__4dCcSFPC12cCcD_GObjInfPC12cCcD_GObjInfP10cCcD_GSttsP10cCcD_GStts();
/* Function             */
extern void Chk__15cCcD_DivideInfoCFRC15cCcD_DivideInfo();
/* Function             */
extern void CalcDivideInfoOverArea__15cCcD_DivideAreaFP15cCcD_DivideInfoRC8cM3dGAab();
/* Function             */
extern void PlusCcMove__9cCcD_SttsFfff();
/* Function             */
extern void PlusDmg__9cCcD_SttsFi();
/* Function             */
extern void GetAc__8cCcD_ObjFv();
/* Function             */
extern void CalcAabBox__12cCcD_CpsAttrFv();
/* Function             */
extern void CalcAabBox__12cCcD_SphAttrFv();
/* Function             */
extern void Ct__4cCcSFv();
/* Function             */
extern void Dt__4cCcSFv();
/* Function             */
extern void Move__4cCcSFv();
/* Function             */
extern void DrawClear__4cCcSFv();
/* ReturnFunction       */
extern void SetCoGCorrectProc__4cCcSFP8cCcD_ObjP8cCcD_Obj();
/* Function             */
extern void cM3d_CalcVecZAngle__FRC3VecP5csXyz();
/* Function             */
extern void __ct__8cM3dGCpsFv();
/* Function             */
extern void __dt__8cM3dGCpsFv();
/* Function             */
extern void Set__8cM3dGCpsFRC4cXyzRC4cXyzf();
/* Function             */
extern void Set__8cM3dGSphFRC9cM3dGSphS();
/* Function             */
extern void cLib_distanceAngleS__Fss();
/* Function             */
extern void __dl__FPv();
/* Function             */
extern void PSMTXMultVecSR();
/* Function             */
extern void PSVECAdd();
/* Function             */
extern void PSVECSubtract();
/* Function             */
extern void PSVECScale();
/* Function             */
extern void PSVECNormalize();
/* Function             */
extern void PSVECMag();
/* Function             */
extern void PSVECDotProduct();
/* Function             */
extern void _savegpr_17();
/* Function             */
extern void _savegpr_23();
/* Function             */
extern void _savegpr_24();
/* Function             */
extern void _savegpr_25();
/* Function             */
extern void _savegpr_26();
/* Function             */
extern void _savegpr_29();
/* Function             */
extern void _restgpr_17();
/* Function             */
extern void _restgpr_23();
/* Function             */
extern void _restgpr_24();
/* Function             */
extern void _restgpr_25();
/* Function             */
extern void _restgpr_26();
/* Function             */
extern void _restgpr_29();
/* VTableData           */
SECTION_DATA extern void* __vt__8cM3dGAab[3];
/* VTableData           */
SECTION_DATA extern void* __vt__15cCcD_DivideInfo[3];
/* VTableData           */
SECTION_DATA extern void* __vt__8cM3dGSph[3];
/* InitializedData      */
SECTION_DATA extern u8 rank_tbl[124];
/* InitializedData      */
SECTION_DATA extern u8 m_mtrl_hit_tbl__4dCcS[64];
/* VTableData           */
SECTION_DATA extern void* __vt__4dCcS[13];
/* VTableData           */
SECTION_DATA extern void* __vt__12cCcD_SphAttr[25];
/* VTableData           */
SECTION_DATA extern void* __vt__12cCcD_CpsAttr[25];
/* VTableData           */
SECTION_DATA extern void* __vt__14cCcD_ShapeAttr[22];
/* ZeroInitializedData  */
SECTION_BSS extern u8 now__14mDoMtx_stack_c[48];
/* ZeroInitializedData  */
SECTION_BSS extern u8 g_dComIfG_gameInfo[122384];
/* ZeroInitializedData  */
SECTION_BSS extern u8 BaseZ__4cXyz[12];
/* ZeroInitializedData  */
SECTION_SBSS extern u8 G_CM3D_F_ABS_MIN[4 + 4 /* padding */];
/* InitializedData      */
SECTION_SDATA2 extern u8 d_d_cc_s__LIT_3705[4];
/* InitializedData      */
SECTION_SDATA2 extern u8 d_d_cc_s__LIT_3924[4];
/* InitializedData      */
SECTION_SDATA2 extern u8 d_d_cc_s__LIT_3925[8];
/* Float64Data          */
SECTION_SDATA2 extern f64 d_d_cc_s__LIT_3927;
/* InitializedData      */
SECTION_SDATA2 extern u8 d_d_cc_s__LIT_4336[8];
}


/* ###################################################################################### */
/*                                         .data                                          */
/* ###################################################################################### */

extern "C" {
/* 803AC328-803AC3A4 0079 .data      rank_tbl                                                     InitializedData */
SECTION_DATA u8 rank_tbl[124] = {
	0x00, 0x64, 0x64, 0x64, 0x64, 0x64, 0x64, 0x64, 0x64, 0x64, 0x64, 0x00, 0x32, 0x64, 0x64, 0x64,
	0x64, 0x64, 0x64, 0x64, 0x64, 0x64, 0x00, 0x00, 0x32, 0x4B, 0x5A, 0x64, 0x64, 0x64, 0x64, 0x64,
	0x64, 0x00, 0x00, 0x19, 0x32, 0x4B, 0x5A, 0x64, 0x64, 0x64, 0x64, 0x64, 0x00, 0x00, 0x0A, 0x19,
	0x32, 0x4B, 0x5A, 0x64, 0x64, 0x64, 0x64, 0x00, 0x00, 0x00, 0x0A, 0x19, 0x32, 0x4B, 0x5A, 0x64,
	0x64, 0x64, 0x00, 0x00, 0x00, 0x00, 0x0A, 0x19, 0x32, 0x4B, 0x5A, 0x64, 0x64, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x0A, 0x19, 0x32, 0x4B, 0x64, 0x64, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0A, 0x19,
	0x32, 0x64, 0x64, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x32, 0x64, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	/* padding */
	0x00, 0x00, 0x00,
};
/* 803AC3A4-803AC3E4 0040 .data      m_mtrl_hit_tbl__4dCcS                                        InitializedData */
SECTION_DATA u8 m_mtrl_hit_tbl__4dCcS[64] = {
	0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x01, 0x01, 0x01, 0x01, 0x00, 0x01, 0x01, 0x01,
};
/* 803AC3E4-803AC418 0034 .data      __vt__4dCcS                                                  VTableData */
SECTION_DATA void* __vt__4dCcS[13] = {
	NULL, /* RTTI */
	NULL,
	(void*)CalcTgPlusDmg__4dCcSFP8cCcD_ObjP8cCcD_ObjP9cCcD_SttsP9cCcD_Stts,
	(void*)SetPosCorrect__4dCcSFP8cCcD_ObjP4cXyzP8cCcD_ObjP4cXyzf,
	(void*)SetCoGObjInf__4dCcSFbbP12cCcD_GObjInfP12cCcD_GObjInfP9cCcD_SttsP9cCcD_SttsP10cCcD_GSttsP10cCcD_GStts,
	(void*)SetAtTgGObjInf__4dCcSFbbP8cCcD_ObjP8cCcD_ObjP12cCcD_GObjInfP12cCcD_GObjInfP9cCcD_SttsP9cCcD_SttsP10cCcD_GSttsP10cCcD_GSttsP4cXyz,
	(void*)ChkNoHitGAtTg__4dCcSFPC12cCcD_GObjInfPC12cCcD_GObjInfP10cCcD_GSttsP10cCcD_GStts,
	(void*)ChkAtTgHitAfterCross__4dCcSFbbPC12cCcD_GObjInfPC12cCcD_GObjInfP9cCcD_SttsP9cCcD_SttsP10cCcD_GSttsP10cCcD_GStts,
	(void*)ChkNoHitGCo__4dCcSFP8cCcD_ObjP8cCcD_Obj,
	(void*)__dt__4dCcSFv,
	(void*)MoveAfterCheck__4dCcSFv,
	(void*)SetCoGCorrectProc__4cCcSFP8cCcD_ObjP8cCcD_Obj,
	(void*)CalcParticleAngle__4dCcSFP12dCcD_GObjInfP9cCcD_SttsP9cCcD_SttsP5csXyz,
};
}


/* ###################################################################################### */
/*                                        .sdata2                                         */
/* ###################################################################################### */

extern "C" {
/* 80452778-8045277C 0004 .sdata2    @3705                                                        InitializedData */
SECTION_SDATA2 u8 d_d_cc_s__LIT_3705[4] = {
	0x00, 0x00, 0x00, 0x00,
};
/* 8045277C-80452780 0004 .sdata2    @3924                                                        InitializedData */
SECTION_SDATA2 u8 d_d_cc_s__LIT_3924[4] = {
	0x3C, 0x23, 0xD7, 0x0A,
};
/* 80452780-80452788 0004 .sdata2    @3925                                                        InitializedData */
SECTION_SDATA2 u8 d_d_cc_s__LIT_3925[8] = {
	0xBF, 0x80, 0x00, 0x00,
	/* padding */
	0x00, 0x00, 0x00, 0x00,
};
/* 80452788-80452790 0008 .sdata2    @3927                                                        Float64Data */
// 0x4330000000000000 | compiler-generated value used in cast: (float)u32
SECTION_SDATA2 f64 d_d_cc_s__LIT_3927 = 4503599627370496.000000;
/* 80452790-80452798 0004 .sdata2    @4336                                                        InitializedData */
SECTION_SDATA2 u8 d_d_cc_s__LIT_4336[8] = {
	0x3F, 0x80, 0x00, 0x00,
	/* padding */
	0x00, 0x00, 0x00, 0x00,
};
}


/* ###################################################################################### */
/*                                         .text                                          */
/* ###################################################################################### */

extern "C" {
/* 80085ED4-80085F08 0034 .text      Ct__4dCcSFv                                                  Function */
// dCcS::Ct(void)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void Ct__4dCcSFv() {
	nofralloc
#include "_include/d/d_cc_s/Ct__4dCcSFv.s"
}
#pragma pop

/* 80085F08-80085F28 0020 .text      Dt__4dCcSFv                                                  Function */
// dCcS::Dt(void)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void Dt__4dCcSFv() {
	nofralloc
#include "_include/d/d_cc_s/Dt__4dCcSFv.s"
}
#pragma pop

/* 80085F28-800860F8 01D0 .text      ChkShieldFrontRange__4dCcSFP8cCcD_ObjP8cCcD_ObjiPC4cXyz      Function */
// dCcS::ChkShieldFrontRange(cCcD_Obj*, cCcD_Obj*, int, const cXyz*)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void ChkShieldFrontRange__4dCcSFP8cCcD_ObjP8cCcD_ObjiPC4cXyz() {
	nofralloc
#include "_include/d/d_cc_s/ChkShieldFrontRange__4dCcSFP8cCcD_ObjP8cCcD_ObjiPC4cXyz.s"
}
#pragma pop

/* 800860F8-800861B0 00B8 .text      ChkShield__4dCcSFP8cCcD_ObjP8cCcD_ObjP12dCcD_GObjInfP12dCcD_GObjInfPC4cXyz Function */
// dCcS::ChkShield(cCcD_Obj*, cCcD_Obj*, dCcD_GObjInf*, dCcD_GObjInf*, const cXyz*)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void ChkShield__4dCcSFP8cCcD_ObjP8cCcD_ObjP12dCcD_GObjInfP12dCcD_GObjInfPC4cXyz() {
	nofralloc
#include "_include/d/d_cc_s/ChkShield__4dCcSFP8cCcD_ObjP8cCcD_ObjP12dCcD_GObjInfP12dCcD_GObjInfPC4cXyz.s"
}
#pragma pop

/* 800861B0-800861B4 0004 .text      CalcTgPlusDmg__4dCcSFP8cCcD_ObjP8cCcD_ObjP9cCcD_SttsP9cCcD_Stts ReturnFunction */
// dCcS::CalcTgPlusDmg(cCcD_Obj*, cCcD_Obj*, cCcD_Stts*, cCcD_Stts*)
void CalcTgPlusDmg__4dCcSFP8cCcD_ObjP8cCcD_ObjP9cCcD_SttsP9cCcD_Stts() {
	return;
}

/* 800861B4-80086240 008C .text      ChkAtTgHitAfterCross__4dCcSFbbPC12cCcD_GObjInfPC12cCcD_GObjInfP9cCcD_SttsP9cCcD_SttsP10cCcD_GSttsP10cCcD_GStts Function */
// dCcS::ChkAtTgHitAfterCross(bool, bool, const cCcD_GObjInf*, const cCcD_GObjInf*, cCcD_Stts*, cCcD_Stts*, cCcD_GStts*, cCcD_GStts*)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void ChkAtTgHitAfterCross__4dCcSFbbPC12cCcD_GObjInfPC12cCcD_GObjInfP9cCcD_SttsP9cCcD_SttsP10cCcD_GSttsP10cCcD_GStts() {
	nofralloc
#include "_include/d/d_cc_s/ChkAtTgHitAfterCross__4dCcSFbbPC12cCcD_GObjInfPC12cCcD_GObjInfP9cCcD_SttsP9cCcD_SttsP10cCcD_GSttsP10cCcD_GStts.s"
}
#pragma pop

/* 80086240-80086360 0120 .text      SetCoGObjInf__4dCcSFbbP12cCcD_GObjInfP12cCcD_GObjInfP9cCcD_SttsP9cCcD_SttsP10cCcD_GSttsP10cCcD_GStts Function */
// dCcS::SetCoGObjInf(bool, bool, cCcD_GObjInf*, cCcD_GObjInf*, cCcD_Stts*, cCcD_Stts*, cCcD_GStts*, cCcD_GStts*)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void SetCoGObjInf__4dCcSFbbP12cCcD_GObjInfP12cCcD_GObjInfP9cCcD_SttsP9cCcD_SttsP10cCcD_GSttsP10cCcD_GStts() {
	nofralloc
#include "_include/d/d_cc_s/SetCoGObjInf__4dCcSFbbP12cCcD_GObjInfP12cCcD_GObjInfP9cCcD_SttsP9cCcD_SttsP10cCcD_GSttsP10cCcD_GStts.s"
}
#pragma pop

/* 80086360-80086404 00A4 .text      GetRank__4dCcSFUc                                            Function */
// dCcS::GetRank(u8)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void GetRank__4dCcSFUc() {
	nofralloc
#include "_include/d/d_cc_s/GetRank__4dCcSFUc.s"
}
#pragma pop

/* 80086404-8008640C 0008 .text      ChkNoHitGCo__4dCcSFP8cCcD_ObjP8cCcD_Obj                      ReturnIntegerFunction */
// dCcS::ChkNoHitGCo(cCcD_Obj*, cCcD_Obj*)
int ChkNoHitGCo__4dCcSFP8cCcD_ObjP8cCcD_Obj() {
	return 0;
}

/* 8008640C-80086754 0348 .text      SetPosCorrect__4dCcSFP8cCcD_ObjP4cXyzP8cCcD_ObjP4cXyzf       Function */
// dCcS::SetPosCorrect(cCcD_Obj*, cXyz*, cCcD_Obj*, cXyz*, f32)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void SetPosCorrect__4dCcSFP8cCcD_ObjP4cXyzP8cCcD_ObjP4cXyzf() {
	nofralloc
#include "_include/d/d_cc_s/SetPosCorrect__4dCcSFP8cCcD_ObjP4cXyzP8cCcD_ObjP4cXyzf.s"
}
#pragma pop

/* 80086754-8008685C 0108 .text      CalcParticleAngle__4dCcSFP12dCcD_GObjInfP9cCcD_SttsP9cCcD_SttsP5csXyz Function */
// dCcS::CalcParticleAngle(dCcD_GObjInf*, cCcD_Stts*, cCcD_Stts*, csXyz*)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void CalcParticleAngle__4dCcSFP12dCcD_GObjInfP9cCcD_SttsP9cCcD_SttsP5csXyz() {
	nofralloc
#include "_include/d/d_cc_s/CalcParticleAngle__4dCcSFP12dCcD_GObjInfP9cCcD_SttsP9cCcD_SttsP5csXyz.s"
}
#pragma pop

/* 8008685C-80086AC0 0264 .text      ProcAtTgHitmark__4dCcSFbbP8cCcD_ObjP8cCcD_ObjP12dCcD_GObjInfP12dCcD_GObjInfP9cCcD_SttsP9cCcD_SttsP10dCcD_GSttsP10dCcD_GSttsP4cXyzb Function */
// dCcS::ProcAtTgHitmark(bool, bool, cCcD_Obj*, cCcD_Obj*, dCcD_GObjInf*, dCcD_GObjInf*, cCcD_Stts*, cCcD_Stts*, dCcD_GStts*, dCcD_GStts*, cXyz*, bool)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void ProcAtTgHitmark__4dCcSFbbP8cCcD_ObjP8cCcD_ObjP12dCcD_GObjInfP12dCcD_GObjInfP9cCcD_SttsP9cCcD_SttsP10dCcD_GSttsP10dCcD_GSttsP4cXyzb() {
	nofralloc
#include "_include/d/d_cc_s/ProcAtTgHitmark__4dCcSFbbP8cCcD_ObjP8cCcD_ObjP12dCcD_GObjInfP12dCcD_GObjInfP9cCcD_SttsP9cCcD_SttsP10dCcD_GSttsP10dCcD_GSttsP4cXyzb.s"
}
#pragma pop

/* 80086AC0-80086D8C 02CC .text      SetAtTgGObjInf__4dCcSFbbP8cCcD_ObjP8cCcD_ObjP12cCcD_GObjInfP12cCcD_GObjInfP9cCcD_SttsP9cCcD_SttsP10cCcD_GSttsP10cCcD_GSttsP4cXyz Function */
// dCcS::SetAtTgGObjInf(bool, bool, cCcD_Obj*, cCcD_Obj*, cCcD_GObjInf*, cCcD_GObjInf*, cCcD_Stts*, cCcD_Stts*, cCcD_GStts*, cCcD_GStts*, cXyz*)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void SetAtTgGObjInf__4dCcSFbbP8cCcD_ObjP8cCcD_ObjP12cCcD_GObjInfP12cCcD_GObjInfP9cCcD_SttsP9cCcD_SttsP10cCcD_GSttsP10cCcD_GSttsP4cXyz() {
	nofralloc
#include "_include/d/d_cc_s/SetAtTgGObjInf__4dCcSFbbP8cCcD_ObjP8cCcD_ObjP12cCcD_GObjInfP12cCcD_GObjInfP9cCcD_SttsP9cCcD_SttsP10cCcD_GSttsP10cCcD_GSttsP4cXyz.s"
}
#pragma pop

/* 80086D8C-80086FBC 0230 .text      ChkCamera__4dCcSFR4cXyzR4cXyzfP10fopAc_ac_cP10fopAc_ac_cP10fopAc_ac_c Function */
// dCcS::ChkCamera(cXyz&, cXyz&, f32, fopAc_ac_c*, fopAc_ac_c*, fopAc_ac_c*)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void ChkCamera__4dCcSFR4cXyzR4cXyzfP10fopAc_ac_cP10fopAc_ac_cP10fopAc_ac_c() {
	nofralloc
#include "_include/d/d_cc_s/ChkCamera__4dCcSFR4cXyzR4cXyzfP10fopAc_ac_cP10fopAc_ac_cP10fopAc_ac_c.s"
}
#pragma pop

/* 80086FBC-8008721C 0260 .text      chkCameraPoint__4dCcSFRC4cXyzPQ214cCcD_ShapeAttr5ShapeP10fopAc_ac_cP10fopAc_ac_c Function */
// dCcS::chkCameraPoint(const cXyz&, cCcD_ShapeAttr::Shape, fopAc_ac_c*, fopAc_ac_c*)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void chkCameraPoint__4dCcSFRC4cXyzPQ214cCcD_ShapeAttr5ShapeP10fopAc_ac_cP10fopAc_ac_c() {
	nofralloc
#include "_include/d/d_cc_s/chkCameraPoint__4dCcSFRC4cXyzPQ214cCcD_ShapeAttr5ShapeP10fopAc_ac_cP10fopAc_ac_c.s"
}
#pragma pop

/* 8008721C-800872A8 008C .text      __dt__12cCcD_SphAttrFv                                       Function */
// cCcD_SphAttr::~cCcD_SphAttr(void)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__12cCcD_SphAttrFv() {
	nofralloc
#include "_include/d/d_cc_s/__dt__12cCcD_SphAttrFv.s"
}
#pragma pop

/* 800872A8-800872AC 0004 .text      MoveAfterCheck__4dCcSFv                                      ReturnFunction */
// dCcS::MoveAfterCheck(void)
void MoveAfterCheck__4dCcSFv() {
	return;
}

/* 800872AC-800872B0 0004 .text      DrawAfter__4dCcSFv                                           ReturnFunction */
// dCcS::DrawAfter(void)
void DrawAfter__4dCcSFv() {
	return;
}

/* 800872B0-800872D0 0020 .text      Move__4dCcSFv                                                Function */
// dCcS::Move(void)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void Move__4dCcSFv() {
	nofralloc
#include "_include/d/d_cc_s/Move__4dCcSFv.s"
}
#pragma pop

/* 800872D0-8008730C 003C .text      Draw__4dCcSFv                                                Function */
// dCcS::Draw(void)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void Draw__4dCcSFv() {
	nofralloc
#include "_include/d/d_cc_s/Draw__4dCcSFv.s"
}
#pragma pop

/* 8008730C-80087330 0024 .text      MassClear__4dCcSFv                                           Function */
// dCcS::MassClear(void)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void MassClear__4dCcSFv() {
	nofralloc
#include "_include/d/d_cc_s/MassClear__4dCcSFv.s"
}
#pragma pop

/* 80087330-8008734C 001C .text      ChkAtTgMtrlHit__4dCcSFUcUc                                   Function */
// dCcS::ChkAtTgMtrlHit(u8, u8)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void ChkAtTgMtrlHit__4dCcSFUcUc() {
	nofralloc
#include "_include/d/d_cc_s/ChkAtTgMtrlHit__4dCcSFUcUc.s"
}
#pragma pop

/* 8008734C-800873B0 0064 .text      ChkNoHitGAtTg__4dCcSFPC12cCcD_GObjInfPC12cCcD_GObjInfP10cCcD_GSttsP10cCcD_GStts Function */
// dCcS::ChkNoHitGAtTg(const cCcD_GObjInf*, const cCcD_GObjInf*, cCcD_GStts*, cCcD_GStts*)
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void ChkNoHitGAtTg__4dCcSFPC12cCcD_GObjInfPC12cCcD_GObjInfP10cCcD_GSttsP10cCcD_GStts() {
	nofralloc
#include "_include/d/d_cc_s/ChkNoHitGAtTg__4dCcSFPC12cCcD_GObjInfPC12cCcD_GObjInfP10cCcD_GSttsP10cCcD_GStts.s"
}
#pragma pop

}

