// 
// Generated By: dol2asm
// 

#include "dolphin/types.h"

// 
// Additional Symbols:
// 


/* ###################################################################################### */
/*                                         .text                                          */
/* ###################################################################################### */

extern "C" {
/* 8036878C 0090 .text      __StringRead                                                 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __StringRead() {
	nofralloc
#include "_include/MSL_C.PPCEABI.bare.H/MSL_Common/Src/scanf/__StringRead.s"
}
#pragma pop

}

