// 
// Generated By: dol2asm
// 

#include "dolphin/types.h"

// 
// Additional Symbols:
// 

extern "C" {
extern void _unresolved();
extern void Reflect__FP4cXyzRC13cBgS_PolyInfof();
extern void __dt__8cM3dGPlaFv();
extern void initBaseMtx__14daItemShield_cFv();
extern void setBaseMtx__14daItemShield_cFv();
extern void Create__14daItemShield_cFv();
extern void __CreateHeap__14daItemShield_cFv();
extern void create__14daItemShield_cFv();
extern void __dt__8cM3dGCylFv();
extern void __dt__8cM3dGAabFv();
extern void __dt__10dCcD_GSttsFv();
extern void __dt__12dBgS_AcchCirFv();
extern void __dt__12dBgS_ObjAcchFv();
extern void bg_check__14daItemShield_cFv();
extern void action_proc_call__14daItemShield_cFv();
extern void actionInit__14daItemShield_cFv();
extern void actionWaitInit__14daItemShield_cFv();
extern void actionWait__14daItemShield_cFv();
extern void initActionOrderGetDemo__14daItemShield_cFv();
extern void actionOrderGetDemo__14daItemShield_cFv();
extern void actionGetDemo__14daItemShield_cFv();
extern void event_proc_call__14daItemShield_cFv();
extern void actionWaitCamDemo__14daItemShield_cFv();
extern void actionOrderCamDemo__14daItemShield_cFv();
extern void actionCamDemo__14daItemShield_cFv();
extern void actionCamDemoEnd__14daItemShield_cFv();
extern void execute__14daItemShield_cFv();
extern void draw__14daItemShield_cFv();
extern void _delete__14daItemShield_cFv();
extern void daItemShield_Draw__FP14daItemShield_c();
extern void daItemShield_Execute__FP14daItemShield_c();
extern void daItemShield_Delete__FP14daItemShield_c();
extern void daItemShield_Create__FP10fopAc_ac_c();
extern void __dt__10cCcD_GSttsFv();
extern void func_80CD8240();
extern void func_80CD825C();
extern void func_80CD8264();
extern const u8 unknown_translation_unit_ctors__data_80CD826C[4];
extern const u8 unknown_translation_unit_dtors__data_80CD8270[4];
SECTION_RODATA extern const u8 l_cyl_src[68];
SECTION_RODATA extern const u8 LIT_3856[4];
SECTION_RODATA extern const u8 LIT_3857[8];
SECTION_RODATA extern const u8 LIT_3858[8];
SECTION_RODATA extern const u8 LIT_3859[8];
SECTION_RODATA extern const u8 LIT_3953[8];
SECTION_RODATA extern const u8 LIT_3954[8];
SECTION_RODATA extern const u8 LIT_3955[4];
SECTION_RODATA extern const u8 LIT_3956[4];
SECTION_RODATA extern const u8 LIT_3957[4];
SECTION_RODATA extern const u8 LIT_3958[4];
SECTION_RODATA extern const u8 LIT_3960[8];
SECTION_RODATA extern const u8 LIT_4003[4];
SECTION_RODATA extern const u8 LIT_4004[4];
SECTION_RODATA extern const u8 LIT_4006[8];
SECTION_RODATA extern const u8 LIT_4180[4];
SECTION_RODATA extern const u8 LIT_4181[4];
SECTION_RODATA extern const u8 LIT_4182[4];
SECTION_RODATA extern const u8 LIT_4183[4];
SECTION_RODATA extern const u8 LIT_4184[4];
SECTION_RODATA extern const u8 LIT_4335[4];
SECTION_RODATA extern const u8 LIT_4336[4];
SECTION_RODATA extern const u8 LIT_4337[4];
SECTION_RODATA extern const u8 stringBase0[16];
SECTION_DATA extern u8 cNullVec__6Z2Calc[12];
SECTION_DATA extern u8 LIT_1787[20];
SECTION_DATA extern u8 LIT_4189[12];
SECTION_DATA extern u8 LIT_4190[12];
SECTION_DATA extern u8 LIT_4191[12];
SECTION_DATA extern u8 LIT_4192[12];
SECTION_DATA extern u8 data_80CD838C[48];
SECTION_DATA extern u8 LIT_4383[12];
SECTION_DATA extern u8 LIT_4384[12];
SECTION_DATA extern u8 LIT_4385[12];
SECTION_DATA extern u8 LIT_4386[12];
SECTION_DATA extern u8 data_80CD83EC[48];
SECTION_DATA extern u8 l_daItemShield_Method[32];
SECTION_DATA extern u8 g_profile_Obj_Shield[48];
SECTION_DATA extern void* __vt__12dBgS_AcchCir[3];
SECTION_DATA extern void* __vt__10cCcD_GStts[3];
SECTION_DATA extern void* __vt__10dCcD_GStts[3];
SECTION_DATA extern void* __vt__8cM3dGCyl[3];
SECTION_DATA extern void* __vt__8cM3dGAab[3];
SECTION_DATA extern void* __vt__12dBgS_ObjAcch[9];
SECTION_DATA extern void* __vt__14daItemShield_c[17];
SECTION_DATA extern void* __vt__8cM3dGPla[3];
SECTION_BSS extern u8 struct_80CD851C[4];
}


/* ###################################################################################### */
/*                                        .rodata                                         */
/* ###################################################################################### */

extern "C" {
/* 80CD832C-80CD833C 0010 .rodata    @stringBase0                                                 */
#pragma push
#pragma force_active on
#pragma section ".dead"
SECTION_DEAD const char* const stringBase_80CD832C = "DEFAULT_GETITEM";
#pragma pop
/* 80CD8274-80CD8274 0000 .rodata    ...rodata.0                                                  */
/* 80CD8274-80CD82B8 0044 .rodata    l_cyl_src                                                    */
SECTION_RODATA const u8 l_cyl_src[68] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x11, 0x00, 0x00, 0x00, 0x59, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x41, 0xA0, 0x00, 0x00,
	0x42, 0x20, 0x00, 0x00,
};
/* 80CD82B8-80CD82BC 0004 .rodata    @3856                                                        */
SECTION_RODATA const u8 LIT_3856[4] = {
	0x00, 0x00, 0x00, 0x00,
};
/* 80CD82BC-80CD82C4 0008 .rodata    @3857                                                        */
SECTION_RODATA const u8 LIT_3857[8] = {
	0x3F, 0xE0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80CD82C4-80CD82CC 0008 .rodata    @3858                                                        */
SECTION_RODATA const u8 LIT_3858[8] = {
	0x40, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80CD82CC-80CD82D4 0008 .rodata    @3859                                                        */
SECTION_RODATA const u8 LIT_3859[8] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80CD82D4-80CD82DC 0004 .rodata    @3953                                                        */
SECTION_RODATA const u8 LIT_3953[8] = {
	0x3F, 0x61, 0x47, 0xAE,
	/* padding */
	0x00, 0x00, 0x00, 0x00,
};
/* 80CD82DC-80CD82E4 0008 .rodata    @3954                                                        */
SECTION_RODATA const u8 LIT_3954[8] = {
	0x40, 0x69, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80CD82E4-80CD82E8 0004 .rodata    @3955                                                        */
SECTION_RODATA const u8 LIT_3955[4] = {
	0xC1, 0xA0, 0x00, 0x00,
};
/* 80CD82E8-80CD82EC 0004 .rodata    @3956                                                        */
SECTION_RODATA const u8 LIT_3956[4] = {
	0xC1, 0x70, 0x00, 0x00,
};
/* 80CD82EC-80CD82F0 0004 .rodata    @3957                                                        */
SECTION_RODATA const u8 LIT_3957[4] = {
	0x41, 0xA0, 0x00, 0x00,
};
/* 80CD82F0-80CD82F4 0004 .rodata    @3958                                                        */
SECTION_RODATA const u8 LIT_3958[4] = {
	0x41, 0x70, 0x00, 0x00,
};
/* 80CD82F4-80CD82FC 0008 .rodata    @3960                                                        */
SECTION_RODATA const u8 LIT_3960[8] = {
	0x43, 0x30, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00,
};
/* 80CD82FC-80CD8300 0004 .rodata    @4003                                                        */
SECTION_RODATA const u8 LIT_4003[4] = {
	0x41, 0xF0, 0x00, 0x00,
};
/* 80CD8300-80CD8304 0004 .rodata    @4004                                                        */
SECTION_RODATA const u8 LIT_4004[4] = {
	0xC0, 0x80, 0x00, 0x00,
};
/* 80CD8304-80CD830C 0008 .rodata    @4006                                                        */
SECTION_RODATA const u8 LIT_4006[8] = {
	0x43, 0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80CD830C-80CD8310 0004 .rodata    @4180                                                        */
SECTION_RODATA const u8 LIT_4180[4] = {
	0x40, 0xA0, 0x00, 0x00,
};
/* 80CD8310-80CD8314 0004 .rodata    @4181                                                        */
SECTION_RODATA const u8 LIT_4181[4] = {
	0x3F, 0x80, 0x00, 0x00,
};
/* 80CD8314-80CD8318 0004 .rodata    @4182                                                        */
SECTION_RODATA const u8 LIT_4182[4] = {
	0x3F, 0x33, 0x33, 0x33,
};
/* 80CD8318-80CD831C 0004 .rodata    @4183                                                        */
SECTION_RODATA const u8 LIT_4183[4] = {
	0x40, 0x40, 0x00, 0x00,
};
/* 80CD831C-80CD8320 0004 .rodata    @4184                                                        */
SECTION_RODATA const u8 LIT_4184[4] = {
	0xBF, 0x80, 0x00, 0x00,
};
/* 80CD8320-80CD8324 0004 .rodata    @4335                                                        */
SECTION_RODATA const u8 LIT_4335[4] = {
	0x43, 0xFA, 0x00, 0x00,
};
/* 80CD8324-80CD8328 0004 .rodata    @4336                                                        */
SECTION_RODATA const u8 LIT_4336[4] = {
	0xC1, 0xC8, 0x00, 0x00,
};
/* 80CD8328-80CD832C 0004 .rodata    @4337                                                        */
SECTION_RODATA const u8 LIT_4337[4] = {
	0x3F, 0x66, 0x66, 0x66,
};
}


/* ###################################################################################### */
/*                                         .data                                          */
/* ###################################################################################### */

extern "C" {
/* 80CD833C-80CD833C 0000 .data      ...data.0                                                    */
/* 80CD833C-80CD8348 000C .data      cNullVec__6Z2Calc                                            */
SECTION_DATA u8 cNullVec__6Z2Calc[12] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80CD8348-80CD835C 0004 .data      @1787                                                        */
SECTION_DATA u8 LIT_1787[20] = {
	0x02, 0x00, 0x02, 0x01,
	/* padding */
	0x40, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x3F, 0xE0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80CD835C-80CD8368 000C .data      @4189                                                        */
SECTION_DATA u8 LIT_4189[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80CD8368-80CD8374 000C .data      @4190                                                        */
SECTION_DATA u8 LIT_4190[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80CD8374-80CD8380 000C .data      @4191                                                        */
SECTION_DATA u8 LIT_4191[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80CD8380-80CD838C 000C .data      @4192                                                        */
SECTION_DATA u8 LIT_4192[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80CD838C-80CD83BC 0030 .data      l_actionFunc$4188                                            */
SECTION_DATA u8 data_80CD838C[48] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80CD83BC-80CD83C8 000C .data      @4383                                                        */
SECTION_DATA u8 LIT_4383[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80CD83C8-80CD83D4 000C .data      @4384                                                        */
SECTION_DATA u8 LIT_4384[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80CD83D4-80CD83E0 000C .data      @4385                                                        */
SECTION_DATA u8 LIT_4385[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80CD83E0-80CD83EC 000C .data      @4386                                                        */
SECTION_DATA u8 LIT_4386[12] = {
	0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00,
};
/* 80CD83EC-80CD841C 0030 .data      l_func$4382                                                  */
SECTION_DATA u8 data_80CD83EC[48] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80CD841C-80CD843C 0020 .data      l_daItemShield_Method                                        */
SECTION_DATA u8 l_daItemShield_Method[32] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};
/* 80CD843C-80CD846C 0030 .data      g_profile_Obj_Shield                                         */
SECTION_DATA u8 g_profile_Obj_Shield[48] = {
	0xFF, 0xFF, 0xFF, 0xFD, 0x00, 0x07, 0xFF, 0xFD, 0x02, 0x1C, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x09, 0x58, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0xF0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x01, 0x00, 0x00, 0x0E, 0x00, 0x00,
};
/* 80CD846C-80CD8478 000C .data      __vt__12dBgS_AcchCir                                         */
SECTION_DATA void* __vt__12dBgS_AcchCir[3] = {
	NULL, /* RTTI */
	NULL,
	NULL,
};
/* 80CD8478-80CD8484 000C .data      __vt__10cCcD_GStts                                           */
SECTION_DATA void* __vt__10cCcD_GStts[3] = {
	NULL, /* RTTI */
	NULL,
	NULL,
};
/* 80CD8484-80CD8490 000C .data      __vt__10dCcD_GStts                                           */
SECTION_DATA void* __vt__10dCcD_GStts[3] = {
	NULL, /* RTTI */
	NULL,
	NULL,
};
/* 80CD8490-80CD849C 000C .data      __vt__8cM3dGCyl                                              */
SECTION_DATA void* __vt__8cM3dGCyl[3] = {
	NULL, /* RTTI */
	NULL,
	NULL,
};
/* 80CD849C-80CD84A8 000C .data      __vt__8cM3dGAab                                              */
SECTION_DATA void* __vt__8cM3dGAab[3] = {
	NULL, /* RTTI */
	NULL,
	NULL,
};
/* 80CD84A8-80CD84CC 0024 .data      __vt__12dBgS_ObjAcch                                         */
SECTION_DATA void* __vt__12dBgS_ObjAcch[9] = {
	NULL, /* RTTI */
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
};
/* 80CD84CC-80CD8510 0044 .data      __vt__14daItemShield_c                                       */
SECTION_DATA void* __vt__14daItemShield_c[17] = {
	NULL, /* RTTI */
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
};
/* 80CD8510-80CD851C 000C .data      __vt__8cM3dGPla                                              */
SECTION_DATA void* __vt__8cM3dGPla[3] = {
	NULL, /* RTTI */
	NULL,
	NULL,
};
}


/* ###################################################################################### */
/*                                         .text                                          */
/* ###################################################################################### */

/* 80CD6A58-80CD6D54 02FC .text      Reflect__FP4cXyzRC13cBgS_PolyInfof                           */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void Reflect__FP4cXyzRC13cBgS_PolyInfof() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/Reflect__FP4cXyzRC13cBgS_PolyInfof.s"
}
#pragma pop

/* 80CD6D54-80CD6D9C 0048 .text      __dt__8cM3dGPlaFv                                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__8cM3dGPlaFv() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/__dt__8cM3dGPlaFv.s"
}
#pragma pop

/* 80CD6D9C-80CD6DD8 003C .text      initBaseMtx__14daItemShield_cFv                              */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void initBaseMtx__14daItemShield_cFv() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/initBaseMtx__14daItemShield_cFv.s"
}
#pragma pop

/* 80CD6DD8-80CD7094 02BC .text      setBaseMtx__14daItemShield_cFv                               */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void setBaseMtx__14daItemShield_cFv() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/setBaseMtx__14daItemShield_cFv.s"
}
#pragma pop

/* 80CD7094-80CD724C 01B8 .text      Create__14daItemShield_cFv                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void Create__14daItemShield_cFv() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/Create__14daItemShield_cFv.s"
}
#pragma pop

/* 80CD724C-80CD7254 0008 .text      __CreateHeap__14daItemShield_cFv                             */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __CreateHeap__14daItemShield_cFv() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/__CreateHeap__14daItemShield_cFv.s"
}
#pragma pop

/* 80CD7254-80CD7420 01CC .text      create__14daItemShield_cFv                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void create__14daItemShield_cFv() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/func_80CD7254.s"
}
#pragma pop

/* 80CD7420-80CD7468 0048 .text      __dt__8cM3dGCylFv                                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__8cM3dGCylFv() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/__dt__8cM3dGCylFv.s"
}
#pragma pop

/* 80CD7468-80CD74B0 0048 .text      __dt__8cM3dGAabFv                                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__8cM3dGAabFv() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/__dt__8cM3dGAabFv.s"
}
#pragma pop

/* 80CD74B0-80CD750C 005C .text      __dt__10dCcD_GSttsFv                                         */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__10dCcD_GSttsFv() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/__dt__10dCcD_GSttsFv.s"
}
#pragma pop

/* 80CD750C-80CD757C 0070 .text      __dt__12dBgS_AcchCirFv                                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__12dBgS_AcchCirFv() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/__dt__12dBgS_AcchCirFv.s"
}
#pragma pop

/* 80CD757C-80CD75EC 0070 .text      __dt__12dBgS_ObjAcchFv                                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__12dBgS_ObjAcchFv() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/__dt__12dBgS_ObjAcchFv.s"
}
#pragma pop

/* 80CD75EC-80CD7734 0148 .text      bg_check__14daItemShield_cFv                                 */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void bg_check__14daItemShield_cFv() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/bg_check__14daItemShield_cFv.s"
}
#pragma pop

/* 80CD7734-80CD77F0 00BC .text      action_proc_call__14daItemShield_cFv                         */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void action_proc_call__14daItemShield_cFv() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/action_proc_call__14daItemShield_cFv.s"
}
#pragma pop

/* 80CD77F0-80CD7828 0038 .text      actionInit__14daItemShield_cFv                               */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void actionInit__14daItemShield_cFv() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/actionInit__14daItemShield_cFv.s"
}
#pragma pop

/* 80CD7828-80CD7890 0068 .text      actionWaitInit__14daItemShield_cFv                           */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void actionWaitInit__14daItemShield_cFv() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/actionWaitInit__14daItemShield_cFv.s"
}
#pragma pop

/* 80CD7890-80CD7C68 03D8 .text      actionWait__14daItemShield_cFv                               */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void actionWait__14daItemShield_cFv() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/actionWait__14daItemShield_cFv.s"
}
#pragma pop

/* 80CD7C68-80CD7D04 009C .text      initActionOrderGetDemo__14daItemShield_cFv                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void initActionOrderGetDemo__14daItemShield_cFv() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/initActionOrderGetDemo__14daItemShield_cFv.s"
}
#pragma pop

/* 80CD7D04-80CD7D80 007C .text      actionOrderGetDemo__14daItemShield_cFv                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void actionOrderGetDemo__14daItemShield_cFv() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/actionOrderGetDemo__14daItemShield_cFv.s"
}
#pragma pop

/* 80CD7D80-80CD7E00 0080 .text      actionGetDemo__14daItemShield_cFv                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void actionGetDemo__14daItemShield_cFv() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/actionGetDemo__14daItemShield_cFv.s"
}
#pragma pop

/* 80CD7E00-80CD7EBC 00BC .text      event_proc_call__14daItemShield_cFv                          */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void event_proc_call__14daItemShield_cFv() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/event_proc_call__14daItemShield_cFv.s"
}
#pragma pop

/* 80CD7EBC-80CD7F20 0064 .text      actionWaitCamDemo__14daItemShield_cFv                        */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void actionWaitCamDemo__14daItemShield_cFv() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/actionWaitCamDemo__14daItemShield_cFv.s"
}
#pragma pop

/* 80CD7F20-80CD7F88 0068 .text      actionOrderCamDemo__14daItemShield_cFv                       */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void actionOrderCamDemo__14daItemShield_cFv() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/actionOrderCamDemo__14daItemShield_cFv.s"
}
#pragma pop

/* 80CD7F88-80CD7FE4 005C .text      actionCamDemo__14daItemShield_cFv                            */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void actionCamDemo__14daItemShield_cFv() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/actionCamDemo__14daItemShield_cFv.s"
}
#pragma pop

/* 80CD7FE4-80CD7FE8 0004 .text      actionCamDemoEnd__14daItemShield_cFv                         */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void actionCamDemoEnd__14daItemShield_cFv() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/actionCamDemoEnd__14daItemShield_cFv.s"
}
#pragma pop

/* 80CD7FE8-80CD80EC 0104 .text      execute__14daItemShield_cFv                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void execute__14daItemShield_cFv() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/execute__14daItemShield_cFv.s"
}
#pragma pop

/* 80CD80EC-80CD8140 0054 .text      draw__14daItemShield_cFv                                     */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void draw__14daItemShield_cFv() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/draw__14daItemShield_cFv.s"
}
#pragma pop

/* 80CD8140-80CD8178 0038 .text      _delete__14daItemShield_cFv                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void _delete__14daItemShield_cFv() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/_delete__14daItemShield_cFv.s"
}
#pragma pop

/* 80CD8178-80CD8198 0020 .text      daItemShield_Draw__FP14daItemShield_c                        */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daItemShield_Draw__FP14daItemShield_c() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/daItemShield_Draw__FP14daItemShield_c.s"
}
#pragma pop

/* 80CD8198-80CD81B8 0020 .text      daItemShield_Execute__FP14daItemShield_c                     */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daItemShield_Execute__FP14daItemShield_c() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/daItemShield_Execute__FP14daItemShield_c.s"
}
#pragma pop

/* 80CD81B8-80CD81D8 0020 .text      daItemShield_Delete__FP14daItemShield_c                      */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daItemShield_Delete__FP14daItemShield_c() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/daItemShield_Delete__FP14daItemShield_c.s"
}
#pragma pop

/* 80CD81D8-80CD81F8 0020 .text      daItemShield_Create__FP10fopAc_ac_c                          */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void daItemShield_Create__FP10fopAc_ac_c() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/daItemShield_Create__FP10fopAc_ac_c.s"
}
#pragma pop

/* 80CD81F8-80CD8240 0048 .text      __dt__10cCcD_GSttsFv                                         */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void __dt__10cCcD_GSttsFv() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/__dt__10cCcD_GSttsFv.s"
}
#pragma pop

/* 80CD8240-80CD825C 001C .text      cLib_calcTimer<Uc>__FPUc                                     */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void func_80CD8240() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/func_80CD8240.s"
}
#pragma pop

/* 80CD825C-80CD8264 0008 .text      @36@__dt__12dBgS_ObjAcchFv                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void func_80CD825C() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/func_80CD825C.s"
}
#pragma pop

/* 80CD8264-80CD826C 0008 .text      @20@__dt__12dBgS_ObjAcchFv                                   */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void func_80CD8264() {
	nofralloc
#include "asm/rel/d_a_obj_shield/d_a_obj_shield/func_80CD8264.s"
}
#pragma pop


