// 
// Generated By: dol2asm
// 

#include "dolphin/types.h"

// 
// Additional Symbols:
// 

extern "C" {
extern void _prolog();
extern void _epilog();
extern void _unresolved();
extern void s_bomb_sub__FPvPv();
extern void shot_b_sub__FPvPv();
extern void useHeapInit__FP10fopAc_ac_c();
extern void __dt__12nest_hahen_sFv();
extern void __ct__12nest_hahen_sFv();
extern void __dt__14daE_Nest_HIO_cFv();
extern const u8 unknown_translation_unit_ctors__data_805046C8[8];
extern const void* __destroy_global_chain_reference;
SECTION_RODATA extern const u8 LIT_3999[4];
SECTION_RODATA extern const u8 LIT_4066[4];
SECTION_RODATA extern const u8 LIT_4208[4];
SECTION_RODATA extern const u8 LIT_4215[8];
SECTION_RODATA extern const u8 LIT_4431[4];
SECTION_RODATA extern const u8 stringBase0[15];
SECTION_DATA extern u8 data_805047FC[12];
SECTION_DATA extern u8 data_80504808[12];
SECTION_DATA extern u8 data_80504814[8];
SECTION_DATA extern u8 data_8050481C[4];
SECTION_DATA extern u8 data_80504820[64];
SECTION_DATA extern u8 data_80504860[68];
SECTION_DATA extern void* __vt__8cM3dGCyl[3];
SECTION_DATA extern void* __vt__8cM3dGSph[3];
SECTION_DATA extern void* __vt__8cM3dGAab[3];
SECTION_DATA extern void* __vt__12dBgS_ObjAcch[9];
SECTION_DATA extern void* __vt__14daE_Nest_HIO_c[3];
SECTION_BSS extern u8 __global_destructor_chain[4 + 4 /* padding */];
SECTION_BSS extern u8 global_destructor_chain__data_80504954[0];
SECTION_BSS extern u8 LIT_3994[12];
SECTION_BSS extern u8 l_HIO[12];
}


/* ###################################################################################### */
/*                                         .text                                          */
/* ###################################################################################### */

/* 80500EA0-80500ECC 002C .text      _prolog                                                      */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void _prolog() {
	nofralloc
#include "asm/rel/d_a_e_nest/executor/_prolog.s"
}
#pragma pop

/* 80500ECC-80500EF8 002C .text      _epilog                                                      */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void _epilog() {
	nofralloc
#include "asm/rel/d_a_e_nest/executor/_epilog.s"
}
#pragma pop

/* 80500EF8-80500F18 0020 .text      _unresolved                                                  */
#pragma push
#pragma optimization_level 0
#pragma optimizewithasm off
asm void _unresolved() {
	nofralloc
#include "asm/rel/d_a_e_nest/executor/_unresolved.s"
}
#pragma pop


